SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

use SIG
go


-- PROC CALCULO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'PRC_p123Ger_MES' AND type = 'P')
   DROP PROCEDURE [dbo].[PRC_p123Ger_MES]
GO

-- PRC_p123Ger_MES '20160131','20160430'

/* 
	EXEC PRC_p123Ger_MES '20131231','20150131'
	EXEC PRC_p123Ger_MES '20140131','20150131'
    EXEC PRC_p123Ger_MES '20140228','20150131'
   EXEC PRC_p123Ger_MES '20140331','20150131'
   EXEC PRC_p123Ger_MES '20140430','20150131'
   EXEC PRC_p123Ger_MES '20140531','20150131'
   EXEC PRC_p123Ger_MES '20140630','20150131'
   EXEC PRC_p123Ger_MES '20140731','20150131'
   EXEC PRC_p123Ger_MES '20140831','20150131'
   EXEC PRC_p123Ger_MES '20140930','20150131'
   EXEC PRC_p123Ger_MES '20141031','20150131'
   EXEC PRC_p123Ger_MES '20141130','20150131'
   EXEC PRC_p123Ger_MES '20141231','20150131'

   EXEC PRC_p123Ger_MES '20141231','20160131'

	EXEC PRC_p123Ger_MES '20150131','20160131'
    EXEC PRC_p123Ger_MES '20150228','20160131'
   EXEC PRC_p123Ger_MES '20150331','20160131'
   EXEC PRC_p123Ger_MES '20150430','20160131'
   EXEC PRC_p123Ger_MES '20150531','20160131'
   EXEC PRC_p123Ger_MES '20150630','20160131'
   EXEC PRC_p123Ger_MES '20150731','20160131'
   EXEC PRC_p123Ger_MES '20150831','20160131'
   EXEC PRC_p123Ger_MES '20150930','20160131'
   EXEC PRC_p123Ger_MES '20151031','20160131'
   EXEC PRC_p123Ger_MES '20151130','20160131'
   EXEC PRC_p123Ger_MES '20151231','20160131'

   EXEC PRC_p123Ger_MES '20160131','20160131'
   EXEC PRC_p123Ger_MES '20160229','20160430'
   EXEC PRC_p123Ger_MES '20160331','20160430'
   EXEC PRC_p123Ger_MES '20160430','20160430'

 select * from P123Ger_MES (nolock) ORDER BY DT_SAFRA

delete from P123Ger_MES where DT_SAFRA= '2016-02-28'
delete from P123Ger_MES where DT_SAFRA= '2013-12-31'
delete from P123Ger_MES where DT_SAFRA= '2013-12-30'
SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='20140131'
SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='2013-12-31'


SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='20150131'
-- ajustar os venctos p2 e p3 de 1/15 a 7/15   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC P		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20150131' AND  '20150731'

-- ajustar os venctos p2 e p3 de 2014   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND   PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	MAX(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20140131' AND  '20141231'

-- ajustar os venctos p2 e p3 de 2014   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND   PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	MAX(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20131231' AND  '20131231'

*/

CREATE Procedure [dbo].[PRC_p123Ger_MES] (@data_SAFRA as datetime, @data_ref as datetime) AS
BEGIN

-- DECLARE @DTREF AS VARCHAR(8) SET @DTREF = CONVERT(varchar(8),@data_ref,112)

-- TTLS DO MES ********************************************* AUXILIA NOS RELATORIOS
-- DECLARE @DTREF  DATETIME  SET @DTREF = '20140630'
		DELETE	FROM	P123Ger_MES
				WHERE	DT_SAFRA	= @data_SAFRA

-- SP_HELP COMERCIAL_PRODUCAO_MES
-- ALTER TABLE COMERCIAL_PRODUCAO_MES ADD  PRAZO FLOAT
-- ALTER TABLE COMERCIAL_PRODUCAO_MES ADD  QTDE_CLI FLOAT
-- ALTER TABLE COMERCIAL_PRODUCAO_MES ADD  VAR_PROD FLOAT
-- select * from p123_historico (nolock)
		INSERT	P123Ger_MES
		SELECT	@data_SAFRA,
				'', --VEICULO,
				'', --AGENTE,
				COUNT(NUM_OPE),		-- QTDE
				SUM(VLR_OP),		-- PRODUCAO
				--  ********** P1	VLR VENCIDO NAO PAGO P1_QTDE ,  VLR: P1_INAD, P1_PRC_INAD EM % DE VLR
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ,0.0, 0.0, 0.0, 0.0,-- 30D
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ,0.0, 0.0, 0.0, 0.0,-- 60D
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ,0.0, 0.0, 0.0, 0.0,-- 90D
				--  *********** P4 CALCULAR A PARTIR DO FUNCAO
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ,0.0, 0.0, 0.0, 0.0 -- 91D
		FROM	P123_HISTORICO		(NOLOCK)
		WHERE	DT_FECHA	 = @data_SAFRA
			AND	NUM_OPE		<>''
			AND RENEGOCIADO =0	AND VLR_OP > 0.0
			
--		GROUP	BY	PRODUTO
/*	
DROP TABLE P123Ger_MES

CREATE TABLE P123Ger_MES (
DT_SAFRA	SMALLDATETIME,
VEICULO		VARCHAR(100),
AGENTE		VARCHAR(100),
QTDE		FLOAT,
PRODUCAO	FLOAT,
-- PARCELAS P1 A P4  ************* 30 D
P1_QTDE_30D	FLOAT,
P1_INAD_30D	FLOAT,
P1_PRC_INAD_30D	FLOAT,
P2_QTDE_30D	FLOAT,
P2_INAD_30D	FLOAT,
P2_PRC_INAD_30D	FLOAT,
P3_QTDE_30D	FLOAT,
P3_INAD_30D	FLOAT,
P3_PRC_INAD_30D	FLOAT,
P4_QTDE_30D	FLOAT,
P4_INAD_30D	FLOAT,
P4_PRC_INAD_30D	FLOAT,
-- PARCELAS P1 A P4  ************* 60 D
P1_QTDE_60D	FLOAT,
P1_INAD_60D	FLOAT,
P1_PRC_INAD_60D	FLOAT,
P2_QTDE_60D	FLOAT,
P2_INAD_60D	FLOAT,
P2_PRC_INAD_60D	FLOAT,
P3_QTDE_60D	FLOAT,
P3_INAD_60D	FLOAT,
P3_PRC_INAD_60D	FLOAT,
P4_QTDE_60D	FLOAT,
P4_INAD_60D	FLOAT,
P4_PRC_INAD_60D	FLOAT,
-- PARCELAS P1 A P4  ************* 90 D
P1_QTDE_90D	FLOAT,
P1_INAD_90D	FLOAT,
P1_PRC_INAD_90D	FLOAT,
P2_QTDE_90D	FLOAT,
P2_INAD_90D	FLOAT,
P2_PRC_INAD_90D	FLOAT,
P3_QTDE_90D	FLOAT,
P3_INAD_90D	FLOAT,
P3_PRC_INAD_90D	FLOAT,
P4_QTDE_90D	FLOAT,
P4_INAD_90D	FLOAT,
P4_PRC_INAD_90D	FLOAT,
-- PARCELAS P1 A P4  ************* 91 D
P1_QTDE_91D	FLOAT,
P1_INAD_91D	FLOAT,
P1_PRC_INAD_91D	FLOAT,
P2_QTDE_91D	FLOAT,
P2_INAD_91D	FLOAT,
P2_PRC_INAD_91D	FLOAT,
P3_QTDE_91D	FLOAT,
P3_INAD_91D	FLOAT,
P3_PRC_INAD_91D	FLOAT,
P4_QTDE_91D	FLOAT,
P4_INAD_91D	FLOAT,
P4_PRC_INAD_91D	FLOAT
 )

CREATE INDEX P123Ger_MES_IDX1 ON P123Ger_MES (DT_SAFRA)

SELECT * FROM	P123_HISTORICO		(NOLOCK) WHERE DT_FECHA='20160131'
SELECT * FROM	P123_HISTORICO		(NOLOCK) WHERE DT_FECHA='20150131'

SELECT * FROM CdcSantanaMicroCredito..CPARC  (NOLOCK) WHERE PANROPER IN ('612189611','552009741A','612090363A')
SELECT * FROM	P123_HISTORICO		(NOLOCK) WHERE DT_FECHA='20150131' AND NUM_OPE IN ('612189611','552009741A','612090363A')

*/
-- SP_HELP 		COMERCIAL_PRODUCAO


		-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150228'
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150331'
-- SELECT TOP 10 * FROM	CdcSantanaMicroCredito..CPARC  (NOLOCK)	

-- PARCELAS P1 A P4  ************* 30 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
DECLARE @DT30D	DATETIME   -- @DTM2
SET @DT30D  =  CONVERT(CHAR(4),DATEPART(YEAR,@data_SAFRA))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@data_SAFRA))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT30D =  DATEADD(M,+3,@DT30D) -- + 1 MES 30D DA SAFRA, erro!  +1 M DO VCTO DA P1
SET	@DT30D =  DATEADD(DD,-1,@DT30D) -- FIM mes , +30 DIAS DO 1o VCTO (1 MES DEPOIS DO FIM DA SAFRA)
--  select @DT30D
-- NAO PAGO  -- P1 E VENCIDO A 1MES DO FIM DA SAFRA
		UPDATE	P123Ger_MES
		SET	P1_QTDE_30D	= QTD1,
			P1_INAD_30D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0		-- SEM RENEG, P1 NAO PAGAS, ATE DIA 30 DO MES
				AND DtVencPARC <= @DT30D -- VENCIDOS P1
				AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT30D )	)  AS R  -- NAO PAGO
		WHERE		DT_SAFRA	= @data_SAFRA

		-- ************************ INCLUI 29/9/16 PQ P4>>
		-- ANALITICO DO ATRASO AUXILIAR P/ CALC P4=P1+P2+P3, CONTRATO PODE SE REPETIR, MAS NAO PODE SOMAR 2OU 3X
		TRUNCATE TABLE SCORE_OVER90_AUX
			-- ANALITICO DA  INADIMPLENCIA *********** P1 A 30D
			-- SELECT * FROM SCORE_OVER90_AUX
			--	(	DT_FECHA	SMALLDATETIME,	CONTRATO	VARCHAR(30), DATA_CONTRATO	DATETIME, PARCELA_ABERTO	INT, ATRASO	INT,
			--		VENCIMENTO		DATETIME,	SCORE	INT,	VLR_FINANCIADO	float	)
			INSERT SCORE_OVER90_AUX
			SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 		1,30,  -- P1 A 30D
					DtVencPARC , 0, VLR_OP ,DT_PAGTO
				FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
								WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
									AND	NUM_OPE		<>''
									AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
							AND	  DtVencPARC <= @DT30D -- VENCIDOS P1
							AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT30D )	)  AS R  -- NAO PAGO

-- DECLARE @DT30D DATETIME SET @DT30D='20150131'
SET @DT30D  =  CONVERT(CHAR(4),DATEPART(YEAR,@DT30D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT30D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT30D =  DATEADD(M,+2,@DT30D) -- + 1 MES P/ P2
SET	@DT30D =  DATEADD(DD,-1,@DT30D) -- FIM mes , +30 DIAS DO 2o VCTO (2 MES DEPOIS DO FIM DA SAFRA)
--  SELECT @DT30D

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P2 A 30D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 2, 30,	-- P2 A 30D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P2VCTO , 0, VLR_OP ,P2PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P2VCTO <= @DT30D -- VENCIDOS P1
						AND (P2PGTO IS NULL OR P2PGTO > @DT30D )	)  AS R  -- NAO PAGO


		-- P2 A 30 D
		-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
		UPDATE	P123Ger_MES
		SET	P2_QTDE_30D	= QTD1,
			P2_INAD_30D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR 
			FROM	P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0				-- SEM RENEG, P2 NAO PAGAS, ATE DIA 30 DO MES
				AND P2VCTO <= @DT30D			-- VENCIDOS P2
				AND (P2PGTO IS NULL OR P2PGTO > @DT30D )	 -- NAO PAGO
				--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1
				AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
					WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1)
						AND	I.ATRASO  = 30 )
					)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA

-- P3 A 30 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
SET @DT30D  =  CONVERT(CHAR(4),DATEPART(YEAR,@DT30D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT30D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT30D =  DATEADD(M,+2,@DT30D) -- + 1 MES P/ P2
SET	@DT30D =  DATEADD(DD,-1,@DT30D) -- FIM mes , +30 DIAS DO 3o VCTO (3 MES DEPOIS DO FIM DA SAFRA)


		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1 E P2
		-- ANALITICO DA INADIMPLENCIA  *********** P3 A 30D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 3, 30,	-- P2 A 30D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P3VCTO , 0, VLR_OP ,P3PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P3VCTO <= @DT30D -- VENCIDOS P1
						AND (P3PGTO IS NULL OR P3PGTO > @DT30D )	)  AS R  -- NAO PAGO

		UPDATE	P123Ger_MES
		SET	P3_QTDE_30D	= QTD1,
			P3_INAD_30D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0		-- SEM RENEG, P3 NAO PAGAS, ATE DIA 30 DO MES
				AND P3VCTO <= @DT30D -- VENCIDOS P3
				AND (P3PGTO IS NULL OR P3PGTO > @DT30D )		-- NAO PAGO
				--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1
				AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
					WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1,2)
						AND	I.ATRASO  = 30 )
					)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA


-- **** 60 D	*************************************************************************
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
DECLARE @DT60D	DATETIME   -- @DTM2
SET @DT60D  =  CONVERT(CHAR(4),DATEPART(YEAR,@data_SAFRA))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@data_SAFRA))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT60D =  DATEADD(M,+4,@DT60D) -- + 3 MESES DA SAFRA, ERRO! + 2M DO VCTO DA P1
SET	@DT60D =  DATEADD(DD,-1,@DT60D) -- FIM mes , +60 DIAS DO 1o VCTO (1 MES DEPOIS DO FIM DA SAFRA)
-- select @DT60D  -- FIM ABR
-- NAO PAGO  -- P1 E VENCIDO A 2 MES DO FIM DA SAFRA
		UPDATE	P123Ger_MES
		SET	P1_QTDE_60D	= QTD1,
			P1_INAD_60D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0		-- SEM RENEG, P1 NAO PAGAS, ATE DIA 60 DO MES
				AND DtVencPARC <= @DT60D -- VENCIDOS P1
				AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT60D )	)  AS R  -- NAO PAGO
		WHERE		DT_SAFRA	= @data_SAFRA


		-- ANALITICO DA  INADIMPLENCIA *********** P1 A 60D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 		1,60,  -- P1 A 60D
				DtVencPARC , 0, VLR_OP ,DT_PAGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  DtVencPARC <= @DT60D -- VENCIDOS P1
						AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT60D )	)  AS R  -- NAO PAGO

SET @DT60D  =  CONVERT(CHAR(4),DATEPART(YEAR,@DT60D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT60D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT60D =  DATEADD(M,+2,@DT60D) -- + 1 MES P/ P2
SET	@DT60D =  DATEADD(DD,-1,@DT60D) -- FIM mes , +60 DIAS DO 2o VCTO (2 MES DEPOIS DO FIM DA SAFRA)
-- P2 A 60 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P2 A 60D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 2, 60,	-- P2 A 60D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P2VCTO , 0, VLR_OP ,P2PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P2
						AND	  P2VCTO <= @DT60D							-- VENCIDOS P2
						AND (P2PGTO IS NULL OR P2PGTO > @DT60D )		-- NAO PAGO P2
							)  AS R

		UPDATE	P123Ger_MES
		SET	P2_QTDE_60D	= QTD1,
			P2_INAD_60D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
				WHERE	R1.DT_FECHA= @data_SAFRA  
					AND RENEGOCIADO = 0		-- SEM RENEG, P2 NAO PAGAS, ATE DIA 60 DO MES
					AND P2VCTO <= @DT60D	-- VENCIDOS P2
					AND (P2PGTO IS NULL OR P2PGTO > @DT60D )	  -- NAO PAGO
					--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1
					AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
						WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1)
							AND	I.ATRASO  = 60 )
					)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA

-- P3 A 60 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
SET @DT60D  =  CONVERT(CHAR(4),DATEPART(YEAR,@DT60D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT60D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT60D =  DATEADD(M,+2,@DT60D) -- + 1 MES P/ P2
SET	@DT60D =  DATEADD(DD,-1,@DT60D) -- FIM mes , +60 DIAS DO 3o VCTO (3 MES DEPOIS DO FIM DA SAFRA)

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P3 A 60D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 3, 60,	-- P2 A 60D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P3VCTO , 0, VLR_OP ,P3PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P3VCTO <= @DT60D -- VENCIDOS P1
						AND (P3PGTO IS NULL OR P3PGTO > @DT60D )	)  AS R  -- NAO PAGO

		UPDATE	P123Ger_MES
		SET	P3_QTDE_60D	= QTD1,
			P3_INAD_60D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
				WHERE	R1.DT_FECHA= @data_SAFRA  
					AND RENEGOCIADO = 0						 -- SEM RENEG, P3 NAO PAGAS, ATE DIA 60 DO MES
					AND P3VCTO <= @DT60D					 -- VENCIDOS P3
					AND (P3PGTO IS NULL OR P3PGTO > @DT60D ) -- NAO PAGO P3
						--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1 E P2
						AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
							WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1,2)
								AND	I.ATRASO  = 60 )
					)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA


-- **** 90 D	*************************************************************************
-- P1 A 90 D	*************************************************************************
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
DECLARE @DT90D	DATETIME   -- @DTM2
SET @DT90D  =  CONVERT(CHAR(4),DATEPART(YEAR,@data_SAFRA))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@data_SAFRA))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT90D =  DATEADD(M,+5,@DT90D) -- + 4 MESES DA SAFRA, ERRO! + 3M DO VCTO DA P1
SET	@DT90D =  DATEADD(DD,-1,@DT90D) -- FIM mes , +90 DIAS DO 1o VCTO (1 MES DEPOIS DO FIM DA SAFRA)
-- SELECT @DT90D  -- MAIO
-- NAO PAGO  -- P1 E VENCIDO A 2 MES DO FIM DA SAFRA
		UPDATE	P123Ger_MES
		SET	P1_QTDE_90D	= QTD1,
			P1_INAD_90D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0		-- SEM RENEG, P1 NAO PAGAS, ATE DIA 90 DO MES
				AND DtVencPARC <= @DT90D -- VENCIDOS P1
				AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT90D )	)  AS R  -- NAO PAGO
		WHERE		DT_SAFRA	= @data_SAFRA

		-- ANALITICO DA  INADIMPLENCIA *********** P1 A 90D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 		1,90,  -- P1 A 90D
				DtVencPARC , 0, VLR_OP ,DT_PAGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  DtVencPARC <= @DT90D -- VENCIDOS P1
						AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT90D )	)  AS R  -- NAO PAGO

-- DECLARE @DT90D DATETIME SET @DT90D = '20160531'
-- mes seguinte da p2
SET	@DT90D =  CONVERT(CHAR(4),DATEPART(YEAR,@DT90D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT90D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT90D =  DATEADD(M,+2,@DT90D) -- + 1 MES P/ P2
SET	@DT90D =  DATEADD(DD,-1,@DT90D) -- FIM mes , +90 DIAS DO 2o VCTO (2 MES DEPOIS DO FIM DA SAFRA)
--  SELECT @DT90D

-- P2 A 90 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P2 A 90D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 2, 90,	-- P2 A 90D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P2VCTO , 0, VLR_OP ,P2PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P2VCTO <= @DT90D -- VENCIDOS P1
						AND (P2PGTO IS NULL OR P2PGTO > @DT90D )	)  AS R  -- NAO PAGO

		UPDATE	P123Ger_MES
		SET	P2_QTDE_90D	= QTD1,
			P2_INAD_90D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
				WHERE	R1.DT_FECHA= @data_SAFRA  
					AND RENEGOCIADO = 0							-- SEM RENEG, P2 NAO PAGAS, ATE DIA 90 DO MES
					AND P2VCTO <= @DT90D						-- VENCIDOS P2
					AND (P2PGTO IS NULL OR P2PGTO > @DT90D )	-- NAO PAGO
							--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1 
							AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
								WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1)
									AND	I.ATRASO  = 90 )
							)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA


-- P3 A 90 D
-- DECLARE @DT90D DATETIME SET @DT90D = '20160630'
SET	@DT90D =  CONVERT(CHAR(4),DATEPART(YEAR,@DT90D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT90D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT90D =  DATEADD(M,+2,@DT90D) -- + 1 MES P/ P2
SET	@DT90D =  DATEADD(DD,-1,@DT90D) -- FIM mes , +90 DIAS DO 3o VCTO (3 MES DEPOIS DO FIM DA SAFRA)
--  SELECT @DT90D

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P3 A 90D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 3, 90,	-- P3 A 90D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P3VCTO , 0, VLR_OP ,P3PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''  	AND VLR_OP > 0.0  -- incluido 30/11/16 corrigir erro do 4o momento do p3
								AND RENEGOCIADO =0	-- P1
						AND	  P3VCTO <= @DT90D -- VENCIDOS P1
						AND (P3PGTO IS NULL OR P3PGTO > @DT90D )	)  AS R  -- NAO PAGO

		UPDATE	P123Ger_MES
		SET	P3_QTDE_90D	= QTD1,
			P3_INAD_90D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND	NUM_OPE		<>''	-- alterado 30/11/16 corrigir erro do 4o momento do p3
				AND RENEGOCIADO = 0		AND VLR_OP > 0.0	-- SEM RENEG, P3 NAO PAGAS, ATE DIA 90 DO MES
				AND P3VCTO <= @DT90D						-- VENCIDOS   P3
				AND (P3PGTO IS NULL OR P3PGTO > @DT90D )	-- NAO PAGO	  P3
					--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1 E P2
					AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
						WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1,2)
							AND	I.ATRASO  = 90 )
					)  AS R
		WHERE		DT_SAFRA	= @data_SAFRA

-- **** ACIMA 90 D	*************************************************************************
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
DECLARE @DT91D	DATETIME   -- @DTM2
SET @DT91D  =  CONVERT(CHAR(4),DATEPART(YEAR,@data_SAFRA))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@data_SAFRA))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT91D =  DATEADD(M,+6,@DT91D) -- + 4 MESES 90D, 5 MESES 120 D DO VCTO DA P1
SET	@DT91D =  DATEADD(DD,-1,@DT91D) -- FIM mes , +91 DIAS DO 1o VCTO (1 MES DEPOIS DO FIM DA SAFRA)
--   select @DT91D  -- JUN

-- NAO PAGO  -- P1 E VENCIDO A 2 MES DO FIM DA SAFRA
		UPDATE	P123Ger_MES
		SET	P1_QTDE_91D		= QTD1,
			P1_INAD_91D		= VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0		-- SEM RENEG, P1 NAO PAGAS 
				AND DtVencPARC <= @DT91D -- VENCIDOS P1
				AND (DT_PAGTO IS NULL   OR DT_PAGTO > @DT91D )	)  AS R  -- NAO PAGO EM 120 D OU +
/*				AND 1= 0+ CASE	WHEN (DT_PAGTO IS NULL) THEN 1	-- NAO PAGA
								WHEN (DT_PAGTO IS NOT NULL) AND DATEDIFF(DD,DtVencPARC,DT_PAGTO)>120 THEN 1
								ELSE 0 END		
				)  AS R  -- NAO PAGO    */
		WHERE		DT_SAFRA	= @data_SAFRA

		-- ANALITICO DA  INADIMPLENCIA *********** P1 A 91D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 		1,91,  -- P1 A 91D, 120 D
				DtVencPARC , 0, VLR_OP ,DT_PAGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  DtVencPARC <= @DT91D -- VENCIDOS P1
						AND (DT_PAGTO IS NULL OR DT_PAGTO > @DT91D )	)  AS R  -- NAO PAGO


-- DECLARE @DT91D DATETIME SET @DT91D = '20160630'
SET	@DT91D =  CONVERT(CHAR(4),DATEPART(YEAR,@DT91D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT91D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT91D =  DATEADD(M,+2,@DT91D) -- + 1 MES P/ P2
SET	@DT91D =  DATEADD(DD,-1,@DT91D) -- FIM mes , +91 DIAS DO 2o VCTO (2 MES DEPOIS DO FIM DA SAFRA)
--  SELECT	@DT91D
-- P2 A 91 D

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P2 A 91D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 2, 91,	-- P2 A 91D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P2VCTO , 0, VLR_OP ,P2PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P2VCTO <= @DT91D -- VENCIDOS P1
						AND (P2PGTO IS NULL OR P2PGTO > @DT91D )	)  AS R  -- NAO PAGO

-- P2 A 91 D
-- DECLARE @data_SAFRA DATETIME SET @data_SAFRA='20150131'
		UPDATE	P123Ger_MES
		SET	P2_QTDE_91D	= QTD1,
			P2_INAD_91D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND RENEGOCIADO = 0							-- SEM RENEG,	P2 NAO PAGAS, ATE DIA 91 DO MES
				AND P2VCTO <= @DT91D						-- VENCIDOS		P2
				AND (P2PGTO IS NULL   OR P2PGTO > @DT91D )	-- NAO PAGO		P2
					--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1 
					AND R1.NUM_OPE NOT IN (SELECT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
						WHERE	I.DT_FECHA= @data_SAFRA   AND I.PARCELA_ABERTO IN (1)
							AND	I.ATRASO  = 91 )
					)  AS R
/*				AND 1= 0+ CASE	WHEN (P2PGTO IS NULL) THEN 1	-- NAO PAGA
								WHEN (P2PGTO IS NOT NULL) AND DATEDIFF(DD,P2VCTO,P2PGTO)>120 THEN 1
								ELSE 0 END  )  AS R   */
		WHERE		DT_SAFRA	= @data_SAFRA

-- P3 A 91 D
-- DECLARE @DT91D DATETIME SET @DT91D = '20160630'
SET	@DT91D =  CONVERT(CHAR(4),DATEPART(YEAR,@DT91D))+
					RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DT91D))),2)+'01'  -- INICIO DO MES SAFRA
SET	@DT91D =  DATEADD(M,+2,@DT91D) -- + 1 MES P/ P2
SET	@DT91D =  DATEADD(DD,-1,@DT91D) -- FIM mes , +91 DIAS DO 3o VCTO (3 MES DEPOIS DO FIM DA SAFRA)
--	SELECT	@DT91D
-- P3 A 91 D

		-- ALTERADO 09/11/2016		   *********** 1o ANALITICO, 2o RELATORIO SEM REPETIDOS DO P1
		-- ANALITICO DA  INADIMPLENCIA *********** P3 A 91D
		INSERT SCORE_OVER90_AUX
		SELECT	@data_SAFRA, NUM_OPE, DT_BASE, 3, 91,	-- P3 A 91D, 120D		--2,DATEDIFF(DD,P2VCTO,@DT30D),
				P3VCTO , 0, VLR_OP ,P3PGTO
			FROM	(SELECT *		FROM P123_HISTORICO	R1 (NOLOCK) 
							WHERE	Dt_fecha=@data_SAFRA   -- PRODUCAO
								AND	NUM_OPE		<>''
								AND RENEGOCIADO =0	AND VLR_OP > 0.0	-- P1
						AND	  P3VCTO <= @DT91D -- VENCIDOS P1
						AND (P3PGTO IS NULL OR P3PGTO > @DT91D )	)  AS R  -- NAO PAGO
		-- P3 A 91 D
		UPDATE	P123Ger_MES
		SET	P3_QTDE_91D	= QTD1,
			P3_INAD_91D		=VLR
		FROM	(SELECT		COUNT(NUM_OPE) AS QTD1, SUM(VLR_OP) AS VLR FROM P123_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_SAFRA  
				AND	NUM_OPE		<>''	-- alterado 30/11/16 corrigir erro do 4o momento do p3
				AND RENEGOCIADO = 0		AND VLR_OP > 0.0	-- SEM RENEG, P3 NAO PAGAS, ATE DIA 90 DO MES
			--	AND RENEGOCIADO = 0							-- SEM RENEG,	P3 NAO PAGAS, ATE DIA 91 DO MES
				AND P3VCTO <= @DT91D						-- VENCIDOS		P3
				AND (P3PGTO IS NULL  OR P3PGTO > @DT91D )	-- NAO PAGO  OR P3PGTO > @DT91D
					--   INCLUIDO 09/11/2016		*************** SEM REPETIDOS P1  E P2
					AND R1.NUM_OPE NOT IN (SELECT DISTINCT CONTRATO FROM SCORE_OVER90_AUX I (NOLOCK)
						WHERE	I.DT_FECHA= @data_SAFRA   
							AND I.PARCELA_ABERTO IN (1,2) -- REMOVI  EM 30/11/16 ***************  PQ NO 4o MOMENTO TINHA + CONTRATOS Q NO 3o MOMENTO. EX '612213610' EM SET-16
							AND	I.ATRASO  IN ( 90 ) )	  -- ALTEREI EM 30/11/16 ***************  PQ NO 4o MOMENTO TINHA + CONTRATOS Q NO 3o MOMENTO. EX '612213610' EM SET-16
							)  AS R
/*				AND 1= 0+ CASE	WHEN (P3PGTO IS NULL) THEN 1	-- NAO PAGA
								WHEN (P3PGTO IS NOT NULL) AND DATEDIFF(DD,P3VCTO,P3PGTO)>90 THEN 1
								ELSE 0 END  )  AS R   */
		WHERE		DT_SAFRA	= @data_SAFRA


-- ************************* CALCULA P4 ************** SEM DUPLICAR OS CONTRATOS
UPDATE	 P123Ger_MES
	SET	 P4_QTDE_30D  = C.Q,		
		 P4_INAD_30D  = C.V
	FROM	(SELECT		SUM(VLR_FINANCIADO) AS V , COUNT(CONTRATO) AS Q
				FROM	(SELECT DISTINCT CONTRATO,VLR_FINANCIADO FROM SCORE_OVER90_AUX 	(NOLOCK)
							WHERE ATRASO =30  ) AS AUX )  AS	C
	WHERE		DT_SAFRA	= @data_SAFRA
-- 60D
UPDATE	 P123Ger_MES
	SET	 P4_QTDE_60D  = C.Q,		
		 P4_INAD_60D  = C.V
	FROM	(SELECT		SUM(VLR_FINANCIADO) AS V , COUNT(CONTRATO) AS Q
				FROM	(SELECT DISTINCT CONTRATO,VLR_FINANCIADO FROM SCORE_OVER90_AUX 	(NOLOCK)
							WHERE ATRASO =60  ) AS AUX )  AS	C
	WHERE		DT_SAFRA	= @data_SAFRA
-- 90D
UPDATE	 P123Ger_MES
	SET	 P4_QTDE_90D  = C.Q,		
		 P4_INAD_90D  = C.V
	FROM	(SELECT		SUM(VLR_FINANCIADO) AS V , COUNT(CONTRATO) AS Q
				FROM	(SELECT DISTINCT CONTRATO,VLR_FINANCIADO FROM SCORE_OVER90_AUX 	(NOLOCK)
							WHERE ATRASO =90  ) AS AUX )  AS	C
	WHERE		DT_SAFRA	= @data_SAFRA

-- 91D
UPDATE	 P123Ger_MES
	SET	 P4_QTDE_91D  = C.Q,		
		 P4_INAD_91D  = C.V
	FROM	(SELECT		SUM(VLR_FINANCIADO) AS V , COUNT(CONTRATO) AS Q
				FROM	(SELECT DISTINCT CONTRATO,VLR_FINANCIADO FROM SCORE_OVER90_AUX 	(NOLOCK)
							WHERE ATRASO =91  ) AS AUX )  AS	C
	WHERE		DT_SAFRA	= @data_SAFRA





-- ************************* CALCULA P4 
-- NAO EH A SOMA PQ TEM CONTRATOS REPETIDOS P1E2E3 3X O VLR FINANC, MAS EH 1 CONTRATO
-- sp_help P123Ger_MES
/*		UPDATE	P123Ger_MES
		SET	P4_QTDE_30D	= P1_QTDE_30D + P2_QTDE_30D + P3_QTDE_30D,
			P4_INAD_30D	= P1_INAD_30D + P2_INAD_30D + P3_INAD_30D,
			P4_QTDE_60D	= P1_QTDE_60D + P2_QTDE_60D + P3_QTDE_60D,
			P4_INAD_60D	= P1_INAD_60D + P2_INAD_60D + P3_INAD_60D,
			P4_QTDE_90D	= P1_QTDE_90D + P2_QTDE_90D + P3_QTDE_90D,
			P4_INAD_90D	= P1_INAD_90D + P2_INAD_90D + P3_INAD_90D,
			P4_QTDE_91D	= P1_QTDE_91D + P2_QTDE_91D + P3_QTDE_91D,
			P4_INAD_91D	= P1_INAD_91D + P2_INAD_91D + P3_INAD_91D
		WHERE		DT_SAFRA	= @data_SAFRA


-- ************************* CALCULA P4 ACIMA 90 D
--   DECLARE @data_REF DATETIME SET @data_REF='20160131' DECLARE  @data_SAFRA DATETIME SET @data_SAFRA ='20150131'
		UPDATE		P123Ger_MES
			SET		P4_QTDE_91D = QTD,
					P4_INAD_91D = VLR
		FROM (	SELECT	COUNT(DISTINCT PANROPER) AS QTD,
						SUM(VLRPARC) AS VLR,
						SUM(CASE WHEN (ISNULL(PADTLIQ,'') <> '') AND ISNULL(PADTLIQ,'') <= @data_REF THEN 1.0     ELSE 0.0 END) AS QPG ,
						SUM(CASE WHEN (ISNULL(PADTLIQ,'') <> '') AND ISNULL(PADTLIQ,'') <= @data_REF THEN VLRPARC ELSE 0.0 END) AS PG
				FROM		(SELECT		PANROPER,PANRPARC, PADTVCTO, PAVLRPR + PAVLRJR AS VLRPARC, PADTLIQ, PACNTRL
								FROM	CdcSantanaMicroCredito..CPARC  P1 (NOLOCK)	
								WHERE	PANROPER IN ( SELECT	NUM_OPE FROM P123_HISTORICO		(NOLOCK)
													  WHERE		DT_FECHA = @data_SAFRA) 
								AND	CONVERT(INT,PANRPARC) >3  -- ALEM DA P3 E VENCIDO
								AND	PADTVCTO <= @data_REF  
								AND P1.PACNTRL =  (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC  P2 (NOLOCK)	
								WHERE	P2.PANROPER= P1.PANROPER AND P2.PANRPARC = P1.PANRPARC  )
							 ) AS P
					) AS PARC
		WHERE		DT_SAFRA	= @data_SAFRA
			--AND		PARC.
*/

UPDATE		P123Ger_MES
			SET		P1_PRC_INAD_30D	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P1_INAD_30D / PRODUCAO *100.0 END),
					P2_PRC_INAD_30D	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P2_INAD_30D / PRODUCAO *100.0 END),
					P3_PRC_INAD_30D	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P3_INAD_30D / PRODUCAO *100.0 END),
					P4_PRC_INAD_30D	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P4_INAD_30D / PRODUCAO *100.0 END),
					P1_PRC_INAD_60D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P1_INAD_60D / PRODUCAO *100.0 END),
					P2_PRC_INAD_60D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P2_INAD_60D / PRODUCAO *100.0 END),
					P3_PRC_INAD_60D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P3_INAD_60D / PRODUCAO *100.0 END),
					P4_PRC_INAD_60D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P4_INAD_60D / PRODUCAO *100.0 END),
					P1_PRC_INAD_90D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P1_INAD_90D / PRODUCAO *100.0 END),
					P2_PRC_INAD_90D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P2_INAD_90D / PRODUCAO *100.0 END),
					P3_PRC_INAD_90D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P3_INAD_90D / PRODUCAO *100.0 END),
					P4_PRC_INAD_90D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P4_INAD_90D / PRODUCAO *100.0 END),
					P1_PRC_INAD_91D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P1_INAD_91D / PRODUCAO *100.0 END),
					P2_PRC_INAD_91D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P2_INAD_91D / PRODUCAO *100.0 END),
					P3_PRC_INAD_91D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P3_INAD_91D / PRODUCAO *100.0 END),
					P4_PRC_INAD_91D	=	(CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P4_INAD_91D / PRODUCAO *100.0 END)
		WHERE		DT_SAFRA	= @data_SAFRA
/*
		UPDATE		P123Ger_MES
			SET		P1_PRC_INAD	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P1_INAD / PRODUCAO *100.0 END),
					P2_PRC_INAD	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P2_INAD / PRODUCAO *100.0 END),
					P3_PRC_INAD	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P3_INAD / PRODUCAO *100.0 END),
					P4_PRC_INAD	= (CASE WHEN ISNULL(PRODUCAO,0.0) = 0.0  THEN 0.0 ELSE P4_INAD / PRODUCAO *100.0 END)
		WHERE		DT_SAFRA	= @data_SAFRA
*/			

--				FROM	CdcSantanaMicroCredito..TOrg4  (NOLOCK)

END
GO