USE [SIG]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--*********************************************************************************************************************************************** 
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PARCELAPULADA' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_PARCELAPULADA

GO

CREATE PROCEDURE SCR_PARCELAPULADA @DATAFECH SMALLDATETIME as  
  
--cria temp pago  
SELECT PANROPER, PADTLIQ, MAX(PANRPARC) AS PANRPARC INTO #TEMP_PAGO FROM CDCSANTANAMICROCREDITO..CPARC P (NOLOCK) WHERE   
PADTLIQ IS NOT NULL AND PACNTRL = (SELECT MAX(PACNTRL) FROM CDCSANTANAMICROCREDITO..CPARC P1 WHERE P1.PANROPER = P.PANROPER AND P1.PANRPARC = P.PANRPARC)  
GROUP BY PANROPER, PADTLIQ  
  
--cria temp aberto  
SELECT PANROPER, MIN(PANRPARC) AS PANRPARC INTO #TEMP_ABERTO FROM CDCSANTANAMICROCREDITO..CPARC P (NOLOCK) WHERE  
PADTLIQ IS NULL  AND PACNTRL = (SELECT MAX(PACNTRL) FROM CDCSANTANAMICROCREDITO..CPARC P1 WHERE P1.PANROPER = P.PANROPER AND P1.PANRPARC = P.PANRPARC)  
GROUP BY PANROPER  
  
--cria temp_pulada  
SELECT P.PANROPER AS PAGO_OPER, P.PANRPARC AS PAGO_PARC, A.PANROPER AS ABERTO_OPER, A.PANRPARC AS ABERTO_PARC, REPLICATE (' ',20) AS COD_AGENTE,  
REPLICATE(' ',200) AS NOME_AGENTE, CONVERT(FLOAT,0.0) AS VLR_PARC, 0 AS QTD_PULADA, 0 AS DIASATRASOREVERSAO, REPLICATE (' ',2) AS RATINGREVERSAO,  
CONVERT(FLOAT,0.0) as VLRREVERSAO, CAST('1900-01-01' AS SMALLDATETIME) AS DTVENC_ABERTO, CONVERT(FLOAT,0.0) AS VLRRESULTADO, PADTLIQ  
INTO #TEMP_PULADA FROM #TEMP_PAGO P (NOLOCK) INNER JOIN #TEMP_ABERTO A (NOLOCK) ON P.PANROPER = A.PANROPER  
where convert(int,p.panrparc) - convert(int,a.panrparc) > 1  
  
--atualiza agente e valor da parcela  
UPDATE #TEMP_PULADA SET COD_AGENTE = OPCODORG3, VLR_PARC = OPVLRPARC  
FROM #TEMP_PULADA (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..COPER (NOLOCK) ON OPNROPER = PAGO_OPER   
  
--atualiza agente  
UPDATE #TEMP_PULADA SET NOME_AGENTE = O3DESCR  
FROM #TEMP_PULADA (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON COD_AGENTE = O3CODORG  
  
--atualiza dt vencto aberto  
UPDATE #TEMP_PULADA SET DTVENC_ABERTO = CAST(PADTVCTO AS SMALLDATETIME)  
FROM #TEMP_PULADA (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..CPARC (NOLOCK) ON PANROPER = PAGO_OPER   
WHERE PANRPARC = CONVERT(INT,PAGO_PARC) + 1 AND PADTVCTO < GETDATE()  
  
--atualiza dias de atraso  
UPDATE #TEMP_PULADA SET DIASATRASOREVERSAO = DATEDIFF(D,DTVENC_ABERTO,GETDATE())  
FROM #TEMP_PULADA INNER JOIN RATING_HISTORICO (NOLOCK) ON PAGO_OPER = NUM_OPE  
WHERE DTVENC_ABERTO <> '1900-01-01 00:00:00' AND DTVENCPARC IS NOT NULL  
AND DT_FECHA = @DATAFECH  
  
--atualiza qtd de parcelas puladas  
UPDATE #TEMP_PULADA SET QTD_PULADA = P.TOTAL FROM (  
SELECT PANROPER, COUNT(*) AS TOTAL FROM #TEMP_PULADA (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..CPARC P (NOLOCK) ON PAGO_OPER = PANROPER   
WHERE PAGO_OPER = PANROPER AND PACNTRL = (SELECT MAX(PACNTRL) FROM CDCSANTANAMICROCREDITO..CPARC P1 (NOLOCK) WHERE P1.PANROPER = P.PANROPER AND P1.PANRPARC = P.PANRPARC)  
AND PANRPARC BETWEEN ABERTO_PARC AND PAGO_PARC AND P.PADTLIQ IS NULL GROUP BY PANROPER) AS P  
WHERE PAGO_OPER = PANROPER  
  
--ATUALIZA RATING  
UPDATE #TEMP_PULADA SET RATINGREVERSAO =   
CASE WHEN DIASATRASOREVERSAO BETWEEN 6 AND 14 THEN 'A'  
WHEN DIASATRASOREVERSAO BETWEEN 15 AND 30 THEN 'B'  
WHEN DIASATRASOREVERSAO BETWEEN 31 AND 60 THEN 'C'  
WHEN DIASATRASOREVERSAO BETWEEN 61 AND 90 THEN 'D'  
WHEN DIASATRASOREVERSAO BETWEEN 91 AND 120 THEN 'E'  
WHEN DIASATRASOREVERSAO BETWEEN 121 AND 150 THEN 'F'  
WHEN DIASATRASOREVERSAO BETWEEN 151 AND 180 THEN 'G'  
WHEN DIASATRASOREVERSAO BETWEEN 181 AND 359 THEN 'H'  
WHEN DIASATRASOREVERSAO >= 360 THEN 'HH' END  
  
--ATUALIZA VALOR  
UPDATE #TEMP_PULADA SET VLRREVERSAO =   
CASE WHEN RATINGREVERSAO = 'A' THEN 0.5/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'B' THEN 1.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'C' THEN 3.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'D' THEN 10.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'E' THEN 30.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'F' THEN 50.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'G' THEN 70.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'H' THEN 100.0/100.0*(SLD_INSCRITO-QTD_PULADA*VLR_PARC)  
WHEN RATINGREVERSAO = 'HH' THEN 0.0  
END  
FROM #TEMP_PULADA INNER JOIN RATING_HISTORICO (NOLOCK) ON PAGO_OPER = NUM_OPE  
WHERE RATINGREVERSAO IS NOT NULL AND DT_FECHA = @DATAFECH  
  
--ATUALIZA RESULTADO  
UPDATE #TEMP_PULADA SET VLRRESULTADO =   
CASE WHEN VLRREVERSAO = 0.0 THEN 0.0  
ELSE convert(FLOAT,VLR_PDD) - convert(FLOAT,VLRREVERSAO) END  
FROM #TEMP_PULADA (NOLOCK) INNER JOIN RATING_HISTORICO (NOLOCK) ON PAGO_OPER = NUM_OPE   
AND DT_FECHA = @DATAFECH  
  
--SELECT *,vlr_pdd,vlrreversao,vlrresultado,RATINGREVERSAO, NVL_RISCO FROM #TEMP_PULADA INNER JOIN RATING_HISTORICO (NOLOCK) ON PAGO_OPER = NUM_OPE  
--WHERE DT_FECHA = @DATAFECH AND NVL_RISCO NOT IN ('HH','A') AND RATINGREVERSAO IS NOT NULL   
----AND PAGO_OPER = '556001373'  
--ORDER BY PAGO_OPER  
  
SELECT   
PAGO_OPER, PAGO_PARC, ABERTO_PARC, QTD_PULADA, A.PADTLIQ, COD_AGENTE, NOME_AGENTE, VLR_PARC, DIASATRASOREVERSAO, Atraso, RATINGREVERSAO, NVL_RISCO,  
VLRREVERSAO, VLRRESULTADO, vlr_pdd, DTVENC_ABERTO, DT_VCTO1, DT_BASE, NOM_CLI, SLD_INSCRITO, VLR_FV, PERC_PDD, parc, dtVencParc, COBRADORA  
FROM #TEMP_PULADA A INNER JOIN RATING_HISTORICO (NOLOCK) ON PAGO_OPER = NUM_OPE  
WHERE DT_FECHA = @DATAFECH AND NVL_RISCO NOT IN ('A') AND RATINGREVERSAO IS NOT NULL   --27/02/2019 - tiago - REMOVI NVL_RISCO = 'HH' para aparecer no relatório
ORDER BY PAGO_OPER  
  
DROP TABLE #TEMP_PAGO  
DROP TABLE #TEMP_ABERTO  
DROP TABLE #TEMP_PULADA