USE SIG
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS 
         WHERE NAME = 'SCR_RECEBIMENTO_PARCELA' AND TYPE = 'P')
   DROP PROCEDURE [DBO].[SCR_RECEBIMENTO_PARCELA]
GO

CREATE PROCEDURE [DBO].[SCR_RECEBIMENTO_PARCELA]
(@DATA_DE SMALLDATETIME,
@DATA_ATE SMALLDATETIME)  AS 
            
BEGIN       

SELECT DISTINCT 
CONTRATO,
DATA_BASE, 
COD_PROD, 
PRODUTO, 
COD_MODALIDADE, 
MODALIDADE,  
PARCELA, 
ATRASO,
DT_VCTO, 
DT_LIQ, 
COD_FINANCEIRO, 
PRINCIPAL_DILUIDO, 
JUROS_PARCELA,
MULTA, 
IOF,  
DESPESAS, 
VALOR_MOVIMENTADO, 
DESCONTO, 
MORA, 
VALOR_TOTAL,
PREJU
FROM AUX_PARC_REC (NOLOCK)
WHERE DT_LIQ>=@DATA_DE AND DT_LIQ<=@DATA_ATE
ORDER BY DT_LIQ

END