'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Paginas
    
    Partial Public Class CnabGerarArquivo
        
        '''<summary>
        '''UpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''txtCessao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCessao As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnCarregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCarregar As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMenu As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnImpressao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnImpressao As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHelp As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''dvCessao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvCessao As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''GridViewCessao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewCessao As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''UpdateProgress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    End Class
End Namespace
