
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go

/*
EXEC [ger_base_contabil_CC] '20150131'
EXEC [ger_base_contabil_CC] '20150228'
EXEC [ger_base_contabil_CC] '20150331'
EXEC [ger_base_contabil_CC] '20150430'
EXEC [ger_base_contabil_CC] '20150531'


SELECT * FROM GER_BASE_BALANCETE_CC (NOLOCK)

SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA = '20150131' AND LEFT(CONTA,1) in ('7','8')


use contabil_santana

-- vazio
select * from centro_custo_rateio_n (nolock)

-- contas 7 e 8
select * from conta_de_custo_filial (nolock)


select * from dbo.DICIONARIO_DADOS (nolock)

-- vazio
select * from dbo.DE_PARA_PCUSTO (nolock)
select * from dbo.DE_PARA_PCUSTO (nolock)

-- 3 li
select * from dbo.GRAU_PLANO_CUSTO (nolock)

-- vazio
select * from dbo.PIS_PLANO_CUSTO (nolock)

select * from dbo.TOTAL_CONTABIL_MENSAL (nolock)

-- 1 lin faixa contas 8
select * from dbo.FAIXA_CUSTOS (nolock)

-- vazio
select * from dbo.GRUPO_RATEIO (nolock)
select * from dbo.RELACOES_CUSTO (nolock)
select * from dbo.BALANCETE_CUSTO_TMP (nolock)

select * from dbo.NOME_PLANO_CUSTO (nolock)
CODX_CONG	NUME_PLAN_CUST	DESC_PLANO_CUST
1	1	PLANO DE CUSTOS FINA
1	10	PLANO DE CUSTO 2014

sp_helptext SPN_BAL_GER_CUSTO

-- lcto e lote
select * from LANCAMENTO_INFORMADO LI  (nolock)                                               
-- lcto historico
select * from      HISTORICO_INFORMADO  HI  (nolock)    
--  lcto centro custo rateados a 100 %       valr_lanc_cent_cust                                                                                                
select * from      RATEIO_INFORMADO     RI   (nolock)  
-- plano de contas                                                                                   
select * from      PLANO_GERAL          PG   (nolock)             
-- deptos com nume_cent_cust                                                                        
select * from      CONTABIL_SANTANA..PLANO_DE_CUSTO       PC   (nolock)  
		WHERE NUME_CENT_CUST='430010000000000000'
-- plano de contas                                                                                                                                                                    
select * from      PLANO_CONTABIL       PL   (nolock)  
-- pg filhas contas                                                                                  
select * from      RELACOES             RL   (nolock)  
-- usuario
select * from      TMP_EMPRESA_FILIAL_N EM   (nolock)                                                                                    

select * from      TOTAL_CONTABIL_MENSAL EM   (nolock) 

select * from     TMP_BALANCETE_GER (nolock) 

SELECT *        FROM APURACAO_POR_FILIAL   (nolock) order by data_apur_sald desc

HIST_LANC_CUS
LINH_LANC_CUS
LINH_LANC_CUST_BAL
LOTE_LANC_CUS
NOME_CENT_CUST
*/
-- PROC CARGA FECHAMENTO por CC **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'ger_base_contabil_CC' AND type = 'P')
   DROP PROCEDURE [dbo].[ger_base_contabil_CC] 
GO

-- MENSAL
-- ***************************************
CREATE Procedure [dbo].[ger_base_contabil_CC] 
 (@DTREF  SMALLDATETIME )	AS  

BEGIN

DECLARE @DTINI  AS DATETIME
DECLARE @DTFIM  AS DATETIME
DECLARE @DTM1   AS DATETIME

-- INICIO DO MES DE REF
SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+'01'
-- NAO CONSIDERAR O MOV DEZ PQ ZERA O BALANCETE !! ****************
IF DATEPART(MONTH,@DTREF)  = 12
BEGIN
	SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+'1101'
END

SET @DTFIM = @DTREF

SET @DTM1 = DATEADD(M,2,@DTINI)
SET @DTM1 = DATEADD(DD,-1,@DTM1)

/*
SELECT * FROM GER_BASE_BALANCETE_CC (NOLOCK)
DROP	TABLE GER_BASE_BALANCETE_CC
CREATE	TABLE GER_BASE_BALANCETE_CC 
(	DT_FECHA	SMALLDATETIME, 
	EMPRESA		INT,
	GRUPO		VARCHAR(20),	
	CONTA		VARCHAR(30), 	
	CONTA_FMT	VARCHAR(50), 	
	DESCR		VARCHAR(200),
	CC			VARCHAR(20),	
	SLD_ANT		FLOAT,
	MOV_DEB		FLOAT,
	MOV_CRED	FLOAT,
	MOV_D_C		FLOAT,
	SLD_ATU		FLOAT,
	DIFERE		FLOAT,
	RESULTA		FLOAT,
	DISTRIB		FLOAT,
	CALC		FLOAT
	)

CREATE INDEX GER_BASE_BALANCETE_IDX1 ON GER_BASE_BALANCETE (DT_FECHA,EMPRESA,GRUPO,CONTA,CC)

Conta Fmtd	Nome  Conta	Sald Ante +/-	Movi Debitos	Movi Creditos	Movi  (D - C)	Sald Atua +/-


SELECT * FROM GER_BASE_BALANCETE (NOLOCK)
DELETE  GER_BASE_BALANCETE
INSERT GER_BASE_BALANCETE  SELECT '20140101',' 80 a 90',1900 ,1979


*/

--  DECLARE @DTREF  DATETIME SET @DTREF ='20150801'
DECLARE @DT_APUR		DATETIME
DECLARE @DT_APUR_OUTRAS	DATETIME
DECLARE @DTINI_APUR		DATETIME
DECLARE @DTINI_APUR_OUTRAS	DATETIME

/*		ANTERIOR ***************************
IF DATEPART(MONTH,@DTREF) < 6
BEGIN 
	-- SET		@DT_APUR = '20141231'
	SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	-- SELECT  @DT_APUR		
	SET		@DTINI_APUR = DATEADD(D,+1,@DT_APUR) -- INICIO DO PERIODO
	SET		@DTINI_APUR_OUTRAS = DATEADD(D,+1,@DT_APUR) -- INICIO DO PERIODO
END
IF DATEPART(MONTH,@DTREF) >= 6  -- FECHAMENTO SEMESTRAL -- SOMENTE EMPRESA 1
BEGIN 
	-- SET		@DT_APUR = '20141231'
	SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0630'
	SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	-- SELECT  @DT_APUR
	IF	DATEPART(MONTH,@DTREF) = 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0601' -- INICIO DO PERIODO DE APURACAO
	END
	IF	DATEPART(MONTH,@DTREF) > 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0701' -- INICIO DO PERIODO DE APURACAO
	END
	SET		@DTINI_APUR_OUTRAS = DATEADD(D,+1,CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231') -- INICIO DO ANO
END

-- DEZ
-- DECLARE @DTREF DATETIME DECLARE @DTINI_APUR DATETIME DECLARE @DTINI_APUR_OUTRAS DATETIME SET @DTREF= '20151231'
	IF	DATEPART(MONTH,@DTREF) = 12
	BEGIN
		--SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1231'
		--SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1201' -- INICIO DO PERIODO DE APURACAO
		SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1231'
		SET		@DTINI_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1201' -- FECHAMENTO GUARDADO NO SALDO DE APURACAO DO ANO
	END
--SELECT @DTREF, @DTINI_APUR, @DTINI_APUR_OUTRAS
*/

SELECT @DTREF, @DT_APUR,@DTINI_APUR,  @DT_APUR_OUTRAS,@DTINI_APUR_OUTRAS
-- @DT_APUR @DTINI_APUR 
             SELECT @DT_APUR =  ( SELECT Max(AP.DATA_APUR_SALD)    
                                        FROM CONTABIL_SANTANA..APURACAO_POR_FILIAL    AP	(NOLOCK),  
                                             CONTABIL_SANTANA..TMP_EMPRESA_FILIAL_N   TM	(NOLOCK)  
                                       WHERE AP.CODX_CONG      = TM.CONG_TMP  
                                         AND AP.CODX_EMPR      = TM.EMPR_TMP  
                                         AND AP.CODX_FILI      = TM.FILI_TMP  
										 AND AP.CODX_EMPR      = 1	
                                         AND AP.DATA_APUR_SALD < @DTREF )  
--SET @DTINI_APUR = DATEADD(DD,+1,@DT_APUR)
	-- SELECT  @DT_APUR
	IF	DATEPART(MONTH,@DTREF) < 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0101' -- INICIO DO PERIODO DE APURACAO
	END
	IF	DATEPART(MONTH,@DTREF) = 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0601' -- INICIO DO PERIODO DE APURACAO
	END
	IF	DATEPART(MONTH,@DTREF) > 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0701' -- INICIO DO PERIODO DE APURACAO
	END

-- @DT_APUR_OUTRAS @DTINI_APUR_OUTRAS 
             SELECT @DT_APUR_OUTRAS =  ( SELECT Max(AP.DATA_APUR_SALD)    
                                        FROM CONTABIL_SANTANA..APURACAO_POR_FILIAL    AP	(NOLOCK),  
                                             CONTABIL_SANTANA..TMP_EMPRESA_FILIAL_N   TM	(NOLOCK)  
                                       WHERE AP.CODX_CONG      = TM.CONG_TMP  
                                         AND AP.CODX_EMPR      = TM.EMPR_TMP  
                                         AND AP.CODX_FILI      = TM.FILI_TMP  
										 AND AP.CODX_EMPR      <> 1	
                                         AND AP.DATA_APUR_SALD < @DTREF )  
-- SET @DTINI_APUR_OUTRAS = DATEADD(DD,+1,@DT_APUR_OUTRAS)
SET		@DTINI_APUR_OUTRAS = DATEADD(D,+1,CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231') -- INICIO DO ANO

SELECT @DTREF, @DT_APUR,@DTINI_APUR,  @DT_APUR_OUTRAS,@DTINI_APUR_OUTRAS

-- LIMPAR PROCESSO ANTERIOR
DELETE FROM GER_BASE_BALANCETE_CC WHERE DT_FECHA=@DTREF

-- JANEIRO : SALDO ANTERIOR = 0	****************  ZERA SALDOS DE DESPESAS NO FIM DO ANO


-- SP_HELP GER_BASE_BALANCETE_CC
-- INCLUIR SALDO INICIAL *****************************************
-- INCLUIR	DE FEV EM DIANTE
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)

--   DECLARE @DTREF DATETIME SET @DTREF ='20150131' DECLARE @DT_APUR DATETIME SET @DT_APUR ='20141231' DECLARE @DTINI_APUR DATETIME SET @DTINI_APUR ='20150101'  DECLARE @DT_APUR_OUTRAS DATETIME SET @DT_APUR_OUTRAS ='20141231'  DECLARE @DTINI_APUR_OUTRAS DATETIME SET @DTINI_APUR_OUTRAS ='20150101' 
SELECT	@DTREF,--*,
		LI.CODX_EMPR,
		'',
		LI.NUME_CONT,
		'',
		'',
		RI.NUME_CENT_CUST,				-- CC
--		0.0, --TOTL_DEBI_SALD_CONT,		-- SLDO MES ANT
-- 
        SUM(RI.VALR_LANC_CENT_CUST),    --  SALD_ANTE_PG_BAL     
		0.0,0.0,0.0,
		0.0, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0

--   DECLARE @DTREF DATETIME SET @DTREF ='20150131' DECLARE @DT_APUR DATETIME SET @DT_APUR ='20141231' DECLARE @DTINI_APUR DATETIME SET @DTINI_APUR ='20150101'  DECLARE @DT_APUR_OUTRAS DATETIME SET @DT_APUR_OUTRAS ='20141231'  DECLARE @DTINI_APUR_OUTRAS DATETIME SET @DTINI_APUR_OUTRAS ='20150101'  select *
      FROM CONTABIL_SANTANA..LANCAMENTO_INFORMADO LI (NOLOCK),                                                                                          
           CONTABIL_SANTANA..RATEIO_INFORMADO     RI (NOLOCK),       
--           CONTABIL_SANTANA..PLANO_GERAL          PG (NOLOCK),                                                                                     
           CONTABIL_SANTANA..PLANO_DE_CUSTO       PC (NOLOCK)
,          CONTABIL_SANTANA..RELACOES             RL (NOLOCK)
--,          TMP_EMPRESA_FILIAL_N EM (NOLOCK)                                                                                         
        WHERE 
/*				PG.CODX_MODE           = RL.CODX_MODE                                      
          AND PG.NUME_CONT_PG        = RL.NUME_CONT_PG                                                                      
          AND */ LI.CODX_CONG           = RL.CODX_CONG                                                                         
          AND LI.NUME_CONT           = RL.NUME_CONT 
          AND RI.NUME_PLAN_CUST      = PC.NUME_PLAN_CUST                                                                    
          AND RI.NUME_CENT_CUST      = PC.NUME_CENT_CUST                                                                    
          AND RI.CODX_CONG           = PC.CODX_CONG     
          AND LI.CODX_CONG           = RI.CODX_CONG                                                                         
          AND LI.CODX_EMPR           = RI.CODX_EMPR                                                                         
          AND LI.CODX_FILI           = RI.CODX_FILI                                                                         
          AND LI.NUME_LANC           = RI.NUME_LANC        
--          AND PG.TIPO_CONT_PG        = 'F'  
			-- LCTOS NO MES @DTINI   @DTREF
         AND 1=1+ CASE WHEN  LI.CODX_EMPR = 1  AND LI.DATA_LOTE BETWEEN @DTINI_APUR AND @DTREF           --  SALD_ANTE_PG_BAL     
              THEN  0
			  WHEN  LI.CODX_EMPR <> 1 AND LI.DATA_LOTE BETWEEN @DTINI_APUR_OUTRAS AND @DTREF                --  SALD_ANTE_PG_BAL     	
              THEN  0  ELSE 1 END
		 GROUP BY 
			LI.CODX_EMPR,
			--LI.DATA_LOTE ,
			LI.NUME_CONT,
			RI.NUME_CENT_CUST		-- CC



-- ATUALIZA OS MOVIMENTOS  *************************************************************************
-- ATUALIZA OS SALDOS  EMPRESA 1
-- SELECT * FROM GER_BASE_BALANCETE_CC  (NOLOCK)
UPDATE	GER_BASE_BALANCETE_CC 
SET		MOV_DEB= DEB
FROM  (	SELECT	@DTREF,
		LI.CODX_EMPR,
		LI.NUME_CONT,
		RI.NUME_CENT_CUST,				-- CC
        SUM(RI.VALR_LANC_CENT_CUST) AS DEB
      FROM CONTABIL_SANTANA..LANCAMENTO_INFORMADO LI (NOLOCK),                                                                                          
           CONTABIL_SANTANA..RATEIO_INFORMADO     RI (NOLOCK),       
           CONTABIL_SANTANA..PLANO_DE_CUSTO       PC (NOLOCK)
,          CONTABIL_SANTANA..RELACOES             RL (NOLOCK)
        WHERE LI.CODX_CONG           = RL.CODX_CONG                                                                         
          AND LI.NUME_CONT           = RL.NUME_CONT 
          AND RI.NUME_PLAN_CUST      = PC.NUME_PLAN_CUST                                                                    
          AND RI.NUME_CENT_CUST      = PC.NUME_CENT_CUST                                                                    
          AND RI.CODX_CONG           = PC.CODX_CONG     
          AND LI.CODX_CONG           = RI.CODX_CONG                                                                         
          AND LI.CODX_EMPR           = RI.CODX_EMPR                                                                         
          AND LI.CODX_FILI           = RI.CODX_FILI                                                                         
          AND LI.NUME_LANC           = RI.NUME_LANC        
		  AND LI.SINAL_LANC='D'		 --  DEB	
			-- LCTOS NO MES @DTINI   @DTREF
         AND 1=1+ CASE WHEN  LI.CODX_EMPR = 1  AND LI.DATA_LOTE BETWEEN @DTINI AND @DTREF          
		               THEN  0  ELSE 1 END
		 GROUP BY 		LI.CODX_EMPR,
						LI.NUME_CONT,
						RI.NUME_CENT_CUST )		AS CC
WHERE	DT_FECHA=@DTREF
	AND CC.CODX_EMPR= EMPRESA
	AND	CC.NUME_CONT= CONTA
	AND	CC.NUME_CENT_CUST= CC

/*          AND LI.CODX_CONG           = EM.CONG_TMP  
          AND LI.CODX_EMPR           = EM.EMPR_TMP                                                                         
          AND LI.CODX_FILI           = EM.FILI_TMP   
          AND EM.USUA_TMP            = @p_USUARIO                
          AND RI.NUME_CENT_CUST     >= CONVERT(NUMERIC(18),@p_CTA_CUSTO_I)  
          AND RI.NUME_CENT_CUST     <= CONVERT(NUMERIC(18),@p_CTA_CUSTO_F)  
          AND PG.NUME_CONT_PG       >= CONVERT(NUMERIC(18),@p_CTA_GEREN_I)  
AND PG.NUME_CONT_PG       <= CONVERT(NUMERIC(18),@p_CTA_GEREN_F)  
          AND LI.DATA_LOTE          >  @v_DATA_APUR        -- Maior que a apuracao  
          AND LI.DATA_LOTE     <= @p_DATA_FINA  
          AND PG.CODX_MODE           = @p_CODX_MODE  
          AND RI.NUME_PLAN_CUST      = @p_NUME_PLAN_CUST   

 FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) 
                         CASE WHEN  LI.DATA_LOTE BETWEEN @DT_APUR AND @DTINI_APUR               --  DATA_REFE_BAL         
                              THEN  @p_DATA_INIC   
                              ELSE  @p_DATA_FINA END,                     

-- plano de contas
JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
			WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
ON SLD.NUME_CONT =PLANO.NUME_CONT 

 WHERE	SLD.data_APUR_sald = @DT_APUR
		-- DEB OU CRED
	AND SLD.SINA_SALD_OLD_APUR  IN ('D','C')
	AND SLD.CODX_EMPR  IN (1)  -- EMPRESA 1 SEMESTRAL
  */

/*

-- ATUALIZA OS SALDOS  *************************************************************************
-- ATUALIZA OS SALDOS  EMPRESA 1
-- SELECT * FROM GER_BASE_BALANCETE_CC  (NOLOCK)
UPDATE	GER_BASE_BALANCETE_CC 
SET		SLD_ANT= SLDO_FIM,
			/*	CASE WHEN SINAL_CTA='C' THEN SLDO_FIM  
					 WHEN SINAL_CTA='D' THEN SLDO_FIM * (-1.0) 
					 ELSE 0.0 END,  */
		SLD_ATU=SLDO_FIM
			/*	CASE WHEN SINAL_CTA='C' THEN SLDO_FIM  
					 WHEN SINAL_CTA='D' THEN SLDO_FIM * (-1.0)
					 ELSE 0.0 END    */
FROM  (	SELECT	SLDO.CODX_EMPR,SLDO.NUME_CONT,
		-- saldos 7 e 8 zerados no semestral anterior: 	
		--		CASE WHEN	LEFT(SLDO.NUME_CONT,1) IN ('7','8') THEN
				-- SOMENTE NOS FECHAMENTOS SEMESTRAIS, USAR OS SALDOS ANTERIORES

				-- DT APUR = 30/6 OU 31/12 USAR OS SALDOS ANTERIORES, SEM ZERAR
				CASE WHEN   @DT_APUR = @DTREF AND DATEPART(MM,@DTREF)=6   THEN
							-- JUNH 0K
							-- TOTL_CRED_OLD_APUR	- TOTL_DEBI_OLD_APUR   ??
							--TOTL_CRED_OLD_APUR	- TOTL_DEBI_OLD_APUR  
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	  
					 WHEN   DATEPART(MM,@DT_APUR) = 12 AND DATEPART(MM,@DTREF)<6   THEN
							-- ATEH JUN OK , COM APURACAO EM DEZ 
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	  -- saldos zerados
								+ ISNULL(MOV_PERIODO,0.0) 
							--VALR_SALD_OLD_APUR			+ ISNULL(MOV_PERIODO,0.0) 

/*  teste nao passou
							--(VALR_SALD_OLD_APUR  ) + ISNULL(MOV_PERIODO,0.0) 
							-- SLDO.VALR_SALD_OLD_APUR
							-- TOTL_cred_CONT_APUR - TOTL_DEBI_CONT_APUR 
							CASE	WHEN SINA_SALD_OLD_APUR='C' THEN SLDO.VALR_SALD_OLD_APUR
									WHEN SINA_SALD_OLD_APUR='D' THEN SLDO.VALR_SALD_OLD_APUR * (-1.0)		
							END  
					 WHEN   @DT_APUR = @DTREF AND DATEPART(MM,@DTREF)=12   THEN
							-- DEZ 0K
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	   */

					 ELSE   --  JUL A DEZ
						CASE	WHEN SINA_SALD_OLD_APUR='C' THEN SLDO.VALR_SALD_OLD_APUR
								WHEN SINA_SALD_OLD_APUR='D' THEN SLDO.VALR_SALD_OLD_APUR * (-1.0)		
							END  
						--  TOTL_cred_CONT_APUR	- TOTL_DEBI_CONT_APUR  -- nao bate
								+ ISNULL(MOV_PERIODO,0.0) 
					 END
				AS SLDO_FIM, 
				ISNULL(MOV_PERIODO,0.0) as mov,
				SINA_SALD_OLD_APUR AS SINAL_CTA 
		FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
							TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR 	,VALR_SALD_OLD_APUR
					FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
					where	data_apur_sald = @DT_APUR  ) AS SLDO
			-- 20141231
			-- and CODX_EMPR=1 AND NUME_CONT='100000000000000000'
			LEFT JOIN 
				-- movimento de 2015 até o fechamento abril
				(select		CODX_EMPR,NUME_CONT,sum(TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT) AS MOV_PERIODO
					 from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
					where	data_refe_sald_cont between @DTINI_APUR AND @DTINI
				-- 20150101 20150401
				--AND  codx_empr=1 AND NUME_CONT='100000000000000000'
					GROUP BY CODX_EMPR,NUME_CONT ) AS MOV
			ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL

WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
	AND CONTA =NUME_CONT 
	AND CODX_EMPR = 1  -- EMPRESA 1

-- ATUALIZA OS SALDOS  EMPRESA OUTRAS  ----------------------------
-- SELECT * FROM GER_BASE_BALANCETE  (NOLOCK)
UPDATE	GER_BASE_BALANCETE_CC 
SET		SLD_ANT=SLDO_FIM,
		SLD_ATU=SLDO_FIM
FROM  (	SELECT	SLDO.CODX_EMPR,SLDO.NUME_CONT,
		-- SALDOS DO INICIO DO ANO
				TOTL_cred_CONT_APUR - TOTL_DEBI_CONT_APUR + ISNULL(MOV_PERIODO,0.0) 
				AS SLDO_FIM, 
				ISNULL(MOV_PERIODO,0.0) as mov,
				SINA_SALD_OLD_APUR AS SINAL_CTA,
				VALR_SALD_OLD_APUR
		FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
							TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR 	, VALR_SALD_OLD_APUR
					FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
					where	data_apur_sald = @DT_APUR_OUTRAS  ) AS SLDO
			-- 20141231
			LEFT JOIN 
				-- movimento de 2015 até o fechamento abril
				(select		CODX_EMPR,NUME_CONT,sum(TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT) AS MOV_PERIODO
					 from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
					where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
				-- 20150101 20150401
					GROUP BY CODX_EMPR,NUME_CONT ) AS MOV
				ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL
WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
	AND CONTA =NUME_CONT 
	AND CODX_EMPR NOT IN ( 1)  --  OUTRAS EMPRESAS
-- FIM  ATUALIZA OS SALDOS  *************************************************************************



-- ************************************
-- INCLUI MOVIMENTOS SEM SLDO DE APURACAO
/*
select * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
	where data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
NOT IN ( SELECT CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
FROM GER_BASE_BALANCETE  (NOLOCK)
WHERE DT_FECHA = '20150430')
-- AND EMPRESA = CODX_EMPR
-- =199100101200000000
*/
-- INCLUIR  EMPRESA 1
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		CRED-DEB, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between @DTINI_APUR AND @DTINI
			and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
			-- SEM SALDOS, MAS COM MOVIMENTOS  ****************************
			NOT IN ( SELECT		CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
						FROM	GER_BASE_BALANCETE  (NOLOCK)
						WHERE	DT_FECHA = @DTREF)
		GROUP BY CODX_EMPR,NUME_CONT ) AS SLD
		-- plano de contas
		JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
					WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
		ON	SLD.NUME_CONT =PLANO.NUME_CONT 
WHERE	SLD.CODX_EMPR = 1 
 --WHERE	SLD.data_APUR_sald = @DT_APUR
		-- DEB OU CRED
	--AND SLD.SINA_SALD_OLD_APUR  IN ('D','C')

-- INCLUIR  EMPRESA 1
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		CRED-DEB, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
			and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
			-- SEM SALDOS, MAS COM MOVIMENTOS
			NOT IN ( SELECT		CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
						FROM	GER_BASE_BALANCETE  (NOLOCK)
						WHERE	DT_FECHA = @DTREF)
		GROUP BY CODX_EMPR,NUME_CONT ) AS SLD
-- plano de contas
JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
			WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
	ON	SLD.NUME_CONT =PLANO.NUME_CONT 
WHERE	SLD.CODX_EMPR <> 1 

-- FIM INCLUIR EMPRESAS


-- ATUALIZA OS MOVIMENTOS  *********************************
UPDATE	GER_BASE_BALANCETE_CC 
SET		MOV_DEB	=TOTL_DEBI_SALD_CONT	,
		MOV_CRED=TOTL_CRED_SALD_CONT	,
		MOV_D_C	=TOTL_DEBI_SALD_CONT - TOTL_CRED_SALD_CONT
FROM	(SELECT		* FROM CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK)
			WHERE	data_refe_sald_cont = @DTINI ) AS T
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND	GER_BASE_BALANCETE_CC.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE_CC.CONTA =NUME_CONT 


-- movimentos qdo APURACAO empresa 1
-- DECLARE @DT_APUR DATETIME SET @DT_APUR= '20140630' DECLARE @DTREF DATETIME SET @DTREF='20140630'
SELECT 	@DTREF , @DT_APUR 
UPDATE	GER_BASE_BALANCETE_CC 
SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
		MOV_CRED=TOTL_CRED_OLD_APUR	,
		MOV_D_C	=TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR ,
					--  ELSE (TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR) * (-1.0)				  END ,
		SLD_ATU =CASE	WHEN SINA_SALD_OLD_APUR ='C' THEN  VALR_SALD_OLD_APUR
						ELSE VALR_SALD_OLD_APUR * (-1.0)	END 
FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
					TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR , VALR_SALD_OLD_APUR
			FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
			where	data_apur_sald = @DT_APUR  ) AS SLDO
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND	@DTREF = @DT_APUR   -- SOMENTE NAS DATAS DE APURACAO, SEM ZERAR CTAS 7 E 8
	AND	GER_BASE_BALANCETE_CC.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE_CC.CONTA =NUME_CONT 
	AND GER_BASE_BALANCETE_CC.EMPRESA = 1  -- SOMENTE EMPRESA 1 SEMESTRAL

-- movimentos qdo APURACAO empresa OUTRAS EXCETO 1 (SEMESTRAL, OUTRAS ANUAL)
-- DECLARE @DT_APUR DATETIME SET @DT_APUR= '20140630' DECLARE @DTREF DATETIME SET @DTREF='20140630'
SELECT 	@DTREF , @DT_APUR 
UPDATE	GER_BASE_BALANCETE_CC 
SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
		MOV_CRED=TOTL_CRED_OLD_APUR	,
		MOV_D_C	=TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR ,
					--  ELSE (TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR) * (-1.0)				  END ,
		SLD_ATU =CASE	WHEN SINA_SALD_OLD_APUR ='C' THEN  VALR_SALD_OLD_APUR
						ELSE VALR_SALD_OLD_APUR * (-1.0)	END 
FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
					TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR , VALR_SALD_OLD_APUR
			FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
			where	data_apur_sald = @DT_APUR_OUTRAS  ) AS SLDO
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND	@DTREF = @DT_APUR_OUTRAS   -- SOMENTE NAS DATAS DE APURACAO, SEM ZERAR CTAS 7 E 8
	AND	GER_BASE_BALANCETE_CC.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE_CC.CONTA   = NUME_CONT 
	AND GER_BASE_BALANCETE_CC.EMPRESA <> 1  -- SOMENTE EMPRESA 1 SEMESTRAL

-- DEZ EXCECAO PQ ZERA SALDOS DE DESPESAS -- PUXAR DO DEZ SALDO APURACAO
-- ATUALIZA OS MOVIMENTOS  ****************
IF DATEPART(MONTH,@DTREF ) = 12 
BEGIN
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
			MOV_CRED=TOTL_CRED_OLD_APUR	,
			MOV_D_C	=TOTL_DEBI_OLD_APUR - TOTL_CRED_OLD_APUR
	FROM	(SELECT		* FROM CONTABIL_SANTANA..SALDO_CONT_APURACAO (NOLOCK)
				WHERE	data_apur_sald = @DT_APUR_OUTRAS ) AS T
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
		AND	GER_BASE_BALANCETE_CC.EMPRESA = CODX_EMPR
		AND GER_BASE_BALANCETE_CC.CONTA =NUME_CONT 
END	

--fim  ATUALIZA OS MOVIMENTOS  *********************************

-- select top 100 * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK)
-- ATUALIZA O PLANO CONTABIL
UPDATE	GER_BASE_BALANCETE_CC 
SET		CONTA_FMT	= NUME_CONT_FMTD	,
		DESCR=NOME_CONT	
		--, 	CONTA_MAE	
FROM	CONTABIL_SANTANA..PLANO_CONTABIL P (NOLOCK)
		--	WHERE	data_refe_sald_cont = @DTREF ) AS P
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND GER_BASE_BALANCETE_CC.CONTA	= P.NUME_CONT 
--	AND	GER_BASE_BALANCETE.EMPRESA  = P.CODX_EMPR

--	 DECLARE @DTREF DATETIME SET @DTREF = '20150430'
--   TODOS OS MESES CALCULAR DESTA FORMA, EXCETO DEZEMBRO
IF NOT ( DATEPART(MONTH,@DTREF) = 12 )
BEGIN
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ANT= SLD_ATU + MOV_DEB - MOV_CRED  --+ MOV_D_C
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 		

	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
END

--    DEZEMBRO   CALCULAR O SALDO ANTERIOR E FAZER O ATUAL
--   O PB NAO ERA O SALDO MAS O MOVIMENTO DE DEZ Q NAO DEVE SER CONSID
--   O SALDO CONSIDERA ATEH NOVEMBRO, SEM MOVIMENTO DE DEZ...
IF DATEPART(MONTH,@DTREF) = 12
BEGIN
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ANT= SLD_ATU + MOV_DEB - MOV_CRED  --+ MOV_D_C
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	-- SO EMPRESA 1?? 
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	--  AJUSTA O SALDO  DE NOV INICIAL E NAO FINAL
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ANT= SLD_ATU
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
		AND	EMPRESA =1
	-- RECALCULA O ATUAL DE DEZ
	UPDATE	GER_BASE_BALANCETE_CC 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
END


--	 DECLARE @DTREF DATETIME SET @DTREF = '20140630'
-- =H760-I760+J760  SLD_ATU - DEB +CRED


-- *********************************** CALCULO DOS SALDOS SE JANEIRO ZERAR O SALDO ANT
/*
UPDATE	GER_BASE_BALANCETE 
SET		SLD_ANT= 0.0,
		SLD_ATU= + MOV_CRED  - MOV_DEB  -- SALDO ATUAL = MOVIMENTO DO MES
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND DATEPART(MM,@DTREF) = 1		-- JAN
*/

-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
-- DECLARE @DTREF	DATETIME	SET		@DTREF = '20150430'
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		EMPRESA,
		'',
		399999999993000000,  -- TESTE
		'3.9.9.99.99.9999-3',
		'Total do Ativo','',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
-- 3.9.9.99.99.9999-3	Total do Ativo
 FROM	(SELECT  EMPRESA,
				 SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
				 SUM (MOV_CRED) - SUM (MOV_DEB) AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM	GER_BASE_BALANCETE_CC (NOLOCK)
		JOIN	CONTABIL_SANTANA..PLANO_CONTABIL (NOLOCK) 
			ON	NUME_CONT = CONTA
		-- ATIVO TTL
		WHERE	DT_FECHA = @DTREF
			AND	CONTA_MAE IN (100000000000000000,200000000000000000,300000000000000000)
		GROUP BY EMPRESA
			 ) AS SLD


-- TTL PASSIVO CALC ********************
-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		EMPRESA,
		'',
		999999999995000000,  -- TESTE
		'9.9.9.99.99.9999-5',
		'Total do Passivo','',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
-- 9.9.9.99.99.9999-5	Total do Passivo
 FROM	(SELECT  EMPRESA,
				 SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
				 SUM (MOV_CRED) - SUM (MOV_DEB)  AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM	GER_BASE_BALANCETE_CC (NOLOCK)
		JOIN	CONTABIL_SANTANA..PLANO_CONTABIL (NOLOCK) 
			ON	NUME_CONT = CONTA
		-- ATIVO TTL
		WHERE	DT_FECHA = @DTREF
			AND	CONTA_MAE IN (400000000000000000,500000000000000000,600000000000000000,700000000000000000,800000000000000000,900000000000000000)
		GROUP BY EMPRESA
			 ) AS SLD




-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
INSERT GER_BASE_BALANCETE_CC 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		99,
		'',
		CONTA,  -- TESTE
		CONTA_FMT,
		DESCR,'',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT  	CONTA,  
					CONTA_FMT,
					DESCR,
					SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
					SUM (MOV_CRED) - SUM (MOV_DEB)  AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM		GER_BASE_BALANCETE_CC (NOLOCK)
		WHERE		DT_FECHA = @DTREF
		GROUP BY	CONTA,  
					CONTA_FMT,
					DESCR		 ) AS SLD


-- TROCAR O SINAL SE MOVIMENTO NEGATIVO
UPDATE	GER_BASE_BALANCETE_CC 
SET		MOV_D_C	= MOV_D_C * (-1.00)  
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND MOV_D_C < 0.0



-- REMOVER MOV E SALDOS ZERADOS
DELETE	GER_BASE_BALANCETE_CC 
WHERE	GER_BASE_BALANCETE_CC.DT_FECHA = @DTREF 
	AND  (	SLD_ANT = 0.0 AND SLD_ATU = 0.0
	AND		MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )


*/

END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
