
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go

/*
 EXEC [ger_CALCULO_CUBO] '20150831'
 EXEC [ger_CALCULO_CUBO] '20150731'
 EXEC [ger_CALCULO_CUBO] '20150630'
 EXEC [ger_CALCULO_CUBO] '20150531'
 EXEC [ger_CALCULO_CUBO] '20150430'
 EXEC [ger_CALCULO_CUBO] '20150331'
 EXEC [ger_CALCULO_CUBO] '20150228'
 EXEC [ger_CALCULO_CUBO] '20150131'
-- 2014
 EXEC [ger_CALCULO_CUBO] '20141231'
 EXEC [ger_CALCULO_CUBO] '20141130'
 EXEC [ger_CALCULO_CUBO] '20141031'
 EXEC [ger_CALCULO_CUBO] '20140930'
 EXEC [ger_CALCULO_CUBO] '20140831'
 EXEC [ger_CALCULO_CUBO] '20140731'
 EXEC [ger_CALCULO_CUBO] '20140630'
 EXEC [ger_CALCULO_CUBO] '20140531'
 EXEC [ger_CALCULO_CUBO] '20140430'
 EXEC [ger_CALCULO_CUBO] '20140331'
 EXEC [ger_CALCULO_CUBO] '20140228'
 EXEC [ger_CALCULO_CUBO] '20140131'
-- 2013
 EXEC [ger_base_contabil] '20131231'
 EXEC [ger_base_contabil] '20131130'
 EXEC [ger_base_contabil] '20131031'
 EXEC [ger_base_contabil] '20130930'
 EXEC [ger_base_contabil] '20130831'
 EXEC [ger_base_contabil] '20130731'
 EXEC [ger_base_contabil] '20130630'
 EXEC [ger_base_contabil] '20130531'
 EXEC [ger_base_contabil] '20130430'
 EXEC [ger_base_contabil] '20130331'
 EXEC [ger_base_contabil] '20130228'
 EXEC [ger_base_contabil] '20130131'

-- 2014
 EXEC [ger_base_contabil] '20141231'
 EXEC [ger_base_contabil] '20141130'
 EXEC [ger_base_contabil] '20141031'
 EXEC [ger_base_contabil] '20140930'
 EXEC [ger_base_contabil] '20140831'
 EXEC [ger_base_contabil] '20140731'
 EXEC [ger_base_contabil] '20140630'
 EXEC [ger_base_contabil] '20140531'
 EXEC [ger_base_contabil] '20140430'
 EXEC [ger_base_contabil] '20140331'
 EXEC [ger_base_contabil] '20140228'
 EXEC [ger_base_contabil] '20140131'


 EXEC [ger_base_contabil] '20150731'
 EXEC [ger_base_contabil] '20150630'
 EXEC [ger_base_contabil] '20150531'
 EXEC [ger_base_contabil] '20150430'
 EXEC [ger_base_contabil] '20150331'
 EXEC [ger_base_contabil] '20150228'
 EXEC [ger_base_contabil] '20150131'


select * from sig..GER_CONTA_CALCULO (nolock)

1.8.8.05.02.001-9  188050200100000000 distribuição Sr Joao

select * from sig..GER_BASE_BALANCETE BAL (NOLOCK) 

select * from sig..GER_BASE_BALANCETE BAL (NOLOCK)  where dt_fecha='20150430' and conta='700000000000000000'
select * from sig..GER_BASE_BALANCETE BAL (NOLOCK)  where dt_fecha='20150430' and conta='909770000100000000'
select * from sig..GER_BASE_BALANCETE BAL (NOLOCK)  where dt_fecha='20150430' and conta='800000000000000000'
309770000000000000
select * from sig..GER_CUBO (NOLOCK) WHERE DT_FECHA='20150430' 

select * from sig..GER_CUBO (NOLOCK) WHERE DT_FECHA='20140731' 

*/
-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'ger_CALCULO_CUBO' AND type = 'P')
   DROP PROCEDURE [dbo].[ger_CALCULO_CUBO] 
GO

-- MENSAL
-- ***************************************
CREATE Procedure [dbo].[ger_CALCULO_CUBO] 
 (@DTREF  SMALLDATETIME )	AS  

BEGIN

DECLARE @DTINI  AS DATETIME
DECLARE @DTFIM  AS DATETIME
DECLARE @DTM1   AS DATETIME

-- INICIO DO MES DE REF
SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+'01'
SET @DTFIM = @DTREF

SET @DTM1 = DATEADD(M,2,@DTINI)
SET @DTM1 = DATEADD(DD,-1,@DTM1)


--  DECLARE @DTREF  DATETIME SET @DTREF ='20150801'
DECLARE @DT_APUR	DATETIME

IF DATEPART(MONTH,@DTREF) <= 6
BEGIN 
	-- SET		@DT_APUR = '20141231'
	SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	-- SELECT  @DT_APUR
END
IF DATEPART(MONTH,@DTREF) > 6  -- FECHAMENTO SEMESTRAL
BEGIN 
	-- SET		@DT_APUR = '20141231'
	SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0630'
	-- SELECT  @DT_APUR
END

DECLARE @DTINI_APUR	DATETIME
SET		@DTINI_APUR = DATEADD(D,+1,@DT_APUR) -- INICIO DO PERIODO

-- LIMPAR PROCESSO ANTERIOR
DELETE FROM GER_CUBO WHERE DT_FECHA=@DTREF

DELETE CUBO_POSIT
DELETE CUBO_NEGAT

-- SELECT * FROM GER_CONTA_CALCULO (NOLOCK)
-- SELECT * FROM CUBO_POSIT (NOLOCK)
-- SELECT * FROM CUBO_NEGAT (NOLOCK)
/*
SELECT  BAL.EMPRESA,CTA.COD_CONTA , 
		SUM(CASE 
				 WHEN CONTA_CAMPO='SLD_ANT'  THEN ISNULL(SLD_ANT,0.0)
				 WHEN CONTA_CAMPO='MOV_DEB'  THEN ISNULL(MOV_DEB,0.0)
				 WHEN CONTA_CAMPO='MOV_CRED' THEN ISNULL(MOV_CRED,0.0)
				 WHEN CONTA_CAMPO='MOV_D_C'  THEN ISNULL(MOV_D_C,0.0)
				 WHEN CONTA_CAMPO='SLD_ATU'  THEN ISNULL(SLD_ATU,0.0)
			END			) AS VLR
	FROM	(SELECT * FROM GER_BASE_BALANCETE B (NOLOCK) 
				WHERE	B.DT_FECHA='20140731' ) AS BAL
	JOIN	GER_CONTA_CALCULO CTA  (NOLOCK) 		
		ON	BAL.CONTA = CTA.CONTA_CALCULO
WHERE	CTA.SINAL = '+'
GROUP BY BAL.EMPRESA,CTA.COD_CONTA

SELECT MAIS.DT_FECHA,MAIS.EMPRESA , MAIS.COD_CONTA, ISNULL(MAIS.VLR,0.0) - ISNULL(MENOS.VLR,0.0) AS VLR_RESULT
FROM  CUBO_POSIT MAIS (NOLOCK) LEFT JOIN CUBO_NEGAT MENOS (NOLOCK) ON
MAIS.DT_FECHA = MENOS.DT_FECHA AND MAIS.EMPRESA = MENOS.EMPRESA AND MAIS.COD_CONTA = MENOS.COD_CONTA
*/
INSERT  CUBO_POSIT
SELECT  @DTREF,BAL.EMPRESA,CTA.COD_CONTA , 
		SUM(CASE 
				 WHEN CONTA_CAMPO='SLD_ANT'  THEN ISNULL(SLD_ANT,0.0)
				 WHEN CONTA_CAMPO='MOV_DEB'  THEN ISNULL(MOV_DEB,0.0)
				 WHEN CONTA_CAMPO='MOV_CRED' THEN ISNULL(MOV_CRED,0.0)
				 WHEN CONTA_CAMPO='MOV_D_C'  THEN ISNULL(MOV_D_C,0.0)
				 WHEN CONTA_CAMPO='SLD_ATU'  THEN ISNULL(SLD_ATU,0.0)
			END			) AS VLR
	FROM	(SELECT * FROM GER_BASE_BALANCETE B (NOLOCK) 
				WHERE	B.DT_FECHA=@DTREF ) AS BAL
	JOIN	GER_CONTA_CALCULO CTA  (NOLOCK) 		
		ON	BAL.CONTA = CTA.CONTA_CALCULO
WHERE	-- BAL.DT_FECHA=@DTREF	AND 
		 CTA.SINAL = '+'
GROUP BY BAL.EMPRESA,CTA.COD_CONTA


INSERT  CUBO_NEGAT
SELECT  @DTREF,BAL.EMPRESA,CTA.COD_CONTA , 
			SUM(CASE 
				 WHEN CONTA_CAMPO='SLD_ANT'  THEN ISNULL(SLD_ANT,0.0)
				 WHEN CONTA_CAMPO='MOV_DEB'  THEN ISNULL(MOV_DEB,0.0)
				 WHEN CONTA_CAMPO='MOV_CRED' THEN ISNULL(MOV_CRED,0.0)
				 WHEN CONTA_CAMPO='MOV_D_C'  THEN ISNULL(MOV_D_C,0.0)
				 WHEN CONTA_CAMPO='SLD_ATU'  THEN ISNULL(SLD_ATU,0.0)
			END			) AS VLR
	FROM	GER_BASE_BALANCETE BAL (NOLOCK) 
	JOIN	GER_CONTA_CALCULO CTA  (NOLOCK) 		
		ON	BAL.CONTA = CTA.CONTA_CALCULO
WHERE	BAL.DT_FECHA=@DTREF
	AND CTA.SINAL = '-'
GROUP BY BAL.EMPRESA,CTA.COD_CONTA


-- *****************
-- INCLUIR cubo positivo
INSERT GER_CUBO 
(	DT_FECHA	, 
	EMPRESA		,
	COD_CONTA	, 
	VLR			)
SELECT MAIS.DT_FECHA,MAIS.EMPRESA , MAIS.COD_CONTA, ISNULL(MAIS.VLR,0.0) - ISNULL(MENOS.VLR,0.0) AS VLR_RESULT
FROM  CUBO_POSIT MAIS (NOLOCK) LEFT JOIN CUBO_NEGAT MENOS (NOLOCK) ON
MAIS.DT_FECHA = MENOS.DT_FECHA AND MAIS.EMPRESA = MENOS.EMPRESA AND MAIS.COD_CONTA = MENOS.COD_CONTA


-- INCLUIR cubo negativo sem o positivo  *******************
INSERT GER_CUBO 
(	DT_FECHA	, 
	EMPRESA		,
	COD_CONTA	, 
	VLR			)
SELECT MENOS.DT_FECHA,MENOS.EMPRESA , MENOS.COD_CONTA, MENOS.VLR * (-1.0)  AS VLR_RESULT
FROM   CUBO_NEGAT MENOS (NOLOCK) 
WHERE  MENOS.DT_FECHA  =@DTREF AND CONVERT(VARCHAR(2),MENOS.EMPRESA) + '-' + MENOS.COD_CONTA
 NOT IN (SELECT CONVERT(VARCHAR(2),EMPRESA) + '-' + COD_CONTA FROM GER_CUBO (NOLOCK) WHERE DT_FECHA =@DTREF )

/*
DT_FECHA
EMPRESA
GRUPO
CONTA
CONTA_FMT
DESCR
CC
SLD_ANT
MOV_DEB
MOV_CRED
MOV_D_C
SLD_ATU
DIFERE
RESULTA
DISTRIB
CALC
*/

--  ************************************ EXCECAO DEZ 14
/*
result
result_acumulado
result_distrib  
SELECT * FROM GER_CUBO (NOLOCK) WHERE DATEPART(MM,DT_FECHA)  =12 AND COD_CONTA
select * from GER_CONTA_CALCulo (nolock)  where cod_conta ='result' 
select * from GER_CONTA_CALCulo (nolock)  where cod_conta ='result_acumulado' 

*/

-- SE JAN AJUSTE  ****************************** EMPRESA 1
IF DATEPART(MM,@DTREF)  =1  -- JAN
BEGIN
	-- RESULT = RESULT_ACUMULADO
	UPDATE	GER_CUBO	
	SET		VLR= 	(SELECT		G1.VLR AS RES FROM GER_CUBO G1 (NOLOCK) 
						WHERE	G1.DT_FECHA  = @DTREF  AND  G1.COD_CONTA IN ( 'result_acumulado')
							AND	G1.EMPRESA = 1) 
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA IN ('result')
		AND GER_CUBO.EMPRESA   = 1		-- 1

	-- RESULT = RESULT_ACUMULADO
	UPDATE	GER_CUBO	
	SET		VLR= 	(SELECT		G1.VLR AS RES FROM GER_CUBO G1 (NOLOCK) 
						WHERE	G1.DT_FECHA  = @DTREF  AND  G1.COD_CONTA IN ('Result Acumulado')
							AND	G1.EMPRESA = 1) 
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA IN ('Lucro')
		AND GER_CUBO.EMPRESA   = 1		-- 1
 
	-- RESULT_DISTRIB  = RESULT_ACUMULADO - result_cont
	UPDATE	GER_CUBO	
	SET		VLR= 	ISNULL((SELECT	VLR AS RES FROM GER_CUBO G1 (NOLOCK) 
							WHERE	G1.DT_FECHA  = @DTREF  AND G1.COD_CONTA IN ( 'result_acumulado')
								AND	G1.EMPRESA = 1) ,0.0) 
				  - ISNULL((SELECT	VLR AS RES FROM GER_CUBO G2 (NOLOCK) 
							WHERE	G2.DT_FECHA  = @DTREF  AND G2.COD_CONTA IN ( 'result_CONT')
								AND	G2.EMPRESA = 1) ,0.0)
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA  IN ( 'result_distrib' )
		AND GER_CUBO.EMPRESA   = 1		-- 1  contas antigas

	-- RESULT_DISTRIB  = RESULT_ACUMULADO - result_cont
	UPDATE	GER_CUBO	
	SET		VLR= 	ISNULL((SELECT	VLR AS RES FROM GER_CUBO G1 (NOLOCK) 
							WHERE	G1.DT_FECHA  = @DTREF  AND G1.COD_CONTA IN ('Result Acumulado')
								AND	G1.EMPRESA = 1) ,0.0) 
				  - ISNULL((SELECT	VLR AS RES FROM GER_CUBO G2 (NOLOCK) 
							WHERE	G2.DT_FECHA  = @DTREF  AND G2.COD_CONTA IN ('Resultado Contabil')
								AND	G2.EMPRESA = 1) ,0.0)
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA  IN ('Resultado Distribuição')
		AND GER_CUBO.EMPRESA   = 1		-- 1

END

-- SE DEZ AJUSTE  ****************************** EMPRESA 2,3,4
IF DATEPART(MM,@DTREF)  =12 
BEGIN
	-- RESULT DISTRIB  TROCAR O SINAL
	UPDATE	GER_CUBO SET VLR= VLR * (-1.0) 
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND COD_CONTA  IN ( 'result_distrib' )
		AND GER_CUBO.EMPRESA   IN (4)		-- 4

	UPDATE	GER_CUBO SET VLR= RC.VLR + RD.VLR		-- RESULT =  SOMA RC + RD
	FROM	(SELECT *	FROM GER_CUBO C (NOLOCK) 
				WHERE	C.DT_FECHA  = @DTREF AND C.COD_CONTA  IN ( 'result_cont' )
					AND C.EMPRESA   IN (4) ) AS RC,
			(SELECT *	FROM GER_CUBO R (NOLOCK) 
				WHERE	R.DT_FECHA  = @DTREF AND R.COD_CONTA  IN ( 'result_distrib' )
					AND R.EMPRESA   IN (4) ) AS RD
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA  IN ( 'result' )
		AND GER_CUBO.EMPRESA   IN (4)		-- 4
END
/*
IF DATEPART(MM,@DTREF)  =12 
BEGIN
	-- RESULT DISTRIB - MOV_DEB
	UPDATE	GER_CUBO SET VLR= CALCULO 
	FROM	(SELECT		EMPRESA, 
						SUM(MOV_DEB)  * (-1.0)  -- CONSIDERAR NEGATIVO EM DEZ
							AS CALCULO	
				FROM	(SELECT * FROM GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF ) AS BAL
				JOIN	(SELECT *	FROM	GER_CONTA_CALCULO CTA1  (NOLOCK) 	
									WHERE	COD_CONTA  IN ( 'result_distrib' )	) AS CTA
					ON	BAL.CONTA = CTA.CONTA_CALCULO
			GROUP BY EMPRESA) AS CALC
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND COD_CONTA  IN ( 'result_distrib' )
		AND GER_CUBO.EMPRESA   = CALC.EMPRESA
		AND GER_CUBO.EMPRESA   IN (2,4)		-- 2 OU 4

	-- RESULT DISTRIB - MOV_DEB
	UPDATE	GER_CUBO SET VLR= CALCULO 
	FROM	(SELECT		EMPRESA, 
						SUM(MOV_DEB)  * (-1.0)  -- CONSIDERAR NEGATIVO EM DEZ
							AS CALCULO	
				FROM	(SELECT * FROM GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF ) AS BAL
				JOIN	(SELECT *	FROM	GER_CONTA_CALCULO CTA1  (NOLOCK) 	
									WHERE	COD_CONTA  IN ('Resultado Distribuição')	) AS CTA
					ON	BAL.CONTA = CTA.CONTA_CALCULO
			GROUP BY EMPRESA) AS CALC
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND COD_CONTA  IN ('Resultado Distribuição')
		AND GER_CUBO.EMPRESA   = CALC.EMPRESA
		AND GER_CUBO.EMPRESA   IN (2,4)		-- 2 OU 4

	-- MUDAR O SINAL DA EMPRESA 2  P/ RESULT_DISTRIB  antes de 17/8/15
	-- UPDATE GER_CUBO SET VLR= VLR * (-1.00) WHERE DT_FECHA  = @DTREF AND COD_CONTA = 'result_distrib' AND EMPRESA IN (2 ,4)

	--		RECALCULAR O RESULT INVERTENDO SINAIS DE CONTAS 1 E 6
	--		select * from GER_CONTA_CALCulo (nolock)  where cod_conta ='result' 

	--result
	-- DECLARE @DTREF DATETIME SET @DTREF = '20141231'
	-- MOV_D_C		'result'
	UPDATE	GER_CUBO SET VLR= CALCULO 
	FROM	(SELECT		EMPRESA, 
						SUM(CASE WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) NOT IN ('6')   THEN MOV_D_C 
								 WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) IN ('6')		 THEN MOV_D_C * (-1.0)  -- CONSIDERAR NEGATIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) IN ('1')		 THEN MOV_D_C   -- CONSIDERAR POSITIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) NOT IN ('1')	 THEN MOV_D_C * (-1.0)  
							END) 	AS CALCULO	
				FROM	(SELECT * FROM GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF ) AS BAL
				JOIN	(SELECT * FROM GER_CONTA_CALCULO CTA1  (NOLOCK) 	WHERE COD_CONTA IN ('result' )	) AS CTA
					ON	BAL.CONTA = CTA.CONTA_CALCULO
			GROUP BY EMPRESA) AS CALC
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND COD_CONTA IN ('result' )
		AND GER_CUBO.EMPRESA =CALC.EMPRESA

	UPDATE	GER_CUBO SET VLR= CALCULO 
	FROM	(SELECT		EMPRESA, 
						SUM(CASE WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) NOT IN ('6')   THEN MOV_D_C 
								 WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) IN ('6')		 THEN MOV_D_C * (-1.0)  -- CONSIDERAR NEGATIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) IN ('1')		 THEN MOV_D_C   -- CONSIDERAR POSITIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) NOT IN ('1')	 THEN MOV_D_C * (-1.0)  
							END) 	AS CALCULO	
				FROM	(SELECT * FROM GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF ) AS BAL
				JOIN	(SELECT * FROM GER_CONTA_CALCULO CTA1  (NOLOCK) 	WHERE COD_CONTA IN ('Lucro' )	) AS CTA
					ON	BAL.CONTA = CTA.CONTA_CALCULO
			GROUP BY EMPRESA) AS CALC
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND COD_CONTA IN ('Lucro' )
		AND GER_CUBO.EMPRESA =CALC.EMPRESA

		-- ALTERADO EM 31/8/15 TESTE
		-- AND GER_CUBO.EMPRESA  NOT IN (2,4)		-- 2 OU 4

		--AND  GER_CUBO.EMPRESA  NOT IN (4)
	--result_acumulado  SLD_ATU
/*  
	UPDATE	GER_CUBO SET VLR= CALCULO 
	FROM	(SELECT		EMPRESA, 
						SUM(CASE WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) NOT IN ('6')   THEN SLD_ATU 
								 WHEN SINAL='+' AND LEFT(CONTA_CALCULO,1) IN ('6')		 THEN SLD_ATU * (-1.0)  -- CONSIDERAR NEGATIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) IN ('1')		 THEN SLD_ATU   -- CONSIDERAR POSITIVO EM DEZ
								 WHEN SINAL='-' AND LEFT(CONTA_CALCULO,1) NOT IN ('1')	 THEN SLD_ATU * (-1.0)  
							END) 	AS CALCULO	
				FROM	(SELECT * FROM GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF ) AS BAL
				JOIN	(SELECT * FROM GER_CONTA_CALCULO CTA1  (NOLOCK) 	WHERE COD_CONTA = 'result_acumulado'	) AS CTA
					ON	BAL.CONTA = CTA.CONTA_CALCULO
			GROUP BY EMPRESA) AS CALC
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA = 'result_acumulado' 
		AND GER_CUBO.EMPRESA  NOT IN ('1')
		AND GER_CUBO.EMPRESA =CALC.EMPRESA
*/
	-- RESULTADO ACUMULADO		618000000000000000   LUCROS OU PREJUÍZOS ACUMULADOS
	--result_acumulado
	UPDATE	GER_CUBO SET VLR= VLR -  MOV_D_C
	FROM	(SELECT		*
				FROM	GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA in ('2','3','4') AND CONTA='618000000000000000') AS BAL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA  IN ( 'result_acumulado', 'Result Acumulado')
		AND GER_CUBO.EMPRESA   IN ('2','3','4')
		AND GER_CUBO.EMPRESA =BAL.EMPRESA


	--613000000000000000   RESERVAS DE CAPITAL
	--result_acumulado
	UPDATE	GER_CUBO SET VLR= VLR -  MOV_D_C
	FROM	(SELECT		*
				FROM	GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA in ('2','3','4') AND CONTA='613000000000000000') AS BAL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF AND GER_CUBO.COD_CONTA  IN ( 'result_acumulado','Result Acumulado')
		AND GER_CUBO.EMPRESA   IN ('2','3','4')
		AND GER_CUBO.EMPRESA =BAL.EMPRESA

	-- RECALCULAR O TTL DE DEZ EMPRESA 99
	-- SELECT * FROM GER_CUBO (NOLOCK)
	UPDATE	GER_CUBO 
	SET VLR= TTL.CALC
	FROM	(SELECT		COD_CONTA,SUM(VLR) AS CALC
				FROM	GER_CUBO T1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA NOT IN ('99')
				GROUP BY  COD_CONTA ) AS TTL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.EMPRESA  = '99'
		AND GER_CUBO.COD_CONTA = TTL.COD_CONTA

END
*/		-- REMOVI DEZ15 ERRO, ALTERADO EM 27/1/16	************************

-- SE JAN-2015 AJUSTE  ****************************** EMPRESA 2
IF DATEPART(MM,@DTREF)  IN ( 1) AND  DATEPART(YYYY,@DTREF) =2015
BEGIN
	UPDATE	GER_CUBO 
	SET VLR= VLR + (BAL.MOV_D_C * 2.0)  -- SOMA, NAO SUBTRAI a conta 5
	FROM	(SELECT		EMPRESA,MOV_D_C
				FROM	GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA in ('2') AND CONTA='500000000000000000') AS BAL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.COD_CONTA IN ( 'result' ,'Resultado','result_cont','result contabil','Resultado Contabil')
		AND GER_CUBO.EMPRESA  = '2'

	-- mudar o sinal
	UPDATE	GER_CUBO 
	SET VLR= VLR * (-1.0)  -- muda sinal
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.COD_CONTA IN ('result_distrib','Resultado Distribuição')
		AND GER_CUBO.EMPRESA  = '2'

	-- RECALCULAR O TTL DE DEZ EMPRESA 99
	-- SELECT * FROM GER_CUBO (NOLOCK)
	UPDATE	GER_CUBO 
	SET VLR= TTL.CALC
	FROM	(SELECT		COD_CONTA,SUM(VLR) AS CALC
				FROM	GER_CUBO T1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA NOT IN ('99')
				GROUP BY  COD_CONTA ) AS TTL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.EMPRESA  = '99'
		AND GER_CUBO.COD_CONTA = TTL.COD_CONTA
	
END

-- SE FEV,MAR-2015 AJUSTE  ****************************** EMPRESA 2
IF DATEPART(MM,@DTREF)  IN ( 2,3) AND  DATEPART(YYYY,@DTREF) =2015
BEGIN
	UPDATE	GER_CUBO 
	SET VLR= VLR - BAL.MOV_D_C
	FROM	(SELECT		EMPRESA,MOV_D_C
				FROM	GER_BASE_BALANCETE BAL1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA in ('2') AND CONTA='500000000000000000') AS BAL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.COD_CONTA IN ( 'result_distrib' ,'Resultado Distribuição')
		AND GER_CUBO.EMPRESA  = '2'
	-- RECALCULAR O TTL DE DEZ EMPRESA 99
	-- SELECT * FROM GER_CUBO (NOLOCK)
	UPDATE	GER_CUBO 
	SET VLR= TTL.CALC
	FROM	(SELECT		COD_CONTA,SUM(VLR) AS CALC
				FROM	GER_CUBO T1 (NOLOCK)  WHERE DT_FECHA  = @DTREF AND EMPRESA NOT IN ('99')
				GROUP BY  COD_CONTA ) AS TTL
	WHERE	GER_CUBO.DT_FECHA  = @DTREF 
		AND GER_CUBO.EMPRESA  = '99'
		AND GER_CUBO.COD_CONTA = TTL.COD_CONTA
	
END

END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
