
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go

/*
EXEC [ger_base_contabil] '20170131'

 EXEC [ger_base_contabil] '20150810'
-- 47 seg mes jul
 EXEC [ger_CALCULO_CUBO] '20150810'
 EXEC [ger_CALCULO_CUBO] '20150731'
 EXEC [dbo].[PRC_GER_RELATORIO] '20150810'
SELECT * FROM GER_RPT_MOD1 (NOLOCK) where dt_fecha='2015-08-10'


 EXEC [dbo].[PRC_GER_RELATORIO] '20150430'

EXEC [dbo].[PRC_GER_RELATORIO] '20150131'


 EXEC [ger_base_contabil] '20151231'
 EXEC [ger_base_contabil] '20151130'
 EXEC [ger_base_contabil] '20151031'

 EXEC [ger_base_contabil] '20150930'

 EXEC [ger_base_contabil] '20150831'
 EXEC [ger_base_contabil] '20150731'

 EXEC [ger_base_contabil] '20150630'
 EXEC [ger_base_contabil] '20150531'

 EXEC [ger_base_contabil] '20150430'
 EXEC [ger_base_contabil] '20150331'
 EXEC [ger_base_contabil] '20150228'
 EXEC [ger_base_contabil] '20150131'
-- 2014
 EXEC [ger_base_contabil] '20141231'
 EXEC [ger_base_contabil] '20141130'
 EXEC [ger_base_contabil] '20141031'
 EXEC [ger_base_contabil] '20140930'
 EXEC [ger_base_contabil] '20140831'
 EXEC [ger_base_contabil] '20140731'
 EXEC [ger_base_contabil] '20140630'
 EXEC [ger_base_contabil] '20140531'
 EXEC [ger_base_contabil] '20140430'
 EXEC [ger_base_contabil] '20140331'
 EXEC [ger_base_contabil] '20140228'
 EXEC [ger_base_contabil] '20140131'
-- 2013
 EXEC [ger_base_contabil] '20131231'
 EXEC [ger_base_contabil] '20131130'
 EXEC [ger_base_contabil] '20131031'
 EXEC [ger_base_contabil] '20130930'
 EXEC [ger_base_contabil] '20130831'
 EXEC [ger_base_contabil] '20130731'
 EXEC [ger_base_contabil] '20130630'
 EXEC [ger_base_contabil] '20130531'
 EXEC [ger_base_contabil] '20130430'
 EXEC [ger_base_contabil] '20130331'
 EXEC [ger_base_contabil] '20130228'
 EXEC [ger_base_contabil] '20130131'

-- 2012
 EXEC [ger_base_contabil] '20121231'
 EXEC [ger_base_contabil] '20121130'
 EXEC [ger_base_contabil] '20121031'
 EXEC [ger_base_contabil] '20120930'
 EXEC [ger_base_contabil] '20120831'
 EXEC [ger_base_contabil] '20120731'
 EXEC [ger_base_contabil] '20120630'
 EXEC [ger_base_contabil] '20120531'
 EXEC [ger_base_contabil] '20120430'
 EXEC [ger_base_contabil] '20120331'
 EXEC [ger_base_contabil] '20120228'
 EXEC [ger_base_contabil] '20120131'

 EXEC [ger_base_contabil] '20150430'
 EXEC [ger_base_contabil] '20150331'
 EXEC [ger_base_contabil] '20150228'
 EXEC [ger_base_contabil] '20150131'

DELETE	GER_BASE_BALANCETE 
WHERE	 (	SLD_ANT = 0.0 AND SLD_ATU = 0.0
	AND		MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )

SELECT DISTINCT DT_FECHA FROM GER_BASE_BALANCETE (NOLOCK)
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=1
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )

-- EMPRESA CONSOLIDADA TTL
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=99
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )

select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock) WHERE NOME_CONT LIKE '%PATRIM%'
-- EMPRESA 2
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=2
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )
-- EMPRESA 3
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=3
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )
-- EMPRESA 4
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=4
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )
-- EMPRESA 5  NT
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=5
AND not ( SLD_ANT = 0.0 AND SLD_ATU = 0.0
 AND	MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )

SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=1
AND CONTA_FMT='1.9.8.99-6'

-- patrimonio
600000000000000000
select top 50 * FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) where nume_cont =600000000000000000 and data_apur_sald = '20141231'
select top 50 * FROM	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL SLD (NOLOCK) where nume_cont =600000000000000000 and data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 

-- TESTES 
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20140630' AND EMPRESA=1
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20140731' AND EMPRESA=1

SELECT DISTINCT EMPRESA FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' 
SELECT * FROM GER_BASE_BALANCETE (NOLOCK) WHERE DT_FECHA='20150430' AND EMPRESA=1
and conta_fmt =

-- dif saldo
199100100400000000
select top 50 * FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) where nume_cont =199100100400000000 and data_apur_sald = '20141231'
select top 50 * FROM	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL SLD (NOLOCK) where nume_cont =199100100400000000 and data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 

-- nao localizou
'1.9.9.10.01.012-6'
select * from CONTABIL_SANTANA..PLANO_CONTABIL where nume_cont_fmtd ='1.9.9.10.01.012-6'
199100101200000000
select top 50 * FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) where nume_cont =199100101200000000 and data_apur_sald= '20141231'
select * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
	where data_refe_sald_cont between '2015-01-01' AND '2015-04-01' and nume_cont =199100101200000000

'1.9.8.99-6'


*/
-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'ger_base_contabil' AND type = 'P')
   DROP PROCEDURE [dbo].[ger_base_contabil] 
GO

-- MENSAL
-- ***************************************
CREATE Procedure [dbo].[ger_base_contabil] 
 (@DTREF  SMALLDATETIME )	AS  

BEGIN

DECLARE @DTINI  AS DATETIME
DECLARE @DTFIM  AS DATETIME
DECLARE @DTM1   AS DATETIME

-- INICIO DO MES DE REF
SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+'01'
-- NAO CONSIDERAR O MOV DEZ PQ ZERA O BALANCETE !! ****************
IF DATEPART(MONTH,@DTREF)  = 12
BEGIN
	-- 2014
	--SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+'1101'
	SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+'1201'
END

SET @DTFIM = @DTREF

SET @DTM1 = DATEADD(M,2,@DTINI)
SET @DTM1 = DATEADD(DD,-1,@DTM1)

/*
DROP	TABLE GER_BASE_BALANCETE
CREATE	TABLE GER_BASE_BALANCETE 
(	DT_FECHA	SMALLDATETIME, 
	EMPRESA		INT,
	GRUPO		VARCHAR(20),	
	CONTA		VARCHAR(30), 	
	CONTA_FMT	VARCHAR(50), 	
	DESCR		VARCHAR(200),
	CC			VARCHAR(20),	
	SLD_ANT		FLOAT,
	MOV_DEB		FLOAT,
	MOV_CRED	FLOAT,
	MOV_D_C		FLOAT,
	SLD_ATU		FLOAT,
	DIFERE		FLOAT,
	RESULTA		FLOAT,
	DISTRIB		FLOAT,
	CALC		FLOAT
	)

CREATE INDEX GER_BASE_BALANCETE_IDX1 ON GER_BASE_BALANCETE (DT_FECHA,EMPRESA,GRUPO,CONTA,CC)

Conta Fmtd	Nome  Conta	Sald Ante +/-	Movi Debitos	Movi Creditos	Movi  (D - C)	Sald Atua +/-


SELECT * FROM GER_BASE_BALANCETE (NOLOCK)
DELETE  GER_BASE_BALANCETE
INSERT GER_BASE_BALANCETE  SELECT '20140101',' 80 a 90',1900 ,1979


*/

--  DECLARE @DTREF  DATETIME SET @DTREF ='20150801'
DECLARE @DT_APUR		DATETIME
DECLARE @DT_APUR_OUTRAS	DATETIME
DECLARE @DTINI_APUR		DATETIME
DECLARE @DTINI_APUR_OUTRAS	DATETIME

IF DATEPART(MONTH,@DTREF) < 6
BEGIN 
	-- SET		@DT_APUR = '20141231'
	SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	-- SELECT  @DT_APUR		
	SET		@DTINI_APUR = DATEADD(D,+1,@DT_APUR) -- INICIO DO PERIODO
	SET		@DTINI_APUR_OUTRAS = DATEADD(D,+1,@DT_APUR) -- INICIO DO PERIODO
END
IF DATEPART(MONTH,@DTREF) >= 6  -- FECHAMENTO SEMESTRAL -- SOMENTE EMPRESA 1
BEGIN 
	-- SET		@DT_APUR = '20141231'
	-- ALTERADO TODAS AS EMPRESAS NAO ZERAM O SALDO EM JUNHO ************** 30/08/17
	-- SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0630'
	SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
	SET		@DT_APUR = @DT_APUR_OUTRAS
	-- SELECT  @DT_APUR
	-- ALTERADO TODAS AS EMPRESAS NAO ZERAM O SALDO EM JUNHO ************** 30/08/17
	/*
	IF	DATEPART(MONTH,@DTREF) = 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0601' -- INICIO DO PERIODO DE APURACAO
	END
	IF	DATEPART(MONTH,@DTREF) > 6
	BEGIN
		SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0701' -- INICIO DO PERIODO DE APURACAO
	END		*/
	SET		@DTINI_APUR_OUTRAS = DATEADD(D,+1,CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231') -- INICIO DO ANO
	SET		@DTINI_APUR = @DTINI_APUR_OUTRAS
END

-- DEZ
-- DECLARE @DTREF DATETIME DECLARE @DTINI_APUR DATETIME DECLARE @DTINI_APUR_OUTRAS DATETIME SET @DTREF= '20151231'
	IF	DATEPART(MONTH,@DTREF) = 12
	BEGIN
		--SET		@DT_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1231'
		--SET		@DTINI_APUR = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1201' -- INICIO DO PERIODO DE APURACAO
		SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1231'

		-- FECHAMENTO DO ANO ATUAL AINDA NAO TEM A APURACAO DE 31-DEZ-15, USAR 14  *************
		SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,DATEADD(YY,-1,@DTREF)))+'1231'
		--SET		@DT_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1231'

		-- P/ 2014 OK, COM APURACAO FINAL OK
		-- SET		@DTINI_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'1201' -- FECHAMENTO GUARDADO NO SALDO DE APURACAO DO ANO
		-- P/ 2015 SEM APURACAO FINAL OK
		SET		@DTINI_APUR_OUTRAS = CONVERT(VARCHAR(4),DATEPART(YYYY,@DTREF))+'0101' -- INICIO DO ANO CORRENTE

		-- ALTERADO TODAS AS EMPRESAS NAO ZERAM O SALDO EM JUNHO ************** 30/08/17
		SET		@DT_APUR = @DT_APUR_OUTRAS
	END
--SELECT @DTREF, @DTINI_APUR, @DTINI_APUR_OUTRAS

-- LIMPAR PROCESSO ANTERIOR
DELETE FROM GER_BASE_BALANCETE WHERE DT_FECHA=@DTREF

-- INCLUIR SALDO INICIAL *****************************************
-- INCLUIR
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		0.0, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) 

-- plano de contas
JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
			WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
ON SLD.NUME_CONT =PLANO.NUME_CONT 

 WHERE	SLD.data_APUR_sald = @DT_APUR
		-- DEB OU CRED
	AND SLD.SINA_SALD_OLD_APUR  IN ('D','C')
	AND SLD.CODX_EMPR  IN (1)  -- EMPRESA 1 SEMESTRAL
-- PLANO DE CONTAS ***********************
-- INCLUIR OUTRAS EMPRESAS
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		0.0, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) 
-- plano de contas
JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
			WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
		ON SLD.NUME_CONT =PLANO.NUME_CONT 
 WHERE	SLD.data_APUR_sald = @DT_APUR_OUTRAS
		-- DEB OU CRED
	AND SLD.SINA_SALD_OLD_APUR  IN ('D','C')
	AND SLD.CODX_EMPR  NOT IN (1)  -- EMPRESA OUTRAS  ANUAL


/*
		-- EXCETO CONTAS Q NAO SAEM NO BALANCETE DO BC
	AND SLD.NUME_CONT NOT IN (SELECT BC.NUME_CONT 
							FROM CONTABIL_SANTANA..BALANCETE_BC BC (NOLOCK) 
							WHERE BC.SAIR_BCXX = 'N')
*/
-- FROM	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK) WHERE	data_refe_sald_cont = @DTINI


-- ATUALIZA OS SALDOS  *************************************************************************
-- ATUALIZA OS SALDOS  EMPRESA 1
-- SELECT * FROM GER_BASE_BALANCETE  (NOLOCK)
UPDATE	GER_BASE_BALANCETE 
SET		SLD_ANT= SLDO_FIM,
			/*	CASE WHEN SINAL_CTA='C' THEN SLDO_FIM  
					 WHEN SINAL_CTA='D' THEN SLDO_FIM * (-1.0) 
					 ELSE 0.0 END,  */
		SLD_ATU=SLDO_FIM
			/*	CASE WHEN SINAL_CTA='C' THEN SLDO_FIM  
					 WHEN SINAL_CTA='D' THEN SLDO_FIM * (-1.0)
					 ELSE 0.0 END    */
FROM  (	SELECT	SLDO.CODX_EMPR,SLDO.NUME_CONT,
		-- saldos 7 e 8 zerados no semestral anterior: 	
		--		CASE WHEN	LEFT(SLDO.NUME_CONT,1) IN ('7','8') THEN
				-- SOMENTE NOS FECHAMENTOS SEMESTRAIS, USAR OS SALDOS ANTERIORES

				-- ALTERADO TODAS AS EMPRESAS NAO ZERAM O SALDO EM JUNHO ************** 30/08/17
				-- DT APUR = 30/6 OU 31/12 USAR OS SALDOS ANTERIORES, SEM ZERAR
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	  -- saldos zerados
								+ ISNULL(MOV_PERIODO,0.0) 
				/*CASE WHEN   @DT_APUR = @DTREF AND DATEPART(MM,@DTREF)=6   THEN
							-- JUNH 0K
							-- TOTL_CRED_OLD_APUR	- TOTL_DEBI_OLD_APUR   ??
							--TOTL_CRED_OLD_APUR	- TOTL_DEBI_OLD_APUR  
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	  
					 WHEN   DATEPART(MM,@DT_APUR) = 12 AND DATEPART(MM,@DTREF)<6   THEN
							-- ATEH JUN OK , COM APURACAO EM DEZ 
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	  -- saldos zerados
								+ ISNULL(MOV_PERIODO,0.0) 
							--VALR_SALD_OLD_APUR			+ ISNULL(MOV_PERIODO,0.0) 
					*/
/*  teste nao passou
							--(VALR_SALD_OLD_APUR  ) + ISNULL(MOV_PERIODO,0.0) 
							-- SLDO.VALR_SALD_OLD_APUR
							-- TOTL_cred_CONT_APUR - TOTL_DEBI_CONT_APUR 
							CASE	WHEN SINA_SALD_OLD_APUR='C' THEN SLDO.VALR_SALD_OLD_APUR
									WHEN SINA_SALD_OLD_APUR='D' THEN SLDO.VALR_SALD_OLD_APUR * (-1.0)		
							END  
					 WHEN   @DT_APUR = @DTREF AND DATEPART(MM,@DTREF)=12   THEN
							-- DEZ 0K
							 TOTL_CRED_CONT_APUR -	TOTL_DEBI_CONT_APUR	   */

				-- ALTERADO TODAS AS EMPRESAS NAO ZERAM O SALDO EM JUNHO ************** 30/08/17
				/*	 ELSE   --  JUL A DEZ
						CASE	WHEN SINA_SALD_OLD_APUR='C' THEN SLDO.VALR_SALD_OLD_APUR
								WHEN SINA_SALD_OLD_APUR='D' THEN SLDO.VALR_SALD_OLD_APUR * (-1.0)		
							END  
						--  TOTL_cred_CONT_APUR	- TOTL_DEBI_CONT_APUR  -- nao bate
								+ ISNULL(MOV_PERIODO,0.0) 
					 END	*/
				AS SLDO_FIM, 
				ISNULL(MOV_PERIODO,0.0) as mov,
				SINA_SALD_OLD_APUR AS SINAL_CTA 
		FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
							TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR 	,VALR_SALD_OLD_APUR
					FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
					where	data_apur_sald = @DT_APUR  ) AS SLDO
			-- 20141231
			-- and CODX_EMPR=1 AND NUME_CONT='100000000000000000'
			LEFT JOIN 
				-- movimento de 2015 até o fechamento abril
				(select		CODX_EMPR,NUME_CONT,sum(TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT) AS MOV_PERIODO
					 from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
					where	data_refe_sald_cont between @DTINI_APUR AND @DTINI
				-- 20150101 20150401
				--AND  codx_empr=1 AND NUME_CONT='100000000000000000'
					GROUP BY CODX_EMPR,NUME_CONT ) AS MOV
			ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL

WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
	AND CONTA =NUME_CONT 
	AND CODX_EMPR = 1  -- EMPRESA 1

-- ATUALIZA OS SALDOS  EMPRESA OUTRAS  ----------------------------
-- SELECT * FROM GER_BASE_BALANCETE  (NOLOCK)
UPDATE	GER_BASE_BALANCETE 
SET		SLD_ANT=SLDO_FIM,
		SLD_ATU=SLDO_FIM
FROM  (	SELECT	SLDO.CODX_EMPR,SLDO.NUME_CONT,
		-- SALDOS DO INICIO DO ANO
				TOTL_cred_CONT_APUR - TOTL_DEBI_CONT_APUR + ISNULL(MOV_PERIODO,0.0) 
				AS SLDO_FIM, 
				ISNULL(MOV_PERIODO,0.0) as mov,
				SINA_SALD_OLD_APUR AS SINAL_CTA,
				VALR_SALD_OLD_APUR
				-- saldo inicial
		FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
							TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR 	, VALR_SALD_OLD_APUR
					FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
					where	data_apur_sald = @DT_APUR_OUTRAS  ) AS SLDO
			-- 20141231
			LEFT JOIN 
				-- movimento de 2015 até o fechamento abril
				(select		CODX_EMPR,NUME_CONT,sum(TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT) AS MOV_PERIODO
					 from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
					where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
				-- 20150101 20150401
					GROUP BY CODX_EMPR,NUME_CONT ) AS MOV
				ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL
WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
	AND CONTA =NUME_CONT 
	AND CODX_EMPR NOT IN ( 1)  --  OUTRAS EMPRESAS

-- SE DEZ ANO CORRENTE 2015



-- FIM  ATUALIZA OS SALDOS  *************************************************************************



-- ************************************
-- INCLUI MOVIMENTOS SEM SLDO DE APURACAO
/*
select * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
	where data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
NOT IN ( SELECT CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
FROM GER_BASE_BALANCETE  (NOLOCK)
WHERE DT_FECHA = '20150430')
-- AND EMPRESA = CODX_EMPR
-- =199100101200000000
*/
-- INCLUIR  EMPRESA 1
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		CRED-DEB, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between @DTINI_APUR AND @DTINI
			and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
			-- SEM SALDOS, MAS COM MOVIMENTOS  ****************************
			NOT IN ( SELECT		CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
						FROM	GER_BASE_BALANCETE  (NOLOCK)
						WHERE	DT_FECHA = @DTREF)
		GROUP BY CODX_EMPR,NUME_CONT ) AS SLD
		-- plano de contas
		JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
					WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
		ON	SLD.NUME_CONT =PLANO.NUME_CONT 
WHERE	SLD.CODX_EMPR = 1 
 --WHERE	SLD.data_APUR_sald = @DT_APUR
		-- DEB OU CRED
	--AND SLD.SINA_SALD_OLD_APUR  IN ('D','C')

-- INCLUIR  EMPRESA 1
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		CODX_EMPR,
		'',
		SLD.NUME_CONT,
		'',
		'','',
		0.0, --TOTL_DEBI_SALD_CONT, -- SLDO MES ANT
		0.0,0.0,0.0,
		CRED-DEB, --TOTL_CRED_SALD_CONT, -- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
			and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
			-- SEM SALDOS, MAS COM MOVIMENTOS
			NOT IN ( SELECT		CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
						FROM	GER_BASE_BALANCETE  (NOLOCK)
						WHERE	DT_FECHA = @DTREF)
		GROUP BY CODX_EMPR,NUME_CONT ) AS SLD
-- plano de contas
JOIN	(select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock)
			WHERE GRAU_CONT NOT IN (7)) AS PLANO  -- NAO APARECER NO BALANCETE
	ON	SLD.NUME_CONT =PLANO.NUME_CONT 
WHERE	SLD.CODX_EMPR <> 1 

-- FIM INCLUIR EMPRESAS

-- ATUALIZA OS SALDOS DAS CONTAS Q NAO ESTAO NO SLDO APURACAO
/*
UPDATE		GER_BASE_BALANCETE 
	SET		SLD_ATU	= 
	FROM	(SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
			and CONVERT(VARCHAR(1),CODX_EMPR)+CONVERT(VARCHAR(30),nume_cont) 
			-- SEM SALDOS, MAS COM MOVIMENTOS
			NOT IN ( SELECT		CONVERT(VARCHAR(1),EMPRESA)+CONVERT(VARCHAR(30),CONTA) 
						FROM	GER_BASE_BALANCETE  (NOLOCK)
						WHERE	DT_FECHA = '20150430')
		GROUP BY CODX_EMPR,NUME_CONT ) AS SLD
*/
/*
1.9.8.99-6
1.9.8.99-6
select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock) WHERE NUME_CONT_FMTD='1.9.8.99-6'
198990000000000000
SELECT *
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_DIARIO (nolock)
		where	data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
			and CODX_EMPR=1 AND nume_cont=198990000000000000
SELECT CODX_EMPR,NUME_CONT,SUM(TOTL_CRED_SALD_CONT) AS CRED,
				SUM(TOTL_DEBI_SALD_CONT) AS DEB
		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
			and CODX_EMPR=1 AND nume_cont=198990000000000000
		GROUP BY CODX_EMPR,NUME_CONT 

1.9.9.10.01.012-6
select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock) WHERE NUME_CONT_FMTD='1.9.9.10.01.012-6'
199100101200000000
SELECT *		from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
		where	data_refe_sald_cont between '2015-01-01' AND '2015-04-01' 
			and CODX_EMPR=1 AND nume_cont=199100101200000000

-- SALDO ??
2.2.4.10-1
select * from CONTABIL_SANTANA..PLANO_CONTABIL (nolock) WHERE NUME_CONT_FMTD='2.2.4.10-1'
224100000000000000
SELECT * FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO SLD (NOLOCK) 
WHERE SLD.NUME_CONT =224100000000000000
AND	SLD.data_APUR_sald = '20141231'

*/
-- select * from TOTAL_CONTABIL_DIARIO where data_refe_sald_cont = '2015-04-30'

-- SELECT *  FROM	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK) WHERE	data_refe_sald_cont = ''

-- ATUALIZA OS MOVIMENTOS  *********************************
UPDATE	GER_BASE_BALANCETE 
SET		MOV_DEB	=TOTL_DEBI_SALD_CONT	,
		MOV_CRED=TOTL_CRED_SALD_CONT	,
		MOV_D_C	=TOTL_DEBI_SALD_CONT - TOTL_CRED_SALD_CONT
FROM	(SELECT		* FROM CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK)
			WHERE	data_refe_sald_cont = @DTINI ) AS T
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND	GER_BASE_BALANCETE.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE.CONTA =NUME_CONT 


-- movimentos qdo APURACAO empresa 1
-- DECLARE @DT_APUR DATETIME SET @DT_APUR= '20140630' DECLARE @DTREF DATETIME SET @DTREF='20140630'
-- SELECT 	@DTREF , @DT_APUR 
UPDATE	GER_BASE_BALANCETE 
SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
		MOV_CRED=TOTL_CRED_OLD_APUR	,
		MOV_D_C	=TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR ,
					--  ELSE (TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR) * (-1.0)				  END ,
		SLD_ATU =CASE	WHEN SINA_SALD_OLD_APUR ='C' THEN  VALR_SALD_OLD_APUR
						ELSE VALR_SALD_OLD_APUR * (-1.0)	END 
FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
					TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR , VALR_SALD_OLD_APUR
			FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
			where	data_apur_sald = @DT_APUR  ) AS SLDO
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND	@DTREF = @DT_APUR   -- SOMENTE NAS DATAS DE APURACAO, SEM ZERAR CTAS 7 E 8
	AND	GER_BASE_BALANCETE.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE.CONTA =NUME_CONT 
	AND GER_BASE_BALANCETE.EMPRESA = 1  -- SOMENTE EMPRESA 1 SEMESTRAL

-- movimentos qdo APURACAO empresa OUTRAS EXCETO 1 (SEMESTRAL, OUTRAS ANUAL)
-- DECLARE @DT_APUR DATETIME SET @DT_APUR= '20140630' DECLARE @DTREF DATETIME SET @DTREF='20140630'
-- SELECT 	@DTREF , @DT_APUR_OUTRAS 
UPDATE	GER_BASE_BALANCETE 
SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
		MOV_CRED=TOTL_CRED_OLD_APUR	,
		MOV_D_C	=TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR ,
					--  ELSE (TOTL_CRED_OLD_APUR - TOTL_DEBI_OLD_APUR) * (-1.0)				  END ,
		SLD_ATU =CASE	WHEN SINA_SALD_OLD_APUR ='C' THEN  VALR_SALD_OLD_APUR
						ELSE VALR_SALD_OLD_APUR * (-1.0)	END 
FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
					TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR , VALR_SALD_OLD_APUR
			FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
			where	data_apur_sald = @DT_APUR_OUTRAS  ) AS SLDO
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND	@DTREF = @DT_APUR_OUTRAS   -- SOMENTE NAS DATAS DE APURACAO, SEM ZERAR CTAS 7 E 8
	AND	GER_BASE_BALANCETE.EMPRESA = CODX_EMPR
	AND GER_BASE_BALANCETE.CONTA   = NUME_CONT 
	AND GER_BASE_BALANCETE.EMPRESA <> 1  -- SOMENTE EMPRESA 1 SEMESTRAL

-- DEZ EXCECAO PQ ZERA SALDOS DE DESPESAS -- PUXAR DO DEZ SALDO APURACAO
-- ATUALIZA OS MOVIMENTOS  ****************
IF DATEPART(MONTH,@DTREF ) = 12 
BEGIN
	UPDATE	GER_BASE_BALANCETE 
	SET		MOV_DEB	=TOTL_DEBI_OLD_APUR	,
			MOV_CRED=TOTL_CRED_OLD_APUR	,
			MOV_D_C	=TOTL_DEBI_OLD_APUR - TOTL_CRED_OLD_APUR
	FROM	(SELECT		* FROM CONTABIL_SANTANA..SALDO_CONT_APURACAO (NOLOCK)
				WHERE	data_apur_sald = @DT_APUR_OUTRAS ) AS T
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
		AND	GER_BASE_BALANCETE.EMPRESA = CODX_EMPR
		AND GER_BASE_BALANCETE.CONTA =NUME_CONT 


END	

--fim  ATUALIZA OS MOVIMENTOS  *********************************

-- select top 100 * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (NOLOCK)
-- ATUALIZA O PLANO CONTABIL
UPDATE	GER_BASE_BALANCETE 
SET		CONTA_FMT	= NUME_CONT_FMTD	,
		DESCR=NOME_CONT	
		--, 	CONTA_MAE	
FROM	CONTABIL_SANTANA..PLANO_CONTABIL P (NOLOCK)
		--	WHERE	data_refe_sald_cont = @DTREF ) AS P
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND GER_BASE_BALANCETE.CONTA	= P.NUME_CONT 
--	AND	GER_BASE_BALANCETE.EMPRESA  = P.CODX_EMPR

--	 DECLARE @DTREF DATETIME SET @DTREF = '20150430'
--   TODOS OS MESES CALCULAR DESTA FORMA, EXCETO DEZEMBRO
IF NOT ( DATEPART(MONTH,@DTREF) = 12 )
BEGIN
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT= SLD_ATU + MOV_DEB - MOV_CRED  --+ MOV_D_C
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 		

	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
END

--  enquanto o saldo de apuracao nao esta fechado, somente a 1 estava com saldo de apuracao
--  apos fev-16 pode retirar
/*
--    DEZEMBRO   CALCULAR O SALDO ANTERIOR E FAZER O ATUAL
--   O PB NAO ERA O SALDO MAS O MOVIMENTO DE DEZ Q NAO DEVE SER CONSID
--   O SALDO CONSIDERA ATEH NOVEMBRO, SEM MOVIMENTO DE DEZ...
IF DATEPART(MONTH,@DTREF) = 12
BEGIN
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT= SLD_ATU + MOV_DEB - MOV_CRED  --+ MOV_D_C
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	-- SO EMPRESA 1?? 
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	--  AJUSTA O SALDO  DE NOV INICIAL E NAO FINAL
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT= SLD_ATU
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
		AND	EMPRESA =1
	-- RECALCULA O ATUAL DE DEZ
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ATU=SLD_ANT  - MOV_DEB + MOV_CRED
	WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
END
*/

--	 DECLARE @DTREF DATETIME SET @DTREF = '20140630'
-- =H760-I760+J760  SLD_ATU - DEB +CRED


-- *********************************** CALCULO DOS SALDOS SE JANEIRO ZERAR O SALDO ANT
/*
UPDATE	GER_BASE_BALANCETE 
SET		SLD_ANT= 0.0,
		SLD_ATU= + MOV_CRED  - MOV_DEB  -- SALDO ATUAL = MOVIMENTO DO MES
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND DATEPART(MM,@DTREF) = 1		-- JAN
*/

-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
-- DECLARE @DTREF	DATETIME	SET		@DTREF = '20150430'
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		EMPRESA,
		'',
		399999999993000000,  -- TESTE
		'3.9.9.99.99.9999-3',
		'Total do Ativo','',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
-- 3.9.9.99.99.9999-3	Total do Ativo
 FROM	(SELECT  EMPRESA,
				 SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
				 SUM (MOV_CRED) - SUM (MOV_DEB) AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM	GER_BASE_BALANCETE (NOLOCK)
		JOIN	CONTABIL_SANTANA..PLANO_CONTABIL (NOLOCK) 
			ON	NUME_CONT = CONTA
		-- ATIVO TTL
		WHERE	DT_FECHA = @DTREF
			AND	CONTA_MAE IN (100000000000000000,200000000000000000,300000000000000000)
		GROUP BY EMPRESA
			 ) AS SLD

--  enquanto o saldo de apuracao nao esta fechado, somente a 1 estava com saldo de apuracao
--  apos fev-16 pode retirar
/*
	-- ******************************* AJUSTE DEZ 15	FEITO EM 27/1/16			***************
IF DATEPART(MONTH,@DTREF) = 12
BEGIN
	-- DECLARE @DTREF DATETIME DECLARE @DTINI DATETIME SET @DTINI='20151201' SET @DTREF='20151231'
	SELECT @DTINI, @DTINI_APUR_OUTRAS,  @DT_APUR_OUTRAS

	UPDATE	GER_BASE_BALANCETE 
	SET		MOV_D_C = ISNULL((TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT),0.0) ,
			MOV_DEB = ISNULL((TOTL_DEBI_SALD_CONT),0.0) ,
			MOV_CRED= ISNULL((TOTL_CRED_SALD_CONT),0.0)
	FROM	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
	--					where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
	--				ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL
	WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
		AND data_refe_sald_cont = @DTINI		-- SLDO DE DEZ
		AND CONTA =NUME_CONT 
	--	AND CODX_EMPR NOT IN ( 1)  --  OUTRAS EMPRESAS  -- NAO TODAS

	-- AJUSTE DOS SALDOS
	-- DECLARE @DTREF DATETIME DECLARE @DT_APUR_OUTRAS DATETIME SET @DT_APUR_OUTRAS='20141231' SET @DTREF='20151231' DECLARE @DTINI_APUR_OUTRAS DATETIME SET @DTINI_APUR_OUTRAS='20150101' DECLARE @DTINI DATETIME SET @DTINI='20151201'
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT=SLDO_FIM,
			SLD_ATU=SLDO_FIM
	FROM  (	SELECT	SLDO.CODX_EMPR,SLDO.NUME_CONT,
					-- SALDOS DO INICIO DO ANO
					CASE WHEN SINA_SALD_OLD_APUR = 'D' 
						 THEN ISNULL(VALR_SALD_OLD_APUR,0.0)*(-1.0) + ISNULL(MOV_PERIODO,0.0)  
						 ELSE ISNULL(VALR_SALD_OLD_APUR,0.0)        + ISNULL(MOV_PERIODO,0.0)  	END
								AS SLDO_FIM, 
					ISNULL(MOV_PERIODO,0.0) as mov,
					SINA_SALD_OLD_APUR AS SINAL_CTA,
					VALR_SALD_OLD_APUR
					-- saldo inicial
			FROM	(select		CODX_EMPR,NUME_CONT,TOTL_cred_CONT_APUR,TOTL_DEBI_CONT_APUR  , SINA_SALD_OLD_APUR    ,
								TOTL_CRED_OLD_APUR	, TOTL_DEBI_OLD_APUR 	, VALR_SALD_OLD_APUR
						FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
						where	data_apur_sald = @DT_APUR_OUTRAS  ) AS SLDO
				-- 20141231
				LEFT JOIN 
					-- movimento de 2015 até o fechamento abril
					(select		CODX_EMPR,NUME_CONT,sum(TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT) AS MOV_PERIODO
						 from	CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
						where	data_refe_sald_cont between @DTINI_APUR_OUTRAS AND @DTINI
					-- 20150101 20151201
						GROUP BY CODX_EMPR,NUME_CONT ) AS MOV
					ON MOV.CODX_EMPR=SLDO.CODX_EMPR AND MOV.NUME_CONT=SLDO.NUME_CONT ) AS TTL
	WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
		AND CONTA =NUME_CONT 
		AND EMPRESA NOT IN ( 1)  --  OUTRAS EMPRESAS

	-- EMPRESA 1 EXCECAO TEM APURACAO CONTABIL	SLDO	********************
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT=CASE WHEN SINA_SALD_OLD_APUR = 'D' 
						 THEN ISNULL(VALR_SALD_OLD_APUR,0.0)*(-1.0) 
						 ELSE ISNULL(VALR_SALD_OLD_APUR,0.0)          	END,
			SLD_ATU=CASE WHEN SINA_SALD_OLD_APUR = 'D' 
						 THEN ISNULL(VALR_SALD_OLD_APUR,0.0)*(-1.0)   
						 ELSE ISNULL(VALR_SALD_OLD_APUR,0.0)          	END
	FROM	CONTABIL_SANTANA..SALDO_CONT_APURACAO   SA (nolock)
	WHERE	data_apur_sald = @DTREF 
		AND	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
		AND CONTA	 = NUME_CONT 
		AND EMPRESA  IN ( 1)  --  OUTRAS EMPRESAS


	-- AJUSTA SLDO ANT
	UPDATE	GER_BASE_BALANCETE 
	SET		SLD_ANT = SLD_ATU - MOV_D_C
	WHERE	DT_FECHA = @DTREF
	--	AND EMPRESA NOT IN ( 1)  --  OUTRAS EMPRESAS

	-- EXCECAO : EMPRESA 1 COM SLDO DE APURACAO ******************** CONTAS 7  E   8	SALDOS ZERADOS
	UPDATE	GER_BASE_BALANCETE 
	SET		MOV_CRED= ISNULL((TOTL_CRED_SALD_CONT),0.0),
			SLD_ANT = ISNULL((TOTL_CRED_SALD_CONT - TOTL_DEBI_SALD_CONT),0.0) * (-1.0)
	FROM	(SELECT * FROM CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
				WHERE data_refe_sald_cont = @DTINI		-- SLDO DE DEZ
				AND CODX_EMPR IN ( 1)			) AS TTL		--  SOMENTE NA 1
	WHERE	DT_FECHA = @DTREF AND EMPRESA = CODX_EMPR
		AND CONTA	 = NUME_CONT 
		AND LEFT(CONTA,1) IN ('7','8')		-- SOMENTE CONTAS 7 E 8
	--  CALCULOS
	UPDATE	GER_BASE_BALANCETE 
	SET		MOV_D_C  = ISNULL((SLD_ATU - SLD_ANT ),0.0) ,		-- MOVIMENTO PELA DIFERENCA DE SALDOS
			MOV_DEB  = ISNULL((MOV_CRED - MOV_D_C ),0.0)
	WHERE	DT_FECHA = @DTREF 
		AND EMPRESA  IN ( 1)  --  SOMENTE NA 1
		AND LEFT(CONTA,1) IN ('7','8')		-- SOMENTE CONTAS 7 E 8


	-- FIM  EXCECAO : EMPRESA 1 COM SLDO DE APURACAO ******************** CONTAS 7  E   8	SALDOS ZERADOS

	-- AJUSTA MOV_D_C SEM SINAL
	UPDATE	GER_BASE_BALANCETE 
	SET		MOV_D_C = MOV_D_C * (-1.0)		-- POSITIVO
	WHERE	DT_FECHA = @DTREF
		AND MOV_D_C  < 0.0   -- NEGATIVO
	--	AND EMPRESA NOT IN ( 1)  --  OUTRAS EMPRESAS
END
*/

-- TTL PASSIVO CALC ********************
-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		EMPRESA,
		'',
		999999999995000000,  -- TESTE
		'9.9.9.99.99.9999-5',
		'Total do Passivo','',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
-- 9.9.9.99.99.9999-5	Total do Passivo
 FROM	(SELECT  EMPRESA,
				 SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
				 SUM (MOV_CRED) - SUM (MOV_DEB)  AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM	GER_BASE_BALANCETE (NOLOCK)
		JOIN	CONTABIL_SANTANA..PLANO_CONTABIL (NOLOCK) 
			ON	NUME_CONT = CONTA
		-- ATIVO TTL
		WHERE	DT_FECHA = @DTREF
			AND	CONTA_MAE IN (400000000000000000,500000000000000000,600000000000000000,700000000000000000,800000000000000000,900000000000000000)
		GROUP BY EMPRESA
			 ) AS SLD




-- TTL ATIVO   CALC ********************
-- INCLUIR ATIVO
INSERT GER_BASE_BALANCETE 
(	DT_FECHA	, 
	EMPRESA		,
	GRUPO		,	
	CONTA		, 	
	CONTA_FMT	,
	DESCR		,
	CC			,	
	SLD_ANT		,
	MOV_DEB		,
	MOV_CRED	,
	MOV_D_C		,
	SLD_ATU		,
	DIFERE		,
	RESULTA		,
	DISTRIB		,
	CALC		
	)
SELECT	@DTREF,
		99,
		'',
		CONTA,  -- TESTE
		CONTA_FMT,
		DESCR,'',
		SLDA, -- -- SLDO MES ANT
		DEB,CRED,MOV,
		SLDATU, ---- SLDO ATU
		0.0,0.0,0.0,0.0
 FROM	(SELECT  	CONTA,  
					CONTA_FMT,
					DESCR,
					SUM (SLD_ANT) AS SLDA, SUM (MOV_DEB) AS DEB, SUM (MOV_CRED) AS CRED, 
					SUM (MOV_CRED) - SUM (MOV_DEB)  AS MOV , SUM (SLD_ATU) AS SLDATU  
		FROM		GER_BASE_BALANCETE (NOLOCK)
		WHERE		DT_FECHA = @DTREF
		GROUP BY	CONTA,  
					CONTA_FMT,
					DESCR		 ) AS SLD


-- TROCAR O SINAL SE MOVIMENTO NEGATIVO
UPDATE	GER_BASE_BALANCETE 
SET		MOV_D_C	= MOV_D_C * (-1.00)  
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND MOV_D_C < 0.0



-- REMOVER MOV E SALDOS ZERADOS
DELETE	GER_BASE_BALANCETE 
WHERE	GER_BASE_BALANCETE.DT_FECHA = @DTREF 
	AND  (	SLD_ANT = 0.0 AND SLD_ATU = 0.0
	AND		MOV_DEB	= 0.0 AND MOV_CRED = 0.0 AND 	MOV_D_C = 0.0 )


-- 30/08/2017 ************** INCLUI AJUSTE DE CONTAS FORMATADAS
UPDATE		GER_BASE_BALANCETE SET CONTA_FMT = LEFT(CONTA,1)+' .7' 
	WHERE	DT_FECHA=@DTREF	
		AND CONTA IN (100000000000000000,200000000000000000,300000000000000000,400000000000000000,500000000000000000,600000000000000000,700000000000000000,800000000000000000,900000000000000000)


/*
-- >
				 CASE	WHEN LEFT(CONTA,1) IN (1,2,3) THEN 'A' 
						WHEN LEFT(CONTA,1) IN (4,5,6,7,8,9) THEN 'P' END , 

*/


/*
SELECT TOP 100 * FROM CONTABIL_SANTANA..PLANO_CONTABIL (NOLOCK)
SELECT * FROM GER_BASE_BALANCETE  (NOLOCK)
-- inicio
select min(data_refe_sald_cont) from dbo.TOTAL_CONTABIL_MENSAL (nolock)
2008-12-01 00:00:00.000


select * from dbo.TOTAL_CONTABIL_MENSAL (nolock)
where data_refe_sald_cont = '2015-04-01' and CODX_EMPR=1

select * from CONTABIL_SANTANA..TOTAL_CONTABIL_MENSAL (nolock)
where data_refe_sald_cont = '2014-05-01'

-- MOVIM
select * from dbo.TOTAL_CONTABIL_MENSAL (nolock)
where data_refe_sald_cont = '2015-04-01' and codx_empr=1 order by nume_cont


select * from CONTABIL_SANTANA..SALDO_CONT_APURACAO (nolock) where data_apur_sald ='20150401'

select * from dbo.BALANCETE_BC (nolock)  -- s ou n

select * from dbo.SALDO_AJUSTE
select * from dbo.SALDO_MEDIO
select * from dbo.TMP_SALDOS_SINT_XML
select * from dbo.TMP_TEMPLATE_SINT_XML

select * from dbo.TMP_BALANCETE_GER
select * from dbo.BALANCETE_TMP
select * from dbo.BALANCETE_CUSTO_TMP
select * from dbo.GAR_SALDO
select * from dbo.GRAU_MODELO_GERAL
select * from dbo.HISTORICO_INFORMADO

select * from dbo.HISTORICO_PADRAO

-- plano de contas
select * from CONTABIL_SANTANA..PLANO_CONTABIL

select * from dbo.PLANO_CONTABIL_PERM
select * from dbo.PLANO_CONTABIL_LOG

-- CC
select * from dbo.PLANO_DE_CUSTO

--saldo dia
select * from TOTAL_CONTABIL_DIARIO
where data_refe_sald_cont = '2014-12-31'

where data_refe_sald_cont = '2015-01-31'


select * from TOTAL_CONTABIL_mensal
where data_refe_sald_cont = '2014-01-01'

select * from sig..spread_historico (nolock) where dt_fecha between '20150401' and '20150430'
select * from 
select * from 
*/

END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
