'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Paginas.Financeiro

    Partial Public Class OperacaoCaptacao

        '''<summary>
        '''UpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''btnDataAnterior2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnterior2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtDataRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataRef As Global.Componentes.Datax

        '''<summary>
        '''btnProximaData2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaData2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDataAnterior1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnterior1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtDataAplicacao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataAplicacao As Global.Componentes.Datax

        '''<summary>
        '''btnProximaData1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaData1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlCliente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCliente As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnEditar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditar As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ddlAtivo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAtivo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtAtivo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAtivo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnCarregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCarregar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMenu As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''btnImpressao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnImpressao As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''btnHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHelp As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''chkCdi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCdi As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtValorCdi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtValorCdi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDataVencimento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataVencimento As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtValorCaptado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtValorCaptado As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCorretor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCorretor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTipoTaxa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTipoTaxa As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTaxaIntermed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaxaIntermed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTaxaCliente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaxaCliente As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCodigoPapel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCodigoPapel As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTaxaFinal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaxaFinal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''dvConsultas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvConsultas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''GridView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdateProgress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

        '''<summary>
        '''hfGridView1SV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SV As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfGridView1SH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SH As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
