SELECT TOP 2000 * FROM FINCILDBS..CILTBLNCV3040 (NOLOCK) WHERE NCCDATREF='20180131'

-- VALOR NO VENCIMENTO

SELECT TOP 2000 * FROM FINCILDBS..CILTBLOCS3082 (NOLOCK)
-- VAZIO

SELECT TOP 2000 * FROM FINCILDBS..CILTBLOPE (NOLOCK)
-- COSIF   Cargas   contratos
 WHERE NCCDATREF='20180131'

 use FINCILDBS
SELECT TOP 200 * FROM  [dbo].[ciltblnop] (NOLOCK)
-- codigos natureza da Operação   proprias cedidas

SELECT TOP 200 * FROM  [dbo].[CILTBLOSCBACEN] (NOLOCK)
--vazia

SELECT TOP 200 * FROM  [dbo].[CILTBLSCRBACEN] (NOLOCK)
--vazia

SELECT TOP 200 * FROM  [dbo].[CILTBLTMPNCO3040] (NOLOCK)
--vazia

SELECT TOP 200 * FROM  [dbo].[ciltbltit] (NOLOCK)
--vazia

SELECT TOP 200 * FROM  [dbo].[ciltbltop] (NOLOCK)
--vazia

SELECT TOP 200 * FROM  [dbo].CILTBLTPC (NOLOCK)
--tipo de financiamento

SELECT TOP 200 * FROM  [dbo].CILTBLrat (NOLOCK) WHERE RATDATREF='20180131'
-- rating RATvalSALDO                *************

SELECT DISTINCT RATCODSIS FROM  [dbo].CILTBLrat (NOLOCK) WHERE RATDATREF='20180131'

1  = FUNCAO
4  = DESCONTO

SELECT  * FROM  [dbo].CILTBLrat (NOLOCK) WHERE RATDATREF='20180131'
AND RATCODSIS = 4
AND RATCODCONTR= 1001332

