USE SIG --[Santana]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_LASTRO_TXT' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_LASTRO_TXT]
GO

CREATE PROCEDURE [DBO].[SCR_LASTRO_TXT] (@DT_ATE AS SMALLDATETIME) AS  

SELECT '0LCC002' AS OPNROPER
UNION  
SELECT DISTINCT LEFT('1'+OPNROPER + REPLICATE(' ',17),17)+'999' + REPLICATE(' ',82) AS OPNROPER
FROM CDCSANTANAMICROCREDITO..CPARC (NOLOCK)  
INNER JOIN CDCSANTANAMICROCREDITO..COPER (NOLOCK) ON PANROPER = OPNROPER  
INNER JOIN CDCSANTANAMICROCREDITO..CCLIE (NOLOCK) ON OPCODCLI = CLCODCLI  
INNER JOIN CDCSANTANAMICROCREDITO..CLCPARC (NOLOCK) ON CPNROPER = OPNROPER AND CPNRPARC = PANRPARC AND CPCNTRL = PACNTRL  
WHERE --PANROPER = '617003000' AND   
OPDTBASE BETWEEN '1900-01-01' AND @DT_ATE  
--AND PADTVCTO >= '01/01/1950' AND PADTVCTO <= '02/02/2079'    
AND (PADTMOV IS NULL OR PADTMOV > @DT_ATE)   
AND  PADTVAL <= @DT_ATE   
AND (OPDTLIQ IS NULL OR OPDTLIQ > @DT_ATE)   
AND OPDTBASE <= @DT_ATE   
AND  NOT (PACODMOV IN ('07', '08', '09', '13', '91', '94') AND PADTLIQ IS NOT NULL)    
AND OPCODOP IN ('770','771','772','773','774','775','776','777')  
AND (( NOT EXISTS(SELECT 1 FROM CDCSANTANAMICROCREDITO..CPCES S, CDCSANTANAMICROCREDITO..CCCRE R WHERE S.PCNRCESS = R.CCNRCESS AND S.PCNROPER = PANROPER AND R.CCTPCESS NOT IN(3, 6)   
AND S.PCDTMOV  >  @DT_ATE AND R.CCDTBASE <= @DT_ATE    
AND ((((R.CCCOOBRIG = 'N' OR PADTVCTO >= @DT_ATE)   
AND ISNULL(R.CCRECAUT, 'N') <> 'S') OR R.CCRECAUT = 'S')))   
AND NOT EXISTS(SELECT * FROM CDCSANTANAMICROCREDITO..CPGAR G, CDCSANTANAMICROCREDITO..CCCRE R WHERE  G.CGNRCESS = R.CCNRCESS AND G.CGNROPER = PANROPER      
AND (G.CGDTMOV IS NULL OR G.CGDTMOV >  @DT_ATE) AND R.CCDTBASE <= @DT_ATE)))    
ORDER BY OPNROPER