USE sig --[Santana]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'JOB_REMESSA_CREDITAS' AND type = 'P')
   DROP PROCEDURE [dbo].[JOB_REMESSA_CREDITAS]
GO   
CREATE PROCEDURE [DBO].[JOB_REMESSA_CREDITAS] AS                          

/*

CREATE INDEX REMESSA_IND1 ON AUX_REMESSA (O3CODORG, OPNROPER, OPDTBASE)
DROP TABLE AUX_REMESSA
CREATE TABLE AUX_REMESSA(
O3CODORG	int,
O3DESCR	varchar(20),
OPNROPER	varchar(15),
OPDTBASE	smalldatetime,
OPCODCLI	varchar(15),
OPNOMEBNF	varchar(200),
ABRENAVAM	varchar(11),
DCFAVNOME	varchar(200),
DCVALOR	float,
ABCHASSI	varchar(20),
ABUFLCPL	varchar(10),
EPDTLNC	datetime,
EPHORALNC	datetime,
OPCODORG6	varchar(10),
OPERADOR	varchar(200),
NRRENAVAM	varchar(11),
OPCODORG4	varchar(10),
LOJA	varchar(200),
CODPROD	varchar(100),
HORA_REMESSA VARCHAR(10),
DT_EMISSAO SMALLDATETIME,
NUM_REMESSA INT,
TIPO VARCHAR(20))   

CREATE INDEX REMESSA_IND1 ON TB_REMESSA (O3CODORG, OPNROPER, OPDTBASE)
DROP TABLE TB_REMESSA
CREATE TABLE TB_REMESSA(
O3CODORG	int,
O3DESCR	varchar(20),
OPNROPER	varchar(15),
OPDTBASE	smalldatetime,
OPCODCLI	varchar(15),
OPNOMEBNF	varchar(200),
ABRENAVAM	varchar(11),
DCFAVNOME	varchar(200),
DCVALOR	float,
ABCHASSI	varchar(20),
ABUFLCPL	varchar(10),
EPDTLNC	datetime,
EPHORALNC	datetime,
OPCODORG6	varchar(10),
OPERADOR	varchar(200),
NRRENAVAM	varchar(11),
OPCODORG4	varchar(10),
LOJA	varchar(200),
CODPROD	varchar(100),
HORA_REMESSA VARCHAR(10),
DT_EMISSAO SMALLDATETIME,
NUM_REMESSA INT,
TIPO VARCHAR(20)) 
*/	

BEGIN     

DECLARE @DT_DE AS DATETIME
DECLARE @DT_ATE AS DATETIME
DECLARE @HR_DE AS VARCHAR(15)
DECLARE @HR_ATE AS VARCHAR(15)
DECLARE @FERI AS INT

SELECT @FERI = COUNT(*) FROM CDCSANTANAMICROCREDITO..TFERI (NOLOCK) WHERE FEDTFER = CONVERT(VARCHAR(10),GETDATE(),121)
IF @FERI > 0 
BEGIN
	RETURN
END

SET @DT_DE = CONVERT(VARCHAR(10),GETDATE(),121)
SET @DT_ATE = CONVERT(VARCHAR(10),GETDATE(),121)
SET @HR_ATE = CONVERT(CHAR(2),GETDATE(),114) + ':01:00'
SET @HR_DE = CONVERT(CHAR(2),DATEADD(HOUR,-1,GETDATE()),114) + ':01:00'

TRUNCATE TABLE AUX_REMESSA

INSERT INTO AUX_REMESSA
SELECT                  
O3CODORG, O3DESCR, OPNROPER, OPDTBASE, OPCODCLI, OPNOMEBNF, '' AS ABRENAVAM, B.DCFAVNOME, B.DCVALOR, '' AS ABCHASSI,'' AS ABUFLCPL,                  
ISNULL(EP,OPDTBASE),ISNULL(EPHORALNC,''), OPCODORG6, O6DESCR, '' AS NRRENAVAM, OPCODORG4, '' AS LOJA, OPCODPROD, 
@HR_ATE, CONVERT(VARCHAR(10), GETDATE(), 121), '', 'CREDITAS'
FROM 
(SELECT * FROM CDCSANTANAMICROCREDITO..COPER AS OP1 (NOLOCK)                  
	WHERE OPDTBASE BETWEEN @DT_DE AND @DT_ATE) AS OP                                
INNER JOIN CDCSANTANAMICROCREDITO..TORG6 WITH (NOLOCK) ON OPCODORG6 = O6CODORG                  
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 WITH (NOLOCK)ON O6CODORG3 = O3CODORG                  
LEFT  JOIN (SELECT  EPNRPROP,MAX(EPDTLNC +EPHORALNC) AS EP,MAX(EPHORALNC) AS EPHORALNC, EPDTHRFIM FROM PROPWEBSMC..EPROP (NOLOCK) 
	WHERE EPNRDECI = '22' GROUP BY  EPNRPROP,EPDTHRFIM ) AS P ON EPNRPROP = OPNRPROP                  
LEFT  JOIN (select   DCNROPER, DCFAVNOME, DCVALOR FROM CDCSANTANAMICROCREDITO..CDOCS AS B1  (NOLOCK)) AS B ON   OP.OPNROPER=B.DCNROPER        
WHERE P.EPDTHRFIM BETWEEN @DT_DE + @HR_DE AND @DT_ATE + @HR_ATE
AND OPCODORG4 = '009180'
                      
DELETE FROM  AUX_REMESSA WHERE RIGHT(OPNROPER,1) IN ('A','B','C','D','E','F','G')

UPDATE  AUX_REMESSA                    
SET  LOJA= B.O4DESCR                   
FROM CDCSANTANAMICROCREDITO..TORG4 B (NOLOCK) WHERE AUX_REMESSA.OPCODORG4 = B.O4CODORG

UPDATE  AUX_REMESSA                    
SET  ABRENAVAM= B.ABPLACA, ABCHASSI=B.ABCHASSI, ABUFLCPL=B.ABUFLCPL,NRRENAVAM= B.ABRENAVAM                    
FROM CDCSANTANAMICROCREDITO..CBFIN B (NOLOCK)                   
WHERE B.ABNROPER=AUX_REMESSA.OPNROPER 
	AND B.ABCNTRL = (SELECT MAX(ABCNTRL) FROM CDCSANTANAMICROCREDITO..CBFIN B1 (NOLOCK) WHERE B1.ABNROPER = B.ABNROPER)

UPDATE  AUX_REMESSA                    
SET  OPNOMEBNF= B.CLNOMECLI                  
FROM CDCSANTANAMICROCREDITO..CCLIE B (NOLOCK)                   
WHERE B.CLCODCLI=AUX_REMESSA.OPCODCLI

UPDATE AUX_REMESSA                
SET DCFAVNOME = 'BOLETO'                
FROM CDCSANTANAMICROCREDITO..CDOCS WHERE DCDTEMISS BETWEEN @DT_DE AND @DT_ATE AND DCCODMOV ='506'                
AND DCNROPER = OPNROPER AND AUX_REMESSA.DCFAVNOME = 'SCFI-PGFR'      

UPDATE AUX_REMESSA                
SET DCFAVNOME = 'ACESSÓRIOS'                
FROM CDCSANTANAMICROCREDITO..CDOCS WHERE DCDTEMISS BETWEEN @DT_DE AND @DT_ATE AND DCCODMOV ='505'                
AND DCNROPER = OPNROPER         
AND AUX_REMESSA.DCFAVNOME <> 'SCFI-PGFR' AND AUX_REMESSA.DCVALOR <= 900.00  

UPDATE AUX_REMESSA            
SET CODPROD = CODPROD + ' - ' + TPDESCR            
FROM PROPWEBSMC..TPROD (NOLOCK) INNER JOIN AUX_REMESSA (NOLOCK)            
ON TPCODPRD = CODPROD  

--ATUALIZAR NUMERO REMESSA
UPDATE AUX_REMESSA
SET NUM_REMESSA = T.CONT + 1 
FROM (SELECT ISNULL(MAX(NUM_REMESSA),0) AS CONT FROM TB_REMESSA (NOLOCK)
WHERE DT_EMISSAO = @DT_ATE AND TIPO = 'CREDITAS') T


INSERT INTO TB_REMESSA
SELECT O3CODORG,O3DESCR,OPNROPER,OPDTBASE,OPCODCLI,OPNOMEBNF,ABRENAVAM,DCFAVNOME,                  
DCVALOR,ABCHASSI,ABUFLCPL,EPDTLNC,                                
LTRIM(RIGHT(CONVERT(VARCHAR(25), EPHORALNC, 120), 8))  AS EPHORALNC, OPCODORG6, OPERADOR, NRRENAVAM, OPCODORG4, LOJA, CODPROD,
HORA_REMESSA, DT_EMISSAO, NUM_REMESSA,TIPO
FROM AUX_REMESSA (NOLOCK)   

END