USE sig
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
CREATE TABLE PROD_LOJA_PAG_REC(
COD_AGENTE_LOJA BIGINT,
AGENTE_LOJA VARCHAR(50),
COD_LOJA VARCHAR(10),
LOJA VARCHAR(100),
PROD_MES FLOAT,
QTD_REC_LOJA FLOAT,
QTD_CRIVO_LOJA FLOAT,
PRC_REC_CRIVO FLOAT,
QTD_APR_LOJA FLOAT,
PRC_APR_REC FLOAT,
QTD_INT_LOJA FLOAT,
PRC_INT_APR FLOAT,
PRC_PAG_REC FLOAT)
*/
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PRODUCAO_LOJA_PAGREC' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PRODUCAO_LOJA_PAGREC]
GO

create Procedure [dbo].[SCR_PRODUCAO_LOJA_PAGREC]  AS 

DECLARE @DATA AS SMALLDATETIME  
SET @DATA = CONVERT(VARCHAR(8),DATEADD(D,-1,GETDATE()),112)  
SELECT @DATA= CASE WHEN DATEPART(DW,@DATA) = 1 THEN DATEADD(D,-2,@DATA) -- DOMINGO            
WHEN DATEPART(DW,@DATA) = 7 THEN DATEADD(D,-1,@DATA) -- SABADO            
ELSE @DATA END  

DECLARE @DATA_INI AS SMALLDATETIME
SET @DATA_INI = CONVERT(CHAR(4),DATEPART(YEAR,@DATA))+          
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DATA))),2)+'01'  

DELETE FROM PROD_LOJA_PAG_REC 

INSERT INTO PROD_LOJA_PAG_REC (COD_AGENTE_LOJA, AGENTE_LOJA,COD_LOJA, LOJA)  
SELECT O3CODORG, O3DESCR, O4CODORG, O4DESCR FROM 
CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) ON O4CODORG3 = O3CODORG
WHERE O3ATIVA IN ('S','A') AND O4ATIVA IN ('S','A')
AND O3CODORG NOT IN('000149', '000147','000001','000098','000163','000166','000168','000169','000200','000980','014214','000190','000165')  

UPDATE PROD_LOJA_PAG_REC SET PROD_MES = A.TOTAL FROM(  
SELECT CODLOJA, SUM(VLR_PRESENTE) AS TOTAL FROM COMERCIAL_PRODUCAO (NOLOCK) WHERE DT_FECHA = @DATA
AND PRODUTO IN ('V') AND NUM_OPE <> '' GROUP BY CODLOJA) AS A   
WHERE A.CODLOJA = PROD_LOJA_PAG_REC.COD_LOJA  

UPDATE PROD_LOJA_PAG_REC SET QTD_REC_LOJA = A.TOTAL FROM(  
SELECT PPCODORG4, COUNT(DISTINCT PPNRPROP) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
INNER JOIN PROPWEBSMC..TDECI (NOLOCK) ON MPNRDECI = TDNRDECI WHERE PPDTBASE BETWEEN @DATA_INI AND @DATA
AND TDDESCR <> 'DADOS BÁSICOS'
AND PPCODOP IN (SELECT M.COD_MODA                      
        FROM Ttipo_prod T  (NOLOCK),         
        TModa_tipo_prod M (NOLOCK)                        
      WHERE M.COD_PROD   = T.COD_PROD                       
       AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
       AND T.COD_PROD IN ('V')                                
       AND T.COD_MODALIDADE NOT IN (14, 87))                                   
GROUP BY PPCODORG4) AS A
WHERE A.PPCODORG4 = PROD_LOJA_PAG_REC.COD_LOJA  

UPDATE PROD_LOJA_PAG_REC SET QTD_CRIVO_LOJA = A.TOTAL FROM(  
SELECT PPCODORG4, COUNT(DISTINCT PPNRPROP) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
INNER JOIN PROPWEBSMC..TDECI (NOLOCK) ON MPNRDECI = TDNRDECI WHERE PPDTBASE BETWEEN @DATA_INI AND @DATA
AND TDDESCR = 'CADASTRO DA PROPOSTA' AND MPSIT = 'AND'
AND PPCODOP IN (SELECT M.COD_MODA                      
        FROM Ttipo_prod T  (NOLOCK),         
        TModa_tipo_prod M (NOLOCK)                        
      WHERE M.COD_PROD   = T.COD_PROD                       
       AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
       AND T.COD_PROD IN ('V')                                
       AND T.COD_MODALIDADE NOT IN (14, 87))                                   
GROUP BY PPCODORG4) AS A
WHERE A.PPCODORG4 = PROD_LOJA_PAG_REC.COD_LOJA  

UPDATE PROD_LOJA_PAG_REC SET PRC_REC_CRIVO = CAST((QTD_CRIVO_LOJA/QTD_REC_LOJA)*100.00 AS NUMERIC(15,2))

UPDATE PROD_LOJA_PAG_REC SET QTD_APR_LOJA = A.TOTAL FROM(  
SELECT PPCODORG4,COUNT(*) AS TOTAL  FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
WHERE PPDTBASE BETWEEN @DATA_INI AND @DATA
AND MPSIT IN ('APR','INT')
AND PPCODOP IN (SELECT M.COD_MODA                      
        FROM Ttipo_prod T  (NOLOCK),         
        TModa_tipo_prod M (NOLOCK)                        
      WHERE M.COD_PROD   = T.COD_PROD                       
       AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
       AND T.COD_PROD IN ('V')                                
       AND T.COD_MODALIDADE NOT IN (14, 87))   
GROUP BY PPCODORG4)AS A    
WHERE A.PPCODORG4 = PROD_LOJA_PAG_REC.COD_LOJA  

UPDATE PROD_LOJA_PAG_REC SET PRC_APR_REC = CAST((QTD_APR_LOJA/QTD_REC_LOJA)*100.00 AS NUMERIC(15,2))                        

UPDATE PROD_LOJA_PAG_REC SET QTD_INT_LOJA = A.TOTAL FROM(  
SELECT PPCODORG4,COUNT(*) AS TOTAL  FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
WHERE PPDTBASE BETWEEN @DATA_INI AND @DATA
AND MPSIT IN ('INT')
AND PPCODOP IN (SELECT M.COD_MODA                      
        FROM Ttipo_prod T  (NOLOCK),         
        TModa_tipo_prod M (NOLOCK)                        
      WHERE M.COD_PROD   = T.COD_PROD                       
       AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
       AND T.COD_PROD IN ('V')                                
       AND T.COD_MODALIDADE NOT IN (14, 87))   
GROUP BY PPCODORG4)AS A    
WHERE A.PPCODORG4 = PROD_LOJA_PAG_REC.COD_LOJA  

UPDATE PROD_LOJA_PAG_REC SET PRC_INT_APR = CAST((QTD_INT_LOJA/QTD_APR_LOJA)*100.00 AS NUMERIC(15,2))    

UPDATE PROD_LOJA_PAG_REC SET PRC_PAG_REC = CAST((QTD_INT_LOJA/QTD_REC_LOJA)*100.00 AS NUMERIC(15,2))    

SELECT * FROM PROD_LOJA_PAG_REC