USE sig
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
CREATE TABLE PROD_META(
COD_AGENTE VARCHAR(10),
AGENTE VARCHAR(50),
ESTOQUE_2 INT,
ESTOQUE_10 INT,
ESTOQUE_MES INT,
PROD_DIA FLOAT,
PROD_ACUM FLOAT,
ACUM_MES_ANT FLOAT,
VARIACAO FLOAT,
QTD_INT INT,
QTD_APR INT)
*/
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PRODUCAO_PERFORMANCE' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PRODUCAO_PERFORMANCE]
GO

create Procedure [dbo].[SCR_PRODUCAO_PERFORMANCE]  AS 
BEGIN  

--DATA DE ONTEM
DECLARE @DATA AS SMALLDATETIME
SET @DATA = CONVERT(VARCHAR(8),DATEADD(D,-1,GETDATE()),112)
SELECT @DATA= CASE WHEN DATEPART(DW,@DATA) = 1 THEN DATEADD(D,-2,@DATA) -- DOMINGO          
	WHEN DATEPART(DW,@DATA) = 7 THEN DATEADD(D,-1,@DATA) -- SABADO          
	ELSE @DATA END    

--LIMPAR TABELA
DELETE FROM PROD_META

--INSERIR AGENTES ATIVOS
INSERT INTO PROD_META (COD_AGENTE, AGENTE)
SELECT O3CODORG, O3DESCR FROM CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) WHERE O3ATIVA IN ('S','A') 
AND O3CODORG NOT IN('000149', '000147','000001','000098','000163','000166','000168','000169','000200','000980','014214','000190','000165')

--SELECIONAR DATAS
DECLARE @DT_2 AS SMALLDATETIME --2 DIAS ATRÁS
DECLARE @DT_10 AS SMALLDATETIME --20 DIAS ATRÁS
DECLARE @DT_1M AS SMALLDATETIME --1º DIA DO MÊS
DECLARE @DT_MES_ANT AS SMALLDATETIME --MESMO DIA MES ANTERIOR EM RELAÇÃO AO DIA ÚTIL
DECLARE @DT_1D_ANT AS SMALLDATETIME --1º DIA MES ANTERIOR

SET @DT_2 = DATEADD(D,-1,@DATA)
SELECT @DT_2 = CASE WHEN DATEPART(DW,@DT_2) = 1 THEN DATEADD(D,-2,@DT_2) -- DOMINGO          
	WHEN DATEPART(DW,@DT_2) = 7 THEN DATEADD(D,-1,@DT_2) -- SABADO          
	ELSE @DT_2 END  
	
SET @DT_10 = DATEADD(D,-13,@DATA)	 
SELECT @DT_10 = CASE WHEN DATEPART(DW,@DT_10) = 1 THEN DATEADD(D,-2,@DT_10) -- DOMINGO          
	WHEN DATEPART(DW,@DT_10) = 7 THEN DATEADD(D,-1,@DT_10) -- SABADO          
	ELSE @DT_10 END  

SELECT @DT_1M = CONVERT(CHAR(4),DATEPART(YYYY,@DATA))+          
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MM,@DATA))),2)+'01'

SET @DT_2 = CONVERT(VARCHAR(8),@DT_2,112) 
SET @DT_10 = CONVERT(VARCHAR(8),@DT_10,112) 
SET @DT_1M = CONVERT(VARCHAR(8),@DT_1M,112) 

--INSERE PROPOSTAS D-2
UPDATE PROD_META SET ESTOQUE_2 = A.TOTAL FROM(
SELECT PPCODORG3, COUNT(*) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK) INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
WHERE PPDTBASE BETWEEN @DT_2 AND @DATA AND MPSIT = 'APR'
GROUP BY PPCODORG3) AS A 
WHERE A.PPCODORG3 = PROD_META.COD_AGENTE

--INSERE PROPOSTAS D-10
UPDATE PROD_META SET ESTOQUE_10 = A.TOTAL FROM(
SELECT PPCODORG3, COUNT(*) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK) INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
WHERE PPDTBASE BETWEEN @DT_10 AND @DATA AND MPSIT = 'APR'
GROUP BY PPCODORG3) AS A 
WHERE A.PPCODORG3 = PROD_META.COD_AGENTE

--INSERE PROPOSTAS MES
UPDATE PROD_META SET ESTOQUE_MES = A.TOTAL FROM(
SELECT PPCODORG3, COUNT(*) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK) INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON PPNRPROP = MPNRPROP
WHERE PPDTBASE BETWEEN @DT_1M AND @DATA AND MPSIT = 'APR'
GROUP BY PPCODORG3) AS A 
WHERE A.PPCODORG3 = PROD_META.COD_AGENTE

--INSERE PRODUCAO DIA
UPDATE PROD_META SET PROD_DIA = A.TOTAL FROM(
SELECT OPCODORG3, SUM(OPVLROPCZ) AS TOTAL FROM CDCSANTANAMICROCREDITO..COPER (NOLOCK)
WHERE OPDTBASE = @DATA AND RIGHT(OPNROPER,1) NOT IN ('A','B','C','D','E','F','G') GROUP BY OPCODORG3) AS A 
WHERE A.OPCODORG3 = PROD_META.COD_AGENTE

--INSERE PRODUCAO ACUM
UPDATE PROD_META SET PROD_ACUM = A.TOTAL FROM(
SELECT AGENTE, SUM(VLR_PRESENTE) AS TOTAL FROM COMERCIAL_PRODUCAO (NOLOCK)
WHERE DT_FECHA = @DATA AND PRODUTO IN ('V') AND NUM_OPE <> '' GROUP BY AGENTE) AS A 
WHERE A.AGENTE = PROD_META.COD_AGENTE

--PRODUÇÃO PROJETADA
--UTILIZAR FUNÇÃO DO QLIK

--************************************ROTINA DIA ÚTIL MES ANTERIOR*****************************************
--VERIFICAR DATA DO MÊS ANTERIOR EM RELAÇÃO AO DIA ÚTIL DO MES ATUAL
DECLARE @QTD INT
SET @QTD = 0
DECLARE @AUX INT
SET @AUX = 0

DECLARE @DATA_AUX SMALLDATETIME
SET @DATA_AUX = @DT_1M

WHILE @DATA_AUX <= @DATA
BEGIN
	IF DATEPART(DW,@DATA_AUX) NOT IN (1,7)
	BEGIN
		IF (SELECT COUNT(*) FROM CDCSANTANAMICROCREDITO..TFERI (NOLOCK) WHERE FEDTFER = @DATA_AUX) = 0
		BEGIN
			SET @QTD = @QTD + 1
		END
	END
	SET @DATA_AUX = DATEADD(DD,+1,@DATA_AUX)
END

SET @QTD = @QTD - 1

SET @DT_MES_ANT = CONVERT(CHAR(4),DATEPART(YEAR, DATEADD(MM,-1,@DATA)))+      
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH, DATEADD(MM,-1,@DATA)))),2)+      
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(DAY, DATEADD(MM,-1,@DATA)))),2)   

SET @AUX = 0

SET @DATA_AUX = CONVERT(CHAR(4),DATEPART(YEAR, @DT_MES_ANT))+      
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH, @DT_MES_ANT))),2)+'01' 

SET @DATA_AUX = DATEADD(DD,-1,@DATA_AUX)

WHILE @AUX <= @QTD
BEGIN
	SET @DATA_AUX = DATEADD(DD,+1,@DATA_AUX)
	IF DATEPART(DW,@DATA_AUX) NOT IN (1,7)
	BEGIN
		IF (SELECT COUNT(*) FROM CDCSANTANAMICROCREDITO..TFERI (NOLOCK) WHERE FEDTFER = @DATA_AUX) = 0
		BEGIN
			SET @AUX = @AUX + 1
		END
	END
END

SET @DT_MES_ANT = @DATA_AUX

IF DATEPART(MONTH,@DT_MES_ANT) <> DATEPART(MONTH,DATEADD(MM,-1,@DATA))
BEGIN
	SET @DT_MES_ANT = (SELECT MAX(DT_FECHA) FROM RR_ROLLRATE_DIA_RPT (NOLOCK)
		WHERE  DATEPART(MONTH,DT_FECHA) = DATEPART(MONTH,DATEADD(MM,-1,@DATA)) 
        AND DATEPART(YEAR ,DT_FECHA) = DATEPART(YEAR ,DATEADD(MM,-1,@DATA))) 
END
--************************************FIM ROTINA DIA ÚTIL MES ANTERIOR*****************************************

--INSERE ACUM MÊS ANTERIOR
UPDATE PROD_META SET ACUM_MES_ANT = A.TOTAL FROM(
SELECT AGENTE, SUM(VLR_PRESENTE) AS TOTAL FROM COMERCIAL_PRODUCAO (NOLOCK)
WHERE DT_FECHA = @DT_MES_ANT AND PRODUTO IN ('V') AND NUM_OPE <> '' GROUP BY AGENTE) AS A 
WHERE A.AGENTE = PROD_META.COD_AGENTE

UPDATE PROD_META SET VARIACAO = ISNULL((PROD_ACUM/ACUM_MES_ANT-1.00)*100.00,-100.00)

UPDATE PROD_META SET QTD_INT = A.TOTAL FROM(
SELECT PPCODORG3, COUNT(*) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON MPNRPROP = PPNRPROP WHERE PPDTBASE BETWEEN @DT_1M AND @DATA
AND MPSIT = 'INT' GROUP BY PPCODORG3) AS A
WHERE A.PPCODORG3 = PROD_META.COD_AGENTE

UPDATE PROD_META SET QTD_APR = A.TOTAL FROM(
SELECT PPCODORG3, COUNT(*) AS TOTAL FROM PROPWEBSMC..CPROP (NOLOCK)
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON MPNRPROP = PPNRPROP WHERE PPDTBASE BETWEEN @DT_1M AND @DATA
AND MPSIT = 'APR' GROUP BY PPCODORG3) AS A
WHERE A.PPCODORG3 = PROD_META.COD_AGENTE

--SELECT @DATA AS ONTEM, @DT_2 AS '-2' ,@DT_10 AS '-10', @DT_1M AS 'PRIMEIRO_MES', @DT_MES_ANT 'DIA_ANT'

SELECT * FROM PROD_META

END