USE SIG --[Santana]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PROMOTORAS' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PROMOTORAS]
GO  
CREATE PROCEDURE SCR_PROMOTORAS @TIPO smallint, @AGNT VARCHAR(10) as          
IF @TIPO = 1 --TODOS          
BEGIN          
SELECT DISTINCT O4CODORG 'CÓDIGO PROMOTORA', O4NOME 'NOME PROMOTORA', O4DESCR 'DESCRIÇÃO PROMOTORA', O4RUA 'RUA', O4CMPT 'COMPLEMENTO',           
O4CEP 'CEP', O4BAI 'BAIRRO', O4CID 'CIDADE', O4UF 'UF', O4FONE 'FONE', O4FAX 'CELULAR', O4CPFCGC 'CPF/CNPJ', O4RESPONSA 'RESPONSÁVEL',           
CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' WHEN O4ATIVA = 'D' THEN 'INATIVA' END AS 'ATIVA',           
O4EMAIL 'EMAIL', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'NOME AGENTE'        
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON O6CODORG3 = O3CODORG        
INNER JOIN CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) ON O4CODORG3 = O3CODORG         
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES            
      WHEN  @AGNT<>'99' AND O3CODORG = @AGNT  THEN 1            
      ELSE  0   END            
AND (O4NOME LIKE 'BALC%'  OR O4DESCR LIKE 'BALC%')   
ORDER BY 1          
END          
ELSE          
          
IF @TIPO = 2 --ATIVOS          
BEGIN          
SELECT DISTINCT O4CODORG 'CÓDIGO PROMOTORA', O4NOME 'NOME PROMOTORA', O4DESCR 'DESCRIÇÃO PROMOTORA', O4RUA 'RUA', O4CMPT 'COMPLEMENTO',           
O4CEP 'CEP', O4BAI 'BAIRRO', O4CID 'CIDADE', O4UF 'UF', O4FONE 'FONE', O4FAX 'CELULAR', O4CPFCGC 'CPF/CNPJ', O4RESPONSA 'RESPONSÁVEL',          
CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' WHEN O4ATIVA = 'D' THEN 'INATIVA' END AS 'ATIVA',           
O4EMAIL 'EMAIL', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'NOME AGENTE'            
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON O6CODORG3 = O3CODORG        
INNER JOIN CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) ON O4CODORG3 = O3CODORG           
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES            
      WHEN  @AGNT<>'99' AND O3CODORG = @AGNT  THEN 1            
      ELSE  0   END            
AND O4ATIVA = 'A'           
AND (O4NOME LIKE 'BALC%'  OR O4DESCR LIKE 'BALC%')       
ORDER BY 1          
END          
ELSE          
          
IF @TIPO = 3 --INATIVOS          
BEGIN          
SELECT DISTINCT O4CODORG 'CÓDIGO PROMOTORA', O4NOME 'NOME PROMOTORA', O4DESCR 'DESCRIÇÃO PROMOTORA', O4RUA 'RUA', O4CMPT 'COMPLEMENTO',           
O4CEP 'CEP', O4BAI 'BAIRRO', O4CID 'CIDADE', O4UF 'UF', O4FONE 'FONE', O4FAX 'CELULAR', O4CPFCGC 'CPF/CNPJ', O4RESPONSA 'RESPONSÁVEL',          
CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' WHEN O4ATIVA = 'D' THEN 'INATIVA' END AS 'ATIVA',           
O4EMAIL 'EMAIL', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'NOME AGENTE'              
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON O6CODORG3 = O3CODORG        
INNER JOIN CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) ON O4CODORG3 = O3CODORG           
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES            
      WHEN  @AGNT<>'99' AND O3CODORG = @AGNT  THEN 1            
      ELSE  0   END            
AND O4ATIVA = 'D'          
AND (O4NOME LIKE 'BALC%'  OR O4DESCR LIKE 'BALC%')
ORDER BY 1          
END