USE SIG --[Santana]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_LOJAS_OPERADORES' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_LOJAS_OPERADORES]
GO

CREATE PROCEDURE SCR_LOJAS_OPERADORES @TIPO SMALLINT, @AGNT VARCHAR(10) AS            

/*
CREATE TABLE LOJAS_OPERADORES(
O4CODORG VARCHAR(20),
O4NOME VARCHAR(200),
O4DESCR VARCHAR(200),
O4RUA VARCHAR(200),
O4CMPT VARCHAR(200),
O4CEP VARCHAR(20),
O4BAI VARCHAR(50),
O4CID VARCHAR(50),
O4UF VARCHAR(5),
O4FONE VARCHAR(20),
O4CPFCGC VARCHAR(30),
O4ATIVA VARCHAR(30),
O4DTDESAT SMALLDATETIME,
O4DTATIV SMALLDATETIME,
O4DTCAD SMALLDATETIME,
O3CODORG VARCHAR(10),
O3DESCR VARCHAR(50),
O4CC1BCONR VARCHAR(20),
O4CC1AGNR VARCHAR(20),
O4CC1CONTA VARCHAR(20),
O4CC2BCONR VARCHAR(20),
O4CC2AGNR VARCHAR(20),
O4CC2CONTA VARCHAR(20),
O4CC3BCONR VARCHAR(20),
O4CC3AGNR VARCHAR(20),
O4CC3CONTA VARCHAR(20),
USNOMEUSU VARCHAR(50),
VLROPCZ FLOAT)
*/

DELETE FROM LOJAS_OPERADORES

INSERT INTO LOJAS_OPERADORES
SELECT DISTINCT O4CODORG , O4NOME , O4DESCR , O4RUA , O4CMPT , O4CEP, O4BAI, O4CID, O4UF, O4FONE, O4CPFCGC, O4ATIVA,
O4DTDESAT, O4DTATIV, O4DTCAD, O3CODORG, O3DESCR, O4CC1BCONR,O4CC1AGNR,O4CC1CONTA, O4CC2BCONR, O4CC2AGNR, O4CC2CONTA ,O4CC3BCONR,
O4CC3AGNR, O4CC3CONTA, NULL, 0.0
FROM CDCSANTANAMICROCREDITO..TORG4 (NOLOCK)          
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON O4CODORG3 = O3CODORG  
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES              
      WHEN  @AGNT<>'99' AND O3CODORG = @AGNT THEN 1              
      ELSE  0   END  

UPDATE LOJAS_OPERADORES SET USNOMEUSU = A.USNOMEUSU FROM 
(SELECT O4CODORG, USNOMEUSU FROM CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) INNER JOIN ACESSOCORP..TOUSU (NOLOCK) ON OUCODORG = O4CODORG AND OUTPORG = 4  
LEFT  JOIN ACESSOCORP..TUSU (NOLOCK) ON USCODUSU = OUCODUSU AND (USGRUPO1 = '04899' OR USGRUPO2 = '04899' OR USGRUPO3 = '04899' OR USGRUPO4 = '04899'))A                                
WHERE A.O4CODORG = LOJAS_OPERADORES.O4CODORG

UPDATE LOJAS_OPERADORES SET VLROPCZ = A.PPVLROPCZ FROM
(SELECT PPCODORG4, SUM(PPVLROPCZ) AS PPVLROPCZ FROM PROPWEBSMC..CPROP (NOLOCK)
WHERE PPDTBASE BETWEEN DATEADD(DAY,-90,GETDATE()) AND GETDATE()
GROUP BY PPCODORG4) A
WHERE A.PPCODORG4 = LOJAS_OPERADORES.O4CODORG

IF @TIPO = 1 --TODOS              
BEGIN              
SELECT DISTINCT O4CODORG 'CÓDIGO LOJA', O4NOME 'NOME LOJA', O4DESCR 'DESCRIÇÃO LOJA', O4RUA 'ENDEREÇO', O4CMPT 'COMPLEMENTO', O4CEP'CEP', O4BAI 'BAIRRO',             
O4CID 'CIDADE', O4UF 'UF', O4FONE 'TELEFONE', O4CPFCGC 'CPF/CNPJ', CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' ELSE 'DESATIVADA' END 'LOJA ATIVA',             
O4DTDESAT 'DATA DESATIVAÇÃO', O4DTATIV 'DATA ATIVAÇÃO', O4DTCAD 'DATA CADASTRO LOJA', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'DESCRIÇÃO AGENTE',             
O4CC1BCONR 'BANCO 1',O4CC1AGNR 'AGENCIA 1',O4CC1CONTA 'CONTA 1',O4CC2BCONR 'BANCO 2',O4CC2AGNR 'AGENCIA 2',O4CC2CONTA 'CONTA 2',O4CC3BCONR 'BANCO 3',    
O4CC3AGNR 'AGENCIA 3',O4CC3CONTA 'CONTA 3', USNOMEUSU, ISNULL(VLROPCZ,0.0) AS VLROPCZ 
FROM LOJAS_OPERADORES   
ORDER BY O3CODORG ASC              
END              
ELSE                            

IF @TIPO = 2 --ATIVOS              
BEGIN              
SELECT DISTINCT O4CODORG 'CÓDIGO LOJA', O4NOME 'NOME LOJA', O4DESCR 'DESCRIÇÃO LOJA', O4RUA 'ENDEREÇO', O4CMPT 'COMPLEMENTO', O4CEP'CEP', O4BAI 'BAIRRO',             
O4CID 'CIDADE', O4UF 'UF', O4FONE 'TELEFONE', O4CPFCGC 'CPF/CNPJ', CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' ELSE 'DESATIVADA' END 'LOJA ATIVA',             
O4DTDESAT 'DATA DESATIVAÇÃO', O4DTATIV 'DATA ATIVAÇÃO', O4DTCAD 'DATA CADASTRO LOJA', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'DESCRIÇÃO AGENTE',             
O4CC1BCONR 'BANCO 1',O4CC1AGNR 'AGENCIA 1',O4CC1CONTA 'CONTA 1',O4CC2BCONR 'BANCO 2',O4CC2AGNR 'AGENCIA 2',O4CC2CONTA 'CONTA 2',O4CC3BCONR 'BANCO 3',    
O4CC3AGNR 'AGENCIA 3',O4CC3CONTA 'CONTA 3', USNOMEUSU, ISNULL(VLROPCZ,0.0) AS VLROPCZ  
FROM LOJAS_OPERADORES   
WHERE O4ATIVA = 'A'   
ORDER BY O3CODORG ASC                
END              
ELSE  
            
IF @TIPO = 3 --INATIVOS              
BEGIN              
SELECT DISTINCT O4CODORG 'CÓDIGO LOJA', O4NOME 'NOME LOJA', O4DESCR 'DESCRIÇÃO LOJA', O4RUA 'ENDEREÇO', O4CMPT 'COMPLEMENTO', O4CEP'CEP', O4BAI 'BAIRRO',             
O4CID 'CIDADE', O4UF 'UF', O4FONE 'TELEFONE', O4CPFCGC 'CPF/CNPJ', CASE WHEN O4ATIVA = 'A' THEN 'ATIVA' ELSE 'DESATIVADA' END 'LOJA ATIVA',             
O4DTDESAT 'DATA DESATIVAÇÃO', O4DTATIV 'DATA ATIVAÇÃO', O4DTCAD 'DATA CADASTRO LOJA', O3CODORG 'CÓDIGO AGENTE', O3DESCR 'DESCRIÇÃO AGENTE',             
O4CC1BCONR 'BANCO 1',O4CC1AGNR 'AGENCIA 1',O4CC1CONTA 'CONTA 1',O4CC2BCONR 'BANCO 2',O4CC2AGNR 'AGENCIA 2',O4CC2CONTA 'CONTA 2',O4CC3BCONR 'BANCO 3',    
O4CC3AGNR 'AGENCIA 3',O4CC3CONTA 'CONTA 3', USNOMEUSU, ISNULL(VLROPCZ,0.0) AS VLROPCZ
FROM LOJAS_OPERADORES 
WHERE O4ATIVA = 'D'               
ORDER BY O3CODORG ASC              
END