--exec SCR_TABELAS 1
USE [SIG]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- PROC TABELAS ********************************************************************************************************************************************************************************** 
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_TABELAS' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_TABELAS

GO

CREATE PROCEDURE SCR_TABELAS @TIPO smallint, @PRODUTO VARCHAR(20) as      
    
IF @TIPO = 1 --TODOS      
BEGIN      
SELECT DISTINCT        
T.TTCODTAB 'CÓDIGO TABELA',         
T.TTDESCR 'DESCRIÇÃO TABELA',        
L.RLCODPRD 'CÓDIGO PRODUTO',  
TP.TPDESCR 'DESCRIÇÃO PRODUTO',           
T.TTDTINI 'DATA INÍCIO',         
T.TTDTFIM 'DATA FIM',      
CASE WHEN TTDTFIM >= GETDATE() THEN 'ATIVO'  
ELSE 'INATIVO' END 'SITUAÇÃO',  
T.TTANOINI 'ANO',  
T.TTANOFIM 'MODELO',  
T.TTVLRENTMN 'ENTRADA MINIMA',  
T.TTSCOREINI 'SCORE',  
TC.OCDESCR 'CÓDIGO DA OCUPAÇÃO',  
T.TTCODDSP 'POLÍTICA DESPESA',  
CASE WHEN T.TTTXCOMRET = 'N' THEN 'NÃO' ELSE 'SIM' END 'RETORNO'  
FROM  CDCSANTANAMICROCREDITO..TTABE T (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TPLOR L (NOLOCK) ON T.TTCODTAB = L.RLCODTAB        
INNER JOIN CDCSANTANAMICROCREDITO..TPROD TP (NOLOCK) ON TP.TPCODPRD = L.RLCODPRD      
LEFT  JOIN CDCSANTANAMICROCREDITO..TOCUP TC (NOLOCK) ON T.TTCODOCUP = TC.OCCODOCUP  
WHERE    
T.TTCNTRL =  (SELECT MAX(T1.TTCNTRL) FROM CDCSANTANAMICROCREDITO..TTABE T1 (NOLOCK) WHERE T1.TTCODTAB=T.TTCODTAB)   
AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1    
      WHEN  @PRODUTO<>'99' AND L.RLCODPRD = @PRODUTO  THEN 1            
      ELSE  0   END    
ORDER BY 1    
END      
ELSE      
      
IF @TIPO = 2 --ATIVOS      
BEGIN      
SELECT DISTINCT        
T.TTCODTAB 'CÓDIGO TABELA',         
T.TTDESCR 'DESCRIÇÃO TABELA',        
L.RLCODPRD 'CÓDIGO PRODUTO',  
TP.TPDESCR 'DESCRIÇÃO PRODUTO',  
T.TTDTINI 'DATA INÍCIO',         
T.TTDTFIM 'DATA FIM',      
CASE WHEN TTDTFIM >= GETDATE() THEN 'ATIVO'  
ELSE 'INATIVO' END 'SITUAÇÃO',  
T.TTANOINI 'ANO',  
T.TTANOFIM 'MODELO',  
T.TTVLRENTMN 'ENTRADA MINIMA',  
T.TTSCOREINI 'SCORE',  
TC.OCDESCR 'CÓDIGO DA OCUPAÇÃO',  
T.TTCODDSP 'POLÍTICA DESPESA',  
CASE WHEN T.TTTXCOMRET = 'N' THEN 'NÃO' ELSE 'SIM' END 'RETORNO'   
FROM  CDCSANTANAMICROCREDITO..TTABE T (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TPLOR L (NOLOCK) ON T.TTCODTAB = L.RLCODTAB        
INNER JOIN CDCSANTANAMICROCREDITO..TPROD TP (NOLOCK) ON TP.TPCODPRD = L.RLCODPRD      
LEFT  JOIN CDCSANTANAMICROCREDITO..TOCUP TC (NOLOCK) ON T.TTCODOCUP = TC.OCCODOCUP  
WHERE    
T.TTCNTRL =  (SELECT MAX(T1.TTCNTRL) FROM CDCSANTANAMICROCREDITO..TTABE T1 (NOLOCK) WHERE T1.TTCODTAB=T.TTCODTAB)   AND   
T.TTDTFIM >=GETDATE()  
AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1    
      WHEN  @PRODUTO<>'99' AND L.RLCODPRD = @PRODUTO  THEN 1            
      ELSE  0   END   
ORDER BY 1    
END      
ELSE      
      
IF @TIPO = 3 --INATIVOS      
BEGIN      
SELECT DISTINCT        
T.TTCODTAB 'CÓDIGO TABELA',         
T.TTDESCR 'DESCRIÇÃO TABELA',        
L.RLCODPRD 'CÓDIGO PRODUTO',  
TP.TPDESCR 'DESCRIÇÃO PRODUTO',   
T.TTDTINI 'DATA INÍCIO',         
T.TTDTFIM 'DATA FIM',      
CASE WHEN TTDTFIM >= GETDATE() THEN 'ATIVO'  
ELSE 'INATIVO' END 'SITUAÇÃO',  
T.TTANOINI 'ANO',  
T.TTANOFIM 'MODELO',  
T.TTVLRENTMN 'ENTRADA MINIMA',  
T.TTSCOREINI 'SCORE',  
TC.OCDESCR 'CÓDIGO DA OCUPAÇÃO',  
T.TTCODDSP 'POLÍTICA DESPESA',  
CASE WHEN T.TTTXCOMRET = 'N' THEN 'NÃO' ELSE 'SIM' END 'RETORNO'  
FROM  CDCSANTANAMICROCREDITO..TTABE T (NOLOCK)        
INNER JOIN CDCSANTANAMICROCREDITO..TPLOR L (NOLOCK) ON T.TTCODTAB = L.RLCODTAB        
INNER JOIN CDCSANTANAMICROCREDITO..TPROD TP (NOLOCK) ON TP.TPCODPRD = L.RLCODPRD      
LEFT  JOIN CDCSANTANAMICROCREDITO..TOCUP TC (NOLOCK) ON T.TTCODOCUP = TC.OCCODOCUP  
WHERE    
T.TTCNTRL =  (SELECT MAX(T1.TTCNTRL) FROM CDCSANTANAMICROCREDITO..TTABE T1 (NOLOCK) WHERE T1.TTCODTAB=T.TTCODTAB)   AND   
T.TTDTFIM <GETDATE()  
AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1    
      WHEN  @PRODUTO<>'99' AND L.RLCODPRD = @PRODUTO  THEN 1            
      ELSE  0   END   
ORDER BY 1     
END 