USE SIG --[Santana]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_OPERADORES' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_OPERADORES
GO

CREATE PROCEDURE SCR_OPERADORES @TIPO SMALLINT, @AGNT VARCHAR(10) AS        
IF @TIPO = 1 --TODOS          
BEGIN          
SELECT O6CODORG 'CÓDIGO OPERADOR', O6DESCR 'NOME OPERADOR', T1.O3CODORG 'CÓDIGO PROMOTORA', T1.O3DESCR 'NOME PROMOTORA',           
CASE WHEN O6ATIVA = 'A' THEN 'ATIVO' ELSE 'DESATIVADO' END AS 'ATIVO', USNOMEUSU, COD_ATIVA + ' - ' + T2.O3DESCR AS 'DEPARA'           
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK)   
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 T1 (NOLOCK) ON O6CODORG3 = T1.O3CODORG  
LEFT  JOIN ACESSOCORP..TOUSU (NOLOCK) ON OUCODORG = O6CODORG AND OUTPORG = 6  
LEFT  JOIN ACESSOCORP..TUSU (NOLOCK) ON USCODUSU = OUCODUSU  
LEFT  JOIN DEPARA_AGENTE (NOLOCK) ON COD_VIUVA = T1.O3CODORG  
LEFT  JOIN CDCSANTANAMICROCREDITO..TORG3 T2 (NOLOCK) ON COD_ATIVA = T2.O3CODORG  
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES          
      WHEN  @AGNT<>'99' AND T1.O3CODORG = @AGNT  THEN 1          
      ELSE  0   END      
AND (USGRUPO1 = '06608' OR USGRUPO2 = '06608' OR USGRUPO3 = '06608' OR USGRUPO4 = '06608')           
ORDER BY O6CODORG ASC            
END          
ELSE        
IF @TIPO = 2        
BEGIN         
SELECT O6CODORG 'CÓDIGO OPERADOR', O6DESCR 'NOME OPERADOR', T1.O3CODORG 'CÓDIGO PROMOTORA', T1.O3DESCR 'NOME PROMOTORA',           
CASE WHEN O6ATIVA = 'A' THEN 'ATIVO' ELSE 'DESATIVADO' END AS 'ATIVO', USNOMEUSU, COD_ATIVA + ' - ' + T2.O3DESCR AS 'DEPARA'           
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..TORG3 T1 (NOLOCK) ON O6CODORG3 = O3CODORG           
LEFT JOIN ACESSOCORP.DBO.TOUSU (NOLOCK) ON OUCODORG = O6CODORG AND OUTPORG = 6      
LEFT JOIN ACESSOCORP.DBO.TUSU (NOLOCK) ON USCODUSU =OUCODUSU      
LEFT JOIN DEPARA_AGENTE (NOLOCK) ON COD_VIUVA = O3CODORG  
LEFT JOIN CDCSANTANAMICROCREDITO..TORG3 T2 (NOLOCK) ON COD_ATIVA = T2.O3CODORG  
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES          
      WHEN  @AGNT<>'99' AND T1.O3CODORG = @AGNT  THEN 1          
      ELSE  0   END       
AND (USGRUPO1 = '06608' OR USGRUPO2 = '06608' OR USGRUPO3 = '06608' OR USGRUPO4 = '06608')                   
AND O6ATIVA = 'A'          
ORDER BY O6CODORG ASC            
END        
ELSE        
IF @TIPO = 3        
BEGIN        
SELECT O6CODORG 'CÓDIGO OPERADOR', O6DESCR 'NOME OPERADOR', T1.O3CODORG 'CÓDIGO PROMOTORA', T1.O3DESCR 'NOME PROMOTORA',           
CASE WHEN O6ATIVA = 'A' THEN 'ATIVO' ELSE 'DESATIVADO' END AS 'ATIVO', USNOMEUSU, COD_ATIVA + ' - ' + T2.O3DESCR AS 'DEPARA'           
FROM CDCSANTANAMICROCREDITO..TORG6 (NOLOCK) INNER JOIN CDCSANTANAMICROCREDITO..TORG3 T1 (NOLOCK) ON O6CODORG3 = O3CODORG           
LEFT JOIN ACESSOCORP.DBO.TOUSU (NOLOCK) ON OUCODORG = O6CODORG AND OUTPORG = 6      
LEFT JOIN ACESSOCORP.DBO.TUSU (NOLOCK) ON USCODUSU =OUCODUSU      
LEFT JOIN DEPARA_AGENTE (NOLOCK) ON COD_VIUVA = O3CODORG  
LEFT JOIN CDCSANTANAMICROCREDITO..TORG3 T2 (NOLOCK) ON COD_ATIVA = T2.O3CODORG   
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES          
      WHEN  @AGNT<>'99' AND T1.O3CODORG = @AGNT  THEN 1          
      ELSE  0   END    
AND (USGRUPO1 = '06608' OR USGRUPO2 = '06608' OR USGRUPO3 = '06608' OR USGRUPO4 = '06608')                    
AND O6ATIVA = 'D'          
ORDER BY O6CODORG ASC          
END