
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_RENEG_GERAL' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_RENEG_GERAL
GO


CREATE Procedure [dbo].SCR_RENEG_GERAL (@rpt as int, @DT_INI as datetime, @DT_FIM as datetime, @DT_REF as datetime)   
AS  
BEGIN    
  
EXEC SPR_PRINCIPAL   @DT_INI , @DT_FIM  , @DT_REF  
  
EXEC SPR_PRINCIPAL_RENEG @DT_INI , @DT_FIM  , @DT_REF  
   
  
-- DEPENDE DO TIPO DE QUEBRA  
IF @RPT =1  -- NATUREZA OCUPACAO  
BEGIN  
 EXEC SPR_TOTALIZADOR  @DT_INI , @DT_FIM  , @DT_REF  
END  
IF @RPT =2  -- ANO VEICULO  
BEGIN  
 EXEC SPR_TOTALIZADOR_ANO  @DT_INI , @DT_FIM  , @DT_REF  
END  
IF @RPT =3  -- ANO VEICULO X NATUREZA OCUPACAO  
BEGIN  
 EXEC SPR_TOTALIZADOR_ANO_OCUP  @DT_INI , @DT_FIM  , @DT_REF  
END  
  
-- NOVOS 2015  
IF @RPT =4  -- TIPO X ANO VEICULO  
BEGIN  
 EXEC SPR_TOTALIZADOR_TIPO_ANO  @DT_INI , @DT_FIM  , @DT_REF  
END  
  
IF @RPT =5  -- TIPO X ANO VEICULO X NATUREZA OCUPACAO  
BEGIN  
 EXEC SPR_TOTALIZADOR_TIPO_ano_Ocup  @DT_INI , @DT_FIM  , @DT_REF  
END  
  
SELECT ATIVIDADE, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO, PREJUIZO,  
  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA,  
   PERC_PERDA_RELIZADA as PERC_PERDA_REALIZADA  
--, TIPO  
-- PERC_PERDA_REAAALIZADA  
  
  
 FROM TOTAL_SPREAD (NOLOCK)  
 ORDER BY  ATIVIDADE, TIPO  
  
END  