
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPR_PRINCIPAL' AND type = 'P')
   DROP PROCEDURE [dbo].[SPR_PRINCIPAL]
GO


CREATE Procedure [dbo].[SPR_PRINCIPAL] (@DT_INI as datetime, @DT_FIM as datetime, @DT_REF as datetime) AS  
BEGIN  
  
TRUNCATE TABLE DESCONTO_PERDA   
TRUNCATE TABLE PREJUIZO_PERDA  
TRUNCATE TABLE AVENCER_PERDA  
TRUNCATE TABLE PDD_PERDA  
TRUNCATE TABLE CARTEIRA_PERDA   
  
--carteira   
INSERT INTO CARTEIRA_PERDA  (CONTRATO, DT_BASE, PV_CONTRATO,FV_CONTRATO, VLR_PARCELA, QTDDPARC, ANO_MOD,ATIVIDADE)  
  
-- NATUREZA DE OCUPACAO  
SELECT DISTINCT OPNROPER,  OPDTBASE,  OPVLROPCZ, OPVLRBRUTO, OPVLRPARC, OPQTDDPARC,   
  '', 
  CASE CLCODOCUP   
    WHEN '01' THEN 'CLT'   
    WHEN '02' THEN 'AUTONOMO'   
    WHEN '03' THEN 'APOSENTADO'   
    WHEN '04' THEN 'EMPRESARIO'  
    ELSE 'CLT'  --'S/ INFO'   
  END as ATIV  
 FROM CDCSANTANAMicroCredito..COPER O (NOLOCK),   
  CDCSANTANAMicroCredito..TMODA T (NOLOCK),    
  PROPWEBSMC..cclip C (NOLOCK)  
 WHERE OPCODCLI = CLCODCLI   
  AND O.OPCODOP = T.TOCODOP   
  AND O.OPDTBASE >= @DT_INI   
  AND O.OPDTBASE <= @DT_FIM    
  AND (OPCODOP IN (SELECT M.COD_MODA  
      FROM Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)    
      WHERE M.COD_PROD = T.COD_PROD   
       AND T.COD_MODALIDADE = M.COD_MODALIDADE   
       AND T.COD_PROD = 'V' )  
--   OR OPCODOP IN (751, 752)   
   OR TOCODCART IN ('75')    )  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM CARTEIRA_PERDA  
  WHERE CONTRATO IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  

-- ATUALIZA O ANOMODELO DO VEICULO  
UPDATE  CARTEIRA_PERDA  
 SET  ANO_MOD = ISNULL(ABANOMOD,'S/INF')  
 FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)  
 WHERE CONTRATO= B.ABNROPER  
  and B.abNrGar = (select max(abnrgar)   
     FROM CDCSANTANAMicroCredito..CBFIN B1 (NOLOCK)  
     where b1.ABNROPER=CONTRATO)  
  and B.AbCNTRL = (select max(AbCNTRL)   
     FROM CDCSANTANAMicroCredito..CBFIN B2 (NOLOCK)  
     where b2.ABNROPER=CONTRATO and b2.abNrGar=B.abNrGar)  
  
-- RENEGOCIADO SEM ANO  
UPDATE  CARTEIRA_PERDA  
 SET  ANO_MOD = ISNULL(ABANOMOD,'S/INF')  
 FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)  
 WHERE CONTRATO = LEFT(RTRIM(B.ABNROPER),LEN(RTRIM(B.ABNROPER))-1)  
  AND B.abNrGar = (SELECT MAX(BX.abNrGar) FROM CDCSANTANAMicroCredito..CBFIN BX  (NOLOCK) WHERE  LEFT(RTRIM(BX.ABNROPER),LEN(RTRIM(BX.ABNROPER))-1) =  LEFT(RTRIM(CONTRATO),LEN(RTRIM(CONTRATO))-1) )  
  AND B.ABCNTRL = (SELECT MAX(BX.ABCNTRL) FROM CDCSANTANAMicroCredito..CBFIN BX  (NOLOCK) WHERE  LEFT(RTRIM(BX.ABNROPER),LEN(RTRIM(BX.ABNROPER))-1) =  LEFT(RTRIM(CONTRATO),LEN(RTRIM(CONTRATO))-1)  and bX.abNrGar=B.abNrGar )  
  AND (ISNULL(ANO_MOD,'') = '' OR ABANOMOD='S/INF')  -- VAZIO  
  
 -- SEM ANO MODELO CADASTRADO  
 UPDATE   CARTEIRA_PERDA set ANO_MOD='1900'  
  WHERE  ANO_MOD =  ''      
  
------ PREJUIZO   
INSERT INTO PREJUIZO_PERDA (OPNROPER, QTD_PARC, VLR_PREJU)  
SELECT DISTINCT OPNROPER, count(panrparc)QTD_PARC,  sum (ISNULL(opvlrparc,0.0)) VLR_PREJU   
FROM CDCSANTANAMicroCredito..COPER O (NOLOCK),   
  CDCSANTANAMicroCredito..CPARC X (NOLOCK),   
  SIG..RATING_HISTORICO H (NOLOCK)  
WHERE OPNROPER = PANROPER  
  AND NUM_OPE = OPNROPER    
  AND x.pacntrl = (Select max(y.pacntrl)   
      from CDCSANTANAMicrocredito .. cparc y (NOLOCK)  
      Where y.panroper = x.panroper and y.panrparc = x.panrparc)                 
  and NVL_RISCO = 'HH'  
  AND PANRPARC <> 0  
  AND O.OPDTBASE >= @DT_INI    
  AND O.OPDTBASE <= @DT_FIM  
  AND (PADTLIQ is null or PADTLIQ >= @DT_REF)  
  and DT_FECHA = ( SELECT MAX(DT_FECHA) FROM SIG..RATING_HISTORICO (NOLOCK) WHERE DT_FECHA <= @DT_REF)  
group by OPNROPER  
  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM PREJUIZO_PERDA  
  WHERE OPNROPER IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  
  
INSERT INTO DESCONTO_PERDA (CONTRATO, VLR_DESCONTO)  
SELECT DISTINCT OPNROPER CONTRATO, (SUM(((PAVLRPR + PAVLRJR + PAVLRTARP) / POWER(((OPTXJRAP / 100.0) + 1.0), (DATEDIFF(DAY, ISNULL(PADTLIQ, @DT_REF), PADTVCTO) / 360.00000000)))) - SUM(PAVLRPAGO)) VLR_DESCONTO  
 FROM CDCSANTANAMICROCREDITO..COPER O (NOLOCK),   
   CDCSANTANAMICROCREDITO..TMODA T (NOLOCK),   
   CDCSANTANAMICROCREDITO..CPARC X (NOLOCK)  
 where panroper= opnroper   
  and X.PACNTRL = (SELECT  MAX(Y.PACNTRL)   
        FROM CDCSANTANAMICROCREDITO .. CPARC Y (NOLOCK)   
        WHERE Y.PANROPER = X.PANROPER AND Y.PANRPARC = X.PANRPARC)                 
  AND PANRPARC <> 0  
  AND PAVLRPAGO < OPVLRPARC -- PAGO COM DESCONTO  
  AND O.OPCODOP = T.TOCODOP    
  AND O.OPDTBASE >= @DT_INI   
  AND O.OPDTBASE <= @DT_FIM  
  AND PADTLIQ    <= @DT_REF   -- PAGOS ATEH A DT REF  
  AND (O.OPCODOP IN (SELECT M.COD_MODA  
       FROM Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)    
       WHERE M.COD_PROD = T.COD_PROD   
        AND T.COD_MODALIDADE = M.COD_MODALIDADE   
        AND T.COD_PROD = 'V' )  
   OR TOCODCART IN ('75')    )   
  AND OPNROPER  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA (NOLOCK))  
  
 GROUP BY OPNROPER  
  
UPDATE DESCONTO_PERDA SET VLR_DESCONTO = 0 WHERE VLR_DESCONTO < 0   
  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM DESCONTO_PERDA  
  WHERE CONTRATO IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  
  
  
---- VENCER   
  
INSERT INTO AVENCER_PERDA (OPNROPER, QTD_PARC,VLR_AVENCER)  
SELECT DISTINCT OPNROPER, count(panrparc)QTD_PARC,  sum (opvlrparc) VLR_AVENCER  
 FROM CDCSANTANAMICROCREDITO..COPER O (NOLOCK),   
   CDCSANTANAMICROCREDITO..TMODA T (NOLOCK),   
   CDCSANTANAMICROCREDITO..CPARC X (NOLOCK)  
 WHERE OPNROPER = PANROPER    
  AND X.PACNTRL = (SELECT  MAX(Y.PACNTRL)   
       FROM CDCSANTANAMICROCREDITO .. CPARC Y (NOLOCK)  
       WHERE Y.PANROPER = X.PANROPER AND Y.PANRPARC = X.PANRPARC)                 
  AND PANRPARC <> 0  
  AND O.OPCODOP = T.TOCODOP    
  AND O.OPDTBASE >= @DT_INI   -- SAFRA  
  AND O.OPDTBASE <= @DT_FIM  
  AND (O.OPCODOP IN (SELECT M.COD_MODA  
       FROM Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)    
       WHERE M.COD_PROD = T.COD_PROD   
        AND T.COD_MODALIDADE = M.COD_MODALIDADE   
        AND T.COD_PROD = 'V' )  
   OR TOCODCART IN ('75')    )  
  AND (PADTLIQ is null or PADTLIQ > @DT_REF)  -- NAO PAGOS OU PAGO APOS A DATA  
  AND OPNROPER  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA (NOLOCK) )  
 GROUP BY OPNROPER  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM AVENCER_PERDA  
  WHERE OPNROPER IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  
  
--- PDD  
  
INSERT INTO PDD_PERDA (NUM_OPE, VLR_PDD)  
  
SELECT  NUM_OPE, ISNULL(VLR_PDD,0.0)  
 FROM SIG..RATING_HISTORICO (NOLOCK)  
 WHERE   DT_FECHA = ( SELECT MAX(DT_FECHA) FROM SIG..RATING_HISTORICO (NOLOCK) WHERE DT_FECHA <= @DT_REF)  
  AND DT_BASE >= @DT_INI   
  AND DT_BASE <= @DT_FIM  
  AND NUM_OPE  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA (NOLOCK))  

DELETE FROM PDD_PERDA  
  WHERE NUM_OPE IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  
  
UPDATE CARTEIRA_PERDA SET VLR_PREJUIZO = 0.0 WHERE VLR_PREJUIZO IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_DESCONTO = 0.0 WHERE VLR_DESCONTO IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_RECEBER  = 0.0 WHERE VLR_RECEBER  IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_PDD      = 0.0 WHERE VLR_PDD      IS NULL  
UPDATE CARTEIRA_PERDA SET TOTAL_PREJUIZO = 0.0 WHERE TOTAL_PREJUIZO  IS NULL  
  
---- AJUSTES 1 (AGRUPA VALORES)  
  
UPDATE CARTEIRA_PERDA SET VLR_PREJUIZO  = ISNULL(VLR_PREJU,0.0)    FROM PREJUIZO_PERDA (NOLOCK)   WHERE CONTRATO = OPNROPER  
UPDATE CARTEIRA_PERDA SET CARTEIRA_PERDA.VLR_DESCONTO  = ISNULL(DESCONTO_PERDA.VLR_DESCONTO,0.0) FROM DESCONTO_PERDA  (NOLOCK)  WHERE CARTEIRA_PERDA.CONTRATO = DESCONTO_PERDA.CONTRATO  
UPDATE CARTEIRA_PERDA SET VLR_RECEBER   = ISNULL(VLR_AVENCER,0.0)  FROM AVENCER_PERDA  (NOLOCK)   WHERE CONTRATO = OPNROPER   
UPDATE CARTEIRA_PERDA SET CARTEIRA_PERDA.VLR_PDD  = ISNULL(PDD_PERDA.VLR_PDD,0.0)      FROM PDD_PERDA  (NOLOCK)       WHERE CONTRATO = NUM_OPE  
  
-- INCLUI 14/11/16 ********************** ZERAR VALORES depois DE AGRUPAR, P/ EVITAR NULL  
-- NULL VLR_RECEBER, VLR_PDD, TOTAL_PREJUIZO  
UPDATE CARTEIRA_PERDA SET VLR_PREJUIZO = 0.0 WHERE VLR_PREJUIZO IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_DESCONTO = 0.0 WHERE VLR_DESCONTO IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_RECEBER  = 0.0 WHERE VLR_RECEBER  IS NULL  
UPDATE CARTEIRA_PERDA SET VLR_PDD      = 0.0 WHERE VLR_PDD      IS NULL  
UPDATE CARTEIRA_PERDA SET TOTAL_PREJUIZO = 0.0 WHERE TOTAL_PREJUIZO  IS NULL  
-- FIM  **********  INCLUI 14/11/16 ********************** ZERAR VALORES depois DE AGRUPAR, P/ EVITAR NULL  
  
  --- AJUSTE 2 (CALCULA PLANILHA)  
 UPDATE CARTEIRA_PERDA SET VLR_RECEBIDO       = (ISNULL(FV_CONTRATO ,0.0) - ISNULL(VLR_PREJUIZO,0.0) - ISNULL(VLR_DESCONTO,0.0) - ISNULL(VLR_RECEBER,0.0))  
 UPDATE CARTEIRA_PERDA SET VLR_TOTAL_PERDA    = (ISNULL(VLR_PREJUIZO,0.0) + ISNULL(VLR_DESCONTO,0.0))      -- 1  
 UPDATE CARTEIRA_PERDA SET VLR_LIQUIDADO      = (ISNULL(VLR_RECEBIDO,0.0) + ISNULL(VLR_TOTAL_PERDA,0.0))  
 UPDATE CARTEIRA_PERDA SET VLR_SAFRA          = (ISNULL(VLR_RECEBIDO,0.0) + ISNULL(VLR_PREJUIZO,0.0) + ISNULL(VLR_DESCONTO,0.0) + ISNULL(VLR_RECEBER,0.0))  
 UPDATE CARTEIRA_PERDA SET VLR_PERDA_RELIZADA = (ISNULL(VLR_TOTAL_PERDA,0.0) + ISNULL(VLR_PDD,0.0) )  
  
  
--- AJUSTE 3 (ATUALIZA TOTAIS)  
 UPDATE CARTEIRA_PERDA SET TOTAL_OPERADO  =  (SELECT SUM(FV_CONTRATO)  FROM CARTEIRA_PERDA (NOLOCK))  
 UPDATE CARTEIRA_PERDA SET TOTAL_RECEBIDO  =  (SELECT SUM(VLR_RECEBIDO) FROM CARTEIRA_PERDA (NOLOCK))  
 UPDATE CARTEIRA_PERDA SET TOTAL_PREJUIZO  =  (SELECT SUM(VLR_PREJUIZO) FROM CARTEIRA_PERDA (NOLOCK))  
 UPDATE CARTEIRA_PERDA SET TOTAL_DESCONTO  =  (SELECT SUM(VLR_DESCONTO) FROM CARTEIRA_PERDA (NOLOCK))    
 UPDATE CARTEIRA_PERDA SET TOTAL_PERDA_TOTAL =  (SELECT SUM(VLR_TOTAL_PERDA) FROM CARTEIRA_PERDA (NOLOCK)) -- 2  
 UPDATE CARTEIRA_PERDA SET TOTAL_LIQUIDADO  =  (SELECT SUM(VLR_LIQUIDADO)   FROM CARTEIRA_PERDA (NOLOCK))  
 UPDATE CARTEIRA_PERDA SET TOTAL_ARECEBER  =  (SELECT SUM(VLR_RECEBER)     FROM CARTEIRA_PERDA (NOLOCK)  )  
 UPDATE CARTEIRA_PERDA SET TOTAL_PDD   =  (SELECT SUM(VLR_PDD)   FROM PDD_PERDA (NOLOCK) WHERE NOT RIGHT(NUM_OPE,1) IN ('A','B','C') )  
 UPDATE CARTEIRA_PERDA SET TOTAL_SAFRA   =  (SELECT SUM(VLR_SAFRA) FROM CARTEIRA_PERDA (NOLOCK))  
 UPDATE CARTEIRA_PERDA SET TOATL_PERDA_REALIZADA = (SELECT SUM(VLR_PERDA_RELIZADA) FROM CARTEIRA_PERDA (NOLOCK))  
  
UPDATE CARTEIRA_PERDA SET PER_OPERADO   = CASE WHEN TOTAL_OPERADO=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(FV_CONTRATO,0.0)/ TOTAL_OPERADO))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_RECEBIDO   = CASE WHEN TOTAL_RECEBIDO=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_RECEBIDO,0.0)/ TOTAL_RECEBIDO))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_PREJUIZO   = CASE WHEN TOTAL_PREJUIZO=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_PREJUIZO,0.0)/ TOTAL_PREJUIZO))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_DESCONTO   = CASE WHEN TOTAL_DESCONTO=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_DESCONTO,0.0)/ TOTAL_DESCONTO))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_TOTAL_PERDA  = CASE WHEN TOTAL_PERDA_TOTAL=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_TOTAL_PERDA,0.0)/ TOTAL_PERDA_TOTAL))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_ARECEBER   = CASE WHEN TOTAL_ARECEBER=0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_RECEBER,0.0)/ TOTAL_ARECEBER))*100.0) END  
UPDATE CARTEIRA_PERDA SET PERC_SAFRA   = CASE WHEN TOTAL_SAFRA=0.0  THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_SAFRA,0.0) / TOTAL_SAFRA))*100.0)  END  
UPDATE CARTEIRA_PERDA SET PERC_PERDA_RELIZADA = CASE WHEN VLR_SAFRA=0.0  THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(VLR_PERDA_RELIZADA,0.0) / VLR_SAFRA))*100.0) END  
  
END  