
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPR_TOTALIZADOR_TIPO_ano_Ocup' AND type = 'P')
   DROP PROCEDURE [dbo].SPR_TOTALIZADOR_TIPO_ano_Ocup
GO

CREATE Procedure [dbo].SPR_TOTALIZADOR_TIPO_ano_Ocup (@DT_INI as datetime, @DT_FIM as datetime, @DT_REF as datetime) AS  
BEGIN  
  
  
TRUNCATE TABLE TOTAL_SPREAD  
  
/*  
CREATE TABLE TOTAL_SPREAD (  
atividade varchar (50),  
OPERADO float ,  
PER_OPERADO float,  
RECEBIDO float,  
PERC_RECEBIDO float,  
PREJUIZO float,  
PERC_PREJUIZO float,  
PERC_PREJUIZO_PERDA float,  
DESCONTO float,  
PERC_DESCONTO float,  
PERC_DESCONTO_PERDA float,  
PERDA_TOTAL float,  
PERC_TOTAL_PERDA float,  
PERC_TOTAL_PERDA1 float,  
LIQUIDADO float,  
PERC_LIQUIDADO float,  
PERC_LIQUIDADO_PERDA float,  
RECEBER float,  
PERC_ARECEBER float,  
PERC_ARECEBER_PERDA float,  
PDD float,  
PERC_PDD float,  
SAFRA float,  
PERC_SAFRA float,  
PERDA_REALIZADA float,  
PERC_PERDA_RELIZADA float,  
TIPO varchar(19),  
TOTAL_OPERADO float,  
TOTAL_RECEBIDO float,  
TOTAL_PREJUIZO float,  
TOTAL_DESCONTO float,  
TOTAL_PERDA_TOTAL float,  
TOTAL_LIQUIDADO float ,  
TOTAL_ARECEBER float ,  
TOTAL_PDD float ,  
TOTAL_SAFRA float ,  
TOTAL_PERDA_REALIZADA float)  
*/  
  
  
 -- ajusta TIPO VEICULO  -- TIPO VEICULO ******************** ATIVIDADE  
 UPDATE CARTEIRA_PERDA  
 SET  TIPO = CASE WHEN DESCR_TIPO= 'Automatico'  THEN 'Leves'   
      WHEN DESCR_TIPO= 'Leves'   THEN 'Leves'   
      WHEN DESCR_TIPO IN ('Utilitario','Utilitarios')  THEN 'Utilitario'   
      WHEN DESCR_TIPO= 'Motos'   THEN 'Motos'   
      WHEN DESCR_TIPO= 'Refinanciamento' THEN 'Leves'   
      WHEN DESCR_TIPO= 'Refinanciamento Utilitarios' THEN 'Utilitario'   
      WHEN DESCR_TIPO IS NULL THEN 'Leves'  
      ELSE DESCR_TIPO  END  
 FROM CDCSANTANAMicroCredito..COPER B (NOLOCK),  
   Ttipo_prod  T (NOLOCK),   
   TModa_tipo_prod M (NOLOCK)    
 WHERE 
   M.COD_PROD      = 'V'     
  AND M.COD_PROD   = T.COD_PROD   
  AND T.COD_MODALIDADE = M.COD_MODALIDADE   
  AND CARTEIRA_PERDA.CONTRATO = B.OPNROPER  
  AND B.OPCODOP = M.COD_MODA  
  
 UPDATE CARTEIRA_PERDA   -- LEVES SE NÃO CATEGORIZADO  
 SET  TIPO = 'Leves'   
 WHERE ISNULL(TIPO,'') = ''  
  
   
   UPDATE  CARTEIRA_PERDA set ANO_MOD='1900' WHERE isnull(ANO_MOD,'') =''  
  
   UPDATE CARTEIRA_PERDA  
   SET  ATIVIDADE = TIPO+ ' '+FX_ANO.DESCR +' - '+  ATIVIDADE -- FAIXA  
   FROM CARTEIRA_PERDA (NOLOCK) LEFT JOIN   
     (SELECT * FROM FX_ANO_SAFRA (NOLOCK) WHERE  DT_DE = (SELECT MAX(DT_DE)   
              FROM FX_ANO_SAFRA A1 (NOLOCK)  
              WHERE A1.DT_DE <=@DT_FIM) )  AS FX_ANO  
     ON ANO_MOD BETWEEN FX_ANO.DE AND FX_ANO.ATE  

   UPDATE  CARTEIRA_PERDA set atividade='' WHERE ATIVIDADE IS NULL  

   UPDATE CARTEIRA_PERDA_RENE  
   SET  ANO_MOD=ISNULL(ABANOMOD,'')  
   FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)  
   WHERE Contrato= B.ABNROPER  
    AND B.ABCNTRL = (SELECT  MAX(BX.ABCNTRL)   
         FROM CDCSANTANAMicroCredito..CBFIN BX (NOLOCK)   
         WHERE BX.ABNROPER = B.ABNROPER )  
    AND B.ABNRGAR = '01'  
   UPDATE  CARTEIRA_PERDA_RENE set ANO_MOD='1900' WHERE isnull(ANO_MOD,'') =''  
  
 UPDATE CARTEIRA_PERDA_RENE  
 SET  TIPO = CASE WHEN DESCR_TIPO= 'Automatico'  THEN 'Leves'   
      WHEN DESCR_TIPO= 'Leves'   THEN 'Leves'   
      WHEN DESCR_TIPO IN ('Utilitario','Utilitarios')  THEN 'Utilitario'   
      WHEN DESCR_TIPO= 'Motos'   THEN 'Motos'   
      WHEN DESCR_TIPO= 'Refinanciamento' THEN 'Leves'   
      WHEN DESCR_TIPO= 'Refinanciamento Utilitarios' THEN 'Utilitario'   
      WHEN DESCR_TIPO IS NULL THEN 'Leves'  
      ELSE DESCR_TIPO  END  
 FROM CDCSANTANAMicroCredito..COPER B (NOLOCK),  
   Ttipo_prod  T (NOLOCK),   
   TModa_tipo_prod M (NOLOCK)    
 WHERE   
   M.COD_PROD      = 'V'     
  AND M.COD_PROD   = T.COD_PROD   
  AND T.COD_MODALIDADE = M.COD_MODALIDADE   
  AND B.OPCODOP = M.COD_MODA  
  
 UPDATE CARTEIRA_PERDA_RENE   -- LEVES SE NÃO CATEGORIZADO  
 SET  TIPO = 'Leves'   
 WHERE ISNULL(TIPO,'') = ''  

   UPDATE  CARTEIRA_PERDA_RENE set ANO_MOD='1900' WHERE isnull(ANO_MOD,'') =''  

   UPDATE CARTEIRA_PERDA_RENE  
   SET  ATIVIDADE = TIPO+ ' '+FX_ANO.DESCR +' - '+ ATIVIDADE  -- FAIXA  
   FROM CARTEIRA_PERDA_RENE (NOLOCK) LEFT JOIN   
     (SELECT * FROM FX_ANO_SAFRA (NOLOCK) WHERE  DT_DE = (SELECT MAX(DT_DE)   
              FROM FX_ANO_SAFRA A1 (NOLOCK)  
              WHERE A1.DT_DE <=@DT_FIM) )  AS FX_ANO  
     ON ANO_MOD BETWEEN FX_ANO.DE AND FX_ANO.ATE  

   UPDATE  CARTEIRA_PERDA_RENE set atividade='' WHERE ATIVIDADE IS NULL  
  
  
  
--- ALIMENTA PRINCIPAL / POR ATIVIDADE  ****************************************  
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT  DISTINCT  
  atividade ,          
    (SUM(FV_CONTRATO)/1000.0)  OPERADO,   
        SUM(PER_OPERADO)       PER_OPERADO,  
    (SUM(ISNULL(VLR_RECEBIDO,0.0))/1000.0)  RECEBIDO,   
  SUM(PERC_RECEBIDO)     PERC_RECEBIDO,  
       (SUM(ISNULL(VLR_PREJUIZO,0.0))/1000.0)  PREJUIZO,   
     SUM(PERC_PREJUIZO)     PERC_PREJUIZO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE   
    (isnull(sum(VLR_PREJUIZO),0.0)/sum(FV_CONTRATO)*100.0) END  PERC_PREJUIZO_PERDA,  
       (SUM(ISNULL(VLR_DESCONTO,0.0))/1000.0)  DESCONTO,   
  SUM(PERC_DESCONTO)       PERC_DESCONTO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE   
    (sum(isnull(VLR_DESCONTO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_DESCONTO_PERDA,  
       (SUM(ISNULL(VLR_TOTAL_PERDA,0.0))/1000.0) PERDA_TOTAL,  
     sum(PERC_TOTAL_PERDA)    PERC_TOTAL_PERDA,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE   
    (sum(isnull(VLR_TOTAL_PERDA,0.0))/sum(FV_CONTRATO)*100.0) END    PERC_TOTAL_PERDA1,   
    (SUM(ISNULL(VLR_LIQUIDADO,0.0))/1000.0) LIQUIDADO,   
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE   
    (sum(isnull(VLR_LIQUIDADO,0.0))/sum(FV_CONTRATO)*100.0)  END       PERC_LIQUIDADO,  
  CASE WHEN sum(VLR_TOTAL_PERDA)+ sum(VLR_RECEBIDO)= 0.0 THEN 0.0 ELSE   
    (sum(VLR_TOTAL_PERDA) /(sum(VLR_TOTAL_PERDA)+ sum(VLR_RECEBIDO))*100.0) END    PERC_LIQUIDADO_PERDA,  
       (SUM(ISNULL(VLR_RECEBER,0.0))/1000.0)  RECEBER,      
  SUM(PERC_ARECEBER)     PERC_ARECEBER,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE   
  (sum(VLR_RECEBER)/sum(FV_CONTRATO)*100.0)   END  PERC_ARECEBER_PERDA,  
     (SUM(ISNULL(VLR_PDD,0.0))/1000.0)   PDD,  
  CASE WHEN SUM(VLR_RECEBER) = 0.0 THEN 0.0 ELSE   
  (sum(VLR_PDD)/sum(VLR_RECEBER)*100.0)    END   PERC_PDD,  
     (SUM(ISNULL(VLR_SAFRA,0.0))/1000.0) SAFRA,   
      SUM(PERC_SAFRA)    PERC_SAFRA,  
     (SUM(ISNULL(VLR_PERDA_RELIZADA,0.0))/1000.0) PERDA_REALIZADA,   
  CASE WHEN SUM(VLR_SAFRA) = 0.0 THEN 0.0 ELSE  
        (sum(VLR_PERDA_RELIZADA)/sum(VLR_SAFRA)*100.0) END  PERC_PERDA_RELIZADA,   
        '01'                                    TIPO  --- 'PRINCIPAL ATIVIDADE'  
FROM CARTEIRA_PERDA (NOLOCK)  
WHERE NOT RIGHT(CONTRATO,1) IN ('A','B','C')  
group by  atividade   
  
  
-----  ALIMENTA RENEGOCIADO POR ATIVIDADE   
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT  DISTINCT  
  atividade ,          
    (SUM(FV_CONTRATO)/1000.0)  OPERADO,   
        SUM(PER_OPERADO)       PER_OPERADO,  
    (SUM(VLR_RECEBIDO)/1000.0)  RECEBIDO,   
  SUM(PERC_RECEBIDO)     PERC_RECEBIDO,  
       (SUM(VLR_PREJUIZO)/1000.0)  PREJUIZO,   
     SUM(PERC_PREJUIZO)     PERC_PREJUIZO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_PREJUIZO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_PREJUIZO_PERDA,  
       (SUM(VLR_DESCONTO)/1000.0)  DESCONTO,   
  SUM(PERC_DESCONTO)       PERC_DESCONTO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_DESCONTO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_DESCONTO_PERDA,  
       (SUM(VLR_TOTAL_PERDA)/1000.0) PERDA_TOTAL,  
     sum(PERC_TOTAL_PERDA)    PERC_TOTAL_PERDA,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_TOTAL_PERDA,0.0))/sum(FV_CONTRATO)*100.0) END    PERC_TOTAL_PERDA1,   
    (SUM(VLR_LIQUIDADO)/1000.0) LIQUIDADO,   
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_LIQUIDADO,0.0))/sum(FV_CONTRATO)*100.0)   END      PERC_LIQUIDADO,  
    case when((sum(VLR_TOTAL_PERDA) + sum(VLR_RECEBIDO)))= 0.0 then 0.0 else(sum(VLR_TOTAL_PERDA)/ (sum(VLR_TOTAL_PERDA) + sum(VLR_RECEBIDO))*100.0) END     PERC_LIQUIDADO_PERDA,  
       (SUM(VLR_RECEBER)/1000.0)  RECEBER,      
  SUM(PERC_ARECEBER)     PERC_ARECEBER,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_RECEBER)/sum(FV_CONTRATO)*100.0)   END PERC_ARECEBER_PERDA,  
     (SUM(VLR_PDD)/1000.0)   PDD,  
  CASE WHEN SUM(VLR_RECEBER) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_PDD)/sum(VLR_RECEBER)*100.0)    END   PERC_PDD,  
     (SUM(VLR_SAFRA)/1000.0)  SAFRA,   
      SUM(PERC_SAFRA)    PERC_SAFRA,  
     (SUM(VLR_PERDA_RELIZADA)/1000.0) PERDA_REALIZADA,   
  CASE WHEN SUM(VLR_SAFRA) = 0.0 THEN 0.0 ELSE  
        (sum(VLR_PERDA_RELIZADA)/sum(VLR_SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
   '02'                                    TIPO  --- 'RENEGOCIADO ATIVIDADE'   
 FROM CARTEIRA_PERDA_RENE (NOLOCK)  
group by  atividade   

UPDATE TOTAL_SPREAD   
SET  SAFRA = TOTAL_SPREAD.SAFRA - S.SAFRA  
FROM (SELECT    *  
   FROM TOTAL_SPREAD  (NOLOCK)    
   WHERE TIPO = '02'    )  AS S -- SAFRA DA RENEG  
WHERE TOTAL_SPREAD.TIPO = '01'    AND TOTAL_SPREAD.ATIVIDADE = S.ATIVIDADE  
-- ************************  
    
    
UPDATE TOTAL_SPREAD SET OPERADO =       0.0  WHERE TIPO = '02'     
UPDATE TOTAL_SPREAD SET PER_OPERADO =   0.0  WHERE TIPO = '02'        
UPDATE TOTAL_SPREAD SET RECEBIDO =     ISNULL(SAFRA,0.0) - ISNULL(DESCONTO,0.0) - ISNULL(PREJUIZO,0.0) - ISNULL(RECEBER,0.0)  
UPDATE TOTAL_SPREAD SET LIQUIDADO =     ISNULL(RECEBIDO,0.0) + ISNULL(PERDA_TOTAL,0.0)  
  
-- FIM 3/2/17  ***************************  
  
  
-----  
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT   DISTINCT  
  'TOTAL' ,          
    (SUM(FV_CONTRATO)/1000.0)  OPERADO,   
        SUM(PER_OPERADO)       PER_OPERADO,  
    (SUM(VLR_RECEBIDO)/1000.0)  RECEBIDO,   
  SUM(PERC_RECEBIDO)     PERC_RECEBIDO,  
       (SUM(VLR_PREJUIZO)/1000.0)  PREJUIZO,   
     SUM(PERC_PREJUIZO)     PERC_PREJUIZO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_PREJUIZO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_PREJUIZO_PERDA,  
       (SUM(VLR_DESCONTO)/1000.0)  DESCONTO,   
  SUM(PERC_DESCONTO)       PERC_DESCONTO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_DESCONTO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_DESCONTO_PERDA,  
       (SUM(VLR_TOTAL_PERDA)/1000.0) PERDA_TOTAL,  
     sum(PERC_TOTAL_PERDA)    PERC_TOTAL_PERDA,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_TOTAL_PERDA,0.0))/sum(FV_CONTRATO)*100.0) END    PERC_TOTAL_PERDA1,   
    (SUM(VLR_LIQUIDADO)/1000) LIQUIDADO,   
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_LIQUIDADO,0.0))/sum(FV_CONTRATO)*100.0)  END       PERC_LIQUIDADO,  
    (sum(VLR_TOTAL_PERDA) /(sum(VLR_TOTAL_PERDA)+ sum(VLR_RECEBIDO))*100.0)     PERC_LIQUIDADO_PERDA,  
       (SUM(VLR_RECEBER)/1000.0)  RECEBER,      
  SUM(PERC_ARECEBER)     PERC_ARECEBER,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_RECEBER)/sum(FV_CONTRATO)*100.0)   END  PERC_ARECEBER_PERDA,  
     (SUM(VLR_PDD)/1000.0)   PDD,  
  CASE WHEN SUM(VLR_RECEBER) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_PDD)/sum(VLR_RECEBER)*100.0)    END   PERC_PDD,  
     (SUM(VLR_SAFRA)/1000.0)  SAFRA,   
      SUM(PERC_SAFRA)    PERC_SAFRA,  
     (SUM(VLR_PERDA_RELIZADA)/1000.0) PERDA_REALIZADA,   
  CASE WHEN SUM(VLR_SAFRA) = 0.0 THEN 0.0 ELSE  
        (sum(VLR_PERDA_RELIZADA)/sum(VLR_SAFRA)*100.0) END   PERC_PERDA_RELIZADA,  
   '03'                                    TIPO  --- 'TOTAL GERAL'  
 FROM CARTEIRA_PERDA (NOLOCK)  
 WHERE NOT RIGHT(CONTRATO,1) IN ('A','B','C')  
  
  
---- TOTAL RENEGOCIAÇÃO   
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT   DISTINCT  
  'TOTAL_RENE' ,          
    (SUM(FV_CONTRATO)/1000.0)  OPERADO,   
        SUM(PER_OPERADO)       PER_OPERADO,  
    (SUM(VLR_RECEBIDO)/1000.0)  RECEBIDO,   
  SUM(PERC_RECEBIDO)     PERC_RECEBIDO,  
       (SUM(VLR_PREJUIZO)/1000.0)  PREJUIZO,   
     SUM(PERC_PREJUIZO)     PERC_PREJUIZO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_PREJUIZO,0.0))/sum(FV_CONTRATO)*100.0) END  PERC_PREJUIZO_PERDA,  
       (SUM(VLR_DESCONTO)/1000.0)  DESCONTO,   
  SUM(PERC_DESCONTO)       PERC_DESCONTO,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_DESCONTO,0.0))/sum(FV_CONTRATO)*100.0) END PERC_DESCONTO_PERDA,  
       (SUM(VLR_TOTAL_PERDA)/1000.0) PERDA_TOTAL,  
     sum(PERC_TOTAL_PERDA)    PERC_TOTAL_PERDA,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_TOTAL_PERDA,0.0))/sum(FV_CONTRATO)*100.0) END    PERC_TOTAL_PERDA1,   
    (SUM(VLR_LIQUIDADO)/1000.0) LIQUIDADO,   
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
    (sum(isnull(VLR_LIQUIDADO,0.0))/sum(FV_CONTRATO)*100.0)   END      PERC_LIQUIDADO,  
  CASE WHEN sum(VLR_TOTAL_PERDA)+ sum(VLR_RECEBIDO) = 0.0 THEN 0.0 ELSE  
    (sum(VLR_TOTAL_PERDA) /(sum(VLR_TOTAL_PERDA)+ sum(VLR_RECEBIDO))*100.0) END    PERC_LIQUIDADO_PERDA,  
       (SUM(VLR_RECEBER)/1000.0)  RECEBER,      
  SUM(PERC_ARECEBER)     PERC_ARECEBER,  
  CASE WHEN SUM(FV_CONTRATO) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_RECEBER)/sum(FV_CONTRATO)*100.0)   END PERC_ARECEBER_PERDA,  
     (SUM(VLR_PDD)/1000.0)   PDD,  
  CASE WHEN SUM(VLR_RECEBER) = 0.0 THEN 0.0 ELSE  
  (sum(VLR_PDD)/sum(VLR_RECEBER)*100.0)    END   PERC_PDD,  
     (SUM(VLR_SAFRA)/1000.0)SAFRA,   
      SUM(PERC_SAFRA)    PERC_SAFRA,  
     (SUM(VLR_PERDA_RELIZADA)/1000.0)PERDA_REALIZADA,   
  CASE WHEN SUM(VLR_SAFRA) = 0.0 THEN 0.0 ELSE  
        (sum(VLR_PERDA_RELIZADA)/sum(VLR_SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
   '04'                                    TIPO  --- 'TOTAL RENE'  
 FROM CARTEIRA_PERDA_RENE (NOLOCK)  

UPDATE TOTAL_SPREAD SET OPERADO =       0.0  WHERE TIPO = '04'   
UPDATE TOTAL_SPREAD SET PER_OPERADO =   0.0  WHERE TIPO = '04'   
-- REMOVI 3/2/17  ***************** RECALCULO ABAIXO  
-- UPDATE TOTAL_SPREAD SET RECEBIDO =     0.0  WHERE TIPO = '04'    UPDATE TOTAL_SPREAD SET PERC_RECEBIDO = 0.0  WHERE TIPO = '04'     
  
  
-- TIPO 3 TTL ************************** ALTERADO EM 3/2/17  INCLUIDO  
UPDATE TOTAL_SPREAD   
SET RECEBIDO =    S.R, LIQUIDADO=S.L, SAFRA =S.SF  
FROM (SELECT SUM(RECEBIDO) AS R, SUM(LIQUIDADO) AS L, SUM(SAFRA) AS SF  FROM TOTAL_SPREAD (NOLOCK)  
   WHERE TIPO IN ( '01')) AS S  
WHERE TOTAL_SPREAD.TIPO='03'  
  
  
---- TOTAL PRINCIPAL + RENEGOCIAÇÃO  - PROFISSÃO   
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO,  RECEBIDO, PREJUIZO, DESCONTO,  PERDA_TOTAL, LIQUIDADO,  
             RECEBER, PDD,  SAFRA, PERDA_REALIZADA, TIPO)  
SELECT   DISTINCT  
  ATIVIDADE ,          
    (SUM(ISNULL(OPERADO, 0.0)))         OPERADO,   
    (SUM(ISNULL(RECEBIDO,0.0)))   RECEBIDO,   
       (SUM(ISNULL(PREJUIZO,0.0)))   PREJUIZO,       
       (SUM(ISNULL(DESCONTO,0.0)))   DESCONTO,   
    (SUM(ISNULL(PERDA_TOTAL, 0.0)))     PERDA_TOTAL,      
    (SUM(ISNULL(LIQUIDADO, 0.0)))  LIQUIDADO,       
       (SUM(ISNULL(RECEBER,  0.0)))  RECEBER,       
       (SUM(ISNULL(PDD,0.0)))       PDD,  
       (SUM(ISNULL(SAFRA,0.0)))    SAFRA,   
    (SUM(ISNULL(PERDA_REALIZADA,0.0))) PERDA_REALIZADA,          
    '05'                                 TIPO  --- 'TOTAL PRINC +RENE - PROF'  
 FROM TOTAL_SPREAD  (NOLOCK)  
WHERE TIPO IN ('01','02')  
GROUP BY ATIVIDADE   


 UPDATE TOTAL_SPREAD SET PERDA_TOTAL    = (ISNULL(PREJUIZO,0.0) + ISNULL(DESCONTO,0.0))  WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET LIQUIDADO      = (ISNULL(RECEBIDO,0.0) + ISNULL(PERDA_TOTAL,0.0))  WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET SAFRA          = (ISNULL(RECEBIDO,0.0) + ISNULL(PREJUIZO,0.0) + ISNULL(DESCONTO,0.0) + ISNULL(RECEBER,0.0)) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET PERDA_REALIZADA = (ISNULL(PERDA_TOTAL,0.0) + ISNULL(PDD,0.0) )  WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_OPERADO     =  (SELECT SUM(ISNULL(OPERADO,0.0)) FROM TOTAL_SPREAD (NOLOCK)  WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_RECEBIDO     =  (SELECT SUM(ISNULL(RECEBIDO,0.0))  FROM TOTAL_SPREAD (NOLOCK)  WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_PREJUIZO     =  (SELECT SUM(ISNULL(PREJUIZO,0.0))  FROM TOTAL_SPREAD (NOLOCK)  WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_DESCONTO     =  (SELECT SUM(ISNULL(DESCONTO,0.0))  FROM TOTAL_SPREAD (NOLOCK)  WHERE TIPO IN ('05'))   WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_PERDA_TOTAL        =  (SELECT SUM(ISNULL(PERDA_TOTAL,0.0)) FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_LIQUIDADO       =  (SELECT SUM(ISNULL(LIQUIDADO,0.0)) FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') )  WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_ARECEBER           =  (SELECT SUM(ISNULL(RECEBER,0.0)) FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_PDD            =  (SELECT SUM(ISNULL(PDD,0.0))  FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_SAFRA        =  (SELECT SUM(ISNULL(SAFRA,0.0))  FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
 UPDATE TOTAL_SPREAD SET TOTAL_PERDA_REALIZADA    =  (SELECT SUM(ISNULL(PERDA_REALIZADA,0.0)) FROM TOTAL_SPREAD (NOLOCK) WHERE TIPO IN ('05') ) WHERE TIPO = '05'  
  
  
UPDATE TOTAL_SPREAD SET PER_OPERADO   =  CASE WHEN ISNULL(TOTAL_OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(OPERADO,0.0)/ TOTAL_OPERADO))*100.0)   
             END         WHERE TIPO = '05'  
UPDATE TOTAL_SPREAD SET PERC_RECEBIDO  = CASE WHEN ISNULL(TOTAL_RECEBIDO,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(RECEBIDO,0.0)/ TOTAL_RECEBIDO))*100.0)   
             END   WHERE TIPO = '05'  
UPDATE TOTAL_SPREAD SET PERC_PREJUIZO  = CASE WHEN ISNULL(TOTAL_PREJUIZO,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(PREJUIZO,0.0)/ TOTAL_PREJUIZO))*100.0)         
             END   WHERE TIPO = '05'          
UPDATE TOTAL_SPREAD SET PERC_DESCONTO  =  CASE WHEN ISNULL(TOTAL_DESCONTO,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(DESCONTO,0.0)/ TOTAL_DESCONTO))*100.0)         
             END    WHERE TIPO = '05'         
UPDATE TOTAL_SPREAD SET PERC_TOTAL_PERDA = CASE WHEN ISNULL(TOTAL_PERDA_TOTAL,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(PERDA_TOTAL,0.0)/ TOTAL_PERDA_TOTAL))*100.0)   
             END    WHERE TIPO = '05'       
UPDATE TOTAL_SPREAD SET PERC_ARECEBER  = CASE WHEN ISNULL(TOTAL_ARECEBER,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(RECEBER,0.0)/ TOTAL_ARECEBER))*100.0)          
             END    WHERE TIPO = '05'         
UPDATE TOTAL_SPREAD SET PERC_SAFRA   = CASE WHEN ISNULL(TOTAL_SAFRA,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(SAFRA,0.0) / TOTAL_SAFRA))*100.0)              
             END    WHERE TIPO = '05'         
UPDATE TOTAL_SPREAD SET PERC_PDD =            CASE WHEN ISNULL(TOTAL_PDD,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(PDD,0.0) / TOTAL_PDD))*100.0)                 
             END     WHERE TIPO = '05'         
  
  
UPDATE TOTAL_SPREAD SET PERC_PERDA_RELIZADA =   CASE WHEN ISNULL(SAFRA,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT,(isnull(PERDA_REALIZADA,0.0) / SAFRA))*100.0)   
              END         WHERE TIPO = '05'  
UPDATE TOTAL_SPREAD SET PERC_PREJUIZO_PERDA =  CASE WHEN ISNULL(OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              (CONVERT (FLOAT, isnull(PREJUIZO,0.0)/(ISNULL(OPERADO,0.0))*100.0))  
              END         WHERE TIPO = '05'   
  
UPDATE TOTAL_SPREAD SET PERC_DESCONTO_PERDA =  CASE WHEN ISNULL(OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              (isnull(DESCONTO,0.0)/isnull(OPERADO,0.0)*100.0)   
              END         WHERE TIPO = '05'   
UPDATE TOTAL_SPREAD SET PERC_TOTAL_PERDA1   =  CASE WHEN ISNULL(OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              (isnull(PERDA_TOTAL,0.0)/isnull(OPERADO,0.0)*100.0)  
              END         WHERE TIPO = '05'   
UPDATE TOTAL_SPREAD SET PERC_LIQUIDADO       = CASE WHEN ISNULL(OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              (isnull(LIQUIDADO,0.0)/isnull(OPERADO,0.0)*100.0)  
              END         WHERE TIPO = '05'   
UPDATE TOTAL_SPREAD SET PERC_LIQUIDADO_PERDA = CASE WHEN ISNULL(PERDA_TOTAL,0.0)+ isnull(RECEBIDO,0.0) = 0.0 THEN 0.0 ELSE  
              (isnull(PERDA_TOTAL,0.0) /(isnull(PERDA_TOTAL,0.0)+ isnull(RECEBIDO,0.0))*100.0)   
              END        WHERE TIPO = '05'   
UPDATE TOTAL_SPREAD SET PERC_ARECEBER_PERDA = CASE WHEN ISNULL(OPERADO,0.0) = 0.0 THEN 0.0 ELSE  
              ((isnull(RECEBER,0.0)/ isnull(OPERADO,0.0)*100.0) )  
              END         WHERE TIPO = '05'   
  
  
--------------- TOTAL GERAL   
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
  SELECT   DISTINCT  
  'TOTAL_GERAL',   
    SUM(OPERADO)           OPERADO,   
    SUM(PER_OPERADO)          PER_OPERADO,  
    SUM(RECEBIDO)          RECEBIDO,  
       SUM(PERC_RECEBIDO)         PERC_RECEBIDO,   
    SUM(PREJUIZO)          PREJUIZO,   
    SUM (PERC_PREJUIZO)         PERC_PREJUIZO,  
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       (SUM (PREJUIZO)/ SUM(OPERADO)*100.0)  END   PERC_PREJUIZO_PERDA,  
       SUM(DESCONTO)          DESCONTO,   
       SUM (PERC_DESCONTO)         PERC_DESCONTO,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
    (SUM (DESCONTO)/ SUM(OPERADO))   END   PERC_DESCONTO_PERDA,   
    (SUM (PREJUIZO)+ SUM(DESCONTO))      PERDA_TOTAL ,        
       SUM(PERC_TOTAL_PERDA)        PERC_TOTAL_PERDA,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       ((SUM (PREJUIZO)+ SUM(DESCONTO))/SUM(OPERADO)*100.0) END  PERC_TOTAL_PERDA1,  
       SUM(LIQUIDADO)          LIQUIDADO,   
       (SUM(LIQUIDADO)/SUM(OPERADO)*100.0)                    PERC_LIQUIDADO,   
  CASE WHEN SUM(LIQUIDADO) = 0.0 THEN 0.0 ELSE  
   (SUM(PERDA_TOTAL) /SUM(LIQUIDADO)*100.0) END  PERC_LIQUIDADO_PERDA,   
       SUM(RECEBER)           RECEBER ,  
       SUM(PERC_ARECEBER)         PERC_ARECEBER,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       (SUM(RECEBER)/SUM(OPERADO)*100.0)   END   PERC_ARECEBER_PERDA,   
       SUM(PDD)            PDD,  
  CASE WHEN SUM(RECEBER) = 0.0 THEN 0.0 ELSE  
       (SUM(PDD)/SUM(RECEBER)*100.0)     END   PERC_PDD,    -- AJUSTEI * 100 EM 7/2/17  
       SUM(SAFRA)           SAFRA,   
       SUM(PERC_SAFRA)          PERC_SAFRA,   
      ((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD))   PERDA_REALIZADA,   
  CASE WHEN SUM(SAFRA) = 0.0 THEN 0.0 ELSE  
      (((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD)) / SUM(SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
     '06'                                    TIPO  --- 'TOTAL PRINC +RENE - PROF'  
FROM TOTAL_SPREAD (NOLOCK) where tipo = '05'  
  

--------------- SUB  TOTAL POR TIPO DE VEICULO  ******************* TIPO 7  
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT  DISTINCT  
  LEFT(ATIVIDADE,5)+' SUB-TTL ',   
    SUM(OPERADO)           OPERADO,   
    SUM(PER_OPERADO)          PER_OPERADO,  
    SUM(RECEBIDO)          RECEBIDO,  
       SUM(PERC_RECEBIDO)         PERC_RECEBIDO,   
    SUM(PREJUIZO)          PREJUIZO,   
    SUM (PERC_PREJUIZO)         PERC_PREJUIZO,  
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       (SUM (PREJUIZO)/ SUM(OPERADO)*100.0)  END   PERC_PREJUIZO_PERDA,  
       SUM(DESCONTO)          DESCONTO,   
       SUM (PERC_DESCONTO)         PERC_DESCONTO,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
    (SUM (DESCONTO)/ SUM(OPERADO))   END   PERC_DESCONTO_PERDA,   
    (SUM (PREJUIZO)+ SUM(DESCONTO))      PERDA_TOTAL ,        
       SUM(PERC_TOTAL_PERDA)        PERC_TOTAL_PERDA,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       ((SUM (PREJUIZO)+ SUM(DESCONTO))/SUM(OPERADO)*100.0) END  PERC_TOTAL_PERDA1,  
       SUM(LIQUIDADO)          LIQUIDADO,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
        (SUM(LIQUIDADO)/SUM(OPERADO)*100.0)     END          PERC_LIQUIDADO,   
  CASE WHEN SUM(LIQUIDADO) = 0.0 THEN 0.0 ELSE  
       (SUM(PERC_TOTAL_PERDA) /SUM(LIQUIDADO)*100.0) END  PERC_LIQUIDADO_PERDA,   
       SUM(RECEBER)           RECEBER ,  
       SUM(PERC_ARECEBER)         PERC_ARECEBER,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
       (SUM(RECEBER)/SUM(OPERADO)*100.0)   END   PERC_ARECEBER_PERDA,   
       SUM(PDD)            PDD,  
  CASE WHEN SUM(RECEBER) = 0.0 THEN 0.0 ELSE  
       (SUM(PDD)/SUM(RECEBER))     END   PERC_PDD,   
       SUM(SAFRA)           SAFRA,   
       SUM(PERC_SAFRA)          PERC_SAFRA,   
      ((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD))   PERDA_REALIZADA,   
  CASE WHEN SUM(SAFRA) = 0.0 THEN 0.0 ELSE  
      (((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD)) / SUM(SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
     '07'                                    TIPO  --- 'TOTAL PRINC +RENE - PROF'  
FROM TOTAL_SPREAD (NOLOCK) where tipo = '01'   
GROUP BY LEFT(ATIVIDADE,5)  
  
  
  
--------------- SUB  TOTAL POR TIPO DE VEICULO  ******************* TIPO 8 RENEG  
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT  DISTINCT  
  LEFT(ATIVIDADE,5) + ' SUB-TTL RENEG ',   
    SUM(OPERADO)           OPERADO,   
    SUM(PER_OPERADO)          PER_OPERADO,  
    SUM(RECEBIDO)          RECEBIDO,  
       SUM(PERC_RECEBIDO)         PERC_RECEBIDO,   
    SUM(PREJUIZO)          PREJUIZO,   
    SUM (PERC_PREJUIZO)         PERC_PREJUIZO,  
    CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM (PREJUIZO)/ SUM(OPERADO)*100.0)  END   PERC_PREJUIZO_PERDA,  
       SUM(DESCONTO)          DESCONTO,   
       SUM (PERC_DESCONTO)         PERC_DESCONTO,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM (DESCONTO)/ SUM(OPERADO))   END   PERC_DESCONTO_PERDA,   
    (SUM (PREJUIZO)+ SUM(DESCONTO))      PERDA_TOTAL ,        
       SUM(PERC_TOTAL_PERDA)        PERC_TOTAL_PERDA,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   ((SUM (PREJUIZO)+ SUM(DESCONTO))/SUM(OPERADO)*100.0) END  PERC_TOTAL_PERDA1,  
       SUM(LIQUIDADO)          LIQUIDADO,   
  CASE WHEN SUM(OPERADO) = 0.0  THEN 0.0 ELSE  
   (SUM(LIQUIDADO)/SUM(OPERADO)*100.0)     END             PERC_LIQUIDADO,   
  CASE WHEN SUM(LIQUIDADO) = 0.0 THEN 0.0 ELSE  
   (SUM(PERC_TOTAL_PERDA) /SUM(LIQUIDADO)*100.0) END  PERC_LIQUIDADO_PERDA,   
       SUM(RECEBER)           RECEBER ,  
       SUM(PERC_ARECEBER)         PERC_ARECEBER,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM(RECEBER)/SUM(OPERADO)*100.0)   END   PERC_ARECEBER_PERDA,   
       SUM(PDD)            PDD,  
  CASE WHEN SUM(RECEBER) = 0.0 THEN 0.0 ELSE  
   (SUM(PDD)/SUM(RECEBER))     END   PERC_PDD,   
       SUM(SAFRA)           SAFRA,   
       SUM(PERC_SAFRA)          PERC_SAFRA,   
      ((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD))   PERDA_REALIZADA,   
  CASE WHEN SUM(SAFRA) = 0.0 THEN 0.0 ELSE  
   (((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD)) / SUM(SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
     '08'                                    TIPO  --- ' RENE - QUEBRA'  
FROM TOTAL_SPREAD (NOLOCK) where tipo = '02'  -- SOMA SOMENTE RENEG  
GROUP BY LEFT(ATIVIDADE,5)  
  
--------------- SUB  TOTAL POR TIPO DE VEICULO  ******************* TIPO 9 TTL GERAL C/ RENEG    
INSERT INTO TOTAL_SPREAD  (atividade, OPERADO, PER_OPERADO, RECEBIDO, PERC_RECEBIDO,  PREJUIZO,  
    PERC_PREJUIZO,  PERC_PREJUIZO_PERDA, DESCONTO, PERC_DESCONTO, PERC_DESCONTO_PERDA,    
    PERDA_TOTAL,  PERC_TOTAL_PERDA,  PERC_TOTAL_PERDA1,  LIQUIDADO, PERC_LIQUIDADO, PERC_LIQUIDADO_PERDA,  
             RECEBER, PERC_ARECEBER, PERC_ARECEBER_PERDA, PDD, PERC_PDD, SAFRA, PERC_SAFRA, PERDA_REALIZADA, PERC_PERDA_RELIZADA, TIPO)  
SELECT  DISTINCT  
  LEFT(ATIVIDADE,5)+ ' SUB-TTL-GERAL ',   
    SUM(OPERADO)           OPERADO,   
    SUM(PER_OPERADO)          PER_OPERADO,  
    SUM(RECEBIDO)          RECEBIDO,  
       SUM(PERC_RECEBIDO)         PERC_RECEBIDO,   
    SUM(PREJUIZO)          PREJUIZO,   
    SUM (PERC_PREJUIZO)         PERC_PREJUIZO,  
    CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM (PREJUIZO)/ SUM(OPERADO)*100.0)  END   PERC_PREJUIZO_PERDA,  
       SUM(DESCONTO)          DESCONTO,   
       SUM (PERC_DESCONTO)         PERC_DESCONTO,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM (DESCONTO)/ SUM(OPERADO))   END   PERC_DESCONTO_PERDA,   
    (SUM (PREJUIZO)+ SUM(DESCONTO))      PERDA_TOTAL ,        
       SUM(PERC_TOTAL_PERDA)        PERC_TOTAL_PERDA,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   ((SUM (PREJUIZO)+ SUM(DESCONTO))/SUM(OPERADO)*100.0) END  PERC_TOTAL_PERDA1,  
       SUM(LIQUIDADO)          LIQUIDADO,   
  CASE WHEN SUM(OPERADO) = 0.0  THEN 0.0 ELSE  
   (SUM(LIQUIDADO)/SUM(OPERADO)*100.0)     END             PERC_LIQUIDADO,   
  CASE WHEN SUM(LIQUIDADO) = 0.0 THEN 0.0 ELSE  
   (SUM(PERC_TOTAL_PERDA) /SUM(LIQUIDADO)*100.0) END  PERC_LIQUIDADO_PERDA,   
       SUM(RECEBER)           RECEBER ,  
       SUM(PERC_ARECEBER)         PERC_ARECEBER,   
  CASE WHEN SUM(OPERADO) = 0.0 THEN 0.0 ELSE  
   (SUM(RECEBER)/SUM(OPERADO)*100.0)   END   PERC_ARECEBER_PERDA,   
       SUM(PDD)            PDD,  
  CASE WHEN SUM(RECEBER) = 0.0 THEN 0.0 ELSE  
   (SUM(PDD)/SUM(RECEBER))     END   PERC_PDD,   
       SUM(SAFRA)           SAFRA,   
       SUM(PERC_SAFRA)          PERC_SAFRA,   
      ((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD))   PERDA_REALIZADA,   
  CASE WHEN SUM(SAFRA) = 0.0 THEN 0.0 ELSE  
   (((SUM (PREJUIZO)+ SUM(DESCONTO))+ SUM (PDD)) / SUM(SAFRA)*100.0)  END PERC_PERDA_RELIZADA,  
     '09'                                    TIPO  --- ' RENE - QUEBRA'  
FROM TOTAL_SPREAD (NOLOCK) where   tipo = '05'--tipo = '05'  -- SOMA SOMENTE RENEG  
GROUP BY LEFT(ATIVIDADE,5)  

-- REMOVE OS NULL  
UPDATE TOTAL_SPREAD SET  PREJUIZO = 0.0   WHERE PREJUIZO   IS NULL  
UPDATE TOTAL_SPREAD SET  PERC_PREJUIZO = 0.0  WHERE PERC_PREJUIZO IS NULL  
UPDATE TOTAL_SPREAD SET  PERC_PREJUIZO_PERDA = 0.0 WHERE PERC_PREJUIZO_PERDA IS NULL  
UPDATE TOTAL_SPREAD SET  DESCONTO = 0.0   WHERE DESCONTO   IS NULL  
UPDATE TOTAL_SPREAD SET  RECEBER = 0.0   WHERE RECEBER    IS NULL  
  
UPDATE TOTAL_SPREAD SET  PERC_ARECEBER_PERDA = 0.0  WHERE PERC_ARECEBER_PERDA    IS NULL  
UPDATE TOTAL_SPREAD SET  PDD = 0.0    WHERE PDD    IS NULL  
UPDATE TOTAL_SPREAD SET  PERC_PDD = 0.0   WHERE PERC_PDD    IS NULL  
  
UPDATE TOTAL_SPREAD SET  TOTAL_OPERADO = 0.0  WHERE TOTAL_OPERADO    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_RECEBIDO = 0.0 WHERE TOTAL_RECEBIDO    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_PREJUIZO = 0.0 WHERE TOTAL_PREJUIZO    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_DESCONTO = 0.0 WHERE TOTAL_DESCONTO    IS NULL  
  
UPDATE TOTAL_SPREAD SET  TOTAL_PERDA_TOTAL = 0.0 WHERE TOTAL_PERDA_TOTAL    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_LIQUIDADO = 0.0 WHERE TOTAL_LIQUIDADO    IS NULL  
  
UPDATE TOTAL_SPREAD SET  TOTAL_ARECEBER = 0.0 WHERE TOTAL_ARECEBER    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_PDD = 0.0   WHERE TOTAL_PDD    IS NULL  
UPDATE TOTAL_SPREAD SET  TOTAL_SAFRA = 0.0  WHERE TOTAL_SAFRA    IS NULL  
  
UPDATE TOTAL_SPREAD SET  TOTAL_PERDA_REALIZADA = 0.0  WHERE TOTAL_PERDA_REALIZADA    IS NULL  
  
UPDATE TOTAL_SPREAD SET  PERC_DESCONTO = 0.0  WHERE PERC_DESCONTO    IS NULL  
  

UPDATE TOTAL_SPREAD   
SET  PER_OPERADO = 100.0, PERC_RECEBIDO = 100.0,  PERC_PREJUIZO = 100.0,  PERC_DESCONTO = 100.0,  PERC_ARECEBER = 100.0,  
  PERC_SAFRA  = 100.0, PERC_TOTAL_PERDA = 100.0  
WHERE TOTAL_SPREAD.TIPO = '03' -- TTL SEM RENEG  

UPDATE TOTAL_SPREAD   
SET  PER_OPERADO = 100.0, PERC_RECEBIDO = 100.0,  PERC_PREJUIZO = 100.0,  PERC_DESCONTO = 100.0,  PERC_ARECEBER = 100.0,  
  PERC_SAFRA  = 100.0, PERC_TOTAL_PERDA = 100.0  
WHERE TOTAL_SPREAD.TIPO = '06' -- TTL GERAL  
  
  
UPDATE TOTAL_SPREAD SET  atividade = case when tipo='01' then atividade  
             when tipo in ('02') then atividade + ' Reneg'  
             when tipo='05' then atividade + '+Reneg'   
             else atividade end    
END  