USE SIG
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go


IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPR_PRINCIPAL_RENEG' AND type = 'P')
   DROP PROCEDURE [dbo].SPR_PRINCIPAL_RENEG
GO

CREATE Procedure [dbo].SPR_PRINCIPAL_RENEG (@DT_INI as datetime, @DT_FIM as datetime, @DT_REF as datetime) AS  
BEGIN  
  
  
TRUNCATE TABLE DESCONTO_PERDA_RENE   
TRUNCATE TABLE PREJUIZO_PERDA_RENE  
TRUNCATE TABLE AVENCER_PERDA_RENE  
TRUNCATE TABLE PDD_PERDA_RENE  
TRUNCATE TABLE CARTEIRA_PERDA_RENE   
TRUNCATE TABLE CARTEIRA_RENEGOCIADA  
TRUNCATE TABLE CARTEIRA_RENEGOCIADA1   
  
------ carteira renegociada   
  
insert into CARTEIRA_RENEGOCIADA (OPNROPER, OPDTBASE, OPNROPER2, OPDTBASE2)  
SELECT DISTINCT OPNROPER ,  OPDTBASE, OPNROPER2, OPDTBASE AS OPDTBASE2  
 FROM CDCSANTANAMicroCredito..COPER O (NOLOCK),   
   CDCSANTANAMicroCredito..TMODA T (NOLOCK)  
 WHERE O.OPCODOP = T.TOCODOP   
  AND T.TOCODCART IN ('75') 
  AND OPDTBASE <= @DT_REF  
  
update  CARTEIRA_RENEGOCIADA   
 set  CARTEIRA_RENEGOCIADA.OPNROPER2 = CASE WHEN RIGHT(OPNROPER,1) ='A' THEN LEFT(OPNROPER,LEN(OPNROPER)-1)  
              WHEN RIGHT(OPNROPER,1) ='B' THEN LEFT(OPNROPER,LEN(OPNROPER)-1)--+'A'  
              WHEN RIGHT(OPNROPER,1) ='C' THEN LEFT(OPNROPER,LEN(OPNROPER)-1)--+'B'  
              END   
 where OPNROPER2 IS NULL   
  
-- AJUSTA DT ORIGINAL DO CONTRATO SEM RENEG - ORIGINAL  
update  CARTEIRA_RENEGOCIADA   
 set  CARTEIRA_RENEGOCIADA.OPDTBASE2 = COPER.opdtbase   
 from CDCSANTANAMicroCredito..COPER coper  (NOLOCK)   
 where COPER.opnroper = CARTEIRA_RENEGOCIADA.opnroper2  

DELETE FROM CARTEIRA_RENEGOCIADA   
 WHERE OPNROPER2 IN (SELECT OPNROPER2 FROM CARTEIRA_RENEGOCIADA R2 (NOLOCK) GROUP BY OPNROPER2 HAVING COUNT(OPNROPER2)>=2 )  
  AND NOT (OPNROPER = (SELECT MAX(OPNROPER) FROM CARTEIRA_RENEGOCIADA R3 (NOLOCK)  WHERE OPNROPER2 = CARTEIRA_RENEGOCIADA.OPNROPER2))  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM CARTEIRA_RENEGOCIADA  
  WHERE OPNROPER IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A')  
  
--carteira   
INSERT INTO CARTEIRA_PERDA_RENE  (CONTRATO, DT_BASE, PV_CONTRATO,FV_CONTRATO, VLR_PARCELA, QTDDPARC, ANO_MOD,ATIVIDADE)  
  
-- NATUREZA DE OCUPACAO  
SELECT DISTINCT O.OPNROPER,  R.OPDTBASE2,  O.OPVLROPCZ, O.OPVLRBRUTO, O.OPVLRPARC, O.OPQTDDPARC,  
  '', 
  CASE CLCODOCUP   
    WHEN '01' THEN 'CLT'   
    WHEN '02' THEN 'AUTONOMO'   
    WHEN '03' THEN 'APOSENTADO'   
    WHEN '04' THEN 'EMPRESARIO'  
    ELSE 'CLT'  -- S/ INFO   
  END as ATIV  
 FROM CDCSANTANAMicroCredito..COPER O  (NOLOCK),   
   CDCSANTANAMicroCredito..TMODA T  (NOLOCK),   
    PROPWEBSMC..cclip C  (NOLOCK),   
   CARTEIRA_RENEGOCIADA R  (NOLOCK)  
 WHERE O.OPCODCLI = C.CLCODCLI   
  AND R.OPNROPER = O.OPNROPER  
  AND O.OPCODOP = T.TOCODOP   
  AND R.OPDTBASE2 BETWEEN  @DT_INI AND  @DT_FIM  
  AND T.TOCODCART IN ('75')  
  
-- remover contratos Renegociados q não sao de VEICULOS  
DELETE FROM CARTEIRA_PERDA_RENE  
  WHERE CONTRATO IN ('40102706A','353002816A','10710571A','10318990A','73000164A','90513755A'  
,'612260563A')  
  
UPDATE  CARTEIRA_PERDA_RENE    
SET  FV_CONTRATO =  O.OPVLRBRUTO  
 FROM CDCSANTANAMicroCredito..COPER O  (NOLOCK),   
   CARTEIRA_RENEGOCIADA R  (NOLOCK)  
 WHERE CARTEIRA_PERDA_RENE.CONTRATO = R.OPNROPER  
  AND R.OPNROPER2 = O.OPNROPER  -- OPERACAO ORIGINAL  
  
  
  
UPDATE  CARTEIRA_PERDA_RENE  
 SET  ANO_MOD = ISNULL(ABANOMOD,'S/INF')  
 FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)  
 WHERE CONTRATO = B.ABNROPER  
  and B.abNrGar = (select max(abnrgar)   
     FROM CDCSANTANAMicroCredito..CBFIN B1 (NOLOCK)  
     where b1.ABNROPER=CONTRATO)  
  and B.AbCNTRL = (select max(AbCNTRL)   
     FROM CDCSANTANAMicroCredito..CBFIN B2 (NOLOCK)  
     where b2.ABNROPER=CONTRATO and b2.abNrGar=B.abNrGar)  
 UPDATE   CARTEIRA_PERDA_RENE set ANO_MOD='1900'  
  WHERE  ANO_MOD =  ''      
  
-- RENEGOCIADO SEM ANO  
UPDATE  CARTEIRA_PERDA_RENE  
 SET  ANO_MOD = ISNULL(ABANOMOD,'S/INF')  
 FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)  
 WHERE CONTRATO = LEFT(RTRIM(B.ABNROPER),LEN(RTRIM(B.ABNROPER))-1)  
  AND B.ABCNTRL = (SELECT MAX(BX.ABCNTRL) FROM CDCSANTANAMicroCredito..CBFIN BX  (NOLOCK) WHERE  LEFT(RTRIM(BX.ABNROPER),LEN(RTRIM(BX.ABNROPER))-1) =  LEFT(RTRIM(CONTRATO),LEN(RTRIM(CONTRATO))-1) )  
  AND B.ABNRGAR = '01'   
  AND (ISNULL(ANO_MOD,'') = '' OR ABANOMOD='S/INF')  -- VAZIO  
  
------ PREJUIZO   
INSERT INTO PREJUIZO_PERDA_RENE (OPNROPER, QTD_PARC, VLR_PREJU)  
SELECT DISTINCT O.OPNROPER, count(panrparc)QTD_PARC,  sum (ISNULL(O.opvlrparc,0.0)) VLR_PREJU  
FROM CDCSANTANAMicroCredito..COPER O  (NOLOCK),   
  CDCSANTANAMicroCredito..CPARC X  (NOLOCK),   
  SIG..RATING_HISTORICO  (NOLOCK),   
  CARTEIRA_RENEGOCIADA R  (NOLOCK)  
WHERE O.OPNROPER = PANROPER  
  AND NUM_OPE = O.OPNROPER    
  AND R.OPNROPER = O.OPNROPER  
  AND x.pacntrl = (Select max(y.pacntrl) from CDCSANTANAMicrocredito .. cparc y  (NOLOCK) Where y.panroper = x.panroper and y.panrparc = x.panrparc)                 
  and NVL_RISCO = 'HH'  
  AND PANRPARC <> 0  
  AND R.OPDTBASE2 >= @DT_INI   
  AND R.OPDTBASE2 <= @DT_FIM   
  AND (PADTLIQ is null or PADTLIQ >= @DT_REF)  
  and DT_FECHA = ( SELECT MAX(DT_FECHA) FROM SIG..RATING_HISTORICO  (NOLOCK) WHERE DT_FECHA <= @DT_REF)  
group by O.OPNROPER  
  
  
---- DESCONTO   
INSERT INTO DESCONTO_PERDA_RENE (CONTRATO, VLR_DESCONTO)  
SELECT DISTINCT O.OPNROPER CONTRATO, (SUM(((PAVLRPR + PAVLRJR + PAVLRTARP) / POWER(((OPTXJRAP / 100.0) + 1.0), (DATEDIFF(DAY, ISNULL(PADTLIQ, @DT_REF), PADTVCTO) / 360.00000000)))) - SUM(PAVLRPAGO)) VLR_DESCONTO  
FROM CDCSANTANAMICROCREDITO..COPER O  (NOLOCK),   
  CDCSANTANAMICROCREDITO..TMODA T  (NOLOCK),  
  CDCSANTANAMICROCREDITO..CPARC X  (NOLOCK),   
  CARTEIRA_RENEGOCIADA R  (NOLOCK)  
where panroper= O.opnroper   
and   X.PACNTRL = (SELECT MAX(Y.PACNTRL) FROM CDCSANTANAMICROCREDITO .. CPARC Y  (NOLOCK) WHERE Y.PANROPER = X.PANROPER AND Y.PANRPARC = X.PANRPARC)                 
AND PANRPARC <> 0  
AND R.OPNROPER = O.OPNROPER  
AND PAVLRPAGO < OPVLRPARC  
AND O.OPCODOP = T.TOCODOP    
AND R.OPDTBASE2 >= @DT_INI   
AND R.OPDTBASE2 <= @DT_FIM   
AND PADTLIQ  <= @DT_REF  
AND T.TOCODCART IN ('75') 
AND O.OPNROPER  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA_RENE  (NOLOCK))  
  
GROUP BY O.OPNROPER  
  
UPDATE DESCONTO_PERDA_RENE SET VLR_DESCONTO = 0 WHERE VLR_DESCONTO < 0   
  
---- VENCER     
INSERT INTO AVENCER_PERDA_RENE (OPNROPER, QTD_PARC,VLR_AVENCER)  
SELECT DISTINCT O.OPNROPER, count(panrparc) QTD_PARC,  sum (opvlrparc)VLR_AVENCER  
FROM CDCSANTANAMICROCREDITO..COPER O  (NOLOCK),   
  CDCSANTANAMICROCREDITO..TMODA T  (NOLOCK),   
  CDCSANTANAMICROCREDITO..CPARC X  (NOLOCK),   
  CARTEIRA_RENEGOCIADA R  (NOLOCK)  
WHERE O.OPNROPER = PANROPER    
AND X.PACNTRL = (SELECT MAX(Y.PACNTRL) FROM CDCSANTANAMICROCREDITO .. CPARC Y  (NOLOCK) WHERE Y.PANROPER = X.PANROPER AND Y.PANRPARC = X.PANRPARC)                 
AND PANRPARC <> 0  
AND R.OPNROPER = O.OPNROPER  
AND O.OPCODOP = T.TOCODOP    
AND R.OPDTBASE2 >= @DT_INI   
AND R.OPDTBASE2 <= @DT_FIM   
AND (PADTLIQ is null or PADTLIQ > @DT_REF)  
AND T.TOCODCART IN ('75') 
AND O.OPNROPER  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA_RENE  (NOLOCK))  
GROUP BY O.OPNROPER  

--- PDD    
INSERT INTO PDD_PERDA_RENE (NUM_OPE, VLR_PDD)  
SELECT NUM_OPE, ISNULL(VLR_PDD,0.0)  
FROM SIG..RATING_HISTORICO  (NOLOCK),   
  CARTEIRA_RENEGOCIADA R  (NOLOCK)  
WHERE DT_FECHA = ( SELECT MAX(DT_FECHA) FROM SIG..RATING_HISTORICO  (NOLOCK) WHERE DT_FECHA <= @DT_REF)  
AND R.OPNROPER = NUM_OPE  
AND R.OPDTBASE2 >= @DT_INI   
AND R.OPDTBASE2 <= @DT_FIM   
AND NUM_OPE  NOT IN ( SELECT OPNROPER FROM PREJUIZO_PERDA_RENE  (NOLOCK) )  
  
---- AJUSTES 1 (AGRUPA VALORES)  
UPDATE CARTEIRA_PERDA_RENE SET VLR_PREJUIZO  = ISNULL(VLR_PREJU,0.0)    FROM PREJUIZO_PERDA_RENE   (NOLOCK)  WHERE CONTRATO = OPNROPER  
UPDATE CARTEIRA_PERDA_RENE SET CARTEIRA_PERDA_RENE.VLR_DESCONTO  = ISNULL(DESCONTO_PERDA_RENE.VLR_DESCONTO,0.0) FROM DESCONTO_PERDA_RENE   (NOLOCK)  WHERE CARTEIRA_PERDA_RENE.CONTRATO = DESCONTO_PERDA_RENE.CONTRATO  
UPDATE CARTEIRA_PERDA_RENE SET VLR_RECEBER   = ISNULL(VLR_AVENCER,0.0)  FROM AVENCER_PERDA_RENE    (NOLOCK)  WHERE CONTRATO = OPNROPER   
UPDATE CARTEIRA_PERDA_RENE SET CARTEIRA_PERDA_RENE.VLR_PDD  = ISNULL(PDD_PERDA_RENE.VLR_PDD,0.0)      FROM PDD_PERDA_RENE    (NOLOCK)      WHERE CONTRATO = NUM_OPE  
  
--- AJUSTE 2 (CALCULA PLANILHA)  
 UPDATE CARTEIRA_PERDA_RENE SET VLR_RECEBIDO       = (ISNULL(FV_CONTRATO,0.0) - ISNULL(VLR_PREJUIZO,0.0) - ISNULL(VLR_DESCONTO,0.0) - ISNULL(VLR_RECEBER,0.0))  
 UPDATE CARTEIRA_PERDA_RENE SET VLR_TOTAL_PERDA    = (ISNULL(VLR_PREJUIZO,0.0) + ISNULL(VLR_DESCONTO,0.0))  
 UPDATE CARTEIRA_PERDA_RENE SET VLR_LIQUIDADO      = (ISNULL(VLR_RECEBIDO,0.0) + ISNULL(VLR_TOTAL_PERDA,0.0))  
 UPDATE CARTEIRA_PERDA_RENE SET VLR_SAFRA          = (ISNULL(VLR_RECEBIDO,0.0) + ISNULL(VLR_PREJUIZO,0.0) + ISNULL(VLR_DESCONTO,0.0) + ISNULL(VLR_RECEBER,0.0))  
 UPDATE CARTEIRA_PERDA_RENE SET VLR_PERDA_RELIZADA = (ISNULL(VLR_TOTAL_PERDA,0.0) + ISNULL(VLR_PDD,0.0) )  
  
--- AJUSTE 3 (ATUALIZA TOTAIS)  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_OPERADO    =  (SELECT SUM(FV_CONTRATO)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_RECEBIDO    =  (SELECT SUM(VLR_RECEBIDO)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_PREJUIZO    =  (SELECT SUM(VLR_PREJUIZO)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_DESCONTO    =  (SELECT SUM(VLR_DESCONTO)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_PERDA_TOTAL   =  (SELECT SUM(VLR_TOTAL_PERDA)  FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_LIQUIDADO    =  (SELECT SUM(VLR_LIQUIDADO)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_ARECEBER    =  (SELECT SUM(VLR_RECEBER)   FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_PDD     =  (SELECT SUM(VLR_PDD)    FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOTAL_SAFRA     =  (SELECT SUM(VLR_SAFRA)    FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
 UPDATE CARTEIRA_PERDA_RENE SET TOATL_PERDA_REALIZADA =  (SELECT SUM(VLR_PERDA_RELIZADA) FROM CARTEIRA_PERDA_RENE  (NOLOCK))  
  
--- AJUSTE 3 (ATUALIZA PERCENTUAIS)  
UPDATE CARTEIRA_PERDA_RENE SET PER_OPERADO   = CASE WHEN TOTAL_OPERADO = 0.0 THEN 0.0 ELSE (CONVERT (FLOAT,(isnull(FV_CONTRATO,0.0)/ TOTAL_OPERADO))*100.0) END   
UPDATE CARTEIRA_PERDA_RENE SET PERC_RECEBIDO  = CASE WHEN TOTAL_RECEBIDO = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_RECEBIDO,0.0)/ TOTAL_RECEBIDO))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_PREJUIZO  = CASE WHEN TOTAL_PREJUIZO = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_PREJUIZO,0.0)/ TOTAL_PREJUIZO))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_DESCONTO  = CASE WHEN TOTAL_DESCONTO = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_DESCONTO,0.0)/ TOTAL_DESCONTO))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_TOTAL_PERDA  = CASE WHEN TOTAL_PERDA_TOTAL = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_TOTAL_PERDA,0.0)/ TOTAL_PERDA_TOTAL))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_ARECEBER  = CASE WHEN TOTAL_ARECEBER = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_RECEBER,0.0)/ TOTAL_ARECEBER))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_SAFRA   = CASE WHEN TOTAL_SAFRA = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_SAFRA,0.0) / TOTAL_SAFRA))*100.0) END  
UPDATE CARTEIRA_PERDA_RENE SET PERC_PERDA_RELIZADA = CASE WHEN VLR_SAFRA = 0.0 THEN 0.0 ELSE(CONVERT (FLOAT,(isnull(VLR_PERDA_RELIZADA,0.0) / VLR_SAFRA))*100.0) END  

END  