USE SIG
GO

/****** Object:  Table [dbo].[prot_ocorrencia_cart]    Script Date: 28/03/2016 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[prot_ocorrencia_cart](

	COD			VARCHAR(20),
	OCORRENCIA	VARCHAR(300)

) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[prot_ocorrencia_de_para]    Script Date: 28/03/2016 18:25:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[prot_ocorrencia_de_para](

COD_CART		VARCHAR(20),
OCORRENCIA_CART	VARCHAR(300),
COD_FC			VARCHAR(20),
OCORRENCIA_FC	VARCHAR(300)

) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[prot_contratos]    Script Date: 28/03/2016 18:25:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[prot_contratos](
	
CONTRATO	VARCHAR(20),
OBS			VARCHAR(300)

 CONSTRAINT [PK_prot_contratos] PRIMARY KEY CLUSTERED 
(
	[CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
