USE SIG --[SANTANA]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT NAME FROM SYSOBJECTS 
WHERE NAME = 'SCR_GRAVAME_QUITACAO' AND TYPE = 'P')
DROP PROCEDURE [DBO].SCR_GRAVAME_QUITACAO
GO

CREATE PROCEDURE [DBO].SCR_GRAVAME_QUITACAO (                             
@DT_INI SMALLDATETIME,                    
@DT_FIM SMALLDATETIME,   
@AGNT  INT,      
@PAGTO INT      
) AS                        
                
BEGIN    
  
/*  
DROP TABLE DCO_GRAVAME_QUITACAO
CREATE TABLE DCO_GRAVAME_QUITACAO(                
OPNROPER VARCHAR(15),                
OPDTBASE SMALLDATETIME,                
CLNOMECLI VARCHAR(200),                
OPCODCLI VARCHAR(15),                
STATUSGRV VARCHAR(50),  
DESCR_GRAVAME VARCHAR(200),  
EGCNTRL INT)     
*/  
  
DELETE FROM DCO_GRAVAME_QUITACAO
  
INSERT INTO DCO_GRAVAME_QUITACAO
SELECT DISTINCT                
OPNROPER,OPDTBASE,CLNOMECLI,OPCODCLI,  
EGCODMOV AS STATUS_GRAVAME, DESCR_GRAVAME ,EGCNTRL  
FROM (SELECT * FROM CDCSANTANAMICROCREDITO..COPER AS OP1 (NOLOCK) WHERE OPDTLIQ BETWEEN @DT_INI AND @DT_FIM) AS OP                    
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 WITH (NOLOCK) ON OP.OPCODORG3 = O3CODORG  
INNER JOIN CDCSANTANAMICROCREDITO..CBFIN WITH (NOLOCK) ON OP.OPNROPER = ABNROPER   
INNER JOIN CDCSANTANAMICROCREDITO..CCLIE WITH (NOLOCK) ON OP.OPCODCLI = CLCODCLI  
LEFT  JOIN CDCSANTANAMICROCREDITO..EXGRV E WITH (NOLOCK) ON EGNROPER = OP.OPNROPER    
LEFT  JOIN AUX_GRAVAME_QUITACAO WITH (NOLOCK) ON EGCODMOV = COD_GRAVAME                
LEFT  JOIN (SELECT  EPNRPROP,MAX(EPDTLNC+EPHORALNC) AS EP,MAX(EPHORALNC) AS EPHORALNC FROM PROPWEBSMC..EPROP (NOLOCK)                     
 WHERE EPNRDECI = '22'                   
 GROUP BY  EPNRPROP ) AS P                    
    ON EPNRPROP = OPNRPROP                    
WHERE E.EGCNTRL = (SELECT TOP 1 E1.EGCNTRL + 1 FROM CDCSANTANAMICROCREDITO..EXGRV E1 (NOLOCK) WHERE E1.EGTPMOV = 4 AND E1.EGNROPER = E.EGNROPER ORDER BY E1.EGCNTRL ASC)
AND ( OP.OPESTORNO IS NULL OR OP.OPESTORNO NOT IN ('S', 'C'))
AND 1= 0+ CASE WHEN  @PAGTO='0' THEN 1         
   WHEN  @PAGTO = '1' AND O3CODORG = '000149' THEN 1        
   WHEN  @PAGTO = '2' AND O3CODORG <> '000149' THEN 1        
   ELSE 0 END  
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1         
   WHEN  @AGNT <> '99' AND O3CODORG = @AGNT THEN 1           
   ELSE 0 END  
UNION 
SELECT DISTINCT                
OPNROPER,OPDTBASE,CLNOMECLI,OPCODCLI,'99','',''
FROM (SELECT * FROM CDCSANTANAMICROCREDITO..COPER AS OP1 (NOLOCK) WHERE OPDTLIQ BETWEEN @DT_INI AND @DT_FIM) AS OP                    
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 WITH (NOLOCK) ON OP.OPCODORG3 = O3CODORG  
INNER JOIN CDCSANTANAMICROCREDITO..CBFIN WITH (NOLOCK) ON OP.OPNROPER = ABNROPER   
INNER JOIN CDCSANTANAMICROCREDITO..CCLIE WITH (NOLOCK) ON OP.OPCODCLI = CLCODCLI  
LEFT  JOIN (SELECT  EPNRPROP,MAX(EPDTLNC+EPHORALNC) AS EP,MAX(EPHORALNC) AS EPHORALNC FROM PROPWEBSMC..EPROP (NOLOCK)                     
 WHERE EPNRDECI = '22'                   
 GROUP BY  EPNRPROP ) AS P                    
    ON EPNRPROP = OPNRPROP                    
WHERE ( OP.OPESTORNO IS NULL OR OP.OPESTORNO NOT IN ('S', 'C'))
AND 1= 0+ CASE WHEN  @PAGTO='0' THEN 1         
   WHEN  @PAGTO = '1' AND O3CODORG = '000149' THEN 1        
   WHEN  @PAGTO = '2' AND O3CODORG <> '000149' THEN 1        
   ELSE 0 END  
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1         
   WHEN  @AGNT <> '99' AND O3CODORG = @AGNT THEN 1           
   ELSE 0 END  
ORDER BY OPNROPER

DELETE FROM DCO_GRAVAME_QUITACAO WHERE STATUSGRV = '99' AND
OPCODCLI IN (SELECT OPCODCLI FROM DCO_GRAVAME_QUITACAO (NOLOCK) GROUP BY OPCODCLI HAVING COUNT(*)>1)

UPDATE DCO_GRAVAME_QUITACAO SET STATUSGRV = '' WHERE STATUSGRV = '99'
  
SELECT OPNROPER,OPDTBASE,CLNOMECLI,OPCODCLI,STATUSGRV,DESCR_GRAVAME FROM DCO_GRAVAME_QUITACAO  (NOLOCK)
WHERE STATUSGRV IS NOT NULL
ORDER BY OPDTBASE
  
END