USE sig
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_ATUALIZA_SCORE' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_ATUALIZA_SCORE 
GO

CREATE PROCEDURE SCR_ATUALIZA_SCORE (                             
@CONTRATO VARCHAR(20), @SCORE INT) AS   
  
BEGIN  
UPDATE PROPWEBSMC..CPROP SET PPSCORING = @SCORE WHERE PPNROPER = @CONTRATO  
END