USE SIG --[SANTANA]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT NAME FROM SYSOBJECTS 
WHERE NAME = 'SCR_GRAVAME_INCLUSAO' AND TYPE = 'P')
DROP PROCEDURE [DBO].SCR_GRAVAME_INCLUSAO 
GO

CREATE PROCEDURE [DBO].SCR_GRAVAME_INCLUSAO (                             
@DT_INI SMALLDATETIME,                    
@DT_FIM SMALLDATETIME,   
@AGNT  INT,      
@PAGTO INT      
) AS                        
                
BEGIN    
  
/*  
DROP TABLE DCO_GRAVAME_INCLUSAO  
CREATE TABLE DCO_GRAVAME_INCLUSAO(                
O3CODORG VARCHAR(20),                
O3DESCR VARCHAR(20),                
OPNROPER VARCHAR(15),                
OPDTBASE SMALLDATETIME,                
OPCODCLI VARCHAR(15),                
CLNOMECLI VARCHAR(200),                
ABPLACA VARCHAR(11),                
ABCHASSI VARCHAR(200),                
ABUFLCPL VARCHAR (10),                
STATUSGRV VARCHAR(50),  
DESCR_GRAVAME VARCHAR(200),  
EGCNTRL INT)     
*/  
  
DELETE FROM DCO_GRAVAME_INCLUSAO  
  
INSERT INTO DCO_GRAVAME_INCLUSAO  
SELECT DISTINCT                
 O3CODORG,O3DESCR,OPNROPER,OPDTBASE,OPCODCLI,CLNOMECLI,  
 ABPLACA,ABCHASSI,ABUFLCPL,  
 EGCODMOV AS STATUS_GRAVAME,CASE WHEN EGCODMOV IS NULL THEN 'GRAVAME ON-LINE' ELSE DESCR_GRAVAME + ' ' + EGFINANC END,EGCNTRL  
FROM (SELECT * FROM CDCSANTANAMICROCREDITO..COPER AS OP1 (NOLOCK) WHERE OPDTBASE BETWEEN  @DT_INI AND @DT_FIM) AS OP                    
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 WITH (NOLOCK) ON OP.OPCODORG3 = O3CODORG  
INNER JOIN CDCSANTANAMICROCREDITO..CBFIN WITH (NOLOCK) ON OP.OPNROPER = ABNROPER   
INNER JOIN CDCSANTANAMICROCREDITO..CCLIE WITH (NOLOCK) ON OP.OPCODCLI = CLCODCLI  
INNER JOIN CDCSANTANAMICROCREDITO..EXGRV E WITH (NOLOCK) ON EGNROPER = OP.OPNROPER    
LEFT  JOIN AUX_GRAVAME_INCLUSAO WITH (NOLOCK) ON EGCODMOV = COD_GRAVAME                
LEFT  JOIN (SELECT  EPNRPROP,MAX(EPDTLNC +EPHORALNC) AS EP,MAX(EPHORALNC) AS EPHORALNC FROM PROPWEBSMC..EPROP (NOLOCK)                     
 WHERE EPNRDECI = '22'                   
 GROUP BY  EPNRPROP ) AS P                    
    ON EPNRPROP = OPNRPROP                    
WHERE EGCNTRL IN ('3')  
AND 1= 0+ CASE WHEN  @PAGTO='0' THEN 1         
   WHEN  @PAGTO = '1' AND O3CODORG = '000149' THEN 1        
   WHEN  @PAGTO = '2' AND O3CODORG <> '000149' THEN 1        
   ELSE 0 END  
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1         
   WHEN  @AGNT <> '99' AND O3CODORG = @AGNT THEN 1           
   ELSE 0 END  

INSERT INTO DCO_GRAVAME_INCLUSAO  
SELECT DISTINCT                
 O3CODORG,O3DESCR,OPNROPER,OPDTBASE,OPCODCLI,CLNOMECLI,  
 ABPLACA,ABCHASSI,ABUFLCPL,  
'','',EGCNTRL  
FROM (SELECT * FROM CDCSANTANAMICROCREDITO..COPER AS OP1 (NOLOCK) WHERE OPDTBASE BETWEEN  @DT_INI AND @DT_FIM) AS OP                    
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 WITH (NOLOCK) ON OP.OPCODORG3 = O3CODORG  
INNER JOIN CDCSANTANAMICROCREDITO..CBFIN WITH (NOLOCK) ON OP.OPNROPER = ABNROPER   
INNER JOIN CDCSANTANAMICROCREDITO..CCLIE WITH (NOLOCK) ON OP.OPCODCLI = CLCODCLI  
INNER JOIN CDCSANTANAMICROCREDITO..EXGRV E WITH (NOLOCK) ON EGNROPER = OP.OPNROPER    
LEFT  JOIN AUX_GRAVAME_INCLUSAO WITH (NOLOCK) ON EGCODMOV = COD_GRAVAME                
LEFT  JOIN (SELECT  EPNRPROP,MAX(EPDTLNC +EPHORALNC) AS EP,MAX(EPHORALNC) AS EPHORALNC FROM PROPWEBSMC..EPROP (NOLOCK)                     
 WHERE EPNRDECI = '22'                   
 GROUP BY  EPNRPROP ) AS P                    
    ON EPNRPROP = OPNRPROP                    
WHERE EGCNTRL IN ('2')  
AND 1= 0+ CASE WHEN  @PAGTO='0' THEN 1         
   WHEN  @PAGTO = '1' AND O3CODORG = '000149' THEN 1        
   WHEN  @PAGTO = '2' AND O3CODORG <> '000149' THEN 1        
   ELSE 0 END  
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1         
   WHEN  @AGNT <> '99' AND O3CODORG = @AGNT THEN 1           
   ELSE 0 END  
AND OPNROPER NOT IN (SELECT OPNROPER FROM DCO_GRAVAME_INCLUSAO (NOLOCK))
  
DELETE FROM  DCO_GRAVAME_INCLUSAO WHERE RIGHT(OPNROPER,1) IN ('A','B','C','D','E','F','G')  
  
SELECT O3CODORG,O3DESCR,OPNROPER,OPDTBASE,OPCODCLI,CLNOMECLI,ABPLACA,ABCHASSI,ABUFLCPL,STATUSGRV,DESCR_GRAVAME FROM DCO_GRAVAME_INCLUSAO  (NOLOCK)
ORDER BY O3CODORG
  
END