Use sig
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_CRV_CATIVA_ANALI_pend' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_CRV_CATIVA_ANALI_pend]
GO

CREATE PROCEDURE[dbo].SCR_CRV_CATIVA_ANALI_pend (      
 @DataContrato as datetime,      
@DT_REF SMALLDATETIME,              
@DT_INI SMALLDATETIME,          
@DT_FIM SMALLDATETIME,         
@AGNT   INT, 
@REGIAO AS VARCHAR(10),
@PREJUIZO AS VARCHAR(10),
@RENEG AS VARCHAR(10),
@ATIVO AS VARCHAR(10)) AS      
      
 begin      
     
      
SELECT COUNT(*) AS CONTRATO FROM crv_PEND_CATIVA_ANALI P (NOLOCK)  
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 T3 (NOLOCK) ON T3.O3CODORG = A13CODORG
LEFT  JOIN DEPARA_REGIAO R ON R.COD_AGENTE = A13CODORG
WHERE 1= 0+ CASE WHEN  @REGIAO='99' THEN 1    
      WHEN  @REGIAO<>'99' AND COD_REGIAO = @REGIAO THEN 1        
      ELSE  0   END    
AND  1= 0+ CASE WHEN  @PREJUIZO='99' THEN 1    
      WHEN  @PREJUIZO= '0' AND PREJU = 'NÃO' THEN 1        
	  WHEN  @PREJUIZO= '1' AND PREJU = 'SIM' THEN 1
      ELSE  0   END  
AND  1= 0+ CASE WHEN  @RENEG='99' THEN 1    
      WHEN  @RENEG= '0' AND RENEG = 'NÃO' THEN 1        
	  WHEN  @RENEG= '1' AND RENEG = 'SIM' THEN 1
      ELSE  0   END  	 
AND  1= 0+ CASE WHEN  @ATIVO='99' THEN 1    
      WHEN  @ATIVO= '0' AND O3ATIVA IN ('N','S') THEN 1        
	  WHEN  @ATIVO= '1' AND O3ATIVA IN ('S','A') THEN 1
      ELSE  0   END  
AND  1= 0+ CASE WHEN  @AGNT='99' THEN 1
WHEN  @AGNT<>'99' AND A13CODORG = @AGNT  THEN 1      
ELSE  0   END  
--LEFT JOIN USUARIO_SVC ON CODAGENTE = CAST(CAST(O3CODORG AS BIGINT) AS VARCHAR)    
  
END 