USE sig
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_CONSULTA_SCORE' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_CONSULTA_SCORE 
GO

CREATE PROCEDURE SCR_CONSULTA_SCORE (                             
@CONTRATO VARCHAR(20)) AS   
  
BEGIN  
SELECT PPNROPER,PPSCORING FROM PROPWEBSMC..CPROP (NOLOCK) WHERE PPNROPER = @CONTRATO  
END