USE sig --[Santana]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_CRIVO' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_CRIVO] 
GO

CREATE Procedure SCR_CRIVO(      
         @DT_INI SMALLDATETIME,          
         @DT_FIM SMALLDATETIME,         
         @AGNT   INT ) AS 

BEGIN

SELECT CSNRCONSEXT, PPCODORG3 + ' - ' + O3DESCR AS PPCODORG3, PPDTBASE, PPNROPER, PPNRPROP FROM MONITOR..ECONSULT (NOLOCK) 
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON CSNREXTERNO = PPNRPROP
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON PPCODORG3 = O3CODORG
WHERE CSNRDECI='662'
AND PPDTBASE BETWEEN @DT_INI AND @DT_FIM
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1      
      WHEN  @AGNT<>'99' AND PPCODORG3 = @AGNT  THEN 1      
      ELSE  0   END    

END
GO