USE sig 
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--ALTER TABLE DCO_PEND_FORMALIZ_ANALITICO ADD DT_FORMALIZ SMALLDATETIME
--ALTER TABLE DCO_PEND_FORMALIZ_ANALITICO ADD DT_INTEG SMALLDATETIME
--ALTER TABLE DCO_PEND_FORMALIZ_ANALITICO ADD VLR_LIB FLOAT
--ALTER TABLE DCO_PEND_FORMALIZ_ANALITICO ADD SCORE INT

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PEND_PAGTO' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PEND_PAGTO]
GO   
  
CREATE PROCEDURE [DBO].SCR_PEND_PAGTO (                                        
         @DT_INI SMALLDATETIME,                            
         @DT_FIM SMALLDATETIME,                           
         @AGNT   INT ) AS                          
                        
 BEGIN      
     
--CREATE TABLE DCO_PEND_PAGTO(    
--COD_AGENTE VARCHAR(20),    
--AGENTE VARCHAR(100),    
--CONTRATO VARCHAR(20),    
--PROPOSTA VARCHAR(20),    
--CPF VARCHAR(20),    
--CLIENTE VARCHAR(200),    
--DT_INT SMALLDATETIME,    
--MOTIVO VARCHAR(100),    
--COD_LOJA VARCHAR(20),    
--LOJA VARCHAR(100),    
--COD_OPERADOR VARCHAR(20),    
--OPERADOR VARCHAR(100),    
--ANALISTA VARCHAR(50),    
--SITUACAO VARCHAR(10),    
--)    
    
--ALTER TABLE DCO_PEND_PAGTO ADD PRAZO SMALLDATETIME

DELETE FROM DCO_PEND_PAGTO    
    
INSERT INTO DCO_PEND_PAGTO    
SELECT PPCODORG3, O3DESCR,PPNROPER,PPNRPROP,CLCGC,CLNOMECLI,PPDTBASE,'' AS MOTIVO,PPCODORG4, O4DESCR,PPCODORG3,O3DESCR,
'' AS ANALISTA, '' AS SITUACAO, '' AS PRAZO FROM                             
 (SELECT * FROM PROPWEBSMC..CPROP E (NOLOCK) WHERE PPDTBASE BETWEEN @DT_INI AND @DT_FIM ) AS O                          
 INNER JOIN PROPWEBSMC..EPROP E (NOLOCK) ON E.EPNRPROP = O.PPNRPROP                          
 LEFT  JOIN CDCSANTANAMICROCREDITO..CCLIE C (NOLOCK) ON O.PPCODCLI = C.CLCODCLI                                                  
 LEFT  JOIN CDCSANTANAMICROCREDITO..TORG6 T6 (NOLOCK) ON O.PPCODORG6 = T6.O6CODORG                             
 LEFT  JOIN CDCSANTANAMICROCREDITO..TORG4 T4 (NOLOCK) ON O.PPCODORG4 = T4.O4CODORG                             
 LEFT  JOIN CDCSANTANAMICROCREDITO..TORG3 T3 (NOLOCK) ON T6.O6CODORG3 = T3.O3CODORG    
WHERE E.EPNRDECI = '123'    
AND (E.EPNRSEQ > (SELECT MIN(E1.EPNRSEQ) FROM  PROPWEBSMC..EPROP E1 (NOLOCK)                           
      WHERE E1.EPNRPROP = O.PPNRPROP  AND  E1.EPNRDECI ='600'))    
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1                     
      WHEN  @AGNT<>'99' AND O3CODORG = @AGNT  THEN 1                        
      ELSE  0   END     
    
UPDATE DCO_PEND_PAGTO               
SET SITUACAO = (SELECT MPSIT FROM PROPWEBSMC..CMOVP M (NOLOCK)                     
WHERE M.MPNRPROP = PROPOSTA)       
    
UPDATE DCO_PEND_PAGTO                    
SET MOTIVO = (SELECT MTDESCR FROM PROPWEBSMC..EPROP E INNER JOIN PROPWEBSMC..TMOTI (NOLOCK) ON REPLACE(SUBSTRING(EPTPMOTIVO, 1, CHARINDEX(';', EPTPMOTIVO)),';','') = MTCODMOT                            
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON MPNRPROP = E.EPNRPROP WHERE EPNRDECI IN('600') AND PROPOSTA = E.EPNRPROP                  
AND E.EPDTHRFIM = (SELECT MAX(E1.EPDTHRFIM) FROM PROPWEBSMC..EPROP E1 WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN('600') AND EPTPMOTIVO <> ''))                    
    
UPDATE DCO_PEND_PAGTO                    
SET ANALISTA = (SELECT E.EPUSUARIO FROM PROPWEBSMC..EPROP E(NOLOCK)                    
WHERE E.EPNRDECI IN ('600') AND PROPOSTA = E.EPNRPROP AND E.EPNRSEQ = (SELECT MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1 WHERE E1.EPNRPROP = E.EPNRPROP AND E1.EPNRDECI IN ('600')))                    

UPDATE DCO_PEND_PAGTO
SET PRAZO = DATEADD(DAY,10,DT_INT)
    
SELECT     
COD_AGENTE,    
AGENTE,     
CONTRATO,     
PROPOSTA,    
CPF,     
CLIENTE,    
DT_INT,    
MOTIVO,     
COD_LOJA,     
LOJA,     
COD_OPERADOR,    
OPERADOR,    
ANALISTA,    
SITUACAO,
PRAZO
FROM DCO_PEND_PAGTO (NOLOCK)    
    
END