Use sig
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_CRV_CATIVA_ANALI_TTL' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_CRV_CATIVA_ANALI_TTL]
GO

CREATE PROCEDURE [DBO].SCR_CRV_CATIVA_ANALI_TTL (      
 @DATACONTRATO AS DATETIME,      
@DT_REF SMALLDATETIME,              
@DT_INI SMALLDATETIME,          
@DT_FIM SMALLDATETIME,         
@AGNT   INT, 
@REGIAO AS VARCHAR(10),
@PREJUIZO AS VARCHAR(10),
@RENEG AS VARCHAR(10),
@ATIVO AS VARCHAR(10)) AS
      
 BEGIN      
      
      
SELECT  OPNROPER,  ISNULL((SELECT MAX(DATEDIFF(DD, P.PADTVCTO, @DT_REF))         
   FROM CDCSANTANAMICROCREDITO..CPARC P  (NOLOCK)        
   WHERE P.PANROPER = OPNROPER           
     AND ( P.PADTMOV IS NULL OR P.PADTMOV > @DT_REF) AND  P.PADTVAL <= @DT_REF AND  NOT (P.PACODMOV IN ('07', '08', '09', '13', '91', '94') AND           
     P.PADTLIQ IS NOT NULL)), 0) AS ATRASO INTO #TEMP_CONTRATOS
FROM CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) 
INNER JOIN CDCSANTANAMICROCREDITO..COPER  (NOLOCK) ON OPCODORG3 = O3CODORG
INNER JOIN CDCSANTANAMICROCREDITO..TORG6 (NOLOCK) ON OPCODORG6 = O6CODORG
LEFT  JOIN DEPARA_REGIAO (NOLOCK) ON  COD_AGENTE = O3CODORG
WHERE OPDTBASE  BETWEEN @DT_INI AND @DT_FIM AND OPDTLIQ IS NULL 
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1
WHEN  @AGNT<>'99' AND O3CODORG = @AGNT  THEN 1      
ELSE  0   END       
AND 1= 0+ CASE WHEN  @REGIAO='99' THEN 1
WHEN  @REGIAO<>'99' AND COD_REGIAO = @REGIAO  THEN 1      
ELSE  0   END       
AND 1= 0+ CASE WHEN  @ATIVO='99' THEN 1
WHEN  @ATIVO='0' AND O3ATIVA IN ('D','N') THEN 1      
WHEN  @ATIVO='1' AND O3ATIVA IN ('S','A') THEN 1
ELSE  0   END      

SELECT COUNT(*) AS CONTRATO FROM #TEMP_CONTRATOS (NOLOCK)
WHERE  1= 0+ CASE WHEN  @PREJUIZO='99' THEN 1
WHEN  @PREJUIZO='0' AND ATRASO <=  360  THEN 1      
WHEN  @PREJUIZO='1' AND ATRASO > 360  THEN 1      
ELSE  0   END       
AND  1= 0+ CASE WHEN  @RENEG='99' THEN 1
WHEN  @RENEG='0' AND RIGHT(OPNROPER,1) NOT IN ('A','B','C','D','E','F','G','H')  THEN 1      
WHEN  @RENEG='1' AND RIGHT(OPNROPER,1) IN ('A','B','C','D','E','F','G','H') THEN 1      
ELSE  0   END 
      
END 