Use sig
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_CRV_CATIVA_ANALI' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_CRV_CATIVA_ANALI]
GO

CREATE PROCEDURE  [dbo].SCR_CRV_CATIVA_ANALI (        
 @DataContrato as datetime,        
@DT_REF SMALLDATETIME,                
@DT_INI SMALLDATETIME,            
@DT_FIM SMALLDATETIME,           
@AGNT   INT,
@REGIAO AS VARCHAR(10),
@PREJUIZO AS VARCHAR(10),
@RENEG AS VARCHAR(10),
@ATIVO AS VARCHAR(10)) AS          
        
begin        
 
TRUNCATE TABLE crv_PEND_CATIVA_ANALI          
          
INSERT INTO  crv_PEND_CATIVA_ANALI (OPCODPROD, OPNROPER, OPDTBASE, OPVLRFIN, OPCODORG1, O1DESCR,          
 OPCODORG2, O2DESCR, OPCODORG3, O3DESCR,  OPCODORG4, O4DESCR,          
 OPCODORG5, O5DESCR, OPCODORG6, EPCODPEN, EPCMPLTO, OPCODCLI,          
 A13CODORG, A13DESCR,         
 ABRENAVAM, ABVLRTAB, ABCHASSI, ABCERTIF,   ABPLACA, ABMODELO,         
 CLNOMECLI, CLFONEFIS, CLFONECOM, CLCGC,          
 DIASATRASO, EPDTAGEN, EPDTPEN, EPDTCAD, EPDTLNCBX, EPDTFIM)          
          
          
SELECT  distinct OPCODPROD,  O.OPNROPER, O.OPDTBASE, O.OPVLRFIN,O.OPCODORG1, '', O.OPCODORG2, '', O.OPCODORG6, '',          
  O.OPCODORG4, '', O.OPCODORG5, '', O.OPCODORG3, E.EPCODPEN, E.EPCMPLTO, O.OPCODCLI,          
  O.OPCODORG3,  replace( REPLACE( replace ('','PROMOTORA',''), 'PROMOT ',''), 'PROM',''),         
-- B.ABRENAVAM, B.ABVLRTAB, B.ABCHASSI, B.ABCERTIF, B.ABPLACA, B.ABMODELO,         
 '',0.0,'','','','',        
  C.CLNOMECLI, C.CLFONEFIS, C.CLFONECOM, C.CLCGC,              
  ISNULL((SELECT MAX(DATEDIFF(DD, P.PADTVCTO, @DT_REF))         
   FROM CDCSANTANAMicroCredito..CPARC P  (NOLOCK)        
   WHERE P.PANROPER = O.OPNROPER           
     AND ( P.PADTMOV IS NULL OR P.PADTMOV > @DT_REF) AND  P.PADTVAL <= @DT_REF AND  NOT (P.PACODMOV IN ('07', '08', '09', '13', '91', '94') AND           
     P.PADTLIQ IS NOT NULL)), 0) AS DIASATRASO,           
  E.EPDTAGEN, E.EPDTPEN, E.EPDTCAD, E.EPDTLNCBX, E.EPDTFIM           
          
FROM           
  CDCSANTANAMicroCredito..COPER O    (NOLOCK)        
  INNER JOIN CDCSANTANAMicroCredito..CCLIE C    (NOLOCK) ON O.OPCODCLI = C.CLCODCLI           
  INNER JOIN CDCSANTANAMicroCredito..EPEND E (NOLOCK) ON O.OPNROPER = E.EPNROPER           
  INNER JOIN CDCSANTANAMicroCredito..TPEND TP (NOLOCK) ON E.EPCODPEN = TP.PDCODPEN                    
  LEFT JOIN CDCSANTANAMicroCredito..TORG3 T1O3 (NOLOCK) ON T1O3.O3CODORG = O.OPCODORG3       
WHERE E.EPCODPEN = '151'       
and   ( O.OPDTLIQ IS NULL OR O.OPDTLIQ > @DT_REF)           
AND O.OPDTBASE <= @DT_FIM          
AND (E.EPDTFIM IS NULL OR E.EPDTFIM > @DT_REF )  AND E.EPDTCAD <= @DT_REF                 
AND E.EPDTCAD >= @DT_INI          
AND E.EPDTCAD <= @DT_FIM          
AND 1= 0+ CASE WHEN  @AGNT='99' THEN 1    
      WHEN  @AGNT<>'99' AND T1O3.O3CODORG = @AGNT  THEN 1        
      ELSE  0   END         
        
IF @AGNT<>'99'        
INSERT INTO  crv_PEND_CATIVA_ANALI (OPCODPROD, OPNROPER, OPDTBASE, OPVLRFIN, OPCODORG1, O1DESCR,          
 OPCODORG2, O2DESCR, OPCODORG3, O3DESCR,  OPCODORG4, O4DESCR,          
 OPCODORG5, O5DESCR, OPCODORG6, EPCODPEN, EPCMPLTO, OPCODCLI,          
 A13CODORG, A13DESCR,         
 ABRENAVAM, ABVLRTAB, ABCHASSI, ABCERTIF,   ABPLACA, ABMODELO,         
 CLNOMECLI, CLFONEFIS, CLFONECOM, CLCGC,          
 DIASATRASO, EPDTAGEN, EPDTPEN, EPDTCAD, EPDTLNCBX, EPDTFIM)             
SELECT  distinct OPCODPROD,  O.OPNROPER, O.OPDTBASE, O.OPVLRFIN,O.OPCODORG1, '', O.OPCODORG2, '', O.OPCODORG6, '',          
  O.OPCODORG4, '', O.OPCODORG5, '', O.OPCODORG3, E.EPCODPEN, E.EPCMPLTO, O.OPCODCLI,          
  O.OPCODORG3,  replace( REPLACE( replace ('','PROMOTORA',''), 'PROMOT ',''), 'PROM',''),         
 '',0.0,'','','','',        
  C.CLNOMECLI, C.CLFONEFIS, C.CLFONECOM, C.CLCGC,              
  ISNULL((SELECT MAX(DATEDIFF(DD, P.PADTVCTO, @DT_REF))         
   FROM CDCSANTANAMicroCredito..CPARC P  (NOLOCK)        
   WHERE P.PANROPER = O.OPNROPER           
     AND ( P.PADTMOV IS NULL OR P.PADTMOV > @DT_REF) AND  P.PADTVAL <= @DT_REF AND  NOT (P.PACODMOV IN ('07', '08', '09', '13', '91', '94') AND           
     P.PADTLIQ IS NOT NULL)), 0) AS DIASATRASO,           
  E.EPDTAGEN, E.EPDTPEN, E.EPDTCAD, E.EPDTLNCBX, E.EPDTFIM                 
FROM           
  CDCSANTANAMicroCredito..COPER O    (NOLOCK)        
  INNER JOIN CDCSANTANAMicroCredito..CCLIE C    (NOLOCK) ON O.OPCODCLI = C.CLCODCLI           
  INNER JOIN CDCSANTANAMicroCredito..EPEND E (NOLOCK) ON O.OPNROPER = E.EPNROPER           
  INNER JOIN CDCSANTANAMicroCredito..TPEND TP (NOLOCK) ON E.EPCODPEN = TP.PDCODPEN                
  INNER  JOIN (select * from CDCSANTANAMicroCredito..TORG6 T3 (NOLOCK)        
    where convert(int,o6codorg) in (select distinct codOperador from usuario_svc S1 (NOLOCK)  where codAgente=@AGNT)        
       ) as T3    
  ON  T3.O6CODORG =O.OPCODORG6   
  INNER JOIN CDCSANTANAMicroCredito..TORG3 T1O3 (NOLOCK)         
   ON  T1O3.O3CODORG = O.OPCODORG3        
WHERE E.EPCODPEN = '151'       
 AND   ( O.OPDTLIQ IS NULL OR O.OPDTLIQ > @DT_REF)           
 AND O.OPDTBASE <= @DT_FIM          
 AND (E.EPDTFIM IS NULL OR E.EPDTFIM > @DT_REF )  AND E.EPDTCAD <= @DT_REF          
 AND E.EPDTCAD >= @DT_INI          
 AND E.EPDTCAD <= @DT_FIM          
                
UPDATE  crv_PEND_CATIVA_ANALI          
 SET  ABRENAVAM= B.ABRENAVAM, ABVLRTAB=B.ABVLRTAB,         
   ABCHASSI=B.ABCHASSI, ABCERTIF=B.ABCERTIF,           
   ABPLACA=B.ABPLACA, ABMODELO=B.ABMODELO        
 FROM CDCSANTANAMicroCredito..CBFIN B (NOLOCK)         
 WHERE B.ABNROPER=crv_PEND_CATIVA_ANALI.OPNROPER        
 AND   B.ABNRGAR ='01'        
  AND       B.ABCNTRL = (SELECT  MAX(BX.ABCNTRL) FROM CDCSANTANAMicroCredito..CBFIN BX (NOLOCK)         
     WHERE BX.ABNROPER = crv_PEND_CATIVA_ANALI.OPNROPER AND BX.ABNRGAR = '01')     
          
UPDATE  crv_PEND_CATIVA_ANALI          
SET  O1DESCR = T1.O1DESCR   
FROM CDCSANTANAMicroCredito..TORG1 T1 (NOLOCK)       
WHERE T1.O1CODORG = OPCODORG1  
  
UPDATE  crv_PEND_CATIVA_ANALI          
SET  O2DESCR = T2.O2DESCR   
FROM CDCSANTANAMicroCredito..TORG2 T2 (NOLOCK)       
WHERE T2.O2CODORG = OPCODORG2  
  
UPDATE  crv_PEND_CATIVA_ANALI          
SET  A13DESCR = T3.O3DESCR   
FROM CDCSANTANAMicroCredito..TORG3 T3 (NOLOCK)       
WHERE T3.O3CODORG = OPCODORG6 
  
UPDATE  crv_PEND_CATIVA_ANALI          
SET  O4DESCR = T4.O4DESCR   
FROM CDCSANTANAMicroCredito..TORG4 T4 (NOLOCK)       
WHERE T4.O4CODORG = OPCODORG4  
  
UPDATE  crv_PEND_CATIVA_ANALI          
SET  O5DESCR = T5.O5DESCR   
FROM CDCSANTANAMicroCredito..TORG5 T5 (NOLOCK)       
WHERE T5.O5CODORG = OPCODORG5  
  
UPDATE  crv_PEND_CATIVA_ANALI          
SET  O3DESCR = T6.O6DESCR   
FROM CDCSANTANAMicroCredito..TORG6 T6 (NOLOCK)       
WHERE T6.O6CODORG = OPCODORG3  

UPDATE crv_PEND_CATIVA_ANALI
SET REGIAO = NOME_REGIAO
FROM DEPARA_REGIAO D (NOLOCK) 
INNER JOIN TAB_REGIAO P (NOLOCK) ON D.COD_REGIAO = P.COD_REGIAO
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON COD_AGENTE = O3CODORG 
WHERE crv_PEND_CATIVA_ANALI.A13CODORG = COD_AGENTE

UPDATE crv_PEND_CATIVA_ANALI
SET PREJU = CASE WHEN DIASATRASO > 360 THEN 'SIM' ELSE 'NÃO' END 

UPDATE crv_PEND_CATIVA_ANALI
SET RENEG = CASE WHEN RIGHT(OPNROPER,1) IN ('A','B','C','D','E','F','G','H') THEN 'SIM' ELSE 'NÃO' END 
          
SELECT OPCODORG6 AS A13CODORG, A13DESCR, OPNROPER, OPDTBASE, CLNOMECLI, OPCODORG3, crv_PEND_CATIVA_ANALI.O3DESCR, OPCODORG4, O4DESCR, ABPLACA, ABRENAVAM, ABCHASSI,         
  CASE WHEN DIASATRASO <0 then '0' else  DIASATRASO  END diasAtraso, REGIAO, PREJU, RENEG, CASE WHEN O3ATIVA IN ('S','A') THEN 'SIM' ELSE 'NÃO' END AS ATIVO
FROM crv_PEND_CATIVA_ANALI (NOLOCK) 
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 T (NOLOCK) ON A13CODORG = T.O3CODORG
LEFT  JOIN DEPARA_REGIAO (NOLOCK) ON T.O3CODORG = COD_AGENTE
WHERE 1= 0+ CASE WHEN  @REGIAO='99' THEN 1    
      WHEN  @REGIAO<>'99' AND COD_REGIAO = @REGIAO THEN 1        
      ELSE  0   END    
AND  1= 0+ CASE WHEN  @PREJUIZO='99' THEN 1    
      WHEN  @PREJUIZO= '0' AND PREJU = 'NÃO' THEN 1        
	  WHEN  @PREJUIZO= '1' AND PREJU = 'SIM' THEN 1
      ELSE  0   END  
AND  1= 0+ CASE WHEN  @RENEG='99' THEN 1    
      WHEN  @RENEG= '0' AND RENEG = 'NÃO' THEN 1        
	  WHEN  @RENEG= '1' AND RENEG = 'SIM' THEN 1
      ELSE  0   END  	 
AND  1= 0+ CASE WHEN  @ATIVO='99' THEN 1    
      WHEN  @ATIVO= '0' AND O3ATIVA IN ('N','D') THEN 1        
	  WHEN  @ATIVO= '1' AND O3ATIVA IN ('S','A') THEN 1
      ELSE  0   END 	     
end