'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Paginas.Comercial
    
    Partial Public Class PendenciasCRVEquipe
        
        '''<summary>
        '''UpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''btnDataAnteriorCont control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnteriorCont As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDataContrato control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataContrato As Global.Componentes.Datax
        
        '''<summary>
        '''btnProximaDataCont control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaDataCont As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnDataAnteriorRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnteriorRef As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDataReferencia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataReferencia As Global.Componentes.Datax
        
        '''<summary>
        '''btnProximaDataRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaDataRef As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnDataAnteriorDe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnteriorDe As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDataDe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataDe As Global.Componentes.Datax
        
        '''<summary>
        '''btnProximaDataDe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaDataDe As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnDataAnteriorAte control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnteriorAte As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDataAte control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataAte As Global.Componentes.Datax
        
        '''<summary>
        '''btnProximaDataAte control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaDataAte As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnCarregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCarregar As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMenu As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnImpressao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnImpressao As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHelp As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''ddlAgente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAgente As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlOperador control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOperador As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlPreju control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPreju As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''btnDtDeAnterior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDtDeAnterior As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDtDeBaixa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDtDeBaixa As Global.Componentes.Datax
        
        '''<summary>
        '''btnDtDeProxima control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDtDeProxima As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnDtAteAnterior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDtAteAnterior As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtDtAteBaixa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDtAteBaixa As Global.Componentes.Datax
        
        '''<summary>
        '''btnDtAteProxima control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDtAteProxima As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtQteContratoRealizado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQteContratoRealizado As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtQtePendAlienacao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQtePendAlienacao As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtPercentual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPercentual As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtQtdBaixa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQtdBaixa As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtVlrBaixa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVlrBaixa As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''dvGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''GridView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''UpdateProgress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
        
        '''<summary>
        '''hfGridView1SV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SV As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hfGridView1SH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SH As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
