'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Paginas.Comercial

    Partial Public Class RelCadastroLojas

        '''<summary>
        '''UpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''btnDataAnterior1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnterior1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtDataDe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataDe As Global.Componentes.Datax

        '''<summary>
        '''btnProximaData1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaData1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDataAnterior2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDataAnterior2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtDataAte control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataAte As Global.Componentes.Datax

        '''<summary>
        '''btnProximaData2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProximaData2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlAgente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAgente As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnCarregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCarregar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMenu As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''btnImpressao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnImpressao As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''btnHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHelp As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''dvRiscoAnalitico control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvRiscoAnalitico As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''GridViewRiscoAnalitico control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewRiscoAnalitico As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdateProgress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

        '''<summary>
        '''hfGridView1SV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SV As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfGridView1SH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfGridView1SH As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
