USE SIG
set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go


-- EXEC CRV_PENDENCIA_151 '2014-01-01','2014-06-30','2014-06-30'
-- PROC CALCULO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'CRV_PENDENCIA_151' AND type = 'P')
   DROP PROCEDURE [dbo].[CRV_PENDENCIA_151]
GO


CREATE  Procedure [dbo].[CRV_PENDENCIA_151] (@DT_REF SMALLDATETIME,  @DT_INI SMALLDATETIME,  @DT_FIM SMALLDATETIME, @AGNT   INT ) AS
BEGIN

TRUNCATE TABLE PEND151

INSERT INTO  PEND151(OPCODPROD, OPNROPER, OPDTBASE, OPVLRFIN, OPCODORG1, O1DESCR,
 OPCODORG2, O2DESCR, OPCODORG3, O3DESCR,  OPCODORG4, O4DESCR,
 OPCODORG5, O5DESCR, OPCODORG6, EPCODPEN, EPCMPLTO, OPCODCLI,
 A13CODORG, A13DESCR, ABRENAVAM, ABVLRTAB, ABCHASSI, ABCERTIF,
 ABPLACA, ABMODELO, CLNOMECLI, CLFONEFIS, CLFONECOM, CLCGC,
 DIASATRASO, EPDTAGEN, EPDTPEN, EPDTCAD, EPDTLNCBX, EPDTFIM)


SELECT  distinct OPCODPROD,  O.OPNROPER, O.OPDTBASE, O.OPVLRFIN,O.OPCODORG1, T1.O1DESCR, O.OPCODORG2, T2.O2DESCR, O.OPCODORG3, T3.O3DESCR,
  O.OPCODORG4, T4.O4DESCR, O.OPCODORG5, T5.O5DESCR, O.OPCODORG6, E.EPCODPEN, E.EPCMPLTO, O.OPCODCLI,
  T1O3.A13CODORG,  replace( REPLACE( replace (A13DESCR,'PROMOTORA',''), 'PROMOT ',''), 'PROM',''), B.ABRENAVAM, B.ABVLRTAB, B.ABCHASSI, B.ABCERTIF, B.ABPLACA, B.ABMODELO, C.CLNOMECLI, C.CLFONEFIS, C.CLFONECOM, C.CLCGC,    
  ISNULL((SELECT		MAX(DATEDIFF(DD, P.PADTVCTO, @DT_REF)) 
				FROM	CDCSANTANAMicroCredito..CPARC P 
				WHERE	P.PANROPER = O.OPNROPER 
					AND ( P.PADTMOV IS NULL OR P.PADTMOV > @DT_REF) 
					AND  P.PADTVAL <= @DT_REF AND  NOT (P.PACODMOV IN ('07', '08', '09', '13', '91', '94') 
					AND  P.PADTLIQ IS NOT NULL)), 0) AS DIASATRASO, 
  E.EPDTAGEN, E.EPDTPEN, E.EPDTCAD, E.EPDTLNCBX, E.EPDTFIM 

FROM 
  CDCSANTANAMicroCredito..COPER O 
  INNER JOIN CDCSANTANAMicroCredito..CCLIE C  ON O.OPCODCLI = C.CLCODCLI 
  INNER JOIN CDCSANTANAMicroCredito..EPEND E ON O.OPNROPER = E.EPNROPER 
  INNER JOIN CDCSANTANAMicroCredito..TPEND TP ON E.EPCODPEN = TP.PDCODPEN 
  LEFT  JOIN CDCSANTANAMicroCredito..CBFIN B  ON O.OPNROPER = B.ABNROPER AND E.EPNRGAR = B.ABNRGAR AND 
    B.ABCNTRL = (SELECT MAX(BX.ABCNTRL) FROM CDCSANTANAMicroCredito..CBFIN BX WHERE BX.ABNROPER = O.OPNROPER AND BX.ABNRGAR = E.EPNRGAR)
  LEFT  JOIN CDCSANTANAMicroCredito..TORG1 T1 ON O.OPCODORG1 = T1.O1CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TORG2 T2 ON O.OPCODORG2 = T2.O2CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TORG3 T3 ON O.OPCODORG3 = T3.O3CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TORG4 T4 ON O.OPCODORG4 = T4.O4CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TORG5 T5 ON O.OPCODORG5 = T5.O5CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TORG6 T6 ON O.OPCODORG6 = T6.O6CODORG 
  LEFT  JOIN CDCSANTANAMicroCredito..TA1O3 T1O3 ON T3.O3CODORGA13 = T1O3.A13CODORG
WHERE E.EPCODPEN =  '151'
--and O.OPDTLIQ IS NULL
and   ( O.OPDTLIQ IS NULL OR O.OPDTLIQ > @DT_REF) 
AND O.OPDTBASE <= @DT_FIM
AND (E.EPDTFIM IS NULL OR E.EPDTFIM > @DT_REF )  AND E.EPDTCAD <= @DT_REF
--AND O.OPCODPROD IN ('000010','000009','000030','000072','000073','000005','000004','020001','000002','000003','999999','000001','000020','020003','000011','000013','000007','002000','000026','000019','020004','000012','000014','000025','000008','020006','020002','020005','020007') 
AND E.EPDTCAD >= @DT_INI
AND E.EPDTCAD <= @DT_FIM
AND T1O3.A13CODORG = @AGNT





--SELECT OPNROPER, OPDTBASE, CLNOMECLI, OPCODORG3, O3DESCR, OPCODORG4, O4DESCR, ABPLACA, ABRENAVAM, ABCHASSI, CASE WHEN DIASATRASO <0 then '0' else  DIASATRASO  END dias_atraso FROM PEND151
END
GO


SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

