use sig

select * FROM TREGIAO
select * FROM tuf
select * FROM TGRUPO

DELETE FROM TREGIAO;
DELETE FROM TUF;
DELETE FROM TGRUPO;

INSERT INTO TUF VALUES('SP', 'SÃO PAULO');

INSERT INTO TREGIAO VALUES(1, 'GRANDE SÃO PAULO');
INSERT INTO TREGIAO VALUES(2, 'SÃO PAULO CENTRAL');
INSERT INTO TREGIAO VALUES(3, 'SÃO PAULO INTERIOR');

INSERT INTO TGRUPO VALUES (1,'ZONA SUL',1);
INSERT INTO TGRUPO VALUES (2,'ZONA LESTE',1);
INSERT INTO TGRUPO VALUES (3,'ZONA NORTE',1);
INSERT INTO TGRUPO VALUES (4,'VALE',1);
INSERT INTO TGRUPO VALUES (5,'SMG',1);

INSERT INTO TGRUPO VALUES (6,'AMERICANA',2);
INSERT INTO TGRUPO VALUES (7,'CAMPINAS',2);
INSERT INTO TGRUPO VALUES (8,'JUNDIAÍ',2);
INSERT INTO TGRUPO VALUES (9,'MOGI GUAÇU',2);
INSERT INTO TGRUPO VALUES (10,'SOROCABA',2);
INSERT INTO TGRUPO VALUES (11,'SOROCABA - FILIAL',2);

INSERT INTO TGRUPO VALUES (12,'BAURU',3);
INSERT INTO TGRUPO VALUES (13,'FRANCA',3);
INSERT INTO TGRUPO VALUES (14,'JALES',3);
INSERT INTO TGRUPO VALUES (15,'MARÍLIA',3);
INSERT INTO TGRUPO VALUES (16,'PORTO FERREIRA',3);
INSERT INTO TGRUPO VALUES (17,'RIBEIRÃO PRETO',3);
INSERT INTO TGRUPO VALUES (18,'SÃO CARLOS',3);
INSERT INTO TGRUPO VALUES (19,'SÃO JOSÉ DO RIO PRETO',3);
INSERT INTO TGRUPO VALUES (20,'PRESIDENTE PRUDENTE',3);


select * from TCIDADE

INSERT TCIDADE (COD_REGIAO,COD_GRUPO,CODIGO, CIDADE,COD_UF,COD_AGENTE,CEP_DE,CEP_ATE) 
SELECT 1	,1	,100,	'SÃO PAULO',1,	30	,'',''	
INSERT TCIDADE (COD_REGIAO,COD_GRUPO,CODIGO, CIDADE,COD_UF,COD_AGENTE,CEP_DE,CEP_ATE) 
SELECT 1	,2	,101,	'SÃO PAULO',1,	119	,'',''	
INSERT TCIDADE (COD_REGIAO,COD_GRUPO,CODIGO, CIDADE,COD_UF,COD_AGENTE,CEP_DE,CEP_ATE) 
SELECT 1	,3	,102,	'SÃO PAULO',1,	2	,'',''	
INSERT TCIDADE (COD_REGIAO,COD_GRUPO,CODIGO, CIDADE,COD_UF,COD_AGENTE,CEP_DE,CEP_ATE) 
SELECT 1	,3	,103,	'SÃO PAULO',1,	107	,'',''	

UPDATE TCIDADE SET CIDADE = 'SAO PAULO' WHERE CIDADE='SÃO PAULO'

REGIAO	GRUPO	COD	CIDADE	UF	COD AGENTE	CEP_DE	CEP_ATE
1	1	100	SÃO PAULO	SP	30		
1	2	101	SÃO PAULO	SP	119		
							
							
1	3	102	SÃO PAULO	SP	2		
1	3	103	SUZANO	SP	107		
							
1	3	103	GUARULHOS	SP	97		
1	3	103	Bom Jesus dos Perdoes	SP	97		
1	3	103	Nazare Paulista	SP	97		
1	3	103	Bragança	SP	97		
1	3	103	Atibaia	SP	97		
1	3	103	Mairiporã	SP	97		
1	3	103	Serra Negra	SP	97		
1	3	103	Socorro	SP	97		
1	3	103	Itatiba	SP	97		


