'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu

    '''<summary>
    '''MenuRoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuRoot As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Parametros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parametros As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Usuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Usuarios As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ComissaoPj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComissaoPj As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Cobrança control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cobrança As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ParametrosGerencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParametrosGerencial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ParametrosAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParametrosAR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ParametrosPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParametrosPT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ParametrosProtesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParametrosProtesto As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MetaFormaliz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MetaFormaliz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ParamRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParamRC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Cadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cadastro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Cobranca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cobranca As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Relatorios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Relatorios As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Graficos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Graficos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Protesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Protesto As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RiscoGerencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiscoGerencial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''IP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RiscoCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiscoCredito As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Spread control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Spread As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpreadAnalitico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpreadAnalitico As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P123 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P123Microcredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P123Microcredito As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RiscoCreditoInd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiscoCreditoInd As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ComercialCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComercialCredito As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddownComissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddownComissao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Comercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comercial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CRV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CRV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CobrancaP123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CobrancaP123 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Credito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Credito As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Gerencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gerencial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CETIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CETIP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PJ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DCO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DCO As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ConferePagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConferePagamento As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GravIncQui control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GravIncQui As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PendCrvCartAtiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PendCrvCartAtiva As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Financeiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Financeiro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Desconto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Desconto As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TbGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbGeral As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell
End Class
