use sig
go

-- TESTE			DT_entra	HR_ENTRA	SITINI	DT_sai	HR_SAI
-- DECLARE @T NUMERIC(6) SELECT @T=DBO.FN_TEMPO_ANALISE('2015-10-17','12:56','2015-10-19','08:54') SELECT @T
-- SELECT DBO.FN_TEMPO_ANALISE('2015-10-16','12:56','2015-10-19','08:54')
-- SELECT DATEPART(WEEKDAY, '2015-10-17')
-- SELECT DATEDIFF(N, CONVERT(DATETIME,dateadd(dd,2,'2015-10-16'))+'08:00', CONVERT(DATETIME,'2015-10-19')+'09:54')
-- ALTER 
-- create 
ALTER FUNCTION dbo.FN_TEMPO_ANALISE
(
@DT_INI DATETIME,
@HR_INI VARCHAR(5),
@DT_FIN DATETIME,
@HR_FIN VARCHAR(5)
)

RETURNS NUMERIC(6)

AS

BEGIN
    DECLARE
        @HRE VARCHAR(5),
        @HRS VARCHAR(5),
        @CONT INT,
		@HR8 VARCHAR(5),
		@HR18 VARCHAR(5)
    DECLARE @SOMA_TEMPO NUMERIC(6)
    DECLARE @FERIADO INT
    
    SET @HRE = ''
    SET @HRS = ''
	SET @HR8 = '08:00'
	SET @HR18  = '18:00'
    

    SET @SOMA_TEMPO = 0
    SET @CONT = 0
    
    WHILE @DT_INI <= @DT_FIN
        BEGIN
            IF @CONT = 0
				BEGIN
					SET @HRE = @HR_INI
				END
			IF @CONT > 0
				BEGIN
					SET @HRE = '08:00'
				END

			SELECT 
				@FERIADO = COUNT(FEDTFER)
			FROM   
				TABCORPSANTANA..TFERI
			WHERE  
			FEDTFER = @DT_INI
			
			SET @HRS = '18:00'

			IF @DT_INI = @DT_FIN
				BEGIN
					SET @HRS = @HR_FIN
				END
            
			IF @FERIADO = 0 AND DATEPART(WEEKDAY, @DT_INI) IN (2, 3, 4, 5, 6)
			BEGIN
				IF DATEDIFF(N, @DT_INI + @HRE, @DT_INI + @HRS) > 0 
					SET @SOMA_TEMPO = @SOMA_TEMPO + DATEDIFF(N, @DT_INI + @HRE, @DT_INI + @HRS)

			-- SE SEXTA TRATAR PQ PODE DORMIR NO FDS NA MESA
			
			END
			
				-- ALTERADO OUT-15  SABADO  ************
				IF DATEPART(WEEKDAY, @DT_INI) IN (7)
				BEGIN
					SET @DT_INI = DATEADD(DD, 2, @DT_INI)
					IF	@DT_INI = @DT_FIN
						SET @HRS = @HR_FIN
					SET @SOMA_TEMPO =  @SOMA_TEMPO +  DATEDIFF(N, @DT_INI + @HR8, @DT_INI + @HRS)
				END

				-- ALTERADO OUT-15  DOMINGO
				IF DATEPART(WEEKDAY, @DT_INI) IN (1)
				BEGIN
					SET @DT_INI = DATEADD(D, 1, @DT_INI)
					IF @DT_INI = @DT_FIN
							SET @HRS = @HR_FIN
					IF @DT_INI < @DT_FIN
							SET @HRS = @HR18
					SET @SOMA_TEMPO = @SOMA_TEMPO + DATEDIFF(N, @DT_INI + @HR8, @DT_INI + @HRS)
				END
			-- PROXIMA DATA, CONTADOR + 1
            SET @DT_INI = DATEADD(D, 1, @DT_INI)
            SET @CONT = @CONT + 1
        END
        
        IF ISNULL(@SOMA_TEMPO,0) < 0
            SET @SOMA_TEMPO = 0
        
        RETURN (ISNULL(@SOMA_TEMPO,0))
END
GO
