ALTER PROCEDURE [DBO].[PRC_RESUMO_PROPOSTA] AS 
DECLARE @data_ref as datetime            
DECLARE @data_DE as datetime            
DECLARE @data_ATE as datetime            
SET @data_ref = GETDATE()            
SET @data_ATE = GETDATE()       

SET  @data_ref= CONVERT(DATETIME, CONVERT(VARCHAR(10),GETDATE(),120))            
            
SET  @data_DE =  CONVERT(CHAR(4),DATEPART(YEAR,GETDATE()))+            
    RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,GETDATE()))),2)+'01'            
            
-- executa às sextas ou no fim do mes            
IF  Datepart(dw,getdate())= 6 OR DATEPART(day,DATEADD (DD,+1,GETDATE()))=1            
            
BEGIN 

DELETE TB_RESUMO_PROPOSTA WHERE DATA_REF = @DATA_REF

INSERT  TB_RESUMO_PROPOSTA (DATA_REF, PPNRPROP, PPDTBASE,   PPSCORING, PPVLRFIN, PPTETOFIN,                   
       PPCODCLI, PPCODORG4 , COD_LOJA, PPCODORG3, COD_OPERADOR, COD_PRODUTO,COD_AGENTE, COD_TABELA,PLANO,VLRPARC)                              
SELECT  @DATA_REF, PPNRPROP,PPDTBASE,PPSCORING, PPVLRFIN, PPTETOFIN,                  
   PPCODCLI, PPCODORG4 , PPCODORG4 , PPCODORG6  , PPCODORG6, PPCODPRD,PPCODORG3,        
   PPCODTAB,PPQTDDPARC,PPVLRPARC                  
 FROM PROPWEBSMC..CPROP (NOLOCK)                  
 WHERE PPDTBASE BETWEEN @DATA_DE  AND @DATA_ATE  AND    
 PPCODPRD IN ('000204','000205','000206','000207','000208','000209','000210','000211','000212','000213','000214','000215','000216','000217','000218',    
'000223','000224','000225','000226','000241','000242','000245','000246','000247','000248','000249','000251','000258','000262','000600','000601','000602',    
'000603','000605','000606','000607','000618','000619','000620','000705','000709','000720','000740','000749')  

UPDATE  TB_RESUMO_PROPOSTA                  
 SET  CLCGC=C.CLCGC,CLNOMECLI=C.CLNOMECLI                  
 FROM PROPWEBSMC..CCLIP C (NOLOCK)                  
 WHERE PPCODCLI=C.CLCODCLI AND DATA_REF = @DATA_REF               
                              
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  MPSIT = M.MPSIT, MPNRDECI = M.MPNRDECI, MPCODDECI = M.MPCODDECI, MPDTSIT = M.MPDTSIT                  
 FROM PROPWEBSMC..CMOVP M (NOLOCK)                  
 WHERE PPNRPROP = M.MPNRPROP AND DATA_REF = @DATA_REF                  
                             
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  O4NOME=L.O4NOME                  
 FROM CDCSANTANAMICROCREDITO..TORG4 L(NOLOCK)                  
 WHERE PPCODORG4 =L.O4CODORG AND DATA_REF = @DATA_REF                  
                           
UPDATE  TB_RESUMO_PROPOSTA                  
 SET              
  OPERADOR = O.O6DESCR                              
 FROM CDCSANTANAMICROCREDITO..TORG6 O (NOLOCK)                  
 WHERE COD_OPERADOR=O.O6CODORG AND DATA_REF = @DATA_REF                
                          
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  O3CODORGA13=O.PPCODORG3,                  
   COD_AGENTE =O.PPCODORG3                            
 FROM PROPWEBSMC..CPROP O (NOLOCK)                  
 WHERE TB_RESUMO_PROPOSTA.PPNRPROP=O.PPNRPROP AND DATA_REF = @DATA_REF              
            
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  A13DESCR = A.O3DESCR           
 FROM CDCSANTANAMICROCREDITO..TORG3 A (NOLOCK)                  
 WHERE TB_RESUMO_PROPOSTA.COD_AGENTE = A.O3CODORG AND DATA_REF = @DATA_REF            
                         
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  TDDESCR = D.TDDESCR                  
 FROM PROPWEBSMC..TDECI D (NOLOCK)                  
 WHERE MPNRDECI = D.TDNRDECI AND MPCODDECI = D.TDCODDECI AND DATA_REF = @DATA_REF                   
                             
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  ABMODELO=B.ABMODELO,ABANOMOD=B.ABANOMOD,ABVLRTAB=B.ABVLRTAB                  
 FROM PROPWEBSMC..CBFIP B (NOLOCK)                  
 WHERE PPNRPROP=B.ABNRPROP AND DATA_REF = @DATA_REF                  
                             
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  PRODUTO = A.TPDESCR                        
 FROM CDCSANTANAMICROCREDITO..TPROD A (NOLOCK)                  
 WHERE COD_PRODUTO = A.TPCODPRD AND DATA_REF = @DATA_REF                               
                 
UPDATE  TB_RESUMO_PROPOSTA                   
SET   ANALISTA = U.USNOMEUSUC                       
FROM  PROPWEBSMC..EPROP C  (NOLOCK),                  
   ACESSOCORP..TUSU  U  (NOLOCK)                  
WHERE    TB_RESUMO_PROPOSTA.PPNRPROP = C.EPNRPROP                  
 AND  USNOMEUSU = C.EPUSUARIO                  
 AND  1= 0+ CASE WHEN EPNRDECI=100 THEN 1                 
     WHEN EPNRDECI=120 THEN 1            
     ELSE 0 END
 AND DATA_REF = @DATA_REF	                    
                  
UPDATE  TB_RESUMO_PROPOSTA                  
 SET  DESCR_TABELA = A.TTDESCR            
 FROM CDCSANTANAMICROCREDITO..TTABE A (NOLOCK)                  
 WHERE COD_TABELA = A.TTCODTAB AND DATA_REF = @DATA_REF            
             
UPDATE TB_RESUMO_PROPOSTA SET PPSCORING = CRCONTEUDO          
FROM  MONITOR..ECONSULT (NOLOCK)           
INNER JOIN  MONITOR..ECONSLTR (NOLOCK) ON CSIDCONS = CRIDCONS          
WHERE TB_RESUMO_PROPOSTA.PPNRPROP = CSNRPROP          
AND COD_PRODUTO IN ('000223','000224','000225','000231')          
AND CRCAMPO = 'DISCRETA - RESULTADO DO SCORE'  AND DATA_REF = @DATA_REF  

DELETE FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DATA_REF = @DATA_REF    

INSERT TB_TOTAL_RESUMO_PROPOSTA(DATA_REF,DESCR, TOTAL, LINHA)    
SELECT @DATA_REF,'BASE DE PROPOSTAS' AS DESCR, COUNT(*) AS TOTAL, 1 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK)  WHERE DATA_REF = @DATA_REF   
UNION    
SELECT @DATA_REF, 'ABANDONADAS (DIGITAÇÃO)' AS DESCR, COUNT(*) AS TOTAL, 2 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE (MPSIT = 'AND' AND TDDESCR = 'DADOS BASICOS') OR (MPSIT IS NULL AND TDDESCR IS NULL) AND DATA_REF = @DATA_REF  
UNION  
SELECT @DATA_REF, 'BASE ANÁLISE PROPOSTA' AS DESCR, 0 AS TOTAL, 3 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE (MPSIT = 'AND' AND TDDESCR = 'DADOS BASICOS') OR (MPSIT IS NULL AND TDDESCR IS NULL)  AND DATA_REF = @DATA_REF 
UNION  
SELECT @DATA_REF, 'REPROVADAS AUTOMATICAMENTE' AS DESCR, COUNT(*) AS TOTAL, 4 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE TDDESCR IN(SELECT DISTINCT TDDESCR FROM PROPWEBSMC..TDECI T1 (NOLOCK) WHERE T1.TDCODDECI = 7003  
AND T1.TDDESCR LIKE 'NOK%' AND T1.TDCODDECI = TDCODDECI) AND DATA_REF = @DATA_REF  
UNION    
SELECT @DATA_REF, TDDESCR AS DESCR, COUNT(*) AS TOTAL, 5 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE TDDESCR IN(SELECT DISTINCT TDDESCR FROM PROPWEBSMC..TDECI T1 (NOLOCK) WHERE T1.TDCODDECI = 7003  
AND T1.TDDESCR LIKE 'NOK%' AND T1.TDCODDECI = TDCODDECI) AND DATA_REF = @DATA_REF  
GROUP BY TDDESCR    
UNION  
SELECT @DATA_REF, 'BASE PROPOSTAS APÓS NOK' AS DESCR, 0 AS TOTAL, 6 AS LINHA
UNION    
SELECT @DATA_REF, 'ABANDONADAS (1ª CHAMADA)' AS DESCR, COUNT(*) AS TOTAL, 7 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT = 'AND' AND TDDESCR NOT IN ('CADASTRO DA PROPOSTA') AND DATA_REF = @DATA_REF     
UNION    
SELECT @DATA_REF, 'ABANDONADAS (2ª CHAMADA)' AS DESCR, COUNT(*) AS TOTAL, 8 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT = 'AND' AND TDDESCR IN ('CADASTRO DA PROPOSTA')  AND DATA_REF = @DATA_REF   
UNION    
SELECT @DATA_REF, 'ANALISADAS MESA' AS DESCR, COUNT(*) AS TOTAL, 9 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT IN ('APR' ,'INT','LIB','PEN','REP','CAN') AND    
TDDESCR NOT IN(SELECT DISTINCT TDDESCR FROM PROPWEBSMC..TDECI T1 (NOLOCK) WHERE T1.TDCODDECI = 7003  
AND T1.TDDESCR LIKE 'NOK%' AND T1.TDCODDECI = TDCODDECI) AND DATA_REF = @DATA_REF  
UNION    
SELECT @DATA_REF, 'APROVADAS' AS DESCR, COUNT(*) AS TOTAL, 10 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT IN ('APR','INT','LIB') AND DATA_REF = @DATA_REF    
UNION    
SELECT @DATA_REF, 'PENDENTES' AS DESCR, COUNT(*) AS TOTAL, 11 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT IN ('PEN') AND DATA_REF = @DATA_REF    
UNION    
SELECT @DATA_REF, 'REPROVADAS MESA' AS DESCR, COUNT(*) AS TOTAL, 12 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT IN ('REP') AND    
TDDESCR NOT IN(SELECT DISTINCT TDDESCR FROM PROPWEBSMC..TDECI T1 (NOLOCK) WHERE T1.TDCODDECI = 7003  
AND T1.TDDESCR LIKE 'NOK%' AND T1.TDCODDECI = TDCODDECI)  AND DATA_REF = @DATA_REF 
UNION    
SELECT @DATA_REF, 'CANCELADAS' AS DESCR, COUNT(*) AS TOTAL, 13 AS LINHA    
FROM TB_RESUMO_PROPOSTA (NOLOCK) WHERE MPSIT IN ('CAN')  AND DATA_REF = @DATA_REF   
    
DECLARE @BASEANALISE AS FLOAT    
DECLARE @REPROV AS FLOAT    
DECLARE @ABANDONADA AS FLOAT    
DECLARE @PRCTOTAL AS FLOAT    
DECLARE @BASEPRE AS FLOAT   
DECLARE @ANALISADAS AS FLOAT    
    
SELECT @BASEANALISE = TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DESCR = 'BASE DE PROPOSTAS'  AND DATA_REF = @DATA_REF   
SELECT @REPROV = TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DESCR = 'REPROVADAS AUTOMATICAMENTE'    AND DATA_REF = @DATA_REF 
SELECT @ABANDONADA = TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DESCR = 'ABANDONADAS (DIGITAÇÃO)'     AND DATA_REF = @DATA_REF
SELECT @ANALISADAS = TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DESCR = 'ANALISADAS MESA' AND DATA_REF = @DATA_REF    
    
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET TOTAL = @BASEANALISE - @ABANDONADA WHERE DESCR = 'BASE ANÁLISE PROPOSTA'  AND DATA_REF = @DATA_REF 
    
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET TOTAL = @BASEANALISE - @REPROV - @ABANDONADA WHERE DESCR = 'BASE PROPOSTAS APÓS NOK'  AND DATA_REF = @DATA_REF   
    
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET PRC_TOTAL = TOTAL/@BASEANALISE*100.00 WHERE DATA_REF = @DATA_REF 
    
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET PRC = TOTAL/@BASEANALISE*100 WHERE DESCR IN ('BASE DE PROPOSTAS','REPROVADAS AUTOMATICAMENTE','ABANDONADAS (DIGITAÇÃO)','BASE PROPOSTAS APÓS NOK','BASE ANÁLISE PROPOSTA')     AND DATA_REF = @DATA_REF
    
SELECT @BASEPRE = TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA WHERE DESCR = 'BASE PROPOSTAS APÓS NOK' AND DATA_REF = @DATA_REF    
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET PRC = TOTAL/@BASEPRE*100 WHERE DESCR IN ('ABANDONADAS (1ª CHAMADA)','ABANDONADAS (2ª CHAMADA)','ANALISADAS MESA')     AND DATA_REF = @DATA_REF
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET PRC = TOTAL/@ANALISADAS*100 WHERE DESCR IN ('APROVADAS','PENDENTES','REPROVADAS MESA','CANCELADAS')     AND DATA_REF = @DATA_REF
UPDATE TB_TOTAL_RESUMO_PROPOSTA SET PRC = TOTAL/@REPROV*100 WHERE LINHA = 5     AND DATA_REF = @DATA_REF
   
END