set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO

use sig
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PASSO_ESTEIRA_CRED_DB' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PASSO_ESTEIRA_CRED_DB] 
GO      
CREATE PROCEDURE SCR_PASSO_ESTEIRA_CRED_DB @DATADE SMALLDATETIME, @DATAATE SMALLDATETIME, @LOJA VARCHAR(10), @AGENTE VARCHAR(10),  
@PRODUTO VARCHAR(10), @ANALISTA VARCHAR(20), @SITUAC VARCHAR(5), @VALOR_DE VARCHAR(100), @VALOR_ATE VARCHAR(100), @REANALISE VARCHAR(10),  
       @ALCADA VARCHAR(2) AS  
  
-- TIAGO 30/07 - PROPOSTAS A PARTIR DA DATA QUE ENTROU NA MESA.  
INSERT AUX_PASSO_ESTEIRA_CREDITO_DB (DTBASE,PPNRPROP)   
SELECT DISTINCT CONVERT(CHAR(10),GETDATE(), 112), E.EPNRPROP FROM PROPWEBSMC..EPROP E (NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON E.EPNRPROP = PPNRPROP   
INNER JOIN PROPWEBSMC..CMOVP M(NOLOCK) ON PPNRPROP = MPNRPROP  
WHERE E.EPDTLNC BETWEEN @DATADE AND @DATAATE AND PPCODPRD NOT IN ('000221','000406')  
AND E.EPNRDECI IN ('1549','100')  
--AND EPNRPROP NOT IN ('941817950','941818548','941818698','941819088','941816836','941819806') --PROPOSTAS COM EXCEÇÃO PARA EXIBIÇÃO NO RELATÓRIO.  
--AND 1= 0+ CASE WHEN  @LOJA='99' THEN 1 -- TODAS AS LOJAS  
--      WHEN  @LOJA<>'99' AND PPCODORG4 = @LOJA  THEN 1          
--      ELSE  0   END      
--AND 1= 0+ CASE WHEN  @AGENTE='99' THEN 1 -- TODAS OS AGENTES  
--      WHEN  @AGENTE<>'99' AND PPCODORG3 = @AGENTE  THEN 1          
--      ELSE  0   END      
--AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1 -- TODAS OS PRODUTOS  
--      WHEN  @PRODUTO<>'99' AND PPCODPRD = @PRODUTO  THEN 1          
--      ELSE  0   END   
--AND 1= 0+ CASE WHEN  @ANALISTA='99' THEN 1 -- TODAS OS ANALISTAS  
--      WHEN  @ANALISTA<>'99' AND E.EPUSUARIO = @ANALISTA  THEN 1          
--      ELSE  0   END   
--AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP  
--AND 1= 0+ CASE WHEN  @SITUAC='99' THEN 1 -- TODAS AS SITUAÇÕES  
--      WHEN  @SITUAC<>'99' AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP AND M1.MPSIT = @SITUAC)  THEN 1          
--      ELSE  0   END  
-- AND 1= 0 + CASE WHEN @VALOR_DE<>'' AND @VALOR_ATE<>'' AND PPVLRFIN BETWEEN CONVERT(FLOAT,@VALOR_DE) AND CONVERT(FLOAT,@VALOR_ATE)  THEN 1 --VALORES  
--     WHEN @VALOR_DE='' AND @VALOR_ATE=''  THEN 1         
--      ELSE 0 END   
--AND 1= 0+ CASE WHEN  @REANALISE='99' THEN 1 -- ANÁLISE/REANÁLISE  
--      WHEN  @REANALISE = '0' AND ISNULL(M.MPNUMRA,0)  = @REANALISE  THEN 1  
--   WHEN  @REANALISE = '1' AND ISNULL(M.MPNUMRA,0) >= @REANALISE  THEN 1         
--      ELSE  0   END   
--AND 1= 0+ CASE WHEN @ALCADA='99' THEN 1  
--  WHEN @ALCADA = '0' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('6','7') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '1' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('158','1521','20','12','32','4157') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '2' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('157','155','4588') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '3' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('4815','156','4589') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '4' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('3521') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  ELSE 0 END  
UNION --inserido dia 15/10 para pegar dthrfim  
SELECT DISTINCT CONVERT(CHAR(10),GETDATE(), 112), E.EPNRPROP FROM PROPWEBSMC..EPROP E (NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON E.EPNRPROP = PPNRPROP   
INNER JOIN PROPWEBSMC..CMOVP M(NOLOCK) ON PPNRPROP = MPNRPROP  
WHERE E.EPDTHRFIM BETWEEN @DATADE + '00:00:00' AND @DATAATE + '23:59:59' AND PPCODPRD NOT IN ('000221','000406')  
AND E.EPNRDECI IN ('1549','100')  
--AND EPNRPROP NOT IN ('941817950','941818548','941818698','941819088','941816836','941819806') --PROPOSTAS COM EXCEÇÃO PARA EXIBIÇÃO NO RELATÓRIO.  
--AND 1= 0+ CASE WHEN  @LOJA='99' THEN 1 -- TODAS AS LOJAS  
--      WHEN  @LOJA<>'99' AND PPCODORG4 = @LOJA  THEN 1          
--      ELSE  0   END      
--AND 1= 0+ CASE WHEN  @AGENTE='99' THEN 1 -- TODAS OS AGENTES  
--      WHEN  @AGENTE<>'99' AND PPCODORG3 = @AGENTE  THEN 1          
--      ELSE  0   END      
--AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1 -- TODAS OS PRODUTOS  
--      WHEN  @PRODUTO<>'99' AND PPCODPRD = @PRODUTO  THEN 1          
--      ELSE  0   END   
--AND 1= 0+ CASE WHEN  @ANALISTA='99' THEN 1 -- TODAS OS ANALISTAS  
--      WHEN  @ANALISTA<>'99' AND E.EPUSUARIO = @ANALISTA  THEN 1          
--      ELSE  0   END   
----AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP  
--AND 1= 0+ CASE WHEN  @SITUAC='99' THEN 1 -- TODAS AS SITUAÇÕES  
--      WHEN  @SITUAC<>'99' AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP AND M1.MPSIT = @SITUAC)  THEN 1          
--      ELSE  0   END  
-- AND 1= 0 + CASE WHEN @VALOR_DE<>'' AND @VALOR_ATE<>'' AND PPVLRFIN BETWEEN CONVERT(FLOAT,@VALOR_DE) AND CONVERT(FLOAT,@VALOR_ATE)  THEN 1 --VALORES  
--     WHEN @VALOR_DE='' AND @VALOR_ATE=''  THEN 1         
--      ELSE 0 END   
--AND 1= 0+ CASE WHEN  @REANALISE='99' THEN 1 -- ANÁLISE/REANÁLISE  
--      WHEN  @REANALISE = '0' AND ISNULL(M.MPNUMRA,0)  = @REANALISE  THEN 1  
--   WHEN  @REANALISE = '1' AND ISNULL(M.MPNUMRA,0) >= @REANALISE  THEN 1         
--      ELSE  0   END   
--AND 1= 0+ CASE WHEN @ALCADA='99' THEN 1  
--  WHEN @ALCADA = '0' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('6','7') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '1' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('158','1521','20','12','32','4157') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '2' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('157','155','4588') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '3' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('4815','156','4589') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  WHEN @ALCADA = '4' AND  E.EPNRPROP IN (SELECT E1.EPNRPROP FROM PROPWEBSMC..EPROP E1 (NOLOCK) WHERE E1.EPNRPROP = E.EPNRPROP   
--   AND E1.EPNRDECI IN ('3521') AND E1.EPDTLNC BETWEEN @DATADE AND @DATAATE) THEN 1  
--  ELSE 0 END  
ORDER BY E.EPNRPROP  
  
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 0  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_ENT_LOJA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_ENT_LOJA = EPHORALNC  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MIN(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('0','1'))  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
          
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 503  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_SAI_LOJA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_SAI_LOJA = EPHORALNC,  
SEQ_LOJA = EPNRSEQ  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP   
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('503'))  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
--DELETAR PROPOSTAS QUE NÃO TEM PASSO 503  
DELETE FROM AUX_PASSO_ESTEIRA_CREDITO_DB WHERE DTBASE = CONVERT(CHAR(10),GETDATE(), 112) AND DT_SAI_LOJA IS NULL  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB 
  SET TEMPO_LOJA = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_LOJA, HR_ENT_LOJA,DT_SAI_LOJA, HR_SAI_LOJA))  
--  WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_ENT_PROM = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_ENT_PROM = EPHORALNC  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('503'))  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_SAI_PROM = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_SAI_PROM = EPHORALNC,  
SEQ_PROM = EPNRSEQ  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('1549','100') AND E1.EPNRSEQ > SEQ_LOJA)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB  
  SET TEMPO_PROM = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_PROM, HR_ENT_PROM,DT_SAI_PROM, HR_SAI_PROM))  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_ENT_MESA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_ENT_MESA = EPHORALNC  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('1549','100') AND E1.EPNRSEQ > SEQ_LOJA)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_SAI_MESA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_SAI_MESA = EPHORALNC,  
SEQ_MESA = EPNRSEQ  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('120','97') AND E1.EPNRSEQ > SEQ_PROM)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB  
  SET TEMPO_MESA = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_MESA, HR_ENT_MESA,DT_SAI_MESA, HR_SAI_MESA))  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_ENT_ANALI = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_ENT_ANALI = EPHORALNC  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('120') AND E1.EPNRSEQ > SEQ_PROM)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_SAI_ANALI = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_SAI_ANALI = EPHORALNC,  
SEQ_ANALI = EPNRSEQ  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP   
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('2','91','96','18','79','97') AND E1.EPNRSEQ > SEQ_MESA)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB  
  SET TEMPO_ANALI = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_ANALI, HR_ENT_ANALI,DT_SAI_ANALI, HR_SAI_ANALI))  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
  
  UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_ENT_ALÇA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_ENT_ALÇA = EPHORALNC  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('2') AND E1.EPNRSEQ > SEQ_MESA)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET   
DT_SAI_ALÇA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+    
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),   
HR_SAI_ALÇA = EPHORALNC,  
SEQ_ALÇA = EPNRSEQ  
FROM PROPWEBSMC..EPROP E (NOLOCK)   
WHERE PPNRPROP = E.EPNRPROP  
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('8','97') AND E1.EPNRSEQ > SEQ_ANALI)  
--AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB  
  SET TEMPO_ALÇA = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_ALÇA, HR_ENT_ALÇA,DT_SAI_ALÇA, HR_SAI_ALÇA))  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE

IF MONTH(@DATADE) = MONTH(GETDATE()) AND DAY(@DATADE) = DAY(GETDATE())
BEGIN
--INCLUSÃO 16/04/2019 PARA DASH DE TEMPO DE CRÉDITO
	DECLARE @DT_HOJE AS SMALLDATETIME
	DECLARE @HR_HOJE AS VARCHAR(7)

	SET @DT_HOJE = CONVERT(VARCHAR(4),DATEPART(YYYY,GETDATE()))+    
	RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,GETDATE()))),2)+    
	RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,GETDATE()))),2)

	SET @HR_HOJE = CONVERT(VARCHAR(5),GETDATE(),114)
	
	IF CAST(LEFT(@HR_HOJE,2) AS INTEGER) >= CAST('18' AS INTEGER) BEGIN
		SET @HR_HOJE = '18:00'
	END

	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_ENT_ALÇA = @DT_HOJE WHERE DT_ENT_ALÇA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_ENT_ALÇA = @HR_HOJE WHERE HR_ENT_ALÇA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_SAI_ALÇA = @DT_HOJE WHERE DT_SAI_ALÇA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_SAI_ALÇA = @HR_HOJE WHERE HR_SAI_ALÇA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET TEMPO_ALÇA = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_ALÇA, HR_ENT_ALÇA,DT_SAI_ALÇA, HR_SAI_ALÇA))  

	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_ENT_ANALI = @DT_HOJE WHERE DT_ENT_ANALI IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_ENT_ANALI = @HR_HOJE WHERE HR_ENT_ANALI IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_SAI_ANALI = @DT_HOJE WHERE DT_SAI_ANALI IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_SAI_ANALI = @HR_HOJE WHERE HR_SAI_ANALI IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET TEMPO_ANALI = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_ANALI, HR_ENT_ANALI,DT_SAI_ANALI, HR_SAI_ANALI))  

	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_ENT_MESA = @DT_HOJE WHERE DT_ENT_MESA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_ENT_MESA = @HR_HOJE WHERE HR_ENT_MESA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET DT_SAI_MESA = @DT_HOJE WHERE DT_SAI_MESA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET HR_SAI_MESA = @HR_HOJE WHERE HR_SAI_MESA IS NULL
	UPDATE AUX_PASSO_ESTEIRA_CREDITO_DB SET TEMPO_MESA = (SIG.dbo.FN_TEMPO_ANALISE(DT_ENT_MESA, HR_ENT_MESA,DT_SAI_MESA, HR_SAI_MESA))  
END