set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO

use sig
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PASSO_ESTEIRA' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PASSO_ESTEIRA] 
GO    
CREATE PROCEDURE SCR_PASSO_ESTEIRA @DATADE SMALLDATETIME, @DATAATE SMALLDATETIME, @LOJA VARCHAR(10), @AGENTE VARCHAR(10),  
@PRODUTO VARCHAR(10), @ANALISTA VARCHAR(20), @SITUAC VARCHAR(5), @VALOR_DE VARCHAR(100), @VALOR_ATE VARCHAR(100), @REANALISE VARCHAR(10),  
       @ALCADA VARCHAR(30), @GERENCIA VARCHAR(5) as  
  
DELETE FROM AUX_PASSO_ESTEIRA_CREDITO  
--DELETE FROM AUX_PASSO_ESTEIRA_FORMALIZ WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
  
EXEC SCR_PASSO_ESTEIRA_CRED @DATADE, @DATAATE, @LOJA, @AGENTE, @PRODUTO, @ANALISTA, @SITUAC, @VALOR_DE, @VALOR_ATE, @REANALISE, @ALCADA, @GERENCIA  
  
SELECT   
'01' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'LOJA' AS PASSO,SUM(TEMPO_LOJA) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_LOJA)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_LOJA)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_LOJA)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_LOJA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_LOJA)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_LOJA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
UNION    
--SELECT '02' AS ORDEM, 'CRÉDITO' AS PROCESSO, 'PROMOTORA' AS PASSO,SUM(TEMPO_PROM) AS TEMPO, CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2))AS TEMPO_HORA,CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC(10,2)) AS TEMPO_PROPOSTA FROM AUX_PASSO_ESTEIRA_CREDITO WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
SELECT   
'02' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'AGENTE' AS PASSO,SUM(TEMPO_PROM) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
UNION    
--SELECT '03' AS ORDEM, 'CRÉDITO' AS PROCESSO, 'MESA' AS PASSO,SUM(TEMPO_MESA) AS TEMPO,CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2)) AS TEMPO_HORA,CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC(10,2)) AS TEMPO_PROPOSTA FROM AUX_PASSO_ESTEIRA_CREDITO WHERE DTBASE BETWEEN @DATADE AND @DATAATE   
SELECT  
'03' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'MESA' AS PASSO,SUM(TEMPO_MESA) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
UNION    
--SELECT '04' AS ORDEM, 'CRÉDITO' AS PROCESSO, 'ANALISTA' AS PASSO,SUM(TEMPO_ANALI) AS TEMPO,CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2)) AS TEMPO_HORA, CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC(10,2)) AS TEMPO_PROPOSTA FROM AUX_PASSO_ESTEIRA_CREDITO WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
SELECT  
'04' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'ANALISTA' AS PASSO,SUM(TEMPO_ANALI) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
UNION    
--SELECT '05' AS ORDEM, 'CRÉDITO' AS PROCESSO, 'ALÇADA' AS PASSO,SUM(TEMPO_ALÇA) AS TEMPO,CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2))AS TEMPO_HORA,CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC(10,2)) AS TEMPO_PROPOSTA   FROM AUX_PASSO_ESTEIRA_CREDITO WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
SELECT  
'05' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'ALÇADA' AS PASSO,SUM(TEMPO_ALÇA) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
UNION    
--SELECT '06' AS ORDEM, 'CRÉDITO' AS PROCESSO, 'TOTAL CRÉDITO' AS PASSO,SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA) AS TEMPO, CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00) AS NUMERIC(10,2)) AS TEMPO_HORA, CAST((((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00)/COUNT(*)) AS NUMERIC(10,2)) AS TEMPO_HORA  FROM AUX_PASSO_ESTEIRA_CREDITO WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
SELECT  
'06' AS ORDEM,   
'CRÉDITO' AS PROCESSO,   
'TOTAL CRÉDITO' AS PASSO,SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA) AS TEMPO,  
replace(cast(convert(decimal(10,2),cast(CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00) AS NUMERIC(10,2)) as int)+((CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00) AS NUMERIC(10,2))-cast(CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  
replace(cast(convert(decimal(10,2),cast(CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST(((SUM(TEMPO_LOJA)+SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA))/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA  
FROM AUX_PASSO_ESTEIRA_CREDITO --WHERE DTBASE BETWEEN @DATADE AND @DATAATE  
ORDER BY 1 ASC