set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO

use sig
go

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PASSO_ESTEIRA_FORMALIZ' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PASSO_ESTEIRA_FORMALIZ] 
GO   

CREATE PROCEDURE SCR_PASSO_ESTEIRA_FORMALIZ @DATADE SMALLDATETIME, @DATAATE SMALLDATETIME, @AGENTE VARCHAR(10), @PRODUTO VARCHAR(10),  
           @ANALISTA VARCHAR(20), @SITUAC VARCHAR(5), @VALOR_DE VARCHAR(100), @VALOR_ATE VARCHAR(100), @REANALISE VARCHAR(10)  
            AS    
  
DELETE FROM AUX_PASSO_ESTEIRA_FORMALIZ  
    
INSERT AUX_PASSO_ESTEIRA_FORMALIZ (DTBASE,PPNRPROP)    
SELECT DISTINCT CONVERT(CHAR(10),GETDATE(), 112), E.EPNRPROP FROM PROPWEBSMC..EPROP E (NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON E.EPNRPROP = PPNRPROP   
INNER JOIN PROPWEBSMC..CMOVP M (NOLOCK) ON PPNRPROP = MPNRPROP   
LEFT  JOIN CDCSANTANAMICROCREDITO..COPER O (NOLOCK) ON PPNRPROP = O.OPNRPROP
--INNER JOIN CDCSANTANAMICROCREDITO..TMODA (NOLOCK) ON TOCODOP = O.OPCODOP
--INNER JOIN CDCSANTANAMICROCREDITO..TCART (NOLOCK) ON TOCODCART = TCCODCART
 WHERE EPDTLNC BETWEEN @DATADE AND @DATAATE AND PPCODPRD <> '000221'   
 AND E.EPNRSEQ = (SELECT MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1 WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('662','663','664'))  
 AND 1= 0+ CASE WHEN  @AGENTE='99' THEN 1 -- TODAS OS AGENTES  
      WHEN  @AGENTE<>'99' AND PPCODORG3 = @AGENTE  THEN 1          
      ELSE  0   END    
AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1 -- TODAS OS PRODUTOS  
      WHEN  @PRODUTO<>'99' AND PPCODPRD = @PRODUTO  THEN 1          
      ELSE  0   END   
AND 1= 0+ CASE WHEN  @ANALISTA='99' THEN 1 -- TODAS OS ANALISTAS  
      WHEN  @ANALISTA<>'99' AND E.EPUSUARIO = @ANALISTA  THEN 1          
      ELSE  0   END   
AND 1= 0+ CASE WHEN  @REANALISE='99' THEN 1 -- ANÁLISE/REANÁLISE  
      WHEN  @REANALISE = '0' AND ISNULL(M.MPNUMRA,0)  = @REANALISE  THEN 1  
   WHEN  @REANALISE = '1' AND ISNULL(M.MPNUMRA,0) >= @REANALISE  THEN 1         
      ELSE  0   END   
 AND 1= 0 + CASE WHEN @VALOR_DE<>'' AND @VALOR_ATE<>'' AND PPVLRFIN BETWEEN CONVERT(FLOAT,@VALOR_DE) AND CONVERT(FLOAT,@VALOR_ATE)  THEN 1 --VALORES  
     WHEN @VALOR_DE='' AND @VALOR_ATE=''  THEN 1         
      ELSE 0 END   
AND 1= 0+ CASE WHEN  @SITUAC='99' THEN 1 -- TODAS AS SITUAÇÕES  
      WHEN  @SITUAC<>'99' AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP AND M1.MPSIT = @SITUAC)  THEN 1          
      ELSE  0   END  
AND PPCODOP IN (SELECT M.COD_MODA                    
FROM TTIPO_PROD T (NOLOCK), TMODA_TIPO_PROD M (NOLOCK)                      
WHERE M.COD_PROD = T.COD_PROD                     
AND T.COD_MODALIDADE = M.COD_MODALIDADE                     
AND T.COD_PROD IN('V','CP'))   
AND (ISNULL(OPESTORNO,'') <>'S')       
UNION ALL 
SELECT DISTINCT CONVERT(CHAR(10),GETDATE(), 112), E.EPNRPROP FROM PROPWEBSMC..EPROP E (NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON E.EPNRPROP = PPNRPROP   
INNER JOIN PROPWEBSMC..CMOVP M (NOLOCK) ON PPNRPROP = MPNRPROP   
LEFT  JOIN CDCSANTANAMICROCREDITO..COPER O (NOLOCK) ON PPNRPROP = O.OPNRPROP
--INNER JOIN CDCSANTANAMICROCREDITO..TMODA (NOLOCK) ON TOCODOP = O.OPCODOP
--INNER JOIN CDCSANTANAMICROCREDITO..TCART (NOLOCK) ON TOCODCART = TCCODCART
 WHERE E.EPDTHRFIM BETWEEN @DATADE + '00:00:00' AND @DATAATE + '23:59:59' AND PPCODPRD <> '000221'   
 AND E.EPNRSEQ = (SELECT MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1 WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('662','663','664'))  
 AND 1= 0+ CASE WHEN  @AGENTE='99' THEN 1 -- TODAS OS AGENTES  
      WHEN  @AGENTE<>'99' AND PPCODORG3 = @AGENTE  THEN 1          
      ELSE  0   END    
AND 1= 0+ CASE WHEN  @PRODUTO='99' THEN 1 -- TODAS OS PRODUTOS  
      WHEN  @PRODUTO<>'99' AND PPCODPRD = @PRODUTO  THEN 1          
      ELSE  0   END   
AND 1= 0+ CASE WHEN  @ANALISTA='99' THEN 1 -- TODAS OS ANALISTAS  
      WHEN  @ANALISTA<>'99' AND E.EPUSUARIO = @ANALISTA  THEN 1          
      ELSE  0   END   
AND 1= 0+ CASE WHEN  @REANALISE='99' THEN 1 -- ANÁLISE/REANÁLISE  
      WHEN  @REANALISE = '0' AND ISNULL(M.MPNUMRA,0)  = @REANALISE  THEN 1  
   WHEN  @REANALISE = '1' AND ISNULL(M.MPNUMRA,0) >= @REANALISE  THEN 1         
      ELSE  0   END   
 AND 1= 0 + CASE WHEN @VALOR_DE<>'' AND @VALOR_ATE<>'' AND PPVLRFIN BETWEEN CONVERT(FLOAT,@VALOR_DE) AND CONVERT(FLOAT,@VALOR_ATE)  THEN 1 --VALORES  
     WHEN @VALOR_DE='' AND @VALOR_ATE=''  THEN 1         
      ELSE 0 END   
AND 1= 0+ CASE WHEN  @SITUAC='99' THEN 1 -- TODAS AS SITUAÇÕES  
      WHEN  @SITUAC<>'99' AND M.MPSIT = (SELECT M1.MPSIT FROM PROPWEBSMC..CMOVP M1 (NOLOCK) WHERE M1.MPNRPROP = M.MPNRPROP AND M1.MPSIT = @SITUAC)  THEN 1          
      ELSE  0   END  
AND PPCODOP IN (SELECT M.COD_MODA                    
FROM TTIPO_PROD T (NOLOCK), TMODA_TIPO_PROD M (NOLOCK)                      
WHERE M.COD_PROD = T.COD_PROD                     
AND T.COD_MODALIDADE = M.COD_MODALIDADE                     
AND T.COD_PROD IN('V','CP'))    
AND (ISNULL(OPESTORNO,'') <>'S')  
          
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 57, 602, 2031   
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_ENT_PROM = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_ENT_PROM = EPHORALNC    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)      
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('57','602','2031'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
            
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 662,663    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_SAI_PROM = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_SAI_PROM = EPHORALNC,    
SEQ_PROM = EPNRSEQ    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP     
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)      
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('662','663'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--DELETAR OPERAÇÕES QUE NÃO ENTRARAM NA ESTEIRA DE FORMALIZAÇÃO  
DELETE FROM AUX_PASSO_ESTEIRA_FORMALIZ WHERE HR_ENT_PROM IS NULL AND DTBASE BETWEEN @DATADE AND @DATAATE  
  
--ATUALIZA TABELA TEMPORÁRIA COM TEMPO CALCULADO - PROMOTORA    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ    
  --SET TEMPO_PROM = (dbo.FN_TEMPO_ANALISE(DT_ENT_PROM, HR_ENT_PROM,DT_SAI_PROM, HR_SAI_PROM))    
SET TEMPO_PROM = CASE WHEN (dbo.FN_TEMPO_ANALISE(DT_ENT_PROM, HR_ENT_PROM,DT_SAI_PROM, HR_SAI_PROM)) = 0 THEN 1  
      ELSE (dbo.FN_TEMPO_ANALISE(DT_ENT_PROM, HR_ENT_PROM,DT_SAI_PROM, HR_SAI_PROM)) END  
  --WHERE DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 662,663,664    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_ENT_MESA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_ENT_MESA = EPHORALNC    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)      
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('662','663','664'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 600,603,107    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_SAI_MESA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_SAI_MESA = EPHORALNC,    
SEQ_MESA = EPNRSEQ    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)     --ALTEREI  
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('600','603','107') AND E1.EPNRSEQ > SEQ_PROM)    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM TEMPO CALCULADO - MESA    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ    
  --SET TEMPO_MESA = (dbo.FN_TEMPO_ANALISE(DT_ENT_MESA, HR_ENT_MESA,DT_SAI_MESA, HR_SAI_MESA))    
  SET TEMPO_MESA = CASE WHEN (dbo.FN_TEMPO_ANALISE(DT_ENT_MESA, HR_ENT_MESA,DT_SAI_MESA, HR_SAI_MESA)) = 0 THEN 1  
      ELSE (dbo.FN_TEMPO_ANALISE(DT_ENT_MESA, HR_ENT_MESA,DT_SAI_MESA, HR_SAI_MESA)) END  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 600,603,107    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_ENT_ANALI = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_ENT_ANALI = EPHORALNC    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    --ALTEREI  
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('600','603','107'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 212,602,664    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_SAI_ANALI = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_SAI_ANALI = EPHORALNC,    
SEQ_ANALI = EPNRSEQ    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    --ALTEREI  
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('602','664','301','1002') AND E1.EPNRSEQ > SEQ_MESA)    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM TEMPO CALCULADO - ANALI    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ    
  --SET TEMPO_ANALI = (dbo.FN_TEMPO_ANALISE(DT_ENT_ANALI, HR_ENT_ANALI,DT_SAI_ANALI, HR_SAI_ANALI))    
  SET TEMPO_ANALI = CASE WHEN (dbo.FN_TEMPO_ANALISE(DT_ENT_ANALI, HR_ENT_ANALI,DT_SAI_ANALI, HR_SAI_ANALI)) = 0 THEN 1  
       ELSE (dbo.FN_TEMPO_ANALISE(DT_ENT_ANALI, HR_ENT_ANALI,DT_SAI_ANALI, HR_SAI_ANALI)) END  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE    
    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 212    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_ENT_ALÇA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_ENT_ALÇA = EPHORALNC    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)   --ALTEREI   
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('301','1002'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 1001,1002,1003,1004,301    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_SAI_ALÇA = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_SAI_ALÇA = EPHORALNC,    
SEQ_ALÇA = EPNRSEQ    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP     
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    --ALTEREI  
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('1001','1002','1003','1004','301','302') AND E1.EPNRSEQ > SEQ_ANALI)    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM TEMPO CALCULADO - ALÇADA    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ    
  --SET TEMPO_ALÇA = (dbo.FN_TEMPO_ANALISE(DT_ENT_ALÇA, HR_ENT_ALÇA,DT_SAI_ALÇA, HR_SAI_ALÇA))    
 SET TEMPO_ALÇA = CASE WHEN (dbo.FN_TEMPO_ANALISE(DT_ENT_ALÇA, HR_ENT_ALÇA,DT_SAI_ALÇA, HR_SAI_ALÇA)) = 0 THEN 1  
        ELSE (dbo.FN_TEMPO_ANALISE(DT_ENT_ALÇA, HR_ENT_ALÇA,DT_SAI_ALÇA, HR_SAI_ALÇA)) END  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 1001,1002,1004,1003,301    
--UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
--DT_ENT_REME = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
--RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
--RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
--HR_ENT_REME = EPHORALNC    
--FROM PROPWEBSMC..EPROP E (NOLOCK)     
--WHERE PPNRPROP = E.EPNRPROP    
--AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    --ALTEREI  
--       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('1001','1002','1004','1003','301','302'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
  
  
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_ENT_REME = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
HR_ENT_REME = EPHORALNC    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)    --ALTEREI  
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('22'))    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM DATA/HORA DE ENTRADA DO PASSO 22    
--UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
--DT_SAI_REME = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTLNC))+      
--RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTLNC))),2)+      
--RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTLNC))),2),     
--HR_SAI_REME = EPHORALNC,    
--SEQ_REME = EPNRSEQ    
--FROM PROPWEBSMC..EPROP E (NOLOCK)     
--WHERE PPNRPROP = E.EPNRPROP    
--AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)   --ALTEREI   
--       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('22') AND E1.EPNRSEQ > SEQ_ALÇA)    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
  
  
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ SET     
DT_SAI_REME = CONVERT(VARCHAR(4),DATEPART(YYYY,EPDTHRFIM))+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(MM,EPDTHRFIM))),2)+      
RIGHT('00'+LTRIM(CONVERT(VARCHAR(2),DATEPART(DD,EPDTHRFIM))),2),     
HR_SAI_REME = CONVERT(VARCHAR(5),EPDTHRFIM,114),    
SEQ_REME = EPNRSEQ    
FROM PROPWEBSMC..EPROP E (NOLOCK)     
WHERE PPNRPROP = E.EPNRPROP    
AND EPNRSEQ = (SELECT  MAX(E1.EPNRSEQ) FROM PROPWEBSMC..EPROP E1  (NOLOCK)   --ALTEREI   
       WHERE E1.EPNRPROP = E.EPNRPROP AND EPNRDECI IN ('22') AND E1.EPNRSEQ > SEQ_ALÇA)    
--AND DTBASE BETWEEN @DATADE AND @DATAATE    
    
--ATUALIZA TABELA TEMPORÁRIA COM TEMPO CALCULADO - ALÇADA    
UPDATE AUX_PASSO_ESTEIRA_FORMALIZ    
  --SET TEMPO_REME = (dbo.FN_TEMPO_ANALISE(DT_ENT_REME, HR_ENT_REME,DT_SAI_REME, HR_SAI_REME))    
 SET TEMPO_REME = CASE WHEN (dbo.FN_TEMPO_ANALISE(DT_ENT_REME, HR_ENT_REME,DT_SAI_REME, HR_SAI_REME)) = 0 THEN 1  
        ELSE (dbo.FN_TEMPO_ANALISE(DT_ENT_REME, HR_ENT_REME,DT_SAI_REME, HR_SAI_REME)) END  
--WHERE DTBASE BETWEEN @DATADE AND @DATAATE    
    
    
SELECT       
'01' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'AGENTE' AS PASSO,SUM(TEMPO_PROM) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_PROM)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_PROM)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
UNION        
SELECT       
'02' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'MESA DE FORMALIZAÇÃO' AS PASSO,SUM(TEMPO_MESA) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_MESA)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_MESA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
UNION        
SELECT      
'03' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'ANALISTA' AS PASSO,SUM(TEMPO_ANALI) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_ANALI)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_ANALI)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.  ',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
UNION        
SELECT      
'04' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'ALÇADA' AS PASSO,SUM(TEMPO_ALÇA) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_ALÇA)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_ALÇA)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar)  ,'.',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
UNION        
SELECT      
'05' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'REMESSA' AS PASSO,SUM(TEMPO_REME) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_REME)/60.00) AS NUMERIC(10,2)) as int)+((CAST((SUM(TEMPO_REME)/60.00) AS NUMERIC(10,2))-cast(CAST((SUM(TEMPO_REME)/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,      
replace(cast(convert(decimal(10,2),cast(CAST((SUM(TEMPO_REME)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST((SUM(TEMPO_REME)/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST((SUM(TEMPO_REME)/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
UNION        
SELECT      
'06' AS ORDEM,       
'FORMALIZAÇÃO' AS PROCESSO,       
'TOTAL FORMALIZAÇÃO' AS PASSO,SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME) AS TEMPO,      
replace(cast(convert(decimal(10,2),cast(CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00) AS NUMERIC(10,2)) as int)+((CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00) AS NUMERIC(10,2))-cast(CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00) AS NUMERIC(10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_HORA,  replace(cast(convert(decimal(10,2),cast(CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00)/COUNT(*) AS NUMERIC (10,2)) as int)+((CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00)/COUNT(*) AS NUMERIC (10,2))-cast(CAST(((SUM(TEMPO_PROM)+SUM(TEMPO_MESA)+SUM(TEMPO_ANALI)+SUM(TEMPO_ALÇA)+SUM(TEMPO_REME))/60.00)/COUNT(*) AS NUMERIC (10,2)) as int))*.60)) as varchar),'.',':') AS TEMPO_PROPOSTA      
FROM AUX_PASSO_ESTEIRA_FORMALIZ --WHERE DTBASE BETWEEN @DATADE AND @DATAATE      
ORDER BY 1 ASC