Use sig

-- RELATORIO TODOS =9
-- EXEC SCR_credito_EXCECAO '2017-06-01', '2017-06-10','9',''

-- EXEC SCR_credito_EXCECAO '20160418', '20160418','1',''
-- EXEC SCR_credito_EXCECAO '20160418', '20160418','2',''
-- EXEC SCR_credito_EXCECAO '20160418', '20160418','3',''

-- EXEC SCR_credito_EXCECAO '2015-11-01', '2015-10-30','1',''
-- EXEC SCR_credito_EXCECAO '2017-06-01', '2017-06-14','2','99'
-- EXEC SCR_credito_EXCECAO '2015-10-01', '2015-10-30','3',''

-- EXEC SCR_credito_EXCECAO '2015-11-01', '2015-11-20','1',''
/*
USE SIG

DUMP TRANSACTION SIG WITH NO_LOG

dbcc ShrinkFile(SIV_log, 1)

*/
-- SELECT *	FROM #CONTRATO
GO

-- PROC Credito INADIMPLENCIA **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_credito_EXCECAO' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_credito_EXCECAO]
GO

-- MENSAL
-- ***************************************
CREATE PROCEDURE [dbo].[SCR_credito_EXCECAO](
	@DATADE  AS DATETIME, 
	@DATAATE AS DATETIME,
	@RPT 	 AS INT,
	@FILTRO	 AS VARCHAR(200))

AS
BEGIN

SET NOCOUNT ON
DECLARE	@DATAATE_PGTO AS DATETIME
SET @DATAATE_PGTO = GETDATE()

/*
DROP   TABLE CRED_EXCECAO
CREATE TABLE CRED_EXCECAO
(CONTRATO VARCHAR(20),
PROPOSTA  VARCHAR(20),
PROMOTORA VARCHAR(20),
VLR_FINANCIADO	FLOAT,
PLANO			INT,
VLR_PARCELA		FLOAT,
DT_1o_VCTO		DATETIME,
DT_PGTO			DATETIME,
DIAS_ATRASO		INT,
MAIOR_PARC_ATRASO	VARCHAR(20) )
 
612220666	941505890	008495


ALTER  TABLE CRED_EXCECAO	ADD  RELATORIO VARCHAR(100)
-- JUN-2017
ALTER   TABLE CRED_EXCECAO ADD ANALISTA VARCHAR(200)

*/

TRUNCATE   TABLE CRED_EXCECAO


-- RPT 1 = Análise Mesa, 2 = Recusa Automática NOK , 3 = Não Formalizado
-- passo 59 excecao
IF @RPT = 1 OR @RPT = 9  -- ANALISE OU TODOS		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO ***
BEGIN
		-- tabela auxiliar
		INSERT CRED_EXCECAO
		select distinct  
		ppnroper as CONTRATO, ppnrprop as PROPOSTA, ppcodorg3 AS PROMOTORA,    -- operador
		--ppnomecli, ppcgc, ppcodorg3, ppusuario, PPCODPRD, PPCODTAB, ppdtbase, ppdtcad,PPVLROPCZ
		 PPVLRFIN   AS vlr_financiado, 
		--ppvlrliq1, pppropfim, mpsit, tddescr,
		PPQTDDPARC  AS PLANO,
		PPVLRPARC	AS vlr_parcela,
		PPDT1VCTO   AS dt_1o_vcto,
		ISNULL((SELECT MAX(PADTLIQ) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = PPNROPER),'')  AS dt_pgto,
		-- VENCIDA E NAO PAGA  DIAS ATRASO
		ISNULL(DATEDIFF(DD,(SELECT MIN(PADTVCTO) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = PPNROPER AND PADTVCTO<= @DATAATE_PGTO AND PADTLIQ IS NULL),@DATAATE_PGTO),0)  AS dias_atraso,
		-- VENCIDA E NAO PAGA NRO PARCELA
		ISNULL((SELECT MIN(PANROPER) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = PPNROPER  AND PADTVCTO<= @DATAATE_PGTO AND PADTLIQ IS NULL),0)    AS maior_parc_atraso

		,	'Análise Mesa' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		,	'' AS ANALISTA		--  INCLUI  EM 6/6/17		****
		--INTO 	#EXCECAO
		from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)

		WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
			-- and  ppdtbase >='2015-10-01' AND ppdtbase <='2015-10-31' 
			and  ppdtbase	BETWEEN @DATADE	AND @DATAATE
			and  epnrdeci ='59' 
			--and EPPROCES = 'AUTAPR'  -- OK			AND TDPROCESS='REMESSSPROCCOMP'
			and ppnrprop=epnrprop
			and epnrprop=mpnrprop

		-- CONTRATO				*************************
		UPDATE	CRED_EXCECAO	SET	CONTRATO = NULL
		UPDATE	CRED_EXCECAO
			SET	CONTRATO = OPNROPER
			FROM CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNRPROP = PROPOSTA
		-- remove se nao foi INTEGRADO
		DELETE	CRED_EXCECAO WHERE  CONTRATO IS NULL

		-- CONTRATO
		UPDATE	CRED_EXCECAO
			SET	dt_pgto = ISNULL(
		(SELECT MAX(PADTLIQ) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = CONTRATO) , ''),
		-- VENCIDA E NAO PAGA  DIAS ATRASO
				dias_atraso = ISNULL(
			DATEDIFF(DD,(SELECT MIN(PADTVCTO) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = CONTRATO AND PADTVCTO<= @DATAATE_PGTO AND PADTLIQ IS NULL),@DATAATE_PGTO),0) ,
		-- VENCIDA E NAO PAGA NRO PARCELA
		maior_parc_atraso =ISNULL(
		-- alterado 15/1/16  ***************** parcela em atraso
			(SELECT MIN(PANRparc) FROM CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER = CONTRATO  AND PADTVCTO<= @DATAATE_PGTO AND PADTLIQ IS NULL) , '')   
--		FROM CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNRPROP = PROPOSTA


		-- COD DO AGENTE ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
		WHERE	PROMOTORA = O3CODORG  -- OPERADOR

		-- SELECT *		FROM CDCSANTANAMicroCredito..TA1O3 (NOLOCK)
		-- NOME DA PROMOTORA ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.A13DESCR,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TA1O3 OP (NOLOCK) 
		WHERE	PROMOTORA = A13CODORG  -- OPERADOR

END


IF @RPT = 2  OR  @RPT = 9  -- RECUSA AUTOMATICA NOK , INCLUI RPT 9= TODOS EM 8/3/17
BEGIN
		-- tabela auxiliar
		-- SP_HELP CRED_EXCECAO
		INSERT	CRED_EXCECAO
				--(CONTRATO,PROPOSTA,PROMOTORA,VLR_FINANCIADO,PLANO,VLR_PARCELA,DT_1o_VCTO)
		select distinct  
				ppnroper , ppnrprop , ppcodorg3 ,  
				--ppnroper as CONTRATO, ppnrprop as PROPOSTA, ppcodorg4 AS PROMOTORA,  
				--ppnomecli, ppcgc, ppcodorg3, ppusuario, PPCODPRD, PPCODTAB, ppdtbase, ppdtcad,PPVLROPCZ
				 PPVLRFIN   , 
				--ppvlrliq1, pppropfim, mpsit, tddescr,
				PPQTDDPARC  ,
				PPVLRPARC	,
				PPDT1VCTO   ,
				'' AS DT_PGTO		,
				0  AS DIAS_ATRASO	,
				0  AS MAIOR_PARC_ATRASO 
				,	'RECUSA NOK' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
				,	'' AS ANALISTA		--  INCLUI  EM 6/6/17		****
				-- INTO 	#EXCECAO
		from	(SELECT *	FROM PROPWEBSMC..cprop (NOLOCK)
					WHERE	ppdtbase	BETWEEN @DATADE	AND @DATAATE ) AS P ,
				--PROPWEBSMC..cmovp	(NOLOCK), 
				PROPWEBSMC..tdeci (NOLOCK),		-- EM 8/3/17 CHECA SE NOK NA DESCR
				PROPWEBSMC..eprop   (NOLOCK)
		WHERE	ppnrprop = epnrprop		AND	-- mpnrprop and 
			--	tdnrdeci = mpnrdeci and		-- NR DECISAO  NOK

--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO, REMOVI OS CODIGOS DOS NOKs
--	EPnrdeci in ('64',  '65' , '66' , '67', '68','69','74','84','85','86','87','88', '89',     '83') AND

--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO, REMOVI OS CODIGOS DOS NOKs  ***********
				TdNrdeci = Epnrdeci and		-- NR DECISAO  NOK
				TDDESCR LIKE ('NOK%') AND   -- NOKs DAS NOVAS ESTEIRAS A PARTIR DE JAN/17


--MPnrdeci in ('64',  '65' , '66' , '67', '68','69','74','84','85','86','87','88', '89',     '83') AND
				--mpcoddeci = tdcoddeci and   -- NAO SAO IGUAIS
				ppnrprop  = epnrprop  
			--and  ppdtbase >='2015-10-01' AND ppdtbase <='2015-10-31' 
--			and  epnrdeci ='59' 

-- SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) ORDER BY TDNRDECI
-- somente codigos NOK
-- and tdnrdeci in ('64',  '65' , '66' , '67', '68','69','74','84','85','86','87','88', '89',     '83')

-- AND	TDCODdeci ='59'

			-- and EPPROCES = 'AUTREP'  -- NOK
			--AND TDPROCESS='REMESSSPROCCOMP'
--			and TDPROCESS = 'AUTREP'  -- NOK   JAN16
			and ppnrprop=epnrprop
--			and epnrprop=mpnrprop

		-- LIMPAR OS NAO NOK		************* JAN16  PROP NOK PASSA NO 59
/*		SELECT * FROM PROPWEBSMC..eprop (NOLOCK) WHERE EPNRPROP='941510881'
		SELECT * FROM PROPWEBSMC..CMOVP (NOLOCK) WHERE MPNRPROP='941510881'  -- REP  MPCODDECI 57  MPNRDECI 83
		SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDCODDECI=57  -- TDCODDECI  ???  TDNRDECI --> NOK
		SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDNRDECI=83   -- NOK


SELECT * FROM PROPWEBSMC..eprop (NOLOCK) WHERE EPNRPROP='941514618'
SELECT * FROM PROPWEBSMC..CMOVP (NOLOCK) WHERE MPNRPROP='941514618'  -- REP  MPCODDECI 57  MPNRDECI 86
		SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDCODDECI=57  -- TDCODDECI  ???  TDNRDECI --> NOK
		SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDNRDECI=86   -- NOK 

SELECT * FROM PROPWEBSMC..eprop (NOLOCK) WHERE EPNRPROP='941525568' AND EPNRDECI=
SELECT * FROM PROPWEBSMC..CMOVP (NOLOCK) WHERE MPNRPROP='941525568'  AND  
MPCODDECI 62
MPnrdeci 22
 in ('64',  '65' , '66' , '67', '68','69','74','84','85','86','87','88', '89',     '83') 
22
SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDCODDECI=22	
SELECT * FROM PROPWEBSMC..tdeci (NOLOCK) WHERE TDNRDECI=66
941514599
*/
		DELETE	FROM CRED_EXCECAO
		WHERE	PROPOSTA NOT IN (	SELECT DISTINCT PPNRPROP FROM
									(SELECT		DISTINCT PPNRPROP FROM PROPWEBSMC..cprop (NOLOCK)
									WHERE	ppdtbase	BETWEEN @DATADE	AND @DATAATE ) AS P
									JOIN	PROPWEBSMC..eprop   (NOLOCK)
									ON		PPNRPROP = EPNRPROP
									WHERE	epnrdeci ='59' )  

		-- alterado 10/2/16 **** somente INT
		DELETE	FROM CRED_EXCECAO
		WHERE	PROPOSTA NOT IN (	SELECT		DISTINCT MPNRPROP FROM PROPWEBSMC..CMOVP (NOLOCK)
									WHERE	MPNRPROP IN (SELECT DISTINCT PROPOSTA FROM CRED_EXCECAO (NOLOCK))
										AND	MPSIT='INT' )   
				

		-- CONTRATO				*************************
		UPDATE	CRED_EXCECAO	SET	CONTRATO = ''
				WHERE RELATORIO = 'RECUSA NOK'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
		UPDATE	CRED_EXCECAO
			SET	CONTRATO = OPNROPER
			FROM CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNRPROP = PROPOSTA
				AND RELATORIO = 'RECUSA NOK'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		-- NUNCA EH INTEGRADO, REPROVADAS NOK
		-- remove se nao foi INTEGRADO
		-- DELETE	CRED_EXCECAO WHERE  CONTRATO IS NULL

		--		DECLARE @DATADE	DATETIME ,  @DATAATE DATETIME SET @DATADE ='20151001'	SET @DATAATE='20151031'
		-- COD DO AGENTE ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
		WHERE	PROMOTORA = O3CODORG  -- OPERADOR
				AND RELATORIO = 'RECUSA NOK'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		-- SELECT *		FROM CDCSANTANAMicroCredito..TA1O3 (NOLOCK)
		-- NOME DA PROMOTORA ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.A13DESCR,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TA1O3 OP (NOLOCK) 
		WHERE	PROMOTORA = A13CODORG  -- OPERADOR
				AND RELATORIO = 'RECUSA NOK'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		
END



IF @RPT = 3  OR  @RPT = 9  -- NAO FORMALIZADA		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO  *************
BEGIN

		INSERT	CRED_EXCECAO
		select distinct  
				--ppnroper
				'' as CONTRATO, ppnrprop as PROPOSTA, ppcodorg3 AS PROMOTORA,  
				--ppnomecli, ppcgc, ppcodorg3, ppusuario, PPCODPRD, PPCODTAB, ppdtbase, ppdtcad,PPVLROPCZ
				 PPVLRFIN   AS vlr_financiado, 
				--ppvlrliq1, pppropfim, mpsit, tddescr,
				PPQTDDPARC  AS PLANO,
				PPVLRPARC	AS vlr_parcela,
				PPDT1VCTO   AS dt_1o_vcto,
				'' AS dt_pgto,
				0  AS dias_atraso,
				0  AS maior_parc_atraso
				,'NAO FORMALIZAD0'  AS RELATORIO  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
				,	'' AS ANALISTA		--  INCLUI  EM 6/6/17		****

		--INTO 	#EXCECAO
		from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)

		WHERE		ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
			--and  ppdtbase >='2015-10-01' AND ppdtbase <='2015-10-31' 
			and		ppdtbase	BETWEEN @DATADE	AND @DATAATE
			and		epnrdeci ='59' 
			--and  ISNULL(ppnroper ,'') =''
			-- NAO LOCALIZA A OPERACAO ANTES, LOCALIZAR A PROPOSTA SE FOI FORMALIZADA
			AND		PPNRPROP NOT IN (select PPNRPROP from	CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE PPNRPROP =OPNRPROP)

			--AND TDPROCESS='REMESSSPROCCOMP'
			and		ppnrprop=epnrprop
			and		epnrprop=mpnrprop

			-- SITUACAO APROVADA
			AND MPSIT IN ('APR')
		-- CONTRATO				*************************
		UPDATE	CRED_EXCECAO	SET	CONTRATO = NULL
			WHERE	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
		UPDATE	CRED_EXCECAO
			SET	CONTRATO = OPNROPER
			FROM CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNRPROP = PROPOSTA
			AND	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		-- remove se  foi INTEGRADO  ---------------- SOMENTE SE NAO FOI INTEGRADA
		DELETE	CRED_EXCECAO WHERE  CONTRATO IS NOT NULL
			AND	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
		UPDATE	CRED_EXCECAO 	SET	CONTRATO = ISNULL(CONTRATO,'')
			WHERE	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO


		-- COD DO AGENTE ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
		WHERE	PROMOTORA = O3CODORG  -- OPERADOR
			AND	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

		-- SELECT *		FROM CDCSANTANAMicroCredito..TA1O3 (NOLOCK)
		-- NOME DA PROMOTORA ********************	DO SISTEMA FUNCAO
		UPDATE	CRED_EXCECAO
		SET		PROMOTORA		= ISNULL(OP.A13DESCR,'') -- ISNULL(A.COD_AGENTE,'')
		FROM	CDCSANTANAMicroCredito..TA1O3 OP (NOLOCK) 
		WHERE	PROMOTORA = A13CODORG  -- OPERADOR
			AND	RELATORIO  = 'NAO FORMALIZAD0'  		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO

/*
		SELECT *
		,			'NAO FORMALIZADO' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
		FROM 		CRED_EXCECAO (NOLOCK)
*/
END

-- ULTIMO ANALISTA DA PROPOSTA		******  INCLUIDO DIA 6/6/17
UPDATE		CRED_EXCECAO 
	SET		ANALISTA = ISNULL(EPUSUARIO,'')
	FROM	(SELECT		EPNRPROP, EPUSUARIO	
				FROM	PROPWEBSMC..EPROP EPROP1 (NOLOCK) 
				WHERE	EPROP1.EPNRDECI IN ( '100', '120') 
					AND EPROP1.EPNRPROP IN (SELECT PROPOSTA FROM CRED_EXCECAO C2 (NOLOCK) )
					AND EPROP1.EPNRSEQ = (SELECT MAX(P2.EPNRSEQ) FROM PROPWEBSMC..EPROP P2 (NOLOCK) WHERE P2.EPNRPROP = EPROP1.EPNRPROP AND P2.EPNRDECI  IN ( '100', '120') ) 
					 )	AS EPROP  
	WHERE	EPROP.EPNRPROP = CRED_EXCECAO.PROPOSTA
-- NOME DO ANALISTA  EM 6/6/17     ***
UPDATE		CRED_EXCECAO
	SET		ANALISTA = USNOMEUSUC
	FROM	ACESSOCORP..TUSU (NOLOCK)
	WHERE	USNOMEUSU = ANALISTA




IF @RPT=1 -- OR @RPT=9 -- MOVI EM 8/3/17
		SELECT		*
--				,	'Análise Mesa' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
			FROM	CRED_EXCECAO (NOLOCK)
			WHERE	1 = 0+ CASE	 WHEN @FILTRO = 99 THEN 1 -- TODAS
								 WHEN @FILTRO = 1 AND DIAS_ATRASO = 0 THEN 1 -- EM DIA
								 WHEN @FILTRO = 2 AND DIAS_ATRASO > 0 THEN 1 -- ATRASADAS
								 WHEN @FILTRO = 3 AND dt_1o_vcto > @DATAATE_PGTO THEN 1 -- NAO VENCIDAS
								 ELSE 0 END
IF @RPT=2 --OR @RPT=9
		select distinct  X.CONTRATO, X.PROPOSTA,  X.PROMOTORA AS PROMOTORA,  
					--ppnomecli, ppcgc, ppcodorg3, ppusuario, PPCODPRD, PPCODTAB, ppdtbase, ppdtcad,PPVLROPCZ
					X.vlr_financiado, 
					--ppvlrliq1, pppropfim, mpsit, tddescr,
					X.PLANO,
					X.vlr_parcela,
					X.dt_1o_vcto,
					'' AS dt_pgto,
					0  AS dias_atraso,
					0  AS maior_parc_atraso--, *
					, 'RECUSA NOK' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
					,	ANALISTA					--  INCLUI  EM 6/6/17		****
		FROM 	CRED_EXCECAO X (NOLOCK)


IF @RPT=3 OR @RPT=9 -- MOVI EM 8/3/17
		SELECT		*
--				,	'Análise Mesa' AS RELATORIO		--  INCLUI RPT 9= TODOS EM 8/3/17 E COLUNA RELATORIO
			FROM	CRED_EXCECAO (NOLOCK)
			-- INCLUI FILTRO DE TELA DO TODOS EM 16/3/17
			WHERE	1 = 0+ CASE	 WHEN @FILTRO = 99 THEN 1 -- TODAS
								 WHEN @FILTRO = 1 AND DIAS_ATRASO = 0 THEN 1 -- EM DIA
								 WHEN @FILTRO = 2 AND DIAS_ATRASO > 0 THEN 1 -- ATRASADAS
								 WHEN @FILTRO = 3 AND dt_1o_vcto > @DATAATE_PGTO THEN 1 -- NAO VENCIDAS
								 ELSE 0 END
END

 
/*

select *		FROM 	CRED_EXCECAO X (NOLOCK)
SELECT 	EPROP.EPUSUARIO USUARIO,
	REPLICATE(' ',200)				analista, 
	PROP.PPNRPROP	proposta, 
	OPER.OPDTBASE	dt_contrato,
	DESCR_TIPO		produto,
	OPER.OPVLRFIN	vlr_financiado,
	OPER.OPCODCLI	COD_CLI
FROM			PROPWEBSMC..CPROP PROP  (NOLOCK) 
--INNER JOIN	PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = PROP.PPNRPROP AND MPSIT IN ('INT') 
INNER JOIN		CDCSANTANAMicroCredito..COPER (NOLOCK) OPER ON PROP.PPNRPROP = OPER.OPNRPROP 
LEFT JOIN 
	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) WHERE EPROP1.EPNRDECI IN ( '100', '120')  )as EPROP  
			ON EPROP.EPNRPROP = PROP.PPNRPROP 
		AND EPROP.EPNRSEQ = (SELECT MAX(P2.EPNRSEQ) FROM PROPWEBSMC..EPROP P2 (NOLOCK) WHERE P2.EPNRPROP = PROP.PPNRPROP AND P2.EPNRDECI  IN ( '100', '120') ) 
 LEFT JOIN 
	TModa_tipo_prod M (NOLOCK)  ON OPER.OPCODOP =	M.COD_MODA	AND M.COD_PROD  in ( 'V','cg') LEFT JOIN 
	Ttipo_prod T (NOLOCK) ON T.COD_MODALIDADE = M.COD_MODALIDADE 
WHERE PPNRPROP='941626434'
	--PROPWEBSMC..EPROP (nolock) EPRO2 ON 	EPRO2.EPNRPROP = OPER.OPNRPROP  AND EPRO2.EPNRDECI = '100' AND EPRO2.EPNRSEQ = (SELECT MAX(EPNRSEQ) FROM PROPWEBSMC..EPROP WHERE EPRO2.EPNRPROP = OPER.OPNRPROP AND EPRO2.EPNRDECI = '100') LEFT JOIN
	--PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = OPER.OPNRPROP AND MPSIT IN ('INT') LEFT JOIN
--	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) where EPnrDECI = 120) as EPROP  ON EPROP.EPNRPROP = PROP.PPNRPROP 

WHERE	
	PROP.PPDTBASE BETWEEN @DATADE AND @DATAATE 



FROM	
	PROPWEBSMC..CPROP PROP  (NOLOCK) 
--INNER JOIN	PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = PROP.PPNRPROP AND MPSIT IN ('INT') 
INNER JOIN 
	CDCSANTANAMicroCredito..COPER (NOLOCK) OPER ON PROP.PPNRPROP = OPER.OPNRPROP 
LEFT JOIN 
	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) WHERE EPROP1.EPNRDECI IN ( '100', '120')  )as EPROP  
			ON EPROP.EPNRPROP = PROP.PPNRPROP 
		AND EPROP.EPNRSEQ = (SELECT MAX(P2.EPNRSEQ) FROM PROPWEBSMC..EPROP P2 (NOLOCK) WHERE P2.EPNRPROP = PROP.PPNRPROP AND P2.EPNRDECI  IN ( '100', '120') ) 
 LEFT JOIN 
	--PROPWEBSMC..EPROP (nolock) EPRO2 ON 	EPRO2.EPNRPROP = OPER.OPNRPROP  AND EPRO2.EPNRDECI = '100' AND EPRO2.EPNRSEQ = (SELECT MAX(EPNRSEQ) FROM PROPWEBSMC..EPROP WHERE EPRO2.EPNRPROP = OPER.OPNRPROP AND EPRO2.EPNRDECI = '100') LEFT JOIN
	--PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = OPER.OPNRPROP AND MPSIT IN ('INT') LEFT JOIN
--	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) where EPnrDECI = 120) as EPROP  ON EPROP.EPNRPROP = PROP.PPNRPROP 

	TModa_tipo_prod M (NOLOCK)  ON OPER.OPCODOP =	M.COD_MODA	AND M.COD_PROD  in ( 'V','cg') LEFT JOIN 
	Ttipo_prod T (NOLOCK) ON T.COD_MODALIDADE = M.COD_MODALIDADE 
WHERE	
	PROP.PPDTBASE BETWEEN @DATADE AND @DATAATE 
--	PROP.PPDTBASE BETWEEN '20150601' AND '20150630'



FROM	
	PROPWEBSMC..CPROP PROP  (NOLOCK) 
INNER JOIN	
	PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = PROP.PPNRPROP AND MPSIT IN ('INT') 
INNER JOIN 
	CDCSANTANAMicroCredito..COPER (NOLOCK) OPER ON PROP.PPNRPROP = OPER.OPNRPROP 
LEFT JOIN 
	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) WHERE EPROP1.EPNRDECI = '100' ) as EPROP  
			ON EPROP.EPNRPROP = PROP.PPNRPROP 
		AND EPROP.EPNRSEQ = (SELECT MAX(P2.EPNRSEQ) FROM PROPWEBSMC..EPROP P2 (NOLOCK) WHERE P2.EPNRPROP = PROP.PPNRPROP  AND P2.EPNRDECI = '100') LEFT JOIN 
	--PROPWEBSMC..EPROP (nolock) EPRO2 ON 	EPRO2.EPNRPROP = OPER.OPNRPROP  AND EPRO2.EPNRDECI = '100' AND EPRO2.EPNRSEQ = (SELECT MAX(EPNRSEQ) FROM PROPWEBSMC..EPROP WHERE EPRO2.EPNRPROP = OPER.OPNRPROP AND EPRO2.EPNRDECI = '100') LEFT JOIN
	--PROPWEBSMC..CMOVP  (Nolock) ON 	CMOVP.MPNRPROP = OPER.OPNRPROP AND MPSIT IN ('INT') LEFT JOIN
--	(select * from PROPWEBSMC..EPROP EPROP1 (NOLOCK) where EPnrDECI = 120) as EPROP  ON EPROP.EPNRPROP = PROP.PPNRPROP 

	TModa_tipo_prod M (NOLOCK)  ON OPER.OPCODOP =	M.COD_MODA	AND M.COD_PROD  in ( 'V','cg') LEFT JOIN 
	Ttipo_prod T (NOLOCK) ON T.COD_MODALIDADE = M.COD_MODALIDADE 
WHERE	
	PROP.PPDTBASE BETWEEN @DATADE AND @DATAATE 
AND
	(
		@ANALISTA = '' OR EPROP.EPUSUARIO = @ANALISTA
	)

SELECT * FROM	ACESSOCORP..TUSU (NOLOCK)

UPDATE	#EXCECAO
SET		ANALISTA = USNOMEUSUC
FROM	ACESSOCORP..TUSU (NOLOCK)
WHERE	USNOMEUSU = USUARIO




--Parcelas em Aberto
-- select * from #CONTRATO
SELECT
	contrato, 
	max(dt_proposta)			AS DT_PROP,
	max(analista) as analista, 
--	case when  analista='' then 'pb cad' 		 else (ISNULL(analista,'pb cad')) end AS analista, 
	MAX(C.CLCGC)		AS proposta, 
	MAX(dt_contrato)    AS dt_contrato,
	ISNULL(MAX(produto),'')  AS produto,
	MAX(vlr_financiado) AS vlr_financiado,  
	MAX(DATEDIFF(d,PARC.PADTVCTO,@DATAATE_PGTO)) dias_atraso, 
	MAX(PAVLRPR)		AS vlr_parcela ,
	COUNT(PARC.PANROPER) qtd_parc_atraso,
	MIN(PARC.PANRPARC)   ATRASO_ANTIGO 
FROM 
	#EXCECAO INNER JOIN CDCSANTANAMicroCredito..cparc PARC (NOLOCK) ON #CONTRATO.contrato = PARC.PANROPER  
--	INNER JOIN CDCSANTANAMicroCredito..cCLIE C (NOLOCK)  ON #CONTRATO.COD_CLI = C.CLCODCLI
WHERE 
	PARC.PADTVCTO <= @DATAATE_PGTO AND (PARC.PADTLIQ IS NULL OR PARC.PADTLIQ > @DATAATE_PGTO) AND 
	PARC.PACNTRL = (
		SELECT 
			MAX(P1.PACNTRL) 
		FROM 
			CDCSANTANAMicroCredito..CPARC P1 (NOLOCK)
		WHERE 
			P1.PANROPER= PARC.PANROPER AND P1.PANRPARC = PARC.PANRPARC)
	AND 1=0+ CASE	WHEN @ATRASO_DE+@ATRASO_ATE = 0 THEN 1
					WHEN @ATRASO_DE+@ATRASO_ATE > 0 AND DATEDIFF(d,PARC.PADTVCTO,@DATAATE_PGTO) BETWEEN @ATRASO_DE AND @ATRASO_ATE THEN 1
					ELSE 0 END

	AND 1=0+ CASE	WHEN @ANALISTA = '99'  THEN 1
					WHEN @ANALISTA <>'99' AND  ANALISTA=@ANALISTA THEN 1
					ELSE 0 END

GROUP BY 
	contrato
--	dt_proposta,	analista, 
--	proposta, 	dt_contrato,	produto,	vlr_financiado

select * from	PROPWEBSMC..CPROP PROP  (NOLOCK)  where ppnrprop='941471483'

select * from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)
WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
and  ppnrprop='941471483'
--and  epnrdeci ='59' 
and ppnrprop=epnrprop

select * from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)
WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
and  ppnrprop='941492082'  and ppnrprop=epnrprop
--and  epnrdeci ='59' 


select * from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)
WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
and  ppnrprop='941495381'  and ppnrprop=epnrprop
TDPROCESS='REMESSSPROCCOMP'

EPPROCES = 'AUTREP'  -- NOK


and epnrprop=mpnrprop

select * from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)
WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
and  ppnrprop='941501673'  and ppnrprop=epnrprop


select * from	PROPWEBSMC..cprop (NOLOCK), PROPWEBSMC..cmovp (NOLOCK), PROPWEBSMC..tdeci (NOLOCK), PROPWEBSMC..eprop    (NOLOCK)
WHERE ppnrprop = mpnrprop and tdnrdeci=mpnrdeci and mpcoddeci =tdcoddeci 
and  ppnrprop='941503232'  and ppnrprop=epnrprop

select * from	CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNROPER='612219043'


612219595	941504133	007185

select * from	CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNRPROP='941504133'
 SELECT * FROM CDCSANTANAMicroCredito..CPARC P1 (NOLOCK) WHERE PANROPER='612219595'

select * from	CDCSANTANAMicroCredito..COPER (NOLOCK) WHERE OPNROPER='612220277'
select * from	CDCSANTANAMicroCredito..CPARC (NOLOCK) WHERE PANROPER='612220277'
*/
--SELECT * FROM #EXCECAO
-- SELECT * FROM CDCSANTANAMicroCredito..CPARC P1 (NOLOCK) WHERE PANROPER='612202331'
