USE sig 
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_RESUMO_PROPOSTA' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_RESUMO_PROPOSTA]
GO   
  
CREATE PROCEDURE [DBO].[SCR_RESUMO_PROPOSTA] (              
 @DATADE   AS DATETIME,               
 @DATAATE  AS DATETIME)  AS              
              
BEGIN     
  
SELECT DESCR,TOTAL,PRC,PRC_TOTAL FROM TB_TOTAL_RESUMO_PROPOSTA
where DATA_REF = @DATAATE
ORDER BY LINHA  
  
END 