use sig
go

set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go


IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_APROVADAS_REDUCAO' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_APROVADAS_REDUCAO] 
GO  

CREATE PROCEDURE SCR_APROVADAS_REDUCAO @DATADE SMALLDATETIME, @DATAATE SMALLDATETIME as  
  
DELETE FROM AUX_APROV_REDUCAO WHERE PPDTBASE BETWEEN @DATADE AND @DATAATE  
  
INSERT INTO AUX_APROV_REDUCAO(  
PPDTBASE,  
EPDTLNC,  
PPNRPROP,  
PPVLRLIB,  
PPSCORING,   
AGENTE,   
LOJA,   
PPCODPRD,   
CGVLRGAR,   
ABMODELO,   
ABANOMOD,   
PPCGC,   
MPSIT,   
EPUSUARIO  
)  
SELECT   
PPDTBASE,  
EPDTLNC,   
PPNRPROP,  
PPVLRLIB,  
PPSCORING,   
PPCODORG3 + ' - ' + O3DESCR AS AGENTE,   
PPCODORG4 + ' - ' + O4DESCR AS LOJA,  
PPCODPRD,   
ISNULL(CGVLRGAR,ABVLRVND) AS CGVLRGAR,  
ABMODELO,   
ABANOMOD,  
PPCGC,   
MPSIT,  
EPUSUARIO   
FROM PROPWEBSMC..EPROP (NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON EPNRPROP = PPNRPROP  
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON PPCODORG3 = O3CODORG   
LEFT  JOIN PROPWEBSMC..EGARP (NOLOCK) ON EPNRPROP = CGNRPROP AND PPNRPROP = CGNRPROP   
INNER JOIN PROPWEBSMC..CMOVP (NOLOCK) ON MPNRPROP = PPNRPROP  
INNER JOIN CDCSANTANAMICROCREDITO..TORG4 (NOLOCK) ON PPCODORG4 = O4CODORG   
LEFT  JOIN PROPWEBSMC..CBFIP (NOLOCK) ON ABNRPROP = PPNRPROP  
WHERE EPNRDECI = 60  
AND EPDTLNC BETWEEN @DATADE AND @DATAATE --ALTEREI PPDTBASE PARA EPDTLNC  
ORDER BY EPDTLNC  
  
  
UPDATE AUX_APROV_REDUCAO SET PPVLRSOL = LPVLRFIN FROM (select PPNRPROP,LPVLRFIN FROM   
PROPWEBSMC..CLOGPROP L WITH(NOLOCK)   
INNER JOIN PROPWEBSMC..CPROP P WITH(NOLOCK) ON L.LPNRPROP = P.PPNRPROP  
INNER JOIN PROPWEBSMC..CMOVP M WITH(NOLOCK) ON M.MPNRPROP = L.LPNRPROP  
WHERE P.PPNRPROP IN (SELECT A.PPNRPROP FROM AUX_APROV_REDUCAO A WHERE A.PPNRPROP = L.LPNRPROP)  
AND LPROTINA = 'ALT_PROP_VEIC'  
AND LPCNTRL = (SELECT MAX(LPCNTRL) - 1 FROM PROPWEBSMC..CLOGPROP L WITH(NOLOCK) WHERE L.LPNRPROP = P.PPNRPROP)) AS A  
WHERE A.PPNRPROP = AUX_APROV_REDUCAO.PPNRPROP  
  
SELECT  
EPDTLNC,   
PPNRPROP,  
PPVLRLIB,   
PPVLRSOL,  
PPSCORING,   
AGENTE,   
LOJA,  
PPCODPRD,   
CGVLRGAR,  
ABMODELO,   
ABANOMOD,  
PPCGC,   
MPSIT,  
EPUSUARIO FROM AUX_APROV_REDUCAO (NOLOCK) 
WHERE PPDTBASE BETWEEN @DATADE AND @DATAATE
AND PPVLRSOL > PPVLRLIB