/*  
ALTER TABLE ECRED ADD SAQUE_SOLICITADO FLOAT
ALTER TABLE ECRED ADD SAQUE_CONTRATADO FLOAT
ALTER TABLE AUX_ECRED ADD SAQUE_SOLICITADO FLOAT
ALTER TABLE AUX_ECRED ADD SAQUE_CONTRATADO FLOAT
*/
USE sig
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_ECRED' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_ECRED]
GO

CREATE PROCEDURE SCR_ECRED @DATA AS SMALLDATETIME, @AGENTE AS VARCHAR(6)  as  
  
IF @AGENTE = '000000'  
BEGIN  
DELETE FROM ECRED WHERE DT_UPLOAD = @DATA  
  
INSERT INTO ECRED (PEDIDO,STATUS,ID_CONSUMIDOR,NOME,CPF,EMAIL,TELEFONE,ENDERECO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,CEP,DTPEDIDO, DTAPROVACAO,  
DTLIBERACAO,TIPOCREDITO,TIPO,TOTAL_PARCELA,VALOR_PARCELA,VALOR_SOLICITADO,VALOR_CONTRATATO,VALOR_TOTAL,LIMITE_SOLICITADO,LIMITE_CONTRATADO,    
SAQUE_SOLICITADO,SAQUE_CONTRATADO,DT_UPLOAD, IND_ENVIO)     
SELECT PEDIDO,STATUS,ID_CONSUMIDOR,NOME,CPF,EMAIL,TELEFONE,ENDERECO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,CEP, DTPEDIDO, DTAPROVACAO,  
DTLIBERACAO,TIPOCREDITO,TIPO,TOTAL_PARCELA,VALOR_PARCELA,VALOR_SOLICITADO,VALOR_CONTRATATO,VALOR_TOTAL,LIMITE_SOLICITADO,LIMITE_CONTRATADO,    
SAQUE_SOLICITADO,SAQUE_CONTRATADO,@DATA,0    
FROM AUX_ECRED (NOLOCK)    
  
UPDATE ECRED SET CODAGENTE = O3CODORG, NOMEAGENTE = O3DESCR, EMAILAGENTE = O3EMAIL FROM  
CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) INNER JOIN TCIDADE (NOLOCK)   
ON CONVERT(INT,COD_AGENTE) = CONVERT(INT,O3CODORG)  
WHERE O3CODORG <> '000001' AND CONVERT(INT,REPLACE(CEP,'-','')) BETWEEN CONVERT(INT,CEP_DE) AND CONVERT(INT,CEP_ATE)  
  
SELECT * FROM ECRED (NOLOCK) WHERE DT_UPLOAD = @DATA ORDER BY CODAGENTE  
END  
ELSE  
BEGIN  
SELECT * FROM ECRED (NOLOCK) WHERE DT_UPLOAD = @DATA AND CODAGENTE = @AGENTE ORDER BY CODAGENTE  
END