USE sig
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_ECRED_CONSULTA' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_ECRED_CONSULTA]
GO  
CREATE PROCEDURE SCR_ECRED_CONSULTA @DATA AS SMALLDATETIME AS   
  
SELECT * FROM ECRED (NOLOCK) WHERE DT_UPLOAD = @DATA