SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

use SIG
go


-- PROC CALCULO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'PRC_PDD_MES' AND type = 'P')
   DROP PROCEDURE [dbo].[PRC_PDD_MES]
GO

-- PRC_PDD_MES '20160131'

/* 
   EXEC PRC_PDD_MES '20141231'

	EXEC PRC_PDD_MES '20150131'
    EXEC PRC_PDD_MES '20150228'
   EXEC PRC_PDD_MES '20150331'
   EXEC PRC_PDD_MES '20150430'
   EXEC PRC_PDD_MES '20150531'
   EXEC PRC_PDD_MES '20150630'
   EXEC PRC_PDD_MES '20150731'
   EXEC PRC_PDD_MES '20150831'
   EXEC PRC_PDD_MES '20150930'
   EXEC PRC_PDD_MES '20151031'
   EXEC PRC_PDD_MES '20151130'
   EXEC PRC_PDD_MES '20151231'

   EXEC PRC_PDD_MES '20160131'
   EXEC PRC_PDD_MES '20160229'
   EXEC PRC_PDD_MES '20160331'
   EXEC PRC_PDD_MES '20160430'

 select * from PDD_MES (nolock) ORDER BY DT_FECHA

delete from P123Ger_MES where DT_SAFRA= '2016-02-28'
delete from P123Ger_MES where DT_SAFRA= '2013-12-31'
delete from P123Ger_MES where DT_SAFRA= '2013-12-30'
SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='20140131'
SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='2013-12-31'


SELECT TOP 100 * FROM P123_HISTORICO (nolock) WHERE DT_FECHA='20150131'
-- ajustar os venctos p2 e p3 de 1/15 a 7/15   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC P		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3 AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20150131' AND  '20150731'

-- ajustar os venctos p2 e p3 de 2014   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND   PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	MAX(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20140131' AND  '20141231'

-- ajustar os venctos p2 e p3 de 2014   **********************
		UPDATE	P123_HISTORICO
		SET		P2VCTO = ( SELECT 	(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2 AND   PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
				P2PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=2  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=2 )),
P3VCTO = ( SELECT 	MAX(PADTVCTO)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 )),
				P3PGTO =  ( SELECT 	MAX(PADTLIQ)
	FROM	CdcSantanaMicroCredito..CPARC 		(NOLOCK)
	WHERE PANROPER = NUM_OPE AND PANRPARC=3  AND PACNTRL = (SELECT MAX(PACNTRL) FROM	CdcSantanaMicroCredito..CPARC P2		(NOLOCK)
	WHERE P2.PANROPER = NUM_OPE AND P2.PANRPARC=3 ))
		WHERE	DT_FECHA	 BETWEEN '20131231' AND  '20131231'

SELECT * 		FROM	RATING_HISTORICO		(NOLOCK)
		WHERE	DT_FECHA	 = '20160131' 			AND	NVL_RISCO    <>'HH'

SELECT SUM(SLD_INSCRITO)  		FROM	RATING_HISTORICO		(NOLOCK)
		WHERE	DT_FECHA	 = '20160131' 			AND	NVL_RISCO    <>'HH'

SELECT		R1.NVL_RISCO , SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= '20160131' AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'A' 
			GROUP	BY R1.NVL_RISCO
*/

CREATE Procedure [dbo].[PRC_PDD_MES] (@data_REF as datetime) AS
BEGIN

-- DECLARE @DTREF AS VARCHAR(8) SET @DTREF = CONVERT(varchar(8),@data_ref,112)

-- TTLS DO MES ********************************************* AUXILIA NOS RELATORIOS
-- DECLARE @DTREF  DATETIME  SET @DTREF = '20140630'
		DELETE	FROM	PDD_MES
				WHERE	DT_FECHA	= @data_REF

-- SP_HELP COMERCIAL_PRODUCAO_MES
/*
SELECT		CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))+'/'+CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE)), R1.NVL_RISCO , SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= '20160131'  AND R1.NVL_RISCO <> 'HH' -- AND R1.NVL_RISCO = 'A' 
AND DT_BASE BETWEEN '20150101' AND '20160430'
			GROUP	BY R1.NVL_RISCO, CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))+'/'+CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))

TRUNCATE TABLE PDD_MES
*/
-- DECLARE @data_REF DATETIME SET @data_REF = '20160430'
		INSERT	PDD_MES
		SELECT	@data_REF,
				CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01',-- DATA SAFRA PRODUCAO
				'V', --VEICULO,
				'', --AGENTE,
				SUM(SLD_INSCRITO), -- SALDO CARTEIRA 	 0.0			--  ********** 	VLR CARTEIRA	
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 , -- SLDO POR FX 				
				0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0   -- PRC

		FROM RATING_HISTORICO	R (NOLOCK) 
			WHERE	R.DT_FECHA= @data_REF  AND R.NVL_RISCO <> 'HH' -- AND R1.NVL_RISCO = 'A' 
--AND DT_BASE BETWEEN '20140101' AND @data_REF
			GROUP	BY CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'

			
--		GROUP	BY	PRODUTO
/*	
SELECT * FROM PDD_MES

DROP TABLE PDD_MES

CREATE TABLE PDD_MES (
DT_FECHA	SMALLDATETIME,
DT_SAFRA	SMALLDATETIME,
PRODUTO		VARCHAR(20),
AGENTE		VARCHAR(100),
SALDO		FLOAT,
-- SALDO POR FAIXA
SLDO_A	FLOAT,
SLDO_B	FLOAT,
SLDO_C	FLOAT,
SLDO_D	FLOAT,
SLDO_E	FLOAT,
SLDO_F	FLOAT,
SLDO_G	FLOAT,
SLDO_H	FLOAT,
PRC_A	FLOAT,
PRC_B	FLOAT,
PRC_C	FLOAT,
PRC_D	FLOAT,
PRC_E	FLOAT,
PRC_F	FLOAT,
PRC_G	FLOAT,
PRC_H	FLOAT
 )

CREATE INDEX PDD_MES_IDX1 ON PDD_MES (DT_FECHA,DT_SAFRA)

SELECT * FROM	PDD_MES		(NOLOCK) WHERE DT_FECHA='20160131'
SELECT * FROM	P123_HISTORICO		(NOLOCK) WHERE DT_FECHA='20150131'

SELECT * FROM CdcSantanaMicroCredito..CPARC  (NOLOCK) WHERE PANROPER IN ('612189611','552009741A','612090363A')
SELECT * FROM	P123_HISTORICO		(NOLOCK) WHERE DT_FECHA='20150131' AND NUM_OPE IN ('612189611','552009741A','612090363A')

SELECT		R1.NVL_RISCO , SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= '20150131' AND R1.NVL_RISCO <> 'HH'  
			GROUP	BY R1.NVL_RISCO

SELECT		CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))+'/'+CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE)), R1.NVL_RISCO , SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= '20160131'  AND R1.NVL_RISCO <> 'HH' -- AND R1.NVL_RISCO = 'A' 
AND DT_BASE BETWEEN '20150101' AND '20160430'
			GROUP	BY R1.NVL_RISCO, CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))+'/'+CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))


*/
-- SP_HELP 		COMERCIAL_PRODUCAO


		-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150228'
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150331'
-- SELECT TOP 10 * FROM	CdcSantanaMicroCredito..CPARC  (NOLOCK)	

-- FAIXAS DE RATING NVL_RISCO  *************		POR FAIXA
-- NAO PAGO  -- P1 E VENCIDO A 1MES DO FIM DA SAFRA
-- DECLARE @data_REF DATETIME SET @data_REF = '20160430'
		UPDATE	PDD_MES
		SET	SLDO_A	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD 
			FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'A' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

-- SELECT * FROM PDD_MES
		UPDATE	PDD_MES
		SET	SLDO_B	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'B' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_C	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
				WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'C' 
				GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_D	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'D' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_E	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'E' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_F	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'F' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_G	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'G' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

		UPDATE	PDD_MES
		SET	SLDO_H	= ISNULL(R.SLD , 0.0)
		FROM	(SELECT		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01' AS DT_SAFRA, 
							SUM(R1.SLD_INSCRITO) AS SLD FROM RATING_HISTORICO	R1 (NOLOCK) 
			WHERE	R1.DT_FECHA= @data_REF AND R1.NVL_RISCO <> 'HH'  AND R1.NVL_RISCO = 'H' 
			GROUP	BY 		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))+RIGHT('00'+CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE)),2)+'01'
						)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA


/* ERRO
UPDATE		PDD_MES
			SET		PRC_A	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_A / SALDO *100.0 END),
					PRC_B	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_B / SALDO *100.0 END),
					PRC_C	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_C / SALDO *100.0 END),
					PRC_D	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_D / SALDO *100.0 END),
					PRC_E	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_E / SALDO *100.0 END),
					PRC_F	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_F / SALDO *100.0 END),
					PRC_G	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_G / SALDO *100.0 END),
					PRC_H	= (CASE WHEN ISNULL(SALDO,0.0) = 0.0  THEN 0.0 ELSE SLDO_H / SALDO *100.0 END)
		WHERE		DT_FECHA	= @data_REF

SELECT * FROM	PDD_MES R1 (NOLOCK) WHERE	R1.DT_FECHA='20160630'
*/
-- DECLARE @data_REF DATETIME SET @data_REF ='20160630'
		UPDATE	PDD_MES
		SET		PRC_A	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_A / R.SALDO *100.0 END),
				PRC_B	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_B / R.SALDO *100.0 END),
				PRC_C	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_C / R.SALDO *100.0 END),
				PRC_D	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_D / R.SALDO *100.0 END),
				PRC_E	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_E / R.SALDO *100.0 END),
				PRC_F	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_F / R.SALDO *100.0 END),
				PRC_G	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_G / R.SALDO *100.0 END),
				PRC_H	= (CASE WHEN ISNULL(R.SALDO,0.0) = 0.0  THEN 0.0 ELSE R.SLDO_H / R.SALDO *100.0 END)
		FROM		  (SELECT	*
						FROM	PDD_MES R1 (NOLOCK)
						WHERE	R1.DT_FECHA= @data_REF 	)  AS R  -- RATING DA PDD
		WHERE		PDD_MES.DT_FECHA	= @data_REF
			AND		PDD_MES.DT_SAFRA	= R.DT_SAFRA

END
GO