Use sig
GO

/*
-- ativos
SELECT * FROM RR_PRJ_CONTRATO_2M 
WHERE DT_FECHA='20140731' AND NVL_RISCO<> 'HH'

-- prejuizo
SELECT * FROM RR_PRJ_CONTRATO_2M 
WHERE DT_FECHA='20140731' AND NVL_RISCO= 'HH'


-- mais dados, reprocessar os contratos projetar Rating
-- EXEC [RR_RATING_PROJETADO] '2014-07-31','2014-06-30','2014-07-01','2014-07-31'
-- SELECT * 	FROM rating_PROJETADO

-- bate
SELECT * FROM RR_PRJ_CONTRATO_2M d (nolock) ,
	(select * from rating_historico h1 (nolock)
		WHERE h1.DT_FECHA='20140731' AND h1.NVL_RISCO<> 'HH' ) as H
WHERE d.DT_FECHA='20140731' AND d.NVL_RISCO<> 'HH'
		and h.num_ope = d.num_ope
		and h.nvl_risco<> d.nvl_risco
		and d.nvl_risco <>'aa' -- sem o aa do diario

*/

-- PROC CALCULO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'RR_DIARIO_ANALITICO' AND type = 'P')
   DROP PROCEDURE [dbo].[RR_DIARIO_ANALITICO]
GO


CREATE Procedure [dbo].[RR_DIARIO_ANALITICO] (@data_ref as datetime) AS
BEGIN

-- LIMPA TABELAS AUXILIAR
TRUNCATE TABLE   AUX_CONTRATO_2M
TRUNCATE TABLE   AUX_CONTRATO_2M_HH
TRUNCATE TABLE   AUX_CONTRATO_2M_DIF


-- SELECT * INTO AUX_CONTRATO_2M     FROM RR_PRJ_CONTRATO_2M  WHERE 1=0
-- SELECT * INTO AUX_CONTRATO_2M_HH  FROM RR_PRJ_CONTRATO_2M  WHERE 1=0
-- SELECT * INTO AUX_CONTRATO_2M_DIF FROM RATING_HISTORICO    WHERE 1=0 
-- ALTER TABLE AUX_CONTRATO_2M_DIF ADD NVL_RISCO_SIGdiario VARCHAR(2)


-- PREENCHE COM O FECHAMENTO PROJETADO DO DIARIO NO FIM DO MES
-- ETAPA DE VERIFICACAO DE RATINGS DO FECHAMENTO

-- CONTRATOS ATIVOS
INSERT AUX_CONTRATO_2M
SELECT * FROM RR_PRJ_CONTRATO_2M (NOLOCK)
WHERE DT_FECHA=@data_ref AND NVL_RISCO<> 'HH'

-- prejuizo
INSERT AUX_CONTRATO_2M_HH
SELECT * FROM RR_PRJ_CONTRATO_2M (NOLOCK)
WHERE DT_FECHA=@data_ref AND NVL_RISCO= 'HH'

-- DIFERENCAS
INSERT		AUX_CONTRATO_2M_DIF
SELECT		H.*,D.NVL_RISCO
	FROM	RR_PRJ_CONTRATO_2M  D (NOLOCK) ,
			(SELECT		* 
				FROM	RATING_HISTORICO	H1 (NOLOCK)
				WHERE	H1.DT_FECHA = @data_ref AND H1.NVL_RISCO<> 'HH' ) AS H
	where	D.DT_FECHA = @data_ref  -- MES ATUAL
		AND H.NUM_OPE = D.NUM_OPE
		AND H.NVL_RISCO <> D.NVL_RISCO
		AND NOT (H.NVL_RISCO ='A' AND D.NVL_RISCO='AA') 
-- SOMENTE OS CONTRATOS COM RISCO DIFERENTE

-- SELECT * FROM AUX_CONTRATO_2M  
-- SP_HELP AUX_CONTRATO_2M  
-- SP_HELP AUX_CONTRATO_2M_DIF  
END
GO


-- SELECT * FROM  RATING_HISTORICO WHERE DT_FECHA='20140731' AND NUM_OPE= '612093708'
-- SELECT * FROM  RR_PRJ_CONTRATO_2M WHERE DT_FECHA='20140731' AND NUM_OPE= '612093708'
--612093719
