USE SIG

DROP TABLE PDD_RPT
CREATE TABLE PDD_RPT
	(	DT_FECHA		SMALLDATETIME,
--		DT_SAFRA		SMALLDATETIME,
		RPT				INT,
		CARTEIRA		INT,
		ORDEM			INT,
		DESCR			VARCHAR(100),

		M1		float,
		M2		float,
		M3		float,
		M4		float,
		M5		float,

		M6		FLOAT,
		M7		float,
		M8		float,
		M9		FLOAT,
		M10		FLOAT,

		M11		FLOAT,	
		M12		FLOAT,
		M13		FLOAT,
		M14		FLOAT,	
		COR_LINHA   varchar(3)
	)
CREATE INDEX PDD_RPT_IDX1 ON PDD_RPT  	(	DT_FECHA,	RPT, ORDEM,	DESCR)

CREATE TABLE PDD_MES (
DT_FECHA	SMALLDATETIME,
DT_SAFRA	SMALLDATETIME,
PRODUTO		VARCHAR(20),
AGENTE		VARCHAR(100),
SALDO		FLOAT,
-- SALDO POR FAIXA
SLDO_A	FLOAT,
SLDO_B	FLOAT,
SLDO_C	FLOAT,
SLDO_D	FLOAT,
SLDO_E	FLOAT,
SLDO_F	FLOAT,
SLDO_G	FLOAT,
SLDO_H	FLOAT,
PRC_A	FLOAT,
PRC_B	FLOAT,
PRC_C	FLOAT,
PRC_D	FLOAT,
PRC_E	FLOAT,
PRC_F	FLOAT,
PRC_G	FLOAT,
PRC_H	FLOAT
 )

CREATE INDEX PDD_MES_IDX1 ON PDD_MES (DT_FECHA,DT_SAFRA)

