USE sig
GO
/****** Object:  StoredProcedure [dbo].[SCR_credito_BASE]    Script Date: 02/05/2017  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- [SCR_credito_BASE] '20170101','20170120'
-- [SCR_credito_BASE] '20170201','20170430'

-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_PAGAS_RECEBIDAS' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_PAGAS_RECEBIDAS]
GO

CREATE PROCEDURE SCR_PAGAS_RECEBIDAS @DATADE SMALLDATETIME, @DATAATE SMALLDATETIME AS        
      
SELECT DISTINCT     
COD_LOJA AS PPCODORG4,      
NUM_PROP AS PPNRPROP,      
NUM_OPE AS PPNROPER,      
P.PPNOMECLI AS PPNOMECLI,      
CPF AS PPCGC,      
PPCODORG3 AS PPCODORG3,       
COD_USU AS PPUSUARIO,       
COD_PROD AS PPCODPRD,      
P.PPCODTAB AS PPCODTAB,      
PROP_DATABASE AS PPDTBASE,       
PROP_DATACAD AS PPDTCAD,       
VALOR_PRINCIPAL AS PPVLROPCZ,      
VALOR_LIQ7 AS PPVLRLIQ1,      
PROP_FIM AS PPPROPFIM,      
SITUACAO AS MPSIT,      
ESTEIRA AS TDDESCR,    
PPVLRENTR AS VLRENTR,  
DTLNC AS DTLNC,  
HORALNC AS HORALNC,  
COD_OPERADOR AS O6CODORG,  
O6DESCR AS O6DESCR  
FROM (SELECT * FROM PAGAS_RECEBIDAS (NOLOCK)        
  WHERE PROP_DATAREF = @DATAATE AND PROP_DATABASE BETWEEN @DATADE AND @DATAATE      
   AND ESTEIRA <>'DADOS BASICOS') AS P        
INNER JOIN (SELECT * FROM PROPWEBSMC..TPROD (NOLOCK)        
  WHERE TPCODCART IN (20,40,45,47,48,50,51,55,56,57,59,60,61,62,63,64,65,66,67,69,70,78,79,80,81,82,83,89,76)) AS PROD         
  ON PROD.TPCODPRD = COD_PROD        
  INNER JOIN PROPWEBSMC..CPROP (NOLOCK) ON PPNRPROP = NUM_PROP  
  INNER JOIN CDCSANTANAMICROCREDITO..TORG6 (NOLOCK) ON O6CODORG = PPCODORG6  