USE sig
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_ACIONAMENTO_CLIENTE' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_ACIONAMENTO_CLIENTE]
GO

CREATE PROCEDURE SCR_ACIONAMENTO_CLIENTE (@DT_DE AS SMALLDATETIME, @DT_ATE AS SMALLDATETIME, @AGNT AS VARCHAR(20)) AS

/*
CREATE INDEX ACIONAMENTO_INDEX1 ON AUX_ACIONAMENTO_CLIENTE (CONTRATO,CONTRATO_ORIG,SCORE,ATRASO,DT_ULT_PGTO,COD_AGENTE, COD_PROD)
*/

/*CREATE TABLE AUX_ACIONAMENTO_CLIENTE
(DT_BASE SMALLDATETIME,
CONTRATO VARCHAR(20), 
NOME VARCHAR(100),
CGC VARCHAR(50),
ENDERECO VARCHAR(200),
BAIRRO VARCHAR(100),
CIDADE VARCHAR(50),
CEP VARCHAR(20),
UF VARCHAR(5),
TELFIXO VARCHAR(20),
CELULAR VARCHAR(20),
FONE_COM VARCHAR(20),
PROFISSAO VARCHAR(30),
PLANO INT,
PARCELAS_PAGAS INT, 
DT_ULT_PGTO SMALLDATETIME,
RENDA FLOAT,
OCUPACAO VARCHAR(30),
VALOR_LIB FLOAT,
VALOR_FIN FLOAT,
COD_PROD VARCHAR(10), 
PRODUTO VARCHAR(50),
DATA_NASCTO SMALLDATETIME,
COD_AGENTE VARCHAR(10), 
AGENTE VARCHAR(50),
SCORE INT,
RENEG VARCHAR(10),
CLI_SANTANA VARCHAR(10),
DT_LIQ SMALLDATETIME,
CONTRATO_ORIG VARCHAR(20),
ATRASO INT)*/

--DELETA TABELA INTEIRA 00:00
TRUNCATE TABLE AUX_ACIONAMENTO_CLIENTE

--INSERE OPERAÇÕES 00:11
INSERT INTO AUX_ACIONAMENTO_CLIENTE(DT_BASE, CONTRATO, PLANO, PARCELAS_PAGAS, VALOR_LIB, VALOR_FIN, COD_PROD, COD_AGENTE, DT_LIQ)
SELECT OPDTBASE, OPNROPER, OPQTDDPARC, OPPARCLIQ, OPVLRFIN, OPVLROPCZ, OPCODPROD, OPCODORG3, OPDTLIQ FROM CDCSANTANAMICROCREDITO..COPER (NOLOCK) 
WHERE 1= 0+ CASE WHEN  @AGNT='99' THEN 1 -- TODOS OS AGENTES
		         WHEN  @AGNT<>'99' AND OPCODORG3 = @AGNT  THEN 1
			     ELSE  0 END	
ORDER BY OPDTBASE

--ATUALIZA CONTRATO ORIGINAL --00:36
UPDATE AUX_ACIONAMENTO_CLIENTE SET CONTRATO_ORIG = LEFT(CONTRATO,LEN(CONTRATO)-1)
WHERE RIGHT(CONTRATO,1) IN ('A','B','C','D','E','F','G','H')

--ATUALIZA CONTRATO QUANDO NÃO HÁ RENEG 00:00
UPDATE AUX_ACIONAMENTO_CLIENTE SET CONTRATO_ORIG = CONTRATO WHERE CONTRATO_ORIG IS NULL

--ATUALIZA SCORE 00:02
UPDATE AUX_ACIONAMENTO_CLIENTE SET SCORE = PPSCORING 
FROM PROPWEBSMC..CPROP (NOLOCK) 
WHERE PPNROPER = CONTRATO_ORIG

--DELETA SCORES MENOR QUE 500 OU NULO 00:00
DELETE FROM AUX_ACIONAMENTO_CLIENTE WHERE SCORE < 500 OR SCORE IS NULL

--DELETA NUMERO DE PARCELAS PAGAS MENOR QUE 36 NÃO LIQUIDADOS
DELETE FROM AUX_ACIONAMENTO_CLIENTE
WHERE DT_LIQ IS NULL AND PARCELAS_PAGAS <36

--DELETA LIQUIDADOS MENOR QUE DATA DE REFERENCIA
DELETE FROM AUX_ACIONAMENTO_CLIENTE
WHERE DT_LIQ IS NOT NULL AND (DT_BASE < @DT_DE OR DT_BASE > @DT_ATE)

--ATUALIZA DIAS DE ATRASO 00:22
UPDATE AUX_ACIONAMENTO_CLIENTE SET ATRASO = PA.ATRASO FROM (SELECT AVG(DATEDIFF(D,P.PADTVCTO,P.PADTLIQ)) AS ATRASO, PANROPER FROM CDCSANTANAMICROCREDITO..CPARC P (NOLOCK)
WHERE P.PADTLIQ IS NOT NULL AND P.PACNTRL = (SELECT MAX(P1.PACNTRL) FROM CDCSANTANAMICROCREDITO..CPARC P1 (NOLOCK) WHERE P1.PANROPER = P.PANROPER)
GROUP BY P.PANROPER) AS PA
WHERE PA.PANROPER = CONTRATO

--DELETA ATRASO MAIOR QUE 30 E NÃO LIQUIDADOS
DELETE FROM AUX_ACIONAMENTO_CLIENTE WHERE 
(ISNULL(ATRASO,0) <= 0 OR ISNULL(ATRASO,0) > 30) AND DT_LIQ IS NULL

--ATUALIZA DATA ULTIMO PAGAMENTO
UPDATE AUX_ACIONAMENTO_CLIENTE SET DT_ULT_PGTO = P.PADTLIQ FROM CDCSANTANAMICROCREDITO..CPARC P (NOLOCK)
WHERE P.PANRPARC = (SELECT MAX(P1.PANRPARC) FROM CDCSANTANAMICROCREDITO..CPARC P1 (NOLOCK) WHERE P1.PANROPER = P.PANROPER AND P1.PADTLIQ IS NOT NULL) AND
P.PACNTRL = (SELECT MAX(P2.PACNTRL) FROM CDCSANTANAMICROCREDITO..CPARC P2 (NOLOCK) WHERE P2.PANROPER = P.PANROPER AND P2.PANRPARC = P.PANRPARC AND P2.PADTLIQ IS NOT NULL)
AND CONTRATO = P.PANROPER

--ATUALIZA PRODUTO
UPDATE AUX_ACIONAMENTO_CLIENTE SET PRODUTO = TPDESCR 
FROM CDCSANTANAMICROCREDITO..TPROD (NOLOCK) WHERE TPCODPRD = COD_PROD

--ATUALIZA AGENTE
UPDATE AUX_ACIONAMENTO_CLIENTE SET AGENTE = O3DESCR
FROM CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) WHERE O3CODORG = COD_AGENTE

--ATUALIZA INDICADOR DE RENEG E CREDITAS
UPDATE AUX_ACIONAMENTO_CLIENTE SET RENEG = CASE WHEN RIGHT(CONTRATO,1) IN ('A','B','C','D','E','F','G','H') THEN 'SIM' ELSE 'NÃO' END,
CLI_SANTANA = CASE WHEN COD_AGENTE = '000146' THEN 'NÃO' ELSE 'SIM' END

--ATUALIZA DADOS DO CLIENTE
UPDATE AUX_ACIONAMENTO_CLIENTE SET
NOME = CLNOMECLI,
CGC = CLCGC,
ENDERECO = CLENDFIS + ' ' + CLNRENDFIS + ' ' + CLCMPTFIS,
BAIRRO = CLBAIFIS,
CIDADE = CLCIDFIS,
CEP = CLCEPFIS,
UF = CLUFFIS,
TELFIXO = CLFONEFIS,
CELULAR = CLDDDCEL + ' ' + CLCELULAR,
FONE_COM = CLFONECOM,
PROFISSAO = CLCARGO,
RENDA = CLRENDA,
OCUPACAO = CASE CLCODOCUP 
           WHEN '01' THEN 'CLT' 
           WHEN '02' THEN 'AUTONOMO' 
           WHEN '03' THEN 'APOSENTADO' 
           WHEN '04' THEN 'EMPRESARIO'
           WHEN '05' THEN 'PROFISSIONAL LIBERAL'
           ELSE 'S/ INFO' END,
DATA_NASCTO = CLDTNASC
FROM PROPWEBSMC..CCLIP (NOLOCK) INNER JOIN
PROPWEBSMC..CPROP (NOLOCK) ON CLCODCLI = PPCODCLI
WHERE PPNROPER = CONTRATO_ORIG

SELECT * FROM AUX_ACIONAMENTO_CLIENTE ORDER BY DT_BASE