
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

-- de ate veic
-- EXEC SCR_MAPACOMERCIAL  '20160101','20160131',1 ,'99'
-- EXEC SCR_MAPACOMERCIAL  '20160101','20160131',1 ,'30'
-- EXEC SCR_MAPACOMERCIAL  '20150101','20150131',1 --,2,0

IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_MAPACOMERCIAL' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_MAPACOMERCIAL
GO


CREATE Procedure [dbo].SCR_MAPACOMERCIAL (@DT_INI as datetime, @DT_FIM as datetime, @veiculo as int , @codAgente as varchar(10))
--, @rpt as int, @CART as int) 
AS
BEGIN



-- @DT3M as datetime, @data_ref as datetime,@veiculo as int

EXEC [CML_CALCULO_RPT]			@DT_INI , @DT_FIM  ,@veiculo

SELECT DT_FECHA, DESCR_VEIC, DESCRICAO, AGENTE, FX1, FX2,
			 FX3,  FX4, FX5, TTL, ORDEM_LINHA
 FROM		CML_RPT (NOLOCK)
	WHERE	DT_FECHA=@DT_FIM AND RPT=2 
		AND (AGENTE = @CodAGENTE OR @CodAGENTE='99')   -- INCLUIDO 28/10/16
	ORDER BY AGENTE,ORDEM_LINHA

-- SELECT * FROM  CML_RPT (NOLOCK) WHERE DT_FECHA='20150131' AND RPT=2 ORDER BY AGENTE,ORDEM_LINHA

END
GO