
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

-- de ate veic
-- EXEC SCR_MAPA_PDV_VEIC_LOJA  '20150531'

/*
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150430'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150331'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150228'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150131'


 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150131'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150228'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150331'
 EXEC [PDV_CALCULO_VEIC_3M_LOJA]  '20150430'

 EXEC SCR_MAPA_PDV_VEIC_LOJA  '20150430'
 EXEC SCR_MAPA_PDV_VEIC_LOJA  '20150531'
EXEC SCR_MAPA_PDV_VEIC_LOJA  '20150930'

*/
-- DELETE FROM CML_PDV  WHERE DT_FECHA= '20150524'


IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_MAPA_PDV_VEIC_LOJA' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_MAPA_PDV_VEIC_LOJA
GO


CREATE Procedure [dbo].SCR_MAPA_PDV_VEIC_LOJA (@DTREF as datetime, @CodAGENTE AS VARCHAR(10))
--, @rpt as int, @CART as int) 
AS
BEGIN
-- @DT3M as datetime, @data_ref as datetime,@veiculo as int
-- SELECT GETDATE()
-- SELECT  DATEDIFF(D,'20150524',GETDATE()) 


SELECT	AGENTE +' - '+ CODAGENTE AS AGENTE,
		ISNULL(QTDM3,0.0) AS QTDM3,
		ISNULL(QTDM2,0.0) AS QTDM2,
		ISNULL(QTDM1,0.0) AS QTDM1,

		ISNULL(LJ_3M,0.0)		AS LJ_3M,
		ISNULL(LJ_ATIVA,0.0)	AS LJ_ATIVA,
		ISNULL(GRAU,0.0)		AS GRAU,
		ISNULL(QTD_LJ_SAI,0.0)  AS QTD_LJ_SAI,
		ISNULL(PERDA,0.0)		AS PERDA

 FROM	CML_PDV_VEIC_LOJA (NOLOCK) WHERE DT_FECHA= @DTREF AND RPT=1
		AND		(CodAGENTE = @CodAGENTE	 OR  @CodAGENTE = '99')	-- ALTERADO 28/10/16
	
/*

SELECT * FROM  CML_PDV_VEIC_LOJA (NOLOCK) WHERE DT_FECHA='20150531'
SELECT DT_FECHA, DESCR_VEIC, DESCRICAO, AGENTE, FX1, FX2,
			 FX3,  FX4, FX5, TTL, ORDEM_LINHA
 FROM		CML_RPT (NOLOCK)
	WHERE	DT_FECHA=@DT_FIM AND RPT=2 
	ORDER BY AGENTE,ORDEM_LINHA
*/
-- SELECT * FROM  CML_RPT (NOLOCK) WHERE DT_FECHA='20150131' AND RPT=2 ORDER BY AGENTE,ORDEM_LINHA

END
GO