
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
use SIG
go

-- de ate veic
-- EXEC SCR_MAPA_PDV_VEIC  '20150531'
-- EXEC SCR_MAPA_PDV  '20150524',1

/*
 EXEC [PDV_CALCULO_VEIC_3M]  '20150131'
 EXEC [PDV_CALCULO_VEIC_3M]  '20150228'
 EXEC [PDV_CALCULO_VEIC_3M]  '20150331'
 EXEC [PDV_CALCULO_VEIC_3M]  '20150430'

 EXEC [PDV_CALCULO_VEIC_3M]  '20150731'

*/
-- DELETE FROM CML_PDV  WHERE DT_FECHA= '20150524'


IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_MAPA_PDV_VEIC' AND type = 'P')
   DROP PROCEDURE [dbo].SCR_MAPA_PDV_VEIC
GO


CREATE Procedure [dbo].SCR_MAPA_PDV_VEIC (@DTREF as datetime, @AGENTE AS VARCHAR(20))
--, @rpt as int, @CART as int) 
AS
BEGIN
-- @DT3M as datetime, @data_ref as datetime,@veiculo as int
-- SELECT GETDATE()
-- SELECT  DATEDIFF(D,'20150524',GETDATE()) 


SELECT	LOJA+' - '+CODLOJA AS LOJA,
		AGENTE +' - '+ CODAGENTE AS AGENTE,
		OPERADOR +' - '+ CODOPERADOR AS OPERADOR,
		ISNULL(QTDM3,0.0) AS QTDM3,
		ISNULL(VLRM3,0.0) AS VLRM3,
		ISNULL(TM3,0.0)	  AS TM3,
		ISNULL(QTDM2,0.0) AS QTDM2,
		ISNULL(VLRM2,0.0) AS VLRM2,
		ISNULL(TM2,0.0)   AS TM2,
		QTDM1, VLRM1, TM1

 FROM	CML_PDV_VEIC (NOLOCK) WHERE DT_FECHA= @DTREF AND RPT=1
	--	FILTRO INCLUIDO EM 16/6/17
	AND 1=0+CASE WHEN @AGENTE='99'		THEN 1
				 WHEN CODAGENTE=@AGENTE THEN 1
				 ELSE 0					END

/*

SELECT * FROM  CML_PDV_VEIC (NOLOCK) WHERE DT_FECHA='20150531'
SELECT DT_FECHA, DESCR_VEIC, DESCRICAO, AGENTE, FX1, FX2,
			 FX3,  FX4, FX5, TTL, ORDEM_LINHA
 FROM		CML_RPT (NOLOCK)
	WHERE	DT_FECHA=@DT_FIM AND RPT=2 
	ORDER BY AGENTE,ORDEM_LINHA
*/
-- SELECT * FROM  CML_RPT (NOLOCK) WHERE DT_FECHA='20150131' AND RPT=2 ORDER BY AGENTE,ORDEM_LINHA

END
GO