
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go


-- PROC CARGA FECHAMENTO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'PRC_COMERCIAL_VEIC_QUEBRAS' AND type = 'P')
   DROP PROCEDURE [dbo].[PRC_COMERCIAL_VEIC_QUEBRAS] 
GO

-- MENSAL
-- ***************************************
CREATE Procedure [dbo].[PRC_COMERCIAL_VEIC_QUEBRAS] 
		 (@DTREF  SMALLDATETIME )	AS  

BEGIN

--DECLARE @DTREF  AS SMALLDATETIME
--SP_HELP COMERCIAL_PRODUCAO_MES

-- LIMPAR O ANTERIOR
		DELETE	COMERCIAL_PRODUCAO_MES
--	SELECT * FROM COMERCIAL_PRODUCAO_MES (NOLOCK)
		WHERE	DT_FECHA = @DTREF 
			AND PRODUTO IN ('VL','VM','VU','VR','VRU')


-- INSERE VEIC POR TIPO NO PRODUCAO_MES  **************************
-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
-- DECLARE @DTREF DATETIME SET @DTREF ='20150228'
-- DECLARE @DTREF DATETIME SET @DTREF ='20150331'
		INSERT	COMERCIAL_PRODUCAO_MES
		SELECT	@DTREF,
				CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
					 --WHEN VEICULO= 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
					 ELSE  'V'+LEFT(VEICULO,1) END AS PRODUTO,
				COUNT(NUM_OPE),		-- QTDE
				SUM(VLR_OP),
				SUM(VLR_PRESENTE),
				SUM(VLR_RECEITA),
				SUM(VLR_FUTURO),
				SUM(VLR_TC),
				SUM(VLR_TARIFA),
				SUM(VLR_IOF),
				AVG(VLR_FIPE),
				AVG(CONVERT(INT,SCORE)),
				CASE	WHEN SUM(VLR_OP) = 0.0			THEN 0.0 
						ELSE ROUND(SUM(PRZ_X_VLR)   / SUM(VLR_OP) / 30.0, 0)	
						END,  -- PLANO_MEDIO antes: SUM(PLANO_X_VLR)/SUM(VLR_OP) ********* alterado 14/03/2016
				CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_X_VLR)/(SUM(VLR_OP)+SUM(RETORNO))	END, -- TAXA_MEDIA
				0.0, -- VARIACAO
				--	0.0,0.0, 
				--AVG(VLR_OP),				-- TKT_MEDIO ANTIGO, COM DIFERENCA
				SUM(VLR_PRESENTE)/COUNT(NUM_OPE),   -- TKT_MEDIO
				COUNT(DISTINCT CODLOJA)			,				-- QTDE_LJ
				0.0,0.0, 0.0,0.0,
				-- AVG(PRAZO), anterior ****************** alterado 14/03/2016
				ROUND(SUM(PRZ_X_VLR)   / SUM(VLR_OP) , 0) ,
				COUNT(DISTINCT CODCLI)  -- QTDE CLIENTES
				, 0.0 -- VAR_PROD
				-- incluido em Set/17
				,CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_CET_X_VLR)/(SUM(VLR_OP)+SUM(RETORNO))	END -- TAXA_MEDIA cet inclui 6/9/17 *******
				,CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_CET_X_VLR_am)/(SUM(VLR_OP)+SUM(RETORNO))	END -- TAXA_MEDIA cet inclui 6/9/17 *******
		FROM	COMERCIAL_PRODUCAO		(NOLOCK)
		WHERE	DT_FECHA	= @DTREF
			AND	NUM_OPE  <>'' AND PRODUTO='V' 
			AND VLR_OP>0.0
			AND VEICULO NOT IN ( 'RENEGOCIACAO', 'Refinanciamento', 'Refinanciamento Utilitarios')
		GROUP	BY	PRODUTO, 
				CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
									 ELSE  'V'+LEFT(VEICULO,1) END-- 'V'+LEFT(VEICULO,1)
-- SP_HELP 		COMERCIAL_PRODUCAO
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'

-- PROD LIQUIDA VEICULOS ***************************
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		PRODUCAO_LIQ  =  VLR_lib,
					TKT_MEDIO_LIQ  =  ISNULL((tkt ),0.0) 
FROM	(-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
SELECT		CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
									 ELSE  'V'+LEFT(VEICULO,1) END as prod,SUM(VLR_LIBERADO) AS VLR_lib, SUM(VLR_LIBERADO)/COUNT(*) AS tkt
								FROM COMERCIAL_PRODUCAO  (NOLOCK) 
						WHERE	DT_FECHA	= @DTREF
							AND PRODUTO='V'  
			AND VEICULO NOT IN ( 'RENEGOCIACAO', 'Refinanciamento', 'Refinanciamento Utilitarios')
AND VLR_OP>0.0
			group by CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
									 ELSE  'V'+LEFT(VEICULO,1) END ) AS V
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = PROD
				

		--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		--		ANO MEDIO BAIXO PQ CONSIDERA VLR NULOS ************** ALTERADO EM 16/3/17
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		--ANO_MEDIO  = VEIC.ANO ,
					SCORE =VEIC.SCORE,
					VLR_FIPE = VEIC.FIPE
			FROM  (
--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
SELECT		CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
									 ELSE  'V'+LEFT(VEICULO,1) END as prod,
								AVG(CONVERT(FLOAT,ANO_MODELO)) AS ANO, 
								SUM(CONVERT(FLOAT,SCORE) * VLR_PRESENTE)/SUM(VLR_PRESENTE) AS SCORE, 
								AVG(VLR_FIPE) AS FIPE
								FROM COMERCIAL_PRODUCAO  (NOLOCK) 
						WHERE	DT_FECHA	= @DTREF
							AND PRODUTO='V' AND VLR_OP > 0.0 
			AND VEICULO NOT IN ( 'RENEGOCIACAO', 'Refinanciamento', 'Refinanciamento Utilitarios')
GROUP BY   CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
									 ELSE  'V'+LEFT(VEICULO,1) END
) AS VEIC
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = PROD

		--		ANO MEDIO BAIXO PQ CONSIDERA VLR NULOS ************** INCLUIDO EM 16/3/17
		--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		ANO_MEDIO  = VEIC.ANO
			FROM  (
				--		DECLARE @DTREF DATETIME SET @DTREF ='20161130'
				SELECT		CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
													 ELSE  'V'+LEFT(VEICULO,1) END as prod,
												AVG(CONVERT(FLOAT,ANO_MODELO)) AS ANO, 
												SUM(CONVERT(FLOAT,SCORE) * VLR_PRESENTE)/SUM(VLR_PRESENTE) AS SCORE, 
												AVG(VLR_FIPE) AS FIPE
												FROM COMERCIAL_PRODUCAO  (NOLOCK) 
										WHERE	DT_FECHA	= @DTREF
											AND PRODUTO='V' AND VLR_OP > 0.0 
							AND VEICULO NOT IN ( 'RENEGOCIACAO', 'Refinanciamento', 'Refinanciamento Utilitarios')
							AND ANO_MODELO >''  -- 3/17 para nao afetar a media
				GROUP BY   CASE WHEN 'V'+LEFT(VEICULO,1)='VA' OR 'V'+LEFT(VEICULO,1)='VL' THEN 'VL'
													 ELSE  'V'+LEFT(VEICULO,1) END
				) AS VEIC
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = PROD


 
	-- AJUSTA MEDIA LOJA
		--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		--		DECLARE @DTREF DATETIME SET @DTREF ='20150228'
--				DECLARE @DTREF DATETIME SET @DTREF ='20150331'
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		MEDIA_LJ  =  CASE WHEN ISNULL(M.Q,0.0)=0.0 THEN 0.0 ELSE M.VLR/M.Q END
--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
FROM (		SELECT		PRODUTO,AVG(VLR_PRESENTE) AS VLR,
								AVG(QTDE_LJ) AS Q FROM COMERCIAL_PRODUCAO_MES  (NOLOCK) 
						WHERE	DT_FECHA	= @DTREF
	AND PRODUTO IN ('VL','VM','VR','VU')
						GROUP BY PRODUTO 					
) AS M

			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = M.PRODUTO



-- *************************************************************************
--Refinanciamento
--Refinanciamento Utilitarios


		INSERT	COMERCIAL_PRODUCAO_MES
		SELECT	@DTREF,
				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END AS PRODUTO,
				COUNT(NUM_OPE),		-- QTDE
				SUM(VLR_OP),
				SUM(VLR_PRESENTE),
				SUM(VLR_RECEITA),
				SUM(VLR_FUTURO),
				SUM(VLR_TC),
				SUM(VLR_TARIFA),
				SUM(VLR_IOF),
				AVG(VLR_FIPE),
				AVG(CONVERT(INT,SCORE)),
				CASE	WHEN SUM(VLR_OP) = 0.0			THEN 0.0					-- alterado 14/03/2016 ********
						ELSE ROUND(SUM(PRZ_X_VLR)   / SUM(VLR_OP) / 30.0, 0) END,  -- PLANO_MEDIO : SUM(PLANO_X_VLR)/SUM(VLR_OP)
				CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_X_VLR)/(SUM(VLR_OP)+SUM(RETORNO))	END, -- TAXA_MEDIA
				0.0, -- VARIACAO
				--	0.0,0.0, 
				--AVG(VLR_OP),				-- TKT_MEDIO ANTIGO, COM DIFERENCA
				SUM(VLR_PRESENTE)/COUNT(NUM_OPE),   -- TKT_MEDIO
				COUNT(DISTINCT CODLOJA)			,				-- QTDE_LJ
				0.0,0.0, 0.0,0.0,
				--AVG(PRAZO),		-- alterado 14/03/2016 ********
				ROUND(SUM(PRZ_X_VLR)   / SUM(VLR_OP) , 0) ,
				COUNT(DISTINCT CODCLI)  -- QTDE CLIENTES
				, 0.0 -- VAR_PROD
				,CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_CET_X_VLR)/(SUM(VLR_OP)+SUM(RETORNO))	END -- TAXA_MEDIA cet inclui 6/9/17 *******
				,CASE	WHEN SUM(VLR_OP)+SUM(RETORNO) = 0.0				THEN 0.0 
						ELSE SUM(TX_CET_X_VLR_am)/(SUM(VLR_OP)+SUM(RETORNO))	END -- TAXA_MEDIA cet inclui 6/9/17 *******
		FROM	COMERCIAL_PRODUCAO		(NOLOCK)
		WHERE	DT_FECHA	= @DTREF
			AND	NUM_OPE  <>'' AND PRODUTO='V' AND VEICULO <> 'RENEGOCIACAO'
			AND VLR_OP > 0.0
			AND VEICULO  IN ('Refinanciamento','Refinanciamento Utilitarios')
		GROUP	BY	PRODUTO, 
				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END
-- SP_HELP 		COMERCIAL_PRODUCAO
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'

-- PRODUCAO LIQUIDA RENEG **************************
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		PRODUCAO_LIQ  =  VLR_lib,
					TKT_MEDIO_LIQ  =  ISNULL((tkt ),0.0) 
FROM	(-- DECLARE @DTREF DATETIME SET @DTREF ='20150131'
SELECT		
				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END
						 as prod,
				SUM(VLR_LIBERADO) AS VLR_lib, SUM(VLR_LIBERADO)/COUNT(*) AS tkt
								FROM COMERCIAL_PRODUCAO  (NOLOCK) 
						WHERE	DT_FECHA	= @DTREF
						AND PRODUTO='V'  AND VEICULO <> 'RENEGOCIACAO' AND VLR_OP>0.0
						AND VEICULO  IN ('Refinanciamento','Refinanciamento Utilitarios')
			group by 
				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END
							 ) AS V
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = PROD
				

		--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		ANO_MEDIO  = VEIC.ANO ,
					SCORE =VEIC.SCORE,
					VLR_FIPE = VEIC.FIPE
			FROM  (
--		DECLARE @DTREF DATETIME SET @DTREF ='20150131'
SELECT		
				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END
			 as prod,
								AVG(CONVERT(FLOAT,ANO_MODELO)) AS ANO, 
								SUM(CONVERT(FLOAT,SCORE) * VLR_PRESENTE)/SUM(VLR_PRESENTE) AS SCORE, 
								AVG(VLR_FIPE) AS FIPE
								FROM COMERCIAL_PRODUCAO  (NOLOCK) 
						WHERE	DT_FECHA	= @DTREF
							AND PRODUTO='V' AND VLR_OP > 0.0 
						 AND VEICULO <> 'RENEGOCIACAO' AND VLR_OP>0.0
						AND VEICULO  IN ('Refinanciamento','Refinanciamento Utilitarios')
GROUP BY   				CASE WHEN VEICULO='Refinanciamento' THEN  'VR'
					 WHEN VEICULO='Refinanciamento Utilitarios' THEN  'VRU'
					 ELSE  'VR'	 END

) AS VEIC
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = PROD


-- ***************************************************************** Veic - score
		UPDATE		COMERCIAL_producao_MES
			SET		SCORE  =  PROD.SCORE
FROM (SELECT	P.PRODUTO, SUM(CONVERT(FLOAT,SCORE) * VLR_PRESENTE)/SUM(VLR_PRESENTE) AS SCORE
									FROM	COMERCIAL_producao  P (NOLOCK)
									WHERE	P.DT_FECHA=@DTREF 
										AND LEFT(PRODUTO,1)  ='V'
										AND P.VLR_OP >0.0
GROUP BY PRODUTO) AS PROD
			WHERE	COMERCIAL_producao_MES.DT_FECHA	= @DTREF 
				AND LEFT(COMERCIAL_producao_MES.PRODUTO,1)  ='V'
					AND PROD.PRODUTO=COMERCIAL_producao_MES.PRODUTO 
					AND COMERCIAL_producao_MES.PRODUTO  IN ('VL','VU','VM','VR','VRU')

-- AJUSTEI O TTL VEICULOS PRA BATER COM A SOMA POR TIPO DE VEIC ***************** INCLUI 20/02/17
		UPDATE		COMERCIAL_PRODUCAO_MES
			SET		PRODUCAO_LIQ  =  VLR_lib
		FROM	(-- DECLARE @DTREF DATETIME SET @DTREF ='20170131'
					SELECT			SUM(VLR_LIBERADO) AS VLR_lib
													FROM COMERCIAL_PRODUCAO  (NOLOCK) 
											WHERE	DT_FECHA	= @DTREF
											AND PRODUTO='V'  --AND VEICULO <> 'RENEGOCIACAO' AND VLR_OP>0.0	--AND VEICULO  IN ('Refinanciamento','Refinanciamento Utilitarios')
												 ) AS V
			WHERE	COMERCIAL_PRODUCAO_MES.DT_FECHA	= @DTREF
				AND COMERCIAL_PRODUCAO_MES.PRODUTO  = 'V'



END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
