USE SIG --[SANTANA]
GO

/*
CREATE TABLE TB_COMISSAO(
COD_AGENTE VARCHAR(10),
AGENTE VARCHAR(50),
OPERACAO VARCHAR(20),
ICM FLOAT,
PRC_REPASSE FLOAT,
VLR_LIQUIDO FLOAT,
VLR_OPERADO FLOAT,
COD_PRODUTO VARCHAR(10),
PRODUTO VARCHAR(100),
COMISSAO FLOAT)
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS 
WHERE NAME = 'SCR_COMISSAO' AND TYPE = 'P')
DROP PROCEDURE [DBO].SCR_COMISSAO
GO

CREATE PROCEDURE [DBO].SCR_COMISSAO (                             
@DT_INI SMALLDATETIME,                    
@DT_FIM SMALLDATETIME) AS

--------------------------------------------------------------------CALCULO ICM------------------------------------------------------------
DELETE FROM TB_COMISSAO

DECLARE @DT_DE AS SMALLDATETIME
DECLARE @DT_ATE AS SMALLDATETIME
 
SET @DT_DE = CONVERT(CHAR(4),DATEPART(YYYY,@DT_INI))+            
   RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MM,@DT_INI))),2)+ '01'

SET @DT_ATE = CONVERT(CHAR(4),DATEPART(YYYY,@DT_FIM))+            
   RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MM,@DT_FIM))),2)+ '01'

SET @DT_ATE = DATEADD(D,-1,@DT_ATE)

SELECT OPCODORG3, CAST(SUM(OPVLROPCZ) AS NUMERIC(15,2)) AS OPVLRFIN, CAST(0.0 AS NUMERIC(15,2)) AS META, CAST(0.0 AS NUMERIC(15,2)) AS ICM INTO #TB_ICM FROM CDCSANTANAMICROCREDITO..COPER (NOLOCK)
WHERE OPDTBASE BETWEEN @DT_DE AND @DT_ATE
AND OPCODOP IN (SELECT M.COD_MODA                      
FROM TTIPO_PROD T (NOLOCK), TMODA_TIPO_PROD M (NOLOCK)                        
WHERE M.COD_PROD = T.COD_PROD                       
AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
AND T.COD_PROD IN('V'))     
AND (ISNULL(OPESTORNO,'') <>'S')
GROUP BY OPCODORG3

UPDATE #TB_ICM SET META = VLR FROM 
TB_META_PROMOTORA WHERE COD_AGENTE = OPCODORG3
AND MONTH(DT_REF) = MONTH(@DT_DE) AND YEAR(DT_REF) = YEAR(@DT_DE)

UPDATE #TB_ICM SET ICM = (OPVLRFIN/META)*100.00 WHERE META > 0.0
--------------------------------------------------------------------FIM CALCULO ICM---------------------------------------------------------
--------------------------------------------------------------------CALCULO REPASSE---------------------------------------------------------
INSERT INTO TB_COMISSAO
SELECT DISTINCT OPCODORG3, O3DESCR, OPNROPER, '' AS ICM, '' AS REPASSE, OPVLRFIN, OPVLROPCZ, OPCODOP, '' AS PRODUTO, '' AS COMISSAO 
FROM CDCSANTANAMICROCREDITO..COPER (NOLOCK)
INNER JOIN CDCSANTANAMICROCREDITO..TORG3 (NOLOCK) ON OPCODORG3 = O3CODORG
INNER JOIN CDCSANTANAMICROCREDITO..TPROD (NOLOCK) ON OPCODPROD = TPCODPRD
WHERE OPDTBASE BETWEEN @DT_INI AND @DT_FIM
AND OPCODOP IN (SELECT M.COD_MODA                      
FROM TTIPO_PROD T (NOLOCK), TMODA_TIPO_PROD M (NOLOCK)                        
WHERE M.COD_PROD = T.COD_PROD                       
AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
AND T.COD_PROD IN('V'))     
AND (ISNULL(OPESTORNO,'') <>'S')
AND O3DESCR NOT LIKE '%SHOP%'

UPDATE TB_COMISSAO SET PRODUTO = DESCR_TIPO 
FROM TTIPO_PROD T (NOLOCK), TMODA_TIPO_PROD M (NOLOCK)                        
WHERE M.COD_PROD = T.COD_PROD                       
AND T.COD_MODALIDADE = M.COD_MODALIDADE                       
AND T.COD_PROD IN('V')
AND COD_PRODUTO = COD_MODA

UPDATE TB_COMISSAO SET COD_AGENTE = A.CODAGENTE FROM 
(SELECT CODAGENTE, OPNROPER FROM TB_COMISSAO (NOLOCK) 
INNER JOIN CDCSANTANAMICROCREDITO..COPER (NOLOCK) ON OPNROPER = OPERACAO
LEFT  JOIN USUARIO_SVC (NOLOCK) ON CAST(CODOPERADOR AS INT)= CAST(OPCODORG6 AS INT)
WHERE COD_AGENTE = '000164') AS A
WHERE A.OPNROPER = TB_COMISSAO.OPERACAO

UPDATE TB_COMISSAO SET AGENTE = O3DESCR 
FROM CDCSANTANAMICROCREDITO..TORG3 (NOLOCK)
WHERE CAST(COD_AGENTE AS INT) = CAST(O3CODORG AS INT)

DELETE FROM TB_COMISSAO WHERE AGENTE LIKE '%SHOP%'

UPDATE TB_COMISSAO SET ICM = A.ICM
FROM #TB_ICM A WHERE CAST(COD_AGENTE AS INT) = CAST(OPCODORG3 AS INT)

UPDATE TB_COMISSAO SET PRC_REPASSE = 
CASE WHEN ICM < 70.00 THEN 0.050
WHEN ICM BETWEEN 70.00 AND 75.00 THEN 0.055
ELSE 0.060 END
--------------------------------------------------------------------FIM CALCULO REPASSE---------------------------------------------------------
--------------------------------------------------------------------CALCULO COMISSÃO------------------------------------------------------------
UPDATE TB_COMISSAO SET COMISSAO = PRC_REPASSE * VLR_LIQUIDO

UPDATE TB_COMISSAO SET COMISSAO = 550
WHERE COMISSAO < 550

UPDATE TB_COMISSAO SET COMISSAO = 1000
WHERE COMISSAO > 1000
AND PRODUTO IN ('Motos', 'Leves','Refinanciamento')

UPDATE TB_COMISSAO SET COMISSAO = 3000
WHERE COMISSAO > 3000
AND PRODUTO IN ('Caminhão','Refinanciamento Utilitarios','Escolar (Utilitários)','Utilitario')

SELECT * FROM TB_COMISSAO
ORDER BY ICM
--------------------------------------------------------------------FIM CALCULO COMISSÃO---------------------------------------------------------