
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go


SELECT * FROM  TEMP_RR (NOLOCK)
SP_HELP RR_AUX_CONTRATO_2M


sp_help TEMP_RR
DROP   TABLE TEMP_RR
CREATE TABLE TEMP_RR   (
DT_FECHA	smalldatetime,
NUM_OPE	varchar	(50),
AGENTE	varchar	(6),
COBRADORA	varchar	(6),
NVL_RISCO	varchar	(50),
NVL_RISCO_ANT	varchar	(50),
SLD_INSCRITO	float	,
SLD_INSCRITO_ANT	float,
Atraso	int,
Atraso_ANT	int,
PARC	int,
PARC_ANT	int	,
VENCTO	smalldatetime,
VENCTO_ANT	smalldatetime  ,
VLR_PDD		FLOAT,
VLR_PDD_ANT	FLOAT,
NUM_OPE_ANT varchar	(50)
)


ALTER TABLE TEMP_RR ADD   VLR_PDD		FLOAT
ALTER TABLE TEMP_RR ADD   VLR_PDD_ANT	FLOAT

sp_help  DRE_ATRASO
DROP   TABLE DRE_ATRASO
CREATE TABLE DRE_ATRASO (
DT_FECHA			DATETIME,
OPNROPER			VARCHAR(20),
CONTRATOoriginal	VARCHAR(20),	
DESCR_TIPO			VARCHAR(30),
NVL_RISCO		VARCHAR(2),
LOAN			FLOAT,
LIBERADO			FLOAT,
TABELADO			FLOAT,
OPQTDDPARC		INT,
PDECOR			INT,
PARC			INT,
CLCEPFIS		VARCHAR(10),
CLCIDFIS		VARCHAR(100),
CLUFFIS			VARCHAR(5),
CLRENDA			FLOAT,
OCUPACAO		VARCHAR(10),
IDADE			INT,
ClSexo			VARCHAR(10),
ClESTciv		INT,
TIPO_CASA		VARCHAR(10),
LojaCod			VARCHAR(20),
LojaCEP			VARCHAR(10),
LojaCIDADE		VARCHAR(50),
LojaUF			VARCHAR(2),
AGENTEcod		VARCHAR(20),
OperadorCod		VARCHAR(20),

TC				FLOAT,
OPTAC			FLOAT,
PASLDXMLT		FLOAT,
PASLDXMR		FLOAT,
PDD				FLOAT,
VLR_PDD_ATU		FLOAT,
VLR_PDD_ANT		FLOAT,
NVL_RISCO_ANT	VARCHAR(2),
VLR_PARCELA		FLOAT,
VLR_RETORNO		FLOAT,
VLR_RECEITA		FLOAT,
VLR_IOF			FLOAT,
VLR_ISS			FLOAT,
VLR_PIS			FLOAT,
VLR_COFINS		FLOAT,
VLR_CAPTACAO	FLOAT,

vlr_IRPJ	FLOAT,
VLR_CSSL	FLOAT,
VLR_CRED_TRIB	FLOAT,
OUTRAS_TX		FLOAT,

REC_APLIC_SLDO_CX FLOAT,
REPASSE_AGENTE_6P	FLOAT,
RETORNO_LOJA	FLOAT,
REPASSE_AGENTE_PROMOT	FLOAT,
DESP_CAPT_SLD_CX	FLOAT,
DESP_CAPT_OPER		FLOAT,
DESP_PESSOAL_VDA	FLOAT,
DESP_PESSOAL_SUP	FLOAT,

SLDO_INSCRITO	float,
PROPORCAO_CARTEIRA	float,
VLR_COMISSAO	float,
VLR_COMISSAO_TERCO_AV	float,
VLR_COMISSAO_DIFERIDA_36AVOS	float,
VLR_FINANCIADO	float,
DT_BASE	datetime,
vlr_comissao_diferida_pzo_Op	float,
COMISSAO_AV	float,
SLD_DIFERIR_2_3	float)

-- CDC (Tarifas)  Multa  Juros de Atraso

CREATE INDEX  DRE_ATRASO_IDX1 ON DRE_ATRASO (DT_FECHA,OPNROPER )
CREATE INDEX  DRE_ATRASO_IDX2 ON DRE_ATRASO (DT_FECHA,NVL_RISCO )


ALTER TABLE  DRE_ATRASO ADD COMISSAO_2_3 FLOAT
ALTER TABLE  DRE_ATRASO ADD VLR_COMISSAO_15 FLOAT
ALTER TABLE  DRE_ATRASO ADD DESPESA_CONTRATO FLOAT

SP_HELP DRE_ATRASO

ALTER TABLE  DRE_ATRASO ADD DESPESA_CADASTRO FLOAT
ALTER TABLE  DRE_ATRASO ADD DESPESA_COMERCIAL FLOAT

ALTER TABLE  DRE_ATRASO ADD CM_TARIFA FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_PROVISAO FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_TARIFA_DESPESA FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_IMOBILIZADO FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_DESP_PESSOAL FLOAT

ALTER TABLE  DRE_ATRASO ADD CM_DIRETORIA FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ALUGUEL FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ADM_FIXA FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ADM_VAR	FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ADM_OUTRAS_TTL2 FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ADM_OUTRAS_TTL3 FLOAT
ALTER TABLE  DRE_ATRASO ADD CM_ADM_VAR_COM	FLOAT

--ALTER TABLE  DRE_ATRASO ADD CM_ADM_TTL2 FLOAT ALTER TABLE  DRE_ATRASO ADD CM_ADM_TTL3 FLOAT
ALTER TABLE  DRE_ATRASO ADD CUSTO_COBRANCA FLOAT
ALTER TABLE  DRE_ATRASO ADD MARGEM_CAIXA FLOAT
ALTER TABLE  DRE_ATRASO ADD DESPESA_ATRASO FLOAT


ALTER TABLE  DRE_ATRASO ADD VLR_IMPOSTOS FLOAT
ALTER TABLE  DRE_ATRASO ADD VLR_LUCRO_BRUTO FLOAT
ALTER TABLE  DRE_ATRASO ADD CUSTO_MANUTENCAO FLOAT

ALTER TABLE  DRE_ATRASO ADD VLR_RECEITA_ATRASO FLOAT

ALTER TABLE  DRE_ATRASO ADD  RWA_VEICULOS  FLOAT

/*
VLR_LUCRO_BRUTO
CUSTO_MANUTENCAO 
vlr_IRPJ
VLR_CSSL
VLR_ISS
VLR_CRED_TRIB
OUTRAS_TX		*/

SP_HELP DRE_ATRASO

-- incluir dados SET-15
ALTER TABLE  DRE_ATRASO ADD  ANO_VEICULO	VARCHAR(20)
ALTER TABLE  DRE_ATRASO ADD  MODELO			VARCHAR(20)
ALTER TABLE  DRE_ATRASO ADD  SCORE			VARCHAR(20)

ALTER TABLE  DRE_ATRASO ADD  VLR_RECEITA_FIN  FLOAT


SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
