
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go
/*
-- 2010
-- 25 soh HH
SELECT min(dt_fecha) FROM RATING_HISTORICO (NOLOCK) where dt_fecha>='20090101'
SELECT min(dt_fecha) FROM RATING_HISTORICO (NOLOCK) where dt_fecha>='20100101'
SELECT min(dt_ref) FROM RATING_HISTORICO (NOLOCK) 
SELECT count(*) FROM RATING_HISTORICO (NOLOCK) where dt_fecha='20100129'
SELECT count(*) FROM RATING_HISTORICO (NOLOCK) where dt_fecha='20100226'
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20100220' and '20100331'
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20101020' and '20101231'
-- 2011
-- soh HH
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20110120' and '20110630'
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20110630' and '20111231'
SELECT DT_REF,COUNT(*) FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20110101' and '20111231'
GROUP BY DT_REF
-- tem dez-11

--2012 SOH HH, TEM DEZ 2012
-- JAN SOH HH
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20120120' and '20120131'
-- FEV SOH HH
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20120201' and '20120229'

SELECT DT_REF,COUNT(*) FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20120101' and '20121231'
GROUP BY DT_REF


-- DEZ TEM RATING
SELECT * FROM RATING_HISTORICO (NOLOCK) where dt_fecha between '20121201' and '20121231'

*/
-- 2012  **************************************************************
DECLARE @DTREF DATETIME
SET	@DTREF ='20121231'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF


-- 2013  **************************************************************
--
  DECLARE @DTREF DATETIME
SET	@DTREF ='20130131'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20130131'
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- FEV13  -- favor ver se não é ano bisexto 29
SET	@DTREF ='20130228'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

--  DECLARE @DTREF DATETIME  -- MAR14
SET	@DTREF ='20130331'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- select datepart(dw,'20140430')
--  DECLARE @DTREF DATETIME  -- ABR14
SET	@DTREF ='20130430'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
 --SELECT * FROM DRE_ATRASO (NOLOCK)

--DECLARE @DTREF DATETIME  -- MAI14
SET	@DTREF ='20130531'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
--  DECLARE @DTREF DATETIME   SET	@DTREF ='20140531'
 EXEC DRE_DESPESAS_ANALITICO @DTREF

--DECLARE @DTREF DATETIME  -- JUN14
SET	@DTREF ='20130630'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF


--		DECLARE @DTREF DATETIME  -- JUL13
SET	@DTREF ='20130731'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF

-- PB AGO
--DECLARE @DTREF DATETIME  -- AGO13
SET	@DTREF ='20130831'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF


--DECLARE @DTREF DATETIME  -- SET13
SET	@DTREF ='20130930'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF

--DECLARE @DTREF DATETIME  -- OUT13
SET	@DTREF ='20131031'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF


--DECLARE @DTREF DATETIME  -- NOV13
SET	@DTREF ='20131130'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF

--DECLARE @DTREF DATETIME  -- DEZ13
SET	@DTREF ='20131231'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF



-- 2014  **************************************************************
DECLARE @DTREF DATETIME
SET	@DTREF ='20140131'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20140131'
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- FEV14
SET	@DTREF ='20140228'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- MAR14
SET	@DTREF ='20140331'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- select datepart(dw,'20140430')
-- DECLARE @DTREF DATETIME  -- ABR14
SET	@DTREF ='20140430'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- MAI14
SET	@DTREF ='20140531'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
--  DECLARE @DTREF DATETIME   SET	@DTREF ='20140531'
 EXEC DRE_DESPESAS_ANALITICO @DTREF
/*
 SELECT * FROM DRE_ATRASO (NOLOCK)
SELECT DATEPART(DW,'2014-05-31')
SELECT * FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA='2014-05-30'
*/

-- DECLARE @DTREF DATETIME  -- JUN14
SET	@DTREF ='20140630'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)



-- DECLARE @DTREF DATETIME  -- JUL14
SET	@DTREF ='20140731'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)	WHERE	DT_FECHA = '20140731'

-- PB AGO
-- DECLARE @DTREF DATETIME  -- AGO14
SET	@DTREF ='20140831'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO  '20140831'
-- SELECT * FROM DRE_ATRASO (NOLOCK)	WHERE	DT_FECHA = '20140831'
-- SELECT * FROM rating_historico (NOLOCK)	WHERE	DT_FECHA = '20140831'


-- DECLARE @DTREF DATETIME  -- SET14
SET	@DTREF ='20140930'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- OUT14
SET	@DTREF ='20141031'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)


-- DECLARE @DTREF DATETIME  -- NOV14
SET	@DTREF ='20141130'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

-- DECLARE @DTREF DATETIME  -- DEZ14
SET	@DTREF ='20141231'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
 --SELECT * FROM DRE_ATRASO (NOLOCK)


-- 2015  **************************************************************
use sig
DECLARE @DTREF DATETIME
SET	@DTREF ='20150131'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)
----2 MIN 7 SEG PROD SEM GERENCIAL
----HOMOLOG ANTIGA DRE

--DECLARE @DTREF DATETIME
SET	@DTREF ='20150228'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
--   DECLARE @DTREF DATETIME  SET	@DTREF ='20150228'
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)

--USE SIG
--   DECLARE @DTREF DATETIME
SET	@DTREF ='20150331'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO @DTREF
-- SELECT * FROM DRE_ATRASO (NOLOCK)
 
--WHERE OPNROPER='552012128'
--SELECT * FROM CDCSANTANAMicroCredito..COPER O (NOLOCK) WHERE OPNROPER='552012128'

-- ABRIL-15

 EXEC DRE_RESULTADO_ANALITICO '20150430'
 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20150430'
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20150430'
--  SELECT * FROM DRE_ATRASO (NOLOCK)


-- MAI-15
-- DECLARE @DT DATETIME
 EXEC DRE_RESULTADO_ANALITICO '20150531'
 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20150531'
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20150531'
--  SELECT * FROM DRE_ATRASO (NOLOCK)

-- JUN-15
--
-- USE SIG
-- DECLARE @DT DATETIME
 EXEC DRE_RESULTADO_ANALITICO '20150630'
 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20150630'
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20150630'
--  SELECT * FROM DRE_ATRASO (NOLOCK)

USE SIG

DUMP TRANSACTION SIG WITH NO_LOG

dbcc ShrinkFile(SIV_log, 1)

-- 2015  ************************************************************** 2o sem
use sig
DECLARE @DTREF DATETIME
SET	@DTREF ='20150731'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
 EXEC DRE_DESPESAS_ANALITICO @DTREF

DECLARE @DTREF DATETIME
SET	@DTREF ='20150831'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
 EXEC DRE_DESPESAS_ANALITICO @DTREF

-- EXEC DRE_DESPESAS_ANALITICO '20150831'
--USE SIG  set
--   DECLARE @DTREF DATETIME
SET	@DTREF ='20150930'
 EXEC DRE_RESULTADO_ANALITICO @DTREF
 EXEC DRE_FUNCAO_ATRASO_ANALITICO @DTREF
 EXEC DRE_DESPESAS_ANALITICO @DTREF
 
-- OUT
 EXEC DRE_RESULTADO_ANALITICO '20151031'
 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20151031'
 EXEC DRE_DESPESAS_ANALITICO '20151031'


-- NOV-15
-- DECLARE @DT DATETIME
 EXEC DRE_RESULTADO_ANALITICO '20151130'
 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20151130'
-- RATEIO PELO CONTABIL
 EXEC DRE_DESPESAS_ANALITICO '20151130'
--  SELECT * FROM DRE_ATRASO (NOLOCK)



/*
-- declare @DTREF DATETIME SET @DTREF ='20150531'
SELECT 
		DESCR_TIPO	AS SEGMENTO,
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_FECHA))),2)+'/'+ 
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_FECHA))),2) +'/'+
		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_FECHA))		AS DATA_BASE,
		ISNULL(CONTRATOoriginal,OPNROPER ) AS CONTRATO_ORIGINAL,
		NVL_RISCO	AS NIVEL_RISCO, 
		LOAN		AS LOAN_TO_VALUE,
		OPQTDDPARC	AS PRAZO_CONTRATO,
		PDECOR		AS NUMERO_PARCELA,
		CLCEPFIS	AS CEP_CLIENTE,
		CLCIDFIS	AS CIDADE_CLIENTE,
		CLUFFIS		AS ESTADO_CLIENTE,
		CLRENDA		AS RENDA_CLIENTE,
		OCUPACAO	AS OCUPACAO_CLIENTE,
		IDADE		AS IDADE_CLIENTE,
		ClSexo		AS SEXO,

		CASE WHEN ClESTciv='1'  THEN 'SOLTEIRO'
			 WHEN ClESTciv='2'  THEN 'CASADO'
			 WHEN ClESTciv='3'  THEN 'DESQUITADO'
			 WHEN ClESTciv='4'  THEN 'DIVORCIADO'
			 WHEN ClESTciv='5'  THEN 'VIUVO'
			 WHEN ClESTciv='9'  THEN 'OUTROS'
			 ELSE '' END	
			AS ESTADO_CIVIL,
			
		CASE WHEN TIPO_CASA='A' THEN 'Alugada'
			 WHEN TIPO_CASA='C' THEN 'C/Pais'
			 WHEN TIPO_CASA='D' THEN 'De Familiares'
			 WHEN TIPO_CASA='E' THEN 'Da Empresa'
			 WHEN TIPO_CASA='F' THEN 'Financiada'
			 WHEN TIPO_CASA='H' THEN 'Hotel'
			 WHEN TIPO_CASA='O' THEN 'Outros'
			 WHEN TIPO_CASA='P' THEN 'Própria'
			 ELSE '' END AS TIPO_CASA_CLIENTE,

		LojaCod AS LOJA,
		LojaCEP AS CEP_LOJA,
		LojaCIDADE AS CIDADE_LOJA,
		LojaUF	AS UF_LOJA,
		AGENTEcod AS AGENTE,
		OperadorCod	AS OPERADOR,
		--''	AS 
		RWA_VEICULOS,
		TC		AS TARIFA_CONTRATACAO,
		--DESP_PESSOAL_SUP
		DESPESA_CADASTRO AS CUSTO_CONTRATACAO,

--		ISNULL(VLR_COMISSAO_TERCO_AV,0.0) +ISNULL(VLR_COMISSAO_DIFERIDA_36AVOS,0.0) AS CUSTO_COMISSAO,
		CASE WHEN	DATEPART(YYYY,DT_BASE) = 2015 AND DATEPART(YYYY,@DTREF) = 2015  -- 2015
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(VLR_COMISSAO,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2014 AND DATEPART(YYYY,@DTREF) = 2014	-- 2014
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 ELSE	0.0 -- A DEF
			 END 	AS CUSTO_COMISSAO,

		ISNULL(VLR_RECEITA,0.0) AS RECEITA_FINANCEIRA,
		DESP_CAPT_OPER AS CUSTO_FUNDING,

		--  FALTA
		case when datepart(mm,DT_FECHA) = 12 then CUSTO_MANUTENCAO/2.0 else CUSTO_MANUTENCAO end as CUSTO_MANUTENCAO, 
		MARGEM_CAIXA, 

		/*CASE WHEN NVL_RISCO_ANT ='HH' AND NVL_RISCO='' THEN PDD * (-1.00) +ISNULL(PASLDXMLT,0.0)+ISNULL(PASLDXMR,0.0) 
				ELSE ISNULL(PASLDXMLT,0.0)+ISNULL(PASLDXMR,0.0)  END	
		AS */ 
		VLR_RECEITA_ATRASO AS RECEITA_ATRASO,

		--  FALTA
		CUSTO_COBRANCA, 
		DESPESA_ATRASO, 

		PDD  AS DESPESA_PROVISAO, 

		--ISNULL(VLR_IOF,0.0)  SEM IOF 12 GER X 122 FUNCAO
		ISNULL(VLR_ISS,0.0) + ISNULL(VLR_PIS,0.0) + ISNULL(VLR_COFINS,0.0) +		
		ISNULL(vlr_IRPJ,0.0)+ISNULL(VLR_CSSL,0.0) - ISNULL(VLR_CRED_TRIB,0.0)+ ISNULL(OUTRAS_TX,0.0)
		AS TRIBUTOS,
		--RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_BASE))),2)+
		'01/'+ 		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))),2) +'/'
		+ CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))	 AS DATA_SAFRA
FROM DRE_ATRASO (NOLOCK)
	WHERE	DT_FECHA = @DTREF
*/