
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go

/*
 EXEC DRE_RESULTADO_ANALITICO '20170430'

 EXEC DRE_FUNCAO_ATRASO_ANALITICO '20150630'
 EXEC DRE_DESPESAS_ANALITICO '20150630'

 EXEC DRE_RESULTADO_ANALITICO '20130131'

*/
-- PROC CARGA DRE_RESULTADO_ANALITICO  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'DRE_RESULTADO_ANALITICO' AND type = 'P')
   DROP PROCEDURE [dbo].[DRE_RESULTADO_ANALITICO] 
GO

-- MENSAL
-- ***************************************
CREATE Procedure [dbo].[DRE_RESULTADO_ANALITICO] 
 (@DTREF  SMALLDATETIME )	AS  

BEGIN

-- DECLARE @DTREF AS DATETIME SET @DTREF ='20150430'
DECLARE @DTINI  AS DATETIME
DECLARE @DTFIM  AS DATETIME
DECLARE @DTM1   AS DATETIME

-- INICIO DO MES DE REF
SET @DTINI = CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+'01'
SET @DTFIM = @DTREF

--SET @DTM1 = DATEADD(M,-,@DTINI)


DECLARE @DTPDD DATETIME
SET @DTPDD = @DTREF
IF  @DTREF < '20140831'
	SELECT	@DTPDD= CASE  WHEN DATEPART(DW,@DTPDD) = 1 THEN DATEADD(D,-2,@DTPDD)	-- DOMINGO
						  WHEN DATEPART(DW,@DTPDD) = 7 THEN DATEADD(D,-1,@DTPDD)	-- SABADO
						  ELSE @DTREF				   END

-- FIM DO MES ANT
SET @DTM1 = DATEADD(DD,-1,@DTINI)
IF  @DTM1 < '20140831'
	SELECT	@DTM1= CASE  WHEN DATEPART(DW,@DTM1) = 1 THEN DATEADD(D,-2,@DTM1)	-- DOMINGO
						 WHEN DATEPART(DW,@DTM1) = 7 THEN DATEADD(D,-1,@DTM1)	-- SABADO
						 ELSE @DTM1				   END
-- SELECT @DTM1
SELECT	@DTPDD , @DTM1



/*
-- ANALITICO DO CONTRATO
SELECT  --  
TOP 100 * 
--	OPDTBASE,OPNROPER, OPCODOP, 

-- OPTAC ,OPVLRBRUTO, OPVLRFIN, OPVLROPCZ, OPVLRFINNG,OPDESPESA1,  OPDESPESA2, OPDESPESA3, OPDESPESA4,OPIOC,OPTXCAP,OPTXJRCL,OPTXJRCET,OPTXJRNOM,*
-- SELECT DATEDIFF(DD,OPDTBASE,OPDTVCTO),* 
	FROM	CDCSANTANAMicroCredito..COPER O (NOLOCK)
	WHERE	-- PRODUCAO
			CONVERT(VARCHAR(8),OPDTBASE,112) BETWEEN @DTINI AND @DTFIM 
		AND RIGHT(OPNROPER,1) NOT IN ('A','B','C','D')

SELECT * FROM RR_AUX_CONTRATO_2M (NOLOCK) WHERE DT_FECHA='20150430' and nvl_risco_ant <> 'hh'

SELECT sum(sld_inscrito-sld_inscrito_ant) FROM RR_AUX_CONTRATO_2M (NOLOCK) WHERE DT_FECHA='20150430' and nvl_risco_ant <> 'hh'

select case when nvl_risco ='A' then (sld_inscrito - sld_inscrito_ant)* 0.5/100.0 
			when nvl_risco ='B' then (sld_inscrito - sld_inscrito_ant)* 1.0/100.0 
			when nvl_risco ='C' then (sld_inscrito - sld_inscrito_ant)* 3.0/100.0 
			when nvl_risco ='D' then (sld_inscrito - sld_inscrito_ant)* 10.0/100.0 
			when nvl_risco ='E' then (sld_inscrito - sld_inscrito_ant)* 30.0/100.0 
			when nvl_risco ='F' then (sld_inscrito - sld_inscrito_ant)* 50.0/100.0 
			when nvl_risco ='G' then (sld_inscrito - sld_inscrito_ant)* 70.0/100.0 
			when nvl_risco ='H' then (sld_inscrito - sld_inscrito_ant)* 100.0/100.0 
end as pdd, *
 FROM RR_AUX_CONTRATO_2M (NOLOCK) WHERE DT_FECHA='20150430' and nvl_risco_ant <> 'hh'

SELECT * FROM RR_AUX_CONTRATO_2M  (NOLOCK) WHERE DT_FECHA='20150430' and nvl_risco_ant <> 'hh'
SELECT * FROM RATING_HISTORICO  (NOLOCK) WHERE DT_FECHA='20150430' and nvl_risco <> 'hh'
SELECT * FROM  #TEMP_RR (NOLOCK)

SELECT * FROM  TEMP_RR (NOLOCK)
SP_HELP RR_AUX_CONTRATO_2M

DROP   TABLE TEMP_RR
CREATE TABLE TEMP_RR   (
DT_FECHA	smalldatetime,
NUM_OPE	varchar	(50),
AGENTE	varchar	(6),
COBRADORA	varchar	(6),
NVL_RISCO	varchar	(50),
NVL_RISCO_ANT	varchar	(50),
SLD_INSCRITO	float	,
SLD_INSCRITO_ANT	float,
Atraso	int,
Atraso_ANT	int,
PARC	int,
PARC_ANT	int	,
VENCTO	smalldatetime,
VENCTO_ANT	smalldatetime  ,
VLR_PDD		FLOAT,
VLR_PDD_ANT	FLOAT,
NUM_OPE_ANT varchar	(50)
)


ALTER TABLE TEMP_RR ADD   VLR_PDD		FLOAT
ALTER TABLE TEMP_RR ADD   VLR_PDD_ANT	FLOAT

*/

-- PDD DO MES ANTERIOR *******************
-- TABELA AUXILIAR PARA CALCULAR A VARIACAO DA PROVISAO DA PDD
-- DROP TABLE #TEMP_RR
/*
DELETE  TEMP_RR
INSERT	TEMP_RR 
SELECT	@DTREF,R.NUM_OPE,R.AGENTE,R.COBRADORA,
		'' AS NVL_RISCO, R.NVL_RISCO AS NVL_RISCO_ANT,
		0.0 AS SLD_INSCRITO, R.SLD_INSCRITO AS SLD_INSCRITO_ANT, 
		0 AS ATRASO, R.ATRASO AS ATRASO_ANT,
		0 AS  PARC, R.PARC AS PARC_ANT,
		GETDATE() AS  VENCTO,R.DTVENCPARC AS VENCTO_ANT
		,0.0,0.0  -- VLR PDD
	-- FECHAMENTO PDD DO MES ANTERIOR	, SEM PREJUIZO
	FROM RATING_HISTORICO  R (NOLOCK) WHERE R.DT_FECHA=@DTM1 --AND R.NVL_RISCO <> 'HH'

-- INSERE NOVOS CONTRATOS DO MES ******************* SEM MES ANTERIOR
INSERT	TEMP_RR 
SELECT	@DTREF,R.NUM_OPE,R.AGENTE,R.COBRADORA,
		R.NVL_RISCO		AS NVL_RISCO,		''	AS NVL_RISCO_ANT,
		R.SLD_INSCRITO	AS SLD_INSCRITO,	0.0 AS SLD_INSCRITO_ANT, 
		R.ATRASO	AS ATRASO,	0 AS ATRASO_ANT,
		R.PARC		AS PARC,	0 AS PARC_ANT,
		R.DTVENCPARC AS  VENCTO,GETDATE() AS VENCTO_ANT
		,0.0,0.0  -- VLR PDD
	-- FECHAMENTO PDD DO MES ANTERIOR	, SEM PREJUIZO
	FROM	RATING_HISTORICO  R (NOLOCK) 
	WHERE	R.DT_FECHA=@DTREF --AND R.NVL_RISCO <> 'HH'
		AND	R.NUM_OPE NOT IN (SELECT NUM_OPE FROM TEMP_RR T (NOLOCK) )

UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO		 = R.ATRASO, 
		TEMP_RR.PARC		 = R.PARC,
		TEMP_RR.VENCTO		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTREF 
		AND R.NUM_OPE = TEMP_RR.NUM_OPE

--SELECT * INTO #TEMP_RR FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA=@DTREF 
--and nvl_risco_ant <> 'hh'

-- RENEGOCIADOS NOVOS ************ RATING DO MES ANTERIOR ********** CONTRATO ORIGINAL
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = R.ATRASO, 
		TEMP_RR.PARC_ANT		 = R.PARC,
		TEMP_RR.VENCTO_ANT		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTM1
		AND RIGHT(TEMP_RR.NUM_OPE,1) IN ('A')
		AND R.NUM_OPE = LEFT(TEMP_RR.NUM_OPE,LEN(TEMP_RR.NUM_OPE)-1)
		AND TEMP_RR.NVL_RISCO_ANT =''			-- SEM RATING ANTERIOR

-- RENEGOCIADOS NOVOS ************ B 2A RENEG ********** CONTRATO ORIGINAL
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = R.ATRASO, 
		TEMP_RR.PARC_ANT		 = R.PARC,
		TEMP_RR.VENCTO_ANT		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTM1
		AND RIGHT(TEMP_RR.NUM_OPE,1) IN ('B')
		AND R.NUM_OPE = LEFT(TEMP_RR.NUM_OPE,LEN(TEMP_RR.NUM_OPE)-1)+'A'
		AND TEMP_RR.NVL_RISCO_ANT =''			-- SEM RATING ANTERIOR

-- RENEGOCIADOS ANTIGOS ************ ********** CONTRATO ORIGINAL NA OPERACAO
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = H.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = H.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = H.ATRASO, 
		TEMP_RR.PARC_ANT		 = H.PARC,
		TEMP_RR.VENCTO_ANT		 = H.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	(SELECT * FROM RATING_HISTORICO R (NOLOCK)  WHERE	R.DT_FECHA = @DTM1 AND R.NVL_RISCO <> 'HH' AND RIGHT(R.NUM_OPE,1) NOT IN ('A','B','C')) AS H,
			CDCSANTANAMicroCredito..COPER O (NOLOCK)		
	WHERE	H.NUM_OPE  =  O.OPNROPER  		-- ATUAL RENEGOCIADO LOCALIZAR A OPERACAO
		AND O.OPCODOP  IN (720,730,731,741,742,751,752,  800,860,861,862,863,890,891,892,893,894  )  -- RENEGOCIACAO		
		--  LOCALIZAR CONTRATO ANTERIOR NO HISTORICO  RENEGOCIADO 
		AND H.NUM_OPE= O.OPNROPER2  		-- OPERACAO ANTERIOR
		AND	H.CODCLI = O.OPCODCLI			-- MESMO CODIGO DE CLIENTE		
--		AND TEMP_RR.NVL_RISCO_ANT =''			-- SEM RATING ANTERIOR

*/
-- 1
DELETE TEMP_RR
-- 2
-- SP_HELP TEMP_RR
INSERT		TEMP_RR
SELECT	@DTREF,
		NUM_OPE,
		AGENTE,
		COBRADORA,
		NVL_RISCO, -- RISCO ATUAL
		 -- RISCO NO MES ANTERIOR
		'',
		SLD_INSCRITO,
		0.0,
		ATRASO,
		0,
		parc, 0,
		dtVencParc,'',
		--PDD
		0,0, 
			-- CONTRATO ORIGINAL
			CASE WHEN RIGHT(NUM_OPE,1) = 'A' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)
				 WHEN RIGHT(NUM_OPE,1) = 'B' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'A'
				 WHEN RIGHT(NUM_OPE,1) = 'C' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'B'
				 ELSE NUM_OPE	
			END	
FROM
		RATING_HISTORICO (NOLOCK)
where	DT_FECHA = @DTPDD  -- MES ATUAL
/*
	SELECT	DT_FECHA	,
			NUM_OPE	,
			AGENTE	,
			COBRADORA	,
			NVL_RISCO	,
			NVL_RISCO_ANT	,
			SLD_INSCRITO	,
			SLD_INSCRITO_ANT	,
			Atraso	,
			Atraso_ANT	,
			PARC	,
			PARC_ANT		,
			VENCTO	,
			VENCTO_ANT, 0.0,0.0,
			-- CONTRATO ORIGINAL
			CASE WHEN RIGHT(NUM_OPE,1) = 'A' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)
				 WHEN RIGHT(NUM_OPE,1) = 'B' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'A'
				 WHEN RIGHT(NUM_OPE,1) = 'C' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'B'
				 ELSE NUM_OPE	
			END	
	FROM	RATING_HISTORICO (NOLOCK) --RR_AUX_CONTRATO_2M (NOLOCK)
	WHERE	DT_FECHA = @DTREF --AND NVL_RISCO_ANT <> 'HH' 
SP_HELP TEMP_RR
*/

-- INSERE OS Q FALTARAM DO MES ANT
--   DECLARE @DTREF DATETIME SET @DTREF = '20150430'  DECLARE @DTM1 DATETIME SET @DTM1 = '20150331'
--  3
INSERT		TEMP_RR
	SELECT	@DTREF	,
			NUM_OPE	,
			AGENTE	,
			COBRADORA	,
			'', -- NVL_RISCO	,
			NVL_RISCO	,
			'', -- SLD_INSCRITO	,
			SLD_INSCRITO	,
			0, --Atraso	,
			Atraso	,
			0, --PARC	,
			PARC		,
			'', --VENCTO	,
			DtVENCparc, 0.0,0.0,
			-- CONTRATO ORIGINAL
			CASE WHEN RIGHT(NUM_OPE,1) = 'A' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)
				 WHEN RIGHT(NUM_OPE,1) = 'B' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'A'
				 WHEN RIGHT(NUM_OPE,1) = 'C' THEN LEFT(NUM_OPE,LEN(NUM_OPE)-1)+'B'
				 ELSE NUM_OPE	
			END	
	FROM	(SELECT * FROM RATING_HISTORICO R (NOLOCK)
				WHERE	DT_FECHA = @DTM1  -- MES ANTERIOR
				) AS RAT
	WHERE	NUM_OPE NOT IN (SELECT NUM_OPE		FROM TEMP_RR T (NOLOCK) )
-- WHERE NVL_RISCO NOT IN ('','HH')
		AND	NUM_OPE NOT IN (SELECT NUM_OPE_ANT  FROM TEMP_RR T (NOLOCK) )

-- 4
-- DECLARE @DTM1 DATETIME SET @DTM1 = '20170430'
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = R.ATRASO, 
		TEMP_RR.PARC_ANT		 = R.PARC,
		TEMP_RR.VENCTO_ANT		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTM1  -- MES ANTERIOR 
		AND R.NUM_OPE = TEMP_RR.NUM_OPE
--  AND TEMP_RR.NUM_OPE='760941000127'
-- EXCLUI OS PREJUIZOS Q CONTINUAM NA CARTEIRA
-- DELETE	FROM TEMP_RR WHERE	NVL_RISCO = NVL_RISCO_ANT AND NVL_RISCO='HH'

-- RENEGOCIADOS NO MES  TRAZER SALDO E RISCO ANTERIOR
/*
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = R.ATRASO, 
		TEMP_RR.PARC_ANT		 = R.PARC,
		TEMP_RR.VENCTO_ANT		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTM1  -- MES ANTERIOR 
		AND ISNULL(SLD_INSCRITO_ANT,0.0) = 0.0
		AND LEFT(R.NUM_OPE,LEN(R.NUM_OPE)-1) = TEMP_RR.NUM_OPE
*/


-- 5
-- RENEGOCIADOS NOVOS ************ RATING DO MES ANTERIOR ********** CONTRATO ORIGINAL  -- set 14
-- declare @DTM1 datetime set @DTM1 ='20170331'
UPDATE	TEMP_RR
	SET TEMP_RR.NVL_RISCO_ANT	 = R.NVL_RISCO,
		TEMP_RR.SLD_INSCRITO_ANT = R.SLD_INSCRITO, 
		TEMP_RR.ATRASO_ANT		 = R.ATRASO, 
		TEMP_RR.PARC_ANT		 = R.PARC,
		TEMP_RR.VENCTO_ANT		 = R.DTVENCPARC
	-- FECHAMENTO PDD DO MES ANTERIOR	
	FROM	RATING_HISTORICO R (NOLOCK) 
	WHERE	R.DT_FECHA= @DTM1
		AND RIGHT(TEMP_RR.NUM_OPE,1) IN ('A','B','C')
		AND R.NUM_OPE = LEFT(TEMP_RR.NUM_OPE,LEN(TEMP_RR.NUM_OPE)-1)
		AND TEMP_RR.NVL_RISCO_ANT =''			-- SEM RATING ANTERIOR

-- 6
UPDATE TEMP_RR
SET  TEMP_RR.VLR_PDD =ISNULL(case  when TEMP_RR.nvl_risco ='A' then (TEMP_RR.sld_inscrito)* 0.5/100.0 
							when TEMP_RR.nvl_risco ='B' then (TEMP_RR.sld_inscrito)* 1.0/100.0 
							when TEMP_RR.nvl_risco ='C' then (TEMP_RR.sld_inscrito)* 3.0/100.0 
							when TEMP_RR.nvl_risco ='D' then (TEMP_RR.sld_inscrito)* 10.0/100.0 
							when TEMP_RR.nvl_risco ='E' then (TEMP_RR.sld_inscrito)* 30.0/100.0 
							when TEMP_RR.nvl_risco ='F' then (TEMP_RR.sld_inscrito)* 50.0/100.0 
							when TEMP_RR.nvl_risco ='G' then (TEMP_RR.sld_inscrito)* 70.0/100.0 
							when TEMP_RR.nvl_risco ='H' then (TEMP_RR.sld_inscrito)* 100.0/100.0 
							when TEMP_RR.nvl_risco ='HH' then (TEMP_RR.sld_inscrito)* 100.0/100.0 
					END,0.0),

--UPDATE TEMP_RR SET  
		TEMP_RR.VLR_PDD_ANT =ISNULL(case when nvl_risco_ANT ='A' then (sld_inscrito_ANT)* 0.5/100.0 
								when nvl_risco_ANT ='B' then (sld_inscrito_ANT)* 1.0/100.0 
								when nvl_risco_ANT ='C' then (sld_inscrito_ANT)* 3.0/100.0 
								when nvl_risco_ANT ='D' then (sld_inscrito_ANT)* 10.0/100.0 
								when nvl_risco_ANT ='E' then (sld_inscrito_ANT)* 30.0/100.0 
								when nvl_risco_ANT ='F' then (sld_inscrito_ANT)* 50.0/100.0 
								when nvl_risco_ANT ='G' then (sld_inscrito_ANT)* 70.0/100.0 
								when nvl_risco_ANT ='H' then (sld_inscrito_ANT)* 100.0/100.0 
								when nvl_risco_ANT ='HH' then (sld_inscrito_ANT)* 100.0/100.0 
					END,0.0)

-- H Q VAI PARA HH TEM Q CONTAR O SALDO NA PDD

--UPDATE	TEMP_RR SET		TEMP_RR.VLR_PDD_ANT =0.0  WHERE	nvl_risco_ANT ='H'  AND nvl_risco ='HH'


-- REMOVER OS HH NO MES ANTERIOR Q JA ESTAO EM PREJUIZO	HH
/*
UPDATE	TEMP_RR
SET		TEMP_RR.VLR_PDD_ANT =0.0 ,
		TEMP_RR.VLR_PDD		=0.0 
*/
-- REMOVER OS HH NO MES ANTERIOR Q JA ESTAO EM PREJUIZO	HH
-- DELETE	TEMP_RR  WHERE	nvl_risco_ANT ='HH' AND nvl_risco ='HH'


-- REMOVER OS HH Q ESTAO EM 2012 E NAO EM 2013  -- HH NO MES ANT E NAO NO ATUAL
IF @DTREF IN ( '20130131', '20130228','20130331','20130430'
,'2013-05-31','2013-06-30','2013-07-31','2013-08-31','2013-09-30','20131031','20131130'  )
  -- PROBLEMA DE CARGA pdd 22/8/15 *****************************  MES ATUAL
		DELETE  TEMP_RR			WHERE NVL_RISCO_ANT = 'HH'  -- REMOVE OS HH ANTERIORES 
			AND NVL_RISCO = '' AND NUM_OPE NOT IN (SELECT NUM_OPE FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA=@DTPDD)



-- REMOVER OS HH Q ESTAO EM 2012 E NAO EM 2013
IF @DTREF in ( '20131231',  '2014-01-31')  -- PROBLEMA DE CARGA pdd 22/8/15 *****************************
		DELETE  TEMP_RR			WHERE NVL_RISCO = 'HH'  -- REMOVE OS HH ANTERIORES  @DTM1  -- MES ANTERIOR
			AND NVL_RISCO_ANT IN ( '','HH') AND NUM_OPE NOT IN (SELECT NUM_OPE FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA=@DTM1)

-- remover HH do mes anterior e do atual  2m5
IF @DTREF = '2014-01-31'   -- AJUSTE HH
begin
		DELETE  TEMP_RR			WHERE NVL_RISCO = 'HH'  -- REMOVE OS HH ANTERIORES   E TB ATUAL
			AND NVL_RISCO_ANT IN ( 'HH','hh') 
		DELETE  TEMP_RR			WHERE NVL_RISCO = ''  -- REMOVE OS '' ANTERIORES   E TB ATUAL
			AND NVL_RISCO_ANT IN ( '')  AND NUM_OPE NOT IN (SELECT NUM_OPE FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA=@DTPDD)
end
/*
IF @DTREF = '2014-01-31'   -- AJUSTE HH
begin
		DELETE  TEMP_RR			WHERE NVL_RISCO = 'HH'  -- REMOVE OS HH ANTERIORES   E TB ATUAL
			AND NVL_RISCO_ANT IN ( 'HH','hh') 
		DELETE  TEMP_RR			WHERE NVL_RISCO_ANT = 'HH'  -- REMOVE OS HH ANTERIORES   E TB ATUAL
			AND NVL_RISCO IN ( '')  AND NUM_OPE NOT IN (SELECT NUM_OPE FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA=@DTPDD)
end  */


-- 7
DELETE  TEMP_RR			WHERE NVL_RISCO = 'HH'  -- REMOVE OS HH ANTERIORES   E TB ATUAL
	AND NVL_RISCO_ANT IN ( 'HH','hh') 

-- 8
-- LIMPAR O PROCESSO ANTERIOR
-- declare @DTREF datetime set @DTREF ='20170430'
DELETE 	DRE_ATRASO		WHERE DT_FECHA=@DTREF

-- SP_HELP DRE_ATRASO
-- 9
-- SP_HELP  DRE_ATRASO
-- alterado 6/6/17 ****************
-- alter table DRE_ATRASO alter column DESCR_TIPO varchar(200)  
-- alter table DRE_ATRASO alter column lojaCidade varchar(200)  


-- OCUPACAO
-- declare @DTREF datetime set @DTREF ='20170430'  declare @DTPDD datetime set @DTPDD ='20170430'
INSERT  DRE_ATRASO
--SELECT SUM(VLR_PDD - VLR_PDD_ANT) FROM #TEMP_RR 
-- WHERE NVL_RISCO <> NVL_RISCO_ANT

-- DECLARE @DTREF DATETIME SET @DTREF = '20170430'		 DECLARE @DTPDD DATETIME SET @DTPDD = '20170430'
-- PDD SEM PREJUIZO
SELECT		DISTINCT
			@DTREF, TEMP_RR.NUM_OPE, 
			CASE WHEN RIGHT(TEMP_RR.NUM_OPE,1) IN ('A','B','C','D') THEN SUBSTRING(TEMP_RR.NUM_OPE,1,LEN(R.NUM_OPE)-1) 
				 ELSE TEMP_RR.NUM_OPE END AS CONTRATOoriginal,
			DESCR_TIPO ,
			TEMP_RR.NVL_RISCO, 
			--R.VLR_FV- R.SLD_INSCRITO AS LOAN, 
			0.0,
			-- LIB / TABELADO 
            opvlrfin , (SELECT		ABVLRTAB FROM			CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
							WHERE	ABNROPER = TEMP_RR.NUM_OPE AND ABNRGAR='01' -- alterado 2/1/17
								AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
												WHERE	B1.ABNROPER = TEMP_RR.NUM_OPE AND B1.ABNRGAR='01')) ,
			OPQTDDPARC,
			DATEDIFF(MM,OPDTBASE,@DTREF)  AS PDECOR,
			R.PARC,
			-- CLIENTE
			CLCEPFIS , CLCIDFIS, CLUFFIS,  	ISNULL(CLRENDA,0.0), 	'' AS OCUPACAO,
			DATEDIFF(YY,CLDTNASC,@DTREF) AS IDADE,
			ClSexo,ClESTciv, 
			-- TIPO CASA ??
			'' AS TIPO_CASA,
			OpCodORG4	AS LojaCod, 
			O4CEP		AS LojaCEP,
			O4CID		AS LojaCIDADE,
			O4UF		AS LojaUF,

			O3CODORGA13 AS AGENTEcod,

			OpCodORG3   AS OperadorCod,

			OpDESPESA3  AS TC,
			OpDESPESA3  ,  -- OPTAC
			0.0, 0.0,   -- ATRASOS
			--(SELECT (VLR_PDD - VLR_PDD_ANT) FROM TEMP_RR RR (NOLOCK) WHERE RR.NUM_OPE = R.NUM_OPE) AS VLR_PDD 

			-- set-15 alterado  ************* RISCO =, SEM PROVISAO NOVA! RISCO <> ALTERA PROVISAO
			-- renegociado tem o mesmo Risco mas VLR pdd Diferentes ************* out-15
			case when TEMP_RR.NVL_RISCO_ANT = TEMP_RR.NVL_RISCO THEN (TEMP_RR.VLR_PDD - TEMP_RR.VLR_PDD_ANT) 			
					ELSE
			(TEMP_RR.VLR_PDD - TEMP_RR.VLR_PDD_ANT)  END, -- PDD
			TEMP_RR.VLR_PDD , TEMP_RR.VLR_PDD_ANT, -- PDD
			TEMP_RR.NVL_RISCO_ANT,
			opvlrPARC,
			opDESPESA4,  -- RETORNO
			-- RECEITA = VF - VP 
			(OPQTDdPARC * opvlrPARC) - OPVlrOpCZ ,
			OPIOC,				-- IOF
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS IRPJ
			0.0,0.0,0.0,0.0	,	-- REC REPASSE RETORNO REPASS
			0.0,0.0,0.0,0.0		-- DESP
			-- 0.0,0.0,0.0,0.0	
			,TEMP_RR.SLD_INSCRITO , 0.0
			,0.0,0.0,0.0	-- COMISSAO
			,OPVLRFIN		-- FINANCIADO
			,OPDTBASE		-- DT BASE DO CONTRATO
			,0.0			-- vlr comissao diferido no prazo do contrato				vlr_comissao_diferida_pzo_Op
			,0.0,0.0		-- COMISSAO_AV  ,	SLD_DIFERIR_2_3
			,0.0,0.0		-- COMISSAO_2_3,	VLR_COMISSAO_15
			,0.0		-- FIM COMISS			DESPESA_CONTRATO
			,0.0, 0.0    -- DESPESA_CADASTRO,	DESPESA_COMERCIAL
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0 ,0.0,0.0, 0.0, 0.0  ,0.0 ,0.0  -- CM
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0
			,0.0
			,0.0
			---	ANO_VEICULO, MODELO, SCORE
			,'','',''
			,0.0  -- RECEITA FIN

/*			,0.0  -- COMISSAO DIFERIDA PELO PRAZO DO CONTRATO
			,0.0  -- COMISSAO AV
			,0.0  -- SLDO A DIFERIR 2/3
			,0.0,0.0
			,0.0
,0.0,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0,0.0,  0.0,0.0,0.0	*/
FROM
		 (SELECT		* 
			FROM	TEMP_RR (NOLOCK) WHERE DT_FECHA= @DTREF --AND NVL_RISCO_ANT<>'HH'
			) AS TEMP_RR
		
		LEFT JOIN
		(SELECT		* 
			FROM	RATING_HISTORICO (NOLOCK) WHERE DT_FECHA= @DTPDD   -- MES ATUAL @DTREF --AND NVL_RISCO_ANT<>'HH'
			) AS R

			ON	R.NUM_OPE = TEMP_RR.NUM_OPE

			LEFT JOIN   CDCSANTANAMicroCredito..COPER O (NOLOCK)
					ON	TEMP_RR.NUM_OPE = OPNROPER
			--   LISTA COM MODALIDADES DO PRODUTO VEIC E RENEGOCIADOS
			JOIN (SELECT	M.COD_MODA, DESCR_TIPO
							FROM	 Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)  
							WHERE	M.COD_PROD = T.COD_PROD 
								AND T.COD_MODALIDADE = M.COD_MODALIDADE 
							AND T.COD_PROD IN ( 'V','R' ) ) AS MOD
					ON OPCODOP =  COD_MODA
	
		LEFT JOIN   CDCSANTANAMicroCredito..CCLIE C (NOLOCK)
			ON		OPCODCLI = CLCODCLI

		LEFT JOIN	(SELECT  * 
							-- ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
						FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
							) AS OPERADOR
				ON	O3CODORG = OpCodORG3  -- OPERADOR

		LEFT JOIN	(SELECT  * 
						FROM	CDCSANTANAMicroCredito..TORG4 OP (NOLOCK) 
							) AS LOJA
				ON	O4CODORG = OpCodORG4  -- OPERADOR



-- DESCR_TIPO E PDD DO MES ANTERIOR

-- LIQUIDACAO DO ORIGINAL, ZERAR A VLR_RECEITA, COMISSAO DO ORIGINAL AJUSTADA PELO Q FALTA PAGAR
/*
SELECT		* 	FROM	TEMP_RR (NOLOCK) WHERE NUM_OPE='760941000127'
LEFT JOIN
( SELECT	*
						FROM	RATING_HISTORICO R2 (NOLOCK) WHERE R2.DT_FECHA= '20150331') AS R1
ON R.NUM_OPE =R1.NUM_OPE


	UPDATE  DRE_ATRASO 
		SET	PDD = PDD * (-1.0)
		WHERE NVL_RISCO='HH'
	UPDATE  DRE_ATRASO 
		SET	PDD = (SELECT VLR_PDD FROM TEMP_RR T (NOLOCK) WHERE T.NUM_OPE = DRE_ATRASO.OPNROPER)
		WHERE NVL_RISCO='HH'
-- NATUREZA DE OCUPACAO  ***********************************
-- select CLCODOCUP from PROPWEBSMC..cclip
	UPDATE	SPREAD_HISTORICO
	SET		OCUPACAO = 		CASE CLCODOCUP 
								  WHEN '01' THEN 'CLT' 
								  WHEN '02' THEN 'AUTONOMO' 
								  WHEN '03' THEN 'APOSENTADO' 
								  WHEN '04' THEN 'EMPRESARIO'
								  ELSE 'S/ INFO' 
								END 
	FROM 	PROPWEBSMC..cclip C (NOLOCK)
	WHERE	CODCLI = CLCODCLI 

	DELETE		DRE_ATRASO 
		WHERE	NVL_RISCO='HH'

	UPDATE		DRE_ATRASO 
		SET		PDD = 0.0
		FROM	DRE_ATRASO D (NOLOCK) JOIN TEMP_RR  T (NOLOCK) ON D.OPNROPER = T.NUM_OPE
		WHERE	D.NVL_RISCO='HH' AND T.NVL_RISCO_ANT = 'HH'

SELECT * FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA='20150430' AND NUM_OPE='61644094A'
SELECT * FROM RATING_HISTORICO (NOLOCK) WHERE NUM_OPE='61644094A'
SELECT * FROM CDCSANTANAMicroCredito..CPARC WHERE PANROPER= '61644094A'
-- LIQUIDOU EM DIA ABR-15

SELECT * FROM RATING_HISTORICO (NOLOCK) WHERE DT_FECHA='20150430' AND NUM_OPE IN ('612060161A','612060161B')
SELECT * FROM CDCSANTANAMicroCredito..CPARC WHERE PANROPER= '612060161A'  -- LIQUIDOU BNDU ??
SELECT * FROM CDCSANTANAMicroCredito..CPARC WHERE PANROPER= '612060161B'  -- NAO RENEGOCIOU

*/

-- INCLUIR OS CONTRATOS NOVOS  PDD  ***********************************************************
--		DECLARE @DTREF DATETIME SET @DTREF = '20150430'
/*
INSERT  DRE_ATRASO
SELECT		@DTREF, R.NUM_OPE, 
			CASE WHEN RIGHT(R.NUM_OPE,1) IN ('A','B','C','D') THEN SUBSTRING(R.NUM_OPE,1,LEN(R.NUM_OPE)-1) 
				 ELSE R.NUM_OPE END AS CONTRATOoriginal,
			DESCR_TIPO,R.NVL_RISCO, 
			--R.VLR_FV- R.SLD_INSCRITO AS LOAN, 
			0.0,
			-- LIB / TABELADO 
            opvlrfin , (SELECT		ABVLRTAB FROM			CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
							WHERE	ABNROPER = R.NUM_OPE AND ABNRGAR=01 
								AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
												WHERE	B1.ABNROPER = TEMP_RR.NUM_OPE AND B1.ABNRGAR=01)) ,
			OPQTDDPARC,
			DATEDIFF(MM,OPDTBASE,@DTREF)  AS PDECOR,
			R.PARC,CLCEPFIS , CLCIDFIS, CLUFFIS, 
			ISNULL(CLRENDA,0.0), 
			'' AS OCUPACAO,
			DATEDIFF(YY,CLDTNASC,@DTREF) AS IDADE,
			ClSexo,ClESTciv, 
			-- TIPO CASA ??
			'' AS TIPO_CASA,
			OpCodORG4	AS LojaCod, 
			O4CEP		AS LojaCEP,
			O4CID		AS LojaCIDADE,
			O4UF		AS LojaUF,

			O3CODORGA13 AS AGENTEcod,

			OpCodORG3   AS OperadorCod,

			OpDESPESA3  AS TC,
			OpDESPESA3  ,  -- OPTAC
			0.0, 0.0,   -- ATRASOS
			(R.VLR_PDD - ISNULL(TEMP_RR.VLR_PDD_ANT,0.0)) ,
			R.VLR_PDD , ISNULL(TEMP_RR.VLR_PDD_ANT,0.0),
			ISNULL(TEMP_RR.NVL_RISCO_ANT,''),
			opvlrPARC,
			opDESPESA4,  -- RETORNO
			-- RECEITA = VF - VP 
			(OPQTDdPARC * opvlrPARC) - OPVlrOpCZ ,
			OPIOC,
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS
			0.0,0.0,0.0,0.0	,	-- DESP
			0.0,0.0,0.0,0.0	
			,R.SLD_INSCRITO , 0.0
			,0.0,0.0,0.0	-- COMISSAO
			,OPVLRFIN		-- FINANCIADO
			,OPDTBASE		-- DT BASE DO CONTRATO
			,0.0			-- vlr comissao diferido no prazo do contrato				vlr_comissao_diferida_pzo_Op
			,0.0,0.0		-- COMISSAO_AV  ,	SLD_DIFERIR_2_3
			,0.0,0.0		-- COMISSAO_2_3,	VLR_COMISSAO_15
			,0.0		-- FIM COMISS			DESPESA_CONTRATO
			,0.0, 0.0    -- DESPESA_CADASTRO,	DESPESA_COMERCIAL
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0 ,0.0,0.0, 0.0, 0.0  ,0.0 ,0.0  -- CM
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0
FROM
		(SELECT		* 
			FROM	RATING_HISTORICO (NOLOCK) WHERE DT_FECHA= @DTREF --AND NVL_RISCO_ANT<>'HH'
			) AS R
		
		LEFT JOIN
		 (SELECT		* 
			FROM	TEMP_RR (NOLOCK) WHERE DT_FECHA= @DTREF -- AND NVL_RISCO_ANT<>'HH'
			) AS TEMP_RR

			ON	R.NUM_OPE = TEMP_RR.NUM_OPE

			LEFT JOIN   CDCSANTANAMicroCredito..COPER O (NOLOCK)
					ON	R.NUM_OPE = OPNROPER
			--   LISTA COM MODALIDADES DO PRODUTO VEIC E RENEGOCIADOS
			JOIN (SELECT	M.COD_MODA, DESCR_TIPO
							FROM	 Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)  
							WHERE	M.COD_PROD = T.COD_PROD 
								AND T.COD_MODALIDADE = M.COD_MODALIDADE 
							AND T.COD_PROD IN ( 'V','R' ) ) AS MOD
					ON OPCODOP =  COD_MODA
	
		LEFT JOIN   CDCSANTANAMicroCredito..CCLIE C (NOLOCK)
			ON		OPCODCLI = CLCODCLI

		LEFT JOIN	(SELECT  * 
							-- ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
						FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
							) AS OPERADOR
				ON	O3CODORG = OpCodORG3  -- OPERADOR

		LEFT JOIN	(SELECT  * 
						FROM	CDCSANTANAMicroCredito..TORG4 OP (NOLOCK) 
							) AS LOJA
				ON	O4CODORG = OpCodORG4  -- OPERADOR
WHERE TEMP_RR.NUM_OPE IS NULL		-- NOVOS CONTRATOS Q NAO ESTAVAM NO MES ANTERIOR
-- FIM NOVOS PDD
*/

-- PDD EM HH ZERAR PDD
-- SELECT * FROM DRE_ATRASO (NOLOCK)
-- sp_help  DRE_ATRASO
--	declare @DTREF datetime set @DTREF = '20150430'
/*
DELETE		DRE_ATRASO  
WHERE	DT_FECHA=@DTREF
		AND DRE_ATRASO.NVL_RISCO = 'HH'		-- CONTINUA EM HH PREJUIZO
		AND DRE_ATRASO.NVL_RISCO_ANT = 'HH'  -- JAH ESTAVA EM HH
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.PDD=	SLDO_INSCRITO, DRE_ATRASO.VLR_PDD_ANT =0.0
	WHERE	DT_FECHA=@DTREF
		AND DRE_ATRASO.NVL_RISCO = 'HH'		-- FOI PARA HH PREJUIZO , ZERAR VLR PDD
	--	AND DRE_ATRASO.NVL_RISCO_ANT <> 'H'  -- ESTAVA EM H

*/
-- REMOVER OS PREJUIZOS ATUAIS
--			DECLARE @DTREF DATETIME SET @DTREF = '20150430'
--  SELECT * FROM 	DRE_ATRASO  (NOLOCK)

-- REMOVER OS PREJUIZOS ANTERIORES
-- DECLARE @DTREF DATETIME SET @DTREF = '20150430'
-- DELETE		DRE_ATRASO 	WHERE	DT_FECHA=@DTREF AND NVL_RISCO =NVL_RISCO_ANT AND NVL_RISCO_ANT = 'HH'
-- DELETE		DRE_ATRASO 	WHERE	DT_FECHA=@DTREF AND NVL_RISCO = 'HH'

-- 10
-- INCLUIR O VLR DE RECEITA DOS LIQUIDADOS  ***************************************
--		DECLARE @DTREF DATETIME SET @DTREF = '20170430'		declare @DTINI datetime set @DTINI ='20170401'
INSERT		DRE_ATRASO
SELECT		@DTREF, OPNROPER, 
			CASE WHEN RIGHT(OPNROPER,1) IN ('A','B','C','D') THEN SUBSTRING(OPNROPER,1,LEN(OPNROPER)-1) 
				 ELSE OPNROPER END AS CONTRATOoriginal,
			DESCR_TIPO,'', 
			--R.VLR_FV- R.SLD_INSCRITO AS LOAN, 
			0.0,
			-- LIB / TABELADO 
            opvlrfin , (SELECT		ABVLRTAB FROM			CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
							WHERE	ABNROPER = OPNROPER AND ABNRGAR='01' 
								AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
												WHERE	B1.ABNROPER = OPNROPER AND B1.ABNRGAR='01')) ,
			OPQTDDPARC,
			DATEDIFF(MM,OPDTBASE,@DTREF)  AS PDECOR,
			-- PARCELA PAGA
			0,
			CLCEPFIS , CLCIDFIS, CLUFFIS, 
			ISNULL(CLRENDA,0.0), 
			'' AS OCUPACAO,
			DATEDIFF(YY,CLDTNASC,@DTREF) AS IDADE,
			ClSexo,ClESTciv, 
			-- TIPO CASA ??
			'' AS TIPO_CASA,
			OpCodORG4	AS LojaCod, 
			O4CEP		AS LojaCEP,
			O4CID		AS LojaCIDADE,
			O4UF		AS LojaUF,

			O3CODORGA13 AS AGENTEcod,

			OpCodORG3   AS OperadorCod,

			OpDESPESA3  AS TC,
			OpDESPESA3  ,  -- OPTAC
			0.0, 0.0,   -- ATRASOS
			--- PDD ZERADA, PQ NAO ESTA MAIS NA CARTEIRA
			0.0 ,	0.0 , 0.0,'',
			opvlrPARC,
			opDESPESA4,  -- RETORNO
			-- RECEITA = VF - VP 
			(OPQTDdPARC * opvlrPARC) - OPVlrOpCZ ,
			OPIOC,
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS
			0.0,0.0,0.0,0.0	,	-- IMPOSTOS
			0.0,0.0,0.0,0.0	,	-- DESP
			0.0,0.0,0.0,0.0	
			,0.0 , 0.0			-- SEM SALDO
			,0.0,0.0,0.0	-- COMISSAO
			,OPVLRFIN		-- FINANCIADO
			,OPDTBASE		-- DT BASE DO CONTRATO
			,0.0			-- vlr comissao diferido no prazo do contrato				vlr_comissao_diferida_pzo_Op
			,0.0,0.0		-- COMISSAO_AV  ,	SLD_DIFERIR_2_3
			,0.0,0.0		-- COMISSAO_2_3,	VLR_COMISSAO_15
			,0.0		-- FIM COMISS			DESPESA_CONTRATO
			,0.0, 0.0    -- DESPESA_CADASTRO,	DESPESA_COMERCIAL
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0 ,0.0,0.0, 0.0, 0.0  ,0.0 ,0.0  -- CM
			,0.0 ,0.0,0.0, 0.0, 0.0			,0.0
			,0.0			,0.0
			--- ANO_VEICULO , MODELO, SCORE
			,'','',''
			,0.0  -- RECEITA FIN
FROM
		(SELECT		* FROM  CDCSANTANAMicroCredito..COPER O1 (NOLOCK)
				WHERE	OpDtLiq BETWEEN @DTINI AND @DTREF 
					AND	OpNrOper NOT IN 
						-- NAO ESTAO NA CARTEIRA
						(SELECT OPNROPER FROM DRE_ATRASO (NOLOCK) WHERE  DT_FECHA=@DTREF)) AS O	
			--   LISTA COM MODALIDADES DO PRODUTO VEIC E RENEGOCIADOS
			JOIN (SELECT	M.COD_MODA, DESCR_TIPO
							FROM	 Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)  
							WHERE	M.COD_PROD = T.COD_PROD 
								AND T.COD_MODALIDADE = M.COD_MODALIDADE 
							AND T.COD_PROD IN ( 'V','R' ) ) AS MOD
					ON OPCODOP =  COD_MODA
	
		LEFT JOIN   CDCSANTANAMicroCredito..CCLIE C (NOLOCK)
			ON		OPCODCLI = CLCODCLI

		LEFT JOIN	(SELECT  * 
							-- ISNULL(OP.O3CODORGA13,'') -- ISNULL(A.COD_AGENTE,'')
						FROM	CDCSANTANAMicroCredito..TORG3 OP (NOLOCK) 
							) AS OPERADOR
				ON	O3CODORG = OpCodORG3  -- OPERADOR

		LEFT JOIN	(SELECT  * 
						FROM	CDCSANTANAMicroCredito..TORG4 OP (NOLOCK) 
							) AS LOJA
				ON	O4CODORG = OpCodORG4  -- OPERADOR
-- FIM NOVOS LIQUIDADOS COM RECEITA
WHERE O.OPNROPER NOT IN (SELECT OPNROPER FROM DRE_ATRASO (NOLOCK) WHERE  DT_FECHA=@DTREF)
-- 14 set 15
		AND	O.OPNROPER NOT IN (SELECT CONTRATOoriginal  FROM DRE_ATRASO T (NOLOCK) WHERE  DT_FECHA=@DTREF)


-- 11
-- AJUSTA AS RENEGOCIACOES ***************************** OUT-15
-- AJUSTA A QTD PARCELAS PAGAS DO CONTRATO ORIGINAL , P/ OS RENEGOCIADOS
--			OPQTDDPARC= (DRE_ATRASO.OPQTDDPARC  + OP.OPQTDDPARC),  -- PAGAS ORIGINAL + RENEGOC
UPDATE 		DRE_ATRASO
						-- RENEG   + PAGAS DO ORIGINAL
	SET		OPQTDDPARC= DRE_ATRASO.OPQTDDPARC  +(SELECT		COUNT(*) -- ORIGINAL PAGAS
							FROM	CDCSANTANAMicroCredito..CPARC OP (NOLOCK) 
							WHERE	DRE_ATRASO.CONTRATOoriginal =OP.PANROPER  -- BUSCA DADOS DO CONTRATO ORIGINAL ************
								AND OP.PADTLIQ < DRE_ATRASO.DT_BASE 
								AND OP.PACODREC='00001'  -- RECEBIDOS FINANCEIRO
								 -- BUSCA DADOS DO CONTRATO ORIGINAL ************
								AND OP.PACNTRL = (SELECT	MAX(PACNTRL)
													FROM	CDCSANTANAMicroCredito..CPARC P2 (NOLOCK) 
													WHERE	DRE_ATRASO.CONTRATOoriginal =P2.PANROPER 
														AND OP.PANRPARC = P2.PANRPARC	)	) ,
			PDECOR = (SELECT		COUNT(*) -- ORIGINAL PAGAS 
							FROM	CDCSANTANAMicroCredito..CPARC OP (NOLOCK) 
							WHERE	DRE_ATRASO.CONTRATOoriginal =OP.PANROPER  -- BUSCA DADOS DO CONTRATO ORIGINAL ************
								AND OP.PADTLIQ < DRE_ATRASO.DT_BASE   -- liq antes de renegocial
								AND OP.PACODREC='00001'  -- RECEBIDOS FINANCEIRO
								 -- BUSCA DADOS DO CONTRATO ORIGINAL ************
								AND OP.PACNTRL = (SELECT	MAX(PACNTRL)
													FROM	CDCSANTANAMicroCredito..CPARC P2 (NOLOCK) 
													WHERE	DRE_ATRASO.CONTRATOoriginal =P2.PANROPER 
														AND OP.PANRPARC = P2.PANRPARC	)	)
					+ DATEDIFF(MM,DT_BASE,@DTREF)  -- DECORRIDAS DO RENEG
	WHERE	DRE_ATRASO.DT_FECHA=@DTREF
		AND	RIGHT(DRE_ATRASO.OPNROPER ,1) IN ('A','B','C')	-- RENEGOCIADOS

-- 12
-- AJUSTA A QTD PARCELAS PAGAS DO CONTRATO ORIGINAL , + 1A RENEG	P/ OS RENEGOCIADOS B
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE 		DRE_ATRASO
	SET		OPQTDDPARC= DRE_ATRASO.OPQTDDPARC + (SELECT		COUNT(*) -- 1A RENEG PAGA
							FROM	CDCSANTANAMicroCredito..CPARC OP (NOLOCK) 
							WHERE	DRE_ATRASO.CONTRATOoriginal =OP.PANROPER  -- BUSCA DADOS DO CONTRATO ORIGINAL ************
								AND OP.PADTLIQ < DRE_ATRASO.DT_BASE 
								AND OP.PACODREC='00001'  -- RECEBIDOS FINANCEIRO
								AND OP.PACNTRL = (SELECT	MAX(PACNTRL)
													FROM	CDCSANTANAMicroCredito..CPARC P2 (NOLOCK) 
													WHERE	DRE_ATRASO.CONTRATOoriginal =P2.PANROPER 
														AND OP.PANRPARC = P2.PANRPARC	)	)
	WHERE	DRE_ATRASO.DT_FECHA=@DTREF
		AND	RIGHT(DRE_ATRASO.OPNROPER ,1) IN ('B','C')	-- RENEGOCIADOS

-- 13
-- SP_HELP DRE_ATRASO
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE 		DRE_ATRASO
	SET		LIBERADO = opvlrfin,
			-- LIB / TABELADO 
            TABELADO = (SELECT		ABVLRTAB FROM			CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
							WHERE	ABNROPER = DRE_ATRASO.CONTRATOoriginal 
								AND ABNRGAR='01'	-- alterado 2/1/17
								AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
												WHERE	B1.ABNROPER = DRE_ATRASO.CONTRATOoriginal AND B1.ABNRGAR='01')  ) ,

/*			-- maior garantia e seu controle		**************** 2/1/17 alterado pq tem garantia com MA
			and b.abNrGAR = (select max(abNrGAR) from CDCSANTANAMicroCredito..CBFIN B2 (NOLOCK)
								WHERE	B2.ABNROPER=B.ABNROPER)
			and b.abCntrl = (select max(abCntrl) from CDCSANTANAMicroCredito..CBFIN B3 (NOLOCK)
								WHERE	B3.ABNROPER=B.ABNROPER and b3.abNrGAR =b.abNrGAR)  */

-- calcular Pagas do Original + decorridas da RENEG acima Out15
--			PDECOR = DATEDIFF(MM,OP.OPDTBASE,@DTREF)  ,         -- ORIGINAL
			DT_BASE = OP.OPDTBASE
	FROM	CDCSANTANAMicroCredito..COPER OP (NOLOCK) 
	WHERE	DRE_ATRASO.DT_FECHA=@DTREF
		AND	RIGHT(DRE_ATRASO.OPNROPER ,1) IN ('A','B','C')	-- RENEGOCIADOS
		AND	DRE_ATRASO.CONTRATOoriginal =OP.OPNROPER  -- BUSCA DADOS DO CONTRATO ORIGINAL ************

-- AJUSTA O CONTRATO ORIGINAL
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE 		DRE_ATRASO
	SET		DRE_ATRASO.CONTRATOoriginal = LEFT(DRE_ATRASO.OPNROPER ,LEN(DRE_ATRASO.OPNROPER)-1)
	WHERE	DRE_ATRASO.DT_FECHA=@DTREF
		AND	RIGHT(DRE_ATRASO.OPNROPER ,1) IN ('A','B','C')	-- RENEGOCIADOS

-- FIM AJUSTE DAS RENEGOCIACOES ***************************** OUT-15



-- AJUSTE DA IDADE 
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.IDADE=	18
	WHERE	DT_FECHA=@DTREF AND IDADE <18

-- OUTRAS RENDAS
-- RENDA OUTRAS
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.CLRENDA=	ISNULL(DRE_ATRASO.CLRENDA,0.0) + ISNULL(CASE WHEN clOutrenda> 900000.0 THEN 0.0 ELSE clOutrenda END ,0.0),
			OCUPACAO = 		CASE CLCODOCUP 
								  WHEN '01' THEN 'CLT' 
								  WHEN '02' THEN 'AUTONOMO' 
								  WHEN '03' THEN 'APOSENTADO' 
								  WHEN '04' THEN 'EMPRESARIO'
								  ELSE 'S/ INFO' 
							END ,
			TIPO_CASA = C.CLTPRES
	FROM	CDCSANTANAMicroCredito..COPER O (NOLOCK)
--	JOIN 	CDCSANTANAMicroCredito..ccliE C (NOLOCK) 
	JOIN 	PROPWEBSMC..cclip C (NOLOCK) 
	ON		OPCODCLI =CLCODCLI
	WHERE	DT_FECHA=@DTREF
		AND DRE_ATRASO.OPNROPER =O.OPNROPER

-- RENDA EM SM
-- SELECT * FROM TSM (NOLOCK)
-- SELECT * FROM CDCSANTANAMicroCredito..ccliE C (NOLOCK) 
-- sp_help  TSM
--	declare @DTREF datetime set @DTREF ='20170430'
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.CLRENDA=	DRE_ATRASO.CLRENDA /vlr_SM
	FROM	TSM O (NOLOCK)
	WHERE	DT_FECHA=@DTREF
		AND	DT_DE = (SELECT MAX(DT_DE) FROM	TSM S (NOLOCK) WHERE DT_DE <=@DTREF)
-- CORRECAO PARA RENDAS BAIXAS PQ CADASTRO
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.CLRENDA=	1.0
	WHERE	DT_FECHA=@DTREF
		AND	CLRENDA < 1.0

-- OCUPACAO


-- LOAN ********************
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.LOAN=	DRE_ATRASO.LIBERADO /TABELADO
	WHERE	DT_FECHA=@DTREF
		AND	TABELADO <>0.0
-- AJUSTA SE MAIOR Q 1
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.LOAN=	1.0
	WHERE	DT_FECHA=@DTREF
		AND	LOAN >1.0

-- IMPOSTOS  ISS (5%)  PIS (0,65%) COFINS (4%)
-- SOBRE VLR_RECEITA = VF - VP
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_ISS=	DRE_ATRASO.TC * 5.00 / 100.00 ,
			DRE_ATRASO.VLR_PIS=	DRE_ATRASO.VLR_RECEITA * 0.65 / 100.00 ,
			DRE_ATRASO.VLR_COFINS=	DRE_ATRASO.VLR_RECEITA * 4.00 / 100.00 
	WHERE	DT_FECHA=@DTREF
		AND	PDECOR = 0 AND DESCR_TIPO <> 'Renegociacao'

 

-- VLR TABELADO NULL CONTRATOS ANTIGOS
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.TABELADO=   (SELECT	ABVLRVND 
									FROM	CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
									WHERE	ABNROPER = DRE_ATRASO.OPNROPER AND ABNRGAR='01'  -- alterado 2/1/17
										AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
														WHERE	B1.ABNROPER = DRE_ATRASO.OPNROPER
															AND B1.ABNRGAR='01'))
	WHERE	DT_FECHA=@DTREF
		AND DRE_ATRASO.TABELADO IS NULL

-- VLR TABELADO NULL CONTRATOS ANTIGOS
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.TABELADO=   (SELECT	ABVLRVND 
									FROM	CDCSANTANAMicroCredito..cbfiN O (NOLOCK) 		
									WHERE	ABNROPER = DRE_ATRASO.contratoOriginal AND ABNRGAR='01'   -- alterado 2/1/17
										AND ABCNTRL = (SELECT MAX(B1.ABCNTRL) FROM CDCSANTANAMicroCredito..cbfiN B1 (NOLOCK) 	
														WHERE	B1.ABNROPER = DRE_ATRASO.contratoOriginal
															AND B1.ABNRGAR='01'))
	WHERE	DT_FECHA=@DTREF
		AND DRE_ATRASO.TABELADO IS NULL


-- ZERAR A RECEITA	FINANCEIRA	******************
--	 UPDATE		DRE_ATRASO 	SET 	DRE_ATRASO.VLR_RECEITA= 0.0 WHERE	DT_FECHA='20150430'
 UPDATE		DRE_ATRASO 	SET 	DRE_ATRASO.VLR_RECEITA_FIN= 0.0 WHERE	DT_FECHA=@DTREF


-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'
/*  CONSIDERA SOMENTE O CONTABIL
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_RECEITA= -- PAVLRJR 	FROM	
			(SELECT SUM(PAVLRJR) FROM CDCSANTANAMicroCredito..CPARC C (NOLOCK) 		
				WHERE	PANROPER = DRE_ATRASO.OPNROPER AND PANRPARC=DRE_ATRASO.PARC 
--					AND	PADTVCTO<=@DTREF						 -- PARCELAS VENCIDAS
--					AND (PADTLIQ IS NOT NULL OR PADTLIQ<@DTREF)  -- NAO PAGOS
					AND PACNTRL = (SELECT MAX(B1.PACNTRL) FROM CDCSANTANAMicroCredito..CPARC B1 (NOLOCK) 	
									WHERE	B1.PANROPER = DRE_ATRASO.OPNROPER
										AND B1.PANRPARC = DRE_ATRASO.PARC) )
WHERE	DT_FECHA=@DTREF
	AND NVL_RISCO <>''			-- SEM O DIFERIMENTO DA COMISSAO		
	AND PARC <> NULL
*/

-- CREATE TABLE AUX_JR (OPNROPER VARCHAR(20), DTBASE DATETIME, DTVCTO DATETIME, VLR_JR FLOAT)
-- TABLE AUXILIAR COM CONTRATOS
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430' DECLARE @DTINI DATETIME SET @DTINI ='20150401'
DELETE AUX_JR
INSERT AUX_JR
SELECT	OPNROPER, DT_BASE,
		-- VCTO 31, MES REF 30 -- USAR DT REF   SENAO   DIA DO VCTO	
		CASE WHEN	DATEPART(DAY,@DTREF) < DATEPART(DAY,DT_BASE) THEN @DTREF
			 ELSE	CONVERT(VARCHAR(4),DATEPART(YEAR,@DTREF))+RIGHT(RTRIM('00'+CONVERT(VARCHAR(2),DATEPART(MONTH,@DTREF))),2)+RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(DAY,DT_BASE))),2)
			 END	, 0.0
FROM	DRE_ATRASO (NOLOCK)
WHERE	DT_FECHA=@DTREF
--	COM OS LIQUIDADOS NO MES **************
--	AND NVL_RISCO <>''			-- SEM O DIFERIMENTO DA COMISSAO		
--	AND PARC <> NULL

-- DECLARE @DTINI AS SMALLDATETIME
-- DIA 1 DO MES DO FECHAMENTO
-- SET		@DTINI =  CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+'01'

-- APROPRIACAO DE JR NO VCTO DA PARCELA
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'
-- SELECT CONVERT(DATETIME,'20150430',120)
-- SELECT CONVERT(DATETIME,CONVERT(CHAR(4),DATEPART(YEAR,'20150430'))+			RIGHT('00'+RTRIM(CONVERT(CHAR(2),DATEPART(MONTH,'20150430'))),2)+			RIGHT('00'+RTRIM(CONVERT(CHAR(2),DATEPART(DAY,'20150415'))),2),120)
/*
UPDATE  AUX_JR
SET		DTVCTO= CONVERT(DATETIME,CONVERT(CHAR(4),DATEPART(YEAR,@DTREF))+
			RIGHT('00'+RTRIM(CONVERT(CHAR(2),DATEPART(MONTH,@DTREF))),2)+
			RIGHT('00'+RTRIM(CONVERT(CHAR(2),DATEPART(DAY,DTBASE))),2),112)
*/

-- APROPRIACAO DE JR NO MES DIARIA   -- RECEITA DE JUROS
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430' DECLARE @DTINI DATETIME SET @DTINI ='20150401'
UPDATE  AUX_JR
SET		VLR_JR= (SELECT SUM(EXVLRMOV) FROM CDCSANTANAMicroCredito..ECONT C (NOLOCK) 		
				WHERE	EXNROPER = AUX_JR.OPNROPER 
					AND	EXCODHIS IN ( 'A304','A312','A412' ,'A508',  'N202', 'N304','N404'  )
			--		AND EXCODHIS IN ( 'N202','A508','A304','A312','A412'  )
			-- VLR ALTO
			--					AND EXCODHIS IN ( 'A202', 'A203','N202','N203','C202','C203','P202','P203')
			--		APROPRIACAO CONTABIL 
					AND	EXDTLNC  BETWEEN  @DTINI AND  @DTREF)

-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_RECEITA_FIN= DRE_ATRASO.VLR_RECEITA_FIN + ISNULL(AUX_JR.VLR_JR,0.0)
	FROM	AUX_JR		(NOLOCK)
	WHERE	DT_FECHA  =  @DTREF
		AND DRE_ATRASO.OPNROPER = AUX_JR.OPNROPER
	-- COM OS LIQUIDADOS NO MES
--		AND NVL_RISCO <> ''			-- SEM O DIFERIMENTO DA COMISSAO		
--		AND PARC <> NULL


-- CALCULAR RECEITA DE ATRASO  ****************************************************** CONTAS DIFERENTES
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430' DECLARE @DTINI DATETIME SET @DTINI ='20150401'
UPDATE  AUX_JR
SET		VLR_JR= 0.0

-- APROPRIACAO DE JR 
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430' DECLARE @DTINI DATETIME SET @DTINI ='20150401'
UPDATE  AUX_JR
SET		VLR_JR= ISNULL((SELECT SUM(EXVLRMOV) FROM CDCSANTANAMicroCredito..ECONT C (NOLOCK) 		
				WHERE	EXNROPER = AUX_JR.OPNROPER 
					AND	EXCODHIS IN ( 'A370','A371', 'N370','N371'  )
			--		atraso juros CONTABIL 
					AND	EXDTLNC  BETWEEN  @DTINI AND  @DTREF),0.0)

UPDATE  AUX_JR
SET		VLR_JR= ISNULL(VLR_JR,0.0)-ISNULL((SELECT SUM(EXVLRMOV) FROM CDCSANTANAMicroCredito..ECONT C (NOLOCK) 		
				WHERE	EXNROPER = AUX_JR.OPNROPER 
					AND	EXCODHIS IN ( 'A470','A471', 'N470','N471'  )
			--		atraso estorno CONTABIL 
					AND	EXDTLNC  BETWEEN  @DTINI AND  @DTREF),0.0)

-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_RECEITA_ATRASO= ISNULL(DRE_ATRASO.VLR_RECEITA_ATRASO,0.0) + ISNULL(AUX_JR.VLR_JR,0.0)
	FROM	AUX_JR		(NOLOCK)
	WHERE	DT_FECHA  =  @DTREF
		AND DRE_ATRASO.OPNROPER = AUX_JR.OPNROPER


-- DADOS DOS VEICULOS ********************* SET-15
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.ANO_VEICULO=   (SELECT		SUM(DRE.SLDO_INSCRITO) 
											FROM	DRE_ATRASO DRE (NOLOCK) 	WHERE	DT_FECHA=@DTREF	)
	WHERE	DT_FECHA=@DTREF



		-- ANO MODELO ********************
		UPDATE		DRE_ATRASO
		SET		ANO_VEICULO = ISNULL(ABANOMOD,'S/INF') , -- com Ano Modelo
				MODELO		= ISNULL(ABMODELO,'S/INF')
-- SELECT * 
		FROM	CDCSANTANAMicroCredito..CBFIN B (NOLOCK)
		WHERE	DT_FECHA  = @DTREF
			AND	OPNROPER  = B.ABNROPER
			AND B.ABCNTRL = (SELECT		MAX(BX.ABCNTRL) 
								FROM	CDCSANTANAMicroCredito..CBFIN BX (NOLOCK) 
								WHERE	BX.ABNROPER = B.ABNROPER and Bx.ABNRGAR = '01')  -- alterado 2/1/17
			AND B.ABNRGAR = '01'


-- SOMENTE  NA PRODUCAO
-- SELECT * FROM MASTER..crivo_proposta
-- SELECT * FROM DRE_ATRASO WHERE DT_FECHA ='20150430'
		-- SCORE  VEIC ****************
		-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'
		-- SP_HELP DRE_ATRASO
		UPDATE		DRE_ATRASO
			SET		SCORE = VEIC.SCORE
			FROM  (select distinct proposta ,   opnroper,  score  
						from CDCSANTANAMicroCredito..coper  (NOLOCK),
								MASTER..crivo_proposta  (NOLOCK)
						where OPNRPROP = proposta  
							and OPDTBASE >= '2014-01-01' 		) AS VEIC
			WHERE	DRE_ATRASO.DT_FECHA	= @DTREF
				AND DRE_ATRASO.OPNROPER  = VEIC.OPNROPER

-- VEICULO ORIGINAL NO RENEGOCIADO ****************** OUT-15
-- DECLARE @DTREF DATETIME SET @DTREF ='20150531'
UPDATE		DRE_ATRASO
	SET		DESCR_TIPO = MOD.DESCR_TIPO
	FROM    CDCSANTANAMicroCredito..COPER O (NOLOCK)
		JOIN (SELECT	M.COD_MODA, DESCR_TIPO
						FROM	 Ttipo_prod T (NOLOCK), TModa_tipo_prod M (NOLOCK)  
						WHERE	M.COD_PROD = T.COD_PROD 
							AND T.COD_MODALIDADE = M.COD_MODALIDADE 
						AND T.COD_PROD IN ( 'V' ) ) AS MOD
				ON OPCODOP =  COD_MODA
	WHERE	DRE_ATRASO.DT_FECHA	= @DTREF
		AND RIGHT(DRE_ATRASO.OPNROPER,1) IN ('A','B','C')  -- RENEG
		-- CONTRATO ORIGINAL
		AND LEFT(DRE_ATRASO.OPNROPER,LEN(DRE_ATRASO.OPNROPER)-1)  = O.OPNROPER
	--   LISTA COM MODALIDADES DO PRODUTO VEIC E RENEGOCIADOS
	
/*
DECLARE @RECEITA_ATRASO FLOAT
SET @RECEITA_ATRASO =	(SELECT	SUM(MOV_D_C)
	FROM	GER_BASE_BALANCETE (NOLOCK) 
	WHERE	DT_FECHA=@DTREF AND EMPRESA=99
		AND CONTA  IN ('894201000100000000') )
SET @TRIBUTO_CSSL_VEIC = @TRIBUTO_CSSL_TTL / @CARTEIRA_TTL * @CARTEIRA_VEICULOS
*/

-- SP_HELP DRE_ATRASO
-- SOMA A APROPRIACAO FINANCEIRA DO RENDAS A APROPRIAR
-- RECEITA PELA PARCELA  1MIN28
-- DECLARE @DTREF DATETIME SET @DTREF ='20150430'  DECLARE @DTINI DATETIME SET @DTINI ='20150401'
-- RECEITA  SALDO A APROPRIAR
--  SELECT  * FROM CDCSANTANAMicroCredito..ECONT (NOLOCK) 	WHERE EXNROPER ='55003322' AND EXCODHIS ='A303' AND EXDTLNC='20150731'
/*
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_RECEITA= DRE_ATRASO.VLR_RECEITA + 
			ISNULL((SELECT SUM(EXVLRMOV) FROM CDCSANTANAMicroCredito..ECONT C (NOLOCK) 		
				WHERE	EXNROPER = DRE_ATRASO.OPNROPER 
					AND EXCODHIS IN ( 'A202', 'A203','N202','N203','C202','C203','P202','P203')
		--		APROPRIACAO CONTABIL  N202     A303
					AND	EXDTLNC  BETWEEN @DTINI AND @DTREF 
					AND EXDTLNC =(SELECT MAX(EXDTLNC) FROM CDCSANTANAMicroCredito..ECONT C2 (NOLOCK) 
									WHERE	EXNROPER = DRE_ATRASO.OPNROPER 
										AND EXDTLNC BETWEEN '20150401' AND @DTREF 
										AND EXCODHIS IN ( 'A202', 'A203','N202','N203','C202','C203','P202','P203')  )
				) , 0.0)
WHERE	DT_FECHA  =  @DTREF
	AND NVL_RISCO <> ''			-- SEM O DIFERIMENTO DA COMISSAO		
	AND PARC <> NULL
--	AND PARC.PANROPER = DRE_ATRASO.OPNROPER AND PANRPARC=DRE_ATRASO.PARC 


-- LCTO
SELECT * FROM CDCSANTANAMicroCredito..ECONT C (NOLOCK) 		
				WHERE	EXNROPER = '552010598'
AND EXDTLNC BETWEEN '20150401' AND '20150430'
AND EXCODHIS IN ( 'A202', 'A203','N202','N203','C202','C203','P202','P203')
AND EXDTLNC =(SELECT MAX(EXDTLNC) FROM CDCSANTANAMicroCredito..ECONT C2 (NOLOCK) 
				WHERE	EXNROPER = '552010598'
					AND EXDTLNC BETWEEN '20150401' AND '20150430'
					AND EXCODHIS IN ( 'A202', 'A203','N202','N203','C202','C203','P202','P203')  )


UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.VLR_RECEITA= -- PAVLRJR 	FROM	
			(SELECT SUM(PAVLRJR) FROM CDCSANTANAMicroCredito..CPARC C (NOLOCK) 		
				WHERE	PANROPER = DRE_ATRASO.OPNROPER AND PANRPARC=DRE_ATRASO.PARC 
					AND	PADTVCTO<=@DTREF
					--  AND (PADTLIQ IS NOT NULL OR PADTLIQ<@DTREF)
					AND PACNTRL = (SELECT MAX(B1.PACNTRL) FROM CDCSANTANAMicroCredito..CPARC B1 (NOLOCK) 	
									WHERE	B1.PANROPER = DRE_ATRASO.OPNROPER
										AND B1.PANRPARC = DRE_ATRASO.PARC) )
WHERE	DT_FECHA=@DTREF
	AND NVL_RISCO <>''			-- SEM O DIFERIMENTO DA COMISSAO		

SP_HELP DRE_ATRASO
SELECT top 100 * FROM CDCSANTANAMicroCredito..ECONT (NOLOCK) 		
SELECT * FROM CDCSANTANAMicroCredito..CPARC C (NOLOCK) 		
				WHERE	PANROPER = '612082536'

SELECT * FROM BACENSANTANAMicroCredito..eclas C (NOLOCK) 		
				WHERE	--CSDTREF='20150630' 
CSNROPER = '612093795'

SP_HELP DRE_ATRASO 
-- PROPORCAO_CARTEIRA VEICULOS
UPDATE		DRE_ATRASO 
	SET 	DRE_ATRASO.PROPORCAO_CARTEIRA=   DRE_ATRASO.SLDO_INSCRITO / 
										(SELECT		SUM(DRE.SLDO_INSCRITO) 
											FROM	DRE_ATRASO DRE (NOLOCK) 	WHERE	DT_FECHA=@DTREF	)
	WHERE	DT_FECHA=@DTREF
*/

-- remove 353 cg
-- 353
DELETE		DRE_ATRASO 
	WHERE	DT_FECHA=@DTREF AND (LEFT(OPNROPER ,3) IN ( '353','103') OR LEFT(OPNROPER,2) ='36' )

-- CP
DELETE		DRE_ATRASO 
	WHERE	DT_FECHA=@DTREF AND OPNROPER IN ('10318990')

DELETE		DRE_ATRASO 
	WHERE	DT_FECHA=@DTREF AND DESCR_TIPO IN ('Renegociacao', 'Crédito Pessoal - Renegociação')


END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
