
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go


SELECT 
		DESCR_TIPO	AS SEGMENTO,
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_FECHA))),2)+'/'+ 
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_FECHA))),2) +'/'+
		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_FECHA))		AS DATA_BASE,
		ISNULL(CONTRATOoriginal,OPNROPER ) AS CONTRATO_ORIGINAL,
		NVL_RISCO	AS NIVEL_RISCO, 
		LOAN		AS LOAN_TO_VALUE,
		OPQTDDPARC	AS PRAZO_CONTRATO,
		PDECOR		AS NUMERO_PARCELA,
		CLCEPFIS	AS CEP_CLIENTE,
		CLCIDFIS	AS CIDADE_CLIENTE,
		CLUFFIS		AS ESTADO_CLIENTE,
		CLRENDA		AS RENDA_CLIENTE,
		OCUPACAO	AS OCUPACAO_CLIENTE,
		IDADE		AS IDADE_CLIENTE,
		ClSexo		AS SEXO,

		CASE WHEN ClESTciv='1'  THEN 'SOLTEIRO'
			 WHEN ClESTciv='2'  THEN 'CASADO'
			 WHEN ClESTciv='3'  THEN 'DESQUITADO'
			 WHEN ClESTciv='4'  THEN 'DIVORCIADO'
			 WHEN ClESTciv='5'  THEN 'VIUVO'
			 WHEN ClESTciv='9'  THEN 'OUTROS'
			 ELSE '' END	
			AS ESTADO_CIVIL,
			
		CASE WHEN TIPO_CASA='A' THEN 'Alugada'
			 WHEN TIPO_CASA='C' THEN 'C/Pais'
			 WHEN TIPO_CASA='D' THEN 'De Familiares'
			 WHEN TIPO_CASA='E' THEN 'Da Empresa'
			 WHEN TIPO_CASA='F' THEN 'Financiada'
			 WHEN TIPO_CASA='H' THEN 'Hotel'
			 WHEN TIPO_CASA='O' THEN 'Outros'
			 WHEN TIPO_CASA='P' THEN 'Própria'
			 ELSE '' END AS TIPO_CASA_CLIENTE,

		LojaCod AS LOJA,
		LojaCEP AS CEP_LOJA,
		LojaCIDADE AS CIDADE_LOJA,
		LojaUF	AS UF_LOJA,
		AGENTEcod AS AGENTE,
		OperadorCod	AS OPERADOR,
		--''	AS 
		RWA_VEICULOS,
		TC		AS TARIFA_CONTRATACAO,
		--DESP_PESSOAL_SUP
		DESPESA_CADASTRO AS CUSTO_CONTRATACAO,

		CASE WHEN	DATEPART(YYYY,DT_BASE) = 2015 AND DATEPART(YYYY,@DTREF) = 2015  -- 2015
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
					-- VLR_COMISSAO  = 1,5% + parte TC
					-- REPASSE_AGENTE_PROMOT = parte TC
			 WHEN	DATEPART(YYYY,DT_BASE) = 2014 AND DATEPART(YYYY,@DTREF) = 2014	-- 2014
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2013 AND DATEPART(YYYY,@DTREF) = 2013	-- 2013
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2012 AND DATEPART(YYYY,@DTREF) = 2012	-- 2012
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2011 AND DATEPART(YYYY,@DTREF) = 2011	-- 2011
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2010 AND DATEPART(YYYY,@DTREF) = 2010	-- 2010
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN   PDECOR	BETWEEN 1 AND	OPQTDDPARC  -- NO PRAZO DO CONTRATO
				THEN	ISNULL(VLR_RETORNO,0.0) --  RETORNO DIFERIDO
			 ELSE	0.0 
			 END 	AS CUSTO_COMISSAO,

		ISNULL(VLR_RECEITA_FIN,0.0) AS RECEITA_FINANCEIRA,
		DESP_CAPT_OPER AS CUSTO_FUNDING,

		--  FALTA
		case when datepart(mm,DT_FECHA) = 12 then CUSTO_MANUTENCAO/1.0 else CUSTO_MANUTENCAO end as CUSTO_MANUTENCAO, 
		MARGEM_CAIXA, 

		VLR_RECEITA_ATRASO AS RECEITA_ATRASO,

		--  FALTA
		CUSTO_COBRANCA, 
		DESPESA_ATRASO, 

		PDD  AS DESPESA_PROVISAO, 

		-- IMPOSTOS PAGOS NA CABECA + IR E CSLL RATEADOS
		CASE WHEN	DATEPART(YYYY,DT_BASE) = DATEPART(YYYY,@DTREF) 
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,@DTREF)THEN
					ISNULL(VLR_ISS,0.0) + ISNULL(VLR_PIS,0.0) + ISNULL(VLR_COFINS,0.0) 
			ELSE 0.0 END + vlr_IRPJ + vlr_CSSL
		AS TRIBUTOS,

		'01/'+ 		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))),2) +'/'
		+ CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))	 AS DATA_SAFRA
		, ANO_VEICULO, MODELO, SCORE,
		CASE WHEN RIGHT(OPNROPER,1) IN ('A','B','C') THEN 'R' ELSE '' END AS RENEGOCIADO

	FROM	DRE_ATRASO (NOLOCK)
	WHERE	DT_FECHA  between '20110101' and '20150831' 
