
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


use SIG
go


--  declare @DTREF DATETIME SET @DTREF ='20150430'
--		declare @DTREF DATETIME SET @DTREF ='20150131'
--		declare @DTREF DATETIME SET @DTREF ='20150531'
SELECT 
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_FECHA))),2)+'/'+ 
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_FECHA))),2) +'/'+
		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_FECHA))		AS DATA_BASE,

/*
		DESCR_TIPO	AS SEGMENTO,
		ISNULL(CONTRATOoriginal,OPNROPER ) AS CONTRATO_ORIGINAL,
		NVL_RISCO	AS NIVEL_RISCO, 
		LOAN		AS LOAN_TO_VALUE,
		OPQTDDPARC	AS PRAZO_CONTRATO,
		PDECOR		AS NUMERO_PARCELA,
		CLCEPFIS	AS CEP_CLIENTE,
		CLCIDFIS	AS CIDADE_CLIENTE,
		CLUFFIS		AS ESTADO_CLIENTE,
		CLRENDA		AS RENDA_CLIENTE,
		OCUPACAO	AS OCUPACAO_CLIENTE,
		IDADE		AS IDADE_CLIENTE,
		ClSexo		AS SEXO,

		CASE WHEN ClESTciv='1'  THEN 'SOLTEIRO'
			 WHEN ClESTciv='2'  THEN 'CASADO'
			 WHEN ClESTciv='3'  THEN 'DESQUITADO'
			 WHEN ClESTciv='4'  THEN 'DIVORCIADO'
			 WHEN ClESTciv='5'  THEN 'VIUVO'
			 WHEN ClESTciv='9'  THEN 'OUTROS'
			 ELSE '' END	
			AS ESTADO_CIVIL,
			
		CASE WHEN TIPO_CASA='A' THEN 'Alugada'
			 WHEN TIPO_CASA='C' THEN 'C/Pais'
			 WHEN TIPO_CASA='D' THEN 'De Familiares'
			 WHEN TIPO_CASA='E' THEN 'Da Empresa'
			 WHEN TIPO_CASA='F' THEN 'Financiada'
			 WHEN TIPO_CASA='H' THEN 'Hotel'
			 WHEN TIPO_CASA='O' THEN 'Outros'
			 WHEN TIPO_CASA='P' THEN 'Própria'
			 ELSE '' END AS TIPO_CASA_CLIENTE,

		LojaCod AS LOJA,
		LojaCEP AS CEP_LOJA,
		LojaCIDADE AS CIDADE_LOJA,
		LojaUF	AS UF_LOJA,
		AGENTEcod AS AGENTE,
		OperadorCod	AS OPERADOR,
		--''	AS 
*/
		sum(RWA_VEICULOS) as RWA_VEICULOS,

		sum(TC)		AS TARIFA_CONTRATACAO,
		--DESP_PESSOAL_SUP
		sum(DESPESA_CADASTRO) AS CUSTO_CONTRATACAO,

--		ISNULL(VLR_COMISSAO_TERCO_AV,0.0) +ISNULL(VLR_COMISSAO_DIFERIDA_36AVOS,0.0) AS CUSTO_COMISSAO,
-- AGO15
/*
		sum(CASE WHEN	DATEPART(YYYY,DT_BASE) = 2015 AND DATEPART(YYYY,DT_FECHA) = 2015  -- 2015
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
--					ISNULL(VLR_RETORNO,0.0) + ISNULL(VLR_COMISSAO,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2014 AND DATEPART(YYYY,DT_FECHA) = 2014	-- 2014
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2013 AND DATEPART(YYYY,DT_FECHA) = 2013	-- 2013
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2012 AND DATEPART(YYYY,DT_FECHA) = 2012	-- 2012
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2011 AND DATEPART(YYYY,DT_FECHA) = 2011	-- 2011
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2010 AND DATEPART(YYYY,DT_FECHA) = 2010	-- 2010
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN   PDECOR	BETWEEN 1 AND	OPQTDDPARC  -- NO PRAZO DO CONTRATO
				THEN	ISNULL(VLR_RETORNO,0.0) --  RETORNO DIFERIDO
			 ELSE	0.0 
			 END  )	AS CUSTO_COMISSAO,
*/

-- SET15
		SUM(CASE WHEN	DATEPART(YYYY,DT_BASE) = 2015 AND DATEPART(YYYY,DT_FECHA) = 2015  -- 2015
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
					-- VLR_COMISSAO  = 1,5% + parte TC
					-- REPASSE_AGENTE_PROMOT = parte TC
			 WHEN	DATEPART(YYYY,DT_BASE) = 2014 AND DATEPART(YYYY,DT_FECHA) = 2014	-- 2014
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2013 AND DATEPART(YYYY,DT_FECHA) = 2013	-- 2013
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2012 AND DATEPART(YYYY,DT_FECHA) = 2012	-- 2012
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2011 AND DATEPART(YYYY,DT_FECHA) = 2011	-- 2011
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN	DATEPART(YYYY,DT_BASE) = 2010 AND DATEPART(YYYY,DT_FECHA) = 2010	-- 2010
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					--ISNULL(VLR_COMISSAO_TERCO_AV,0.0) 
					ISNULL(VLR_RETORNO,0.0) + ISNULL(vlr_comissao_15,0.0) +ISNULL(REPASSE_AGENTE_PROMOT,0.0) 
			 WHEN   PDECOR	BETWEEN 1 AND	OPQTDDPARC  -- NO PRAZO DO CONTRATO
				THEN	ISNULL(VLR_RETORNO,0.0) --  RETORNO DIFERIDO
			 ELSE	0.0 
			 END) 	AS CUSTO_COMISSAO,

-- AGO 15
--		sum(ISNULL(VLR_RECEITA,0.0)) AS RECEITA_FINANCEIRA,

-- SET 15
		sum(ISNULL(VLR_RECEITA_FIN,0.0)) AS RECEITA_FINANCEIRA,

		sum(DESP_CAPT_OPER) AS CUSTO_FUNDING,

		
		--case when datepart(mm,DT_FECHA) = 12 then CUSTO_MANUTENCAO/1.0 else CUSTO_MANUTENCAO end as CUSTO_MANUTENCAO, 
		sum(CUSTO_MANUTENCAO)  as CUSTO_MANUTENCAO, 
		sum(MARGEM_CAIXA) as MARGEM_CAIXA, 

		/*CASE WHEN NVL_RISCO_ANT ='HH' AND NVL_RISCO='' THEN PDD * (-1.00) +ISNULL(PASLDXMLT,0.0)+ISNULL(PASLDXMR,0.0) 
				ELSE ISNULL(PASLDXMLT,0.0)+ISNULL(PASLDXMR,0.0)  END	
		AS */ 
		sum(VLR_RECEITA_ATRASO) AS RECEITA_ATRASO,

		
		sum(CUSTO_COBRANCA) as CUSTO_COBRANCA, 
		sum(DESPESA_ATRASO) as DESPESA_ATRASO, 

		sum(PDD)  AS DESPESA_PROVISAO, 

		--ISNULL(VLR_IOF,0.0)  SEM IOF 12 GER X 122 FUNCAO
-- AGO15
--		sum(ISNULL(VLR_ISS,0.0) + ISNULL(VLR_PIS,0.0) + ISNULL(VLR_COFINS,0.0) +				ISNULL(vlr_IRPJ,0.0)+ISNULL(VLR_CSSL,0.0) - ISNULL(VLR_CRED_TRIB,0.0)+ ISNULL(OUTRAS_TX,0.0))

-- SET 15
		SUM(CASE WHEN	DATEPART(YYYY,DT_BASE) = DATEPART(YYYY,DT_FECHA) 
				AND	DATEPART(MM,DT_BASE)   = DATEPART(MM,DT_FECHA)THEN
					ISNULL(VLR_ISS,0.0) + ISNULL(VLR_PIS,0.0) + ISNULL(VLR_COFINS,0.0) 
			ELSE 0.0 END + vlr_IRPJ + vlr_CSSL )
		AS TRIBUTOS


/*,
		--RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_BASE))),2)+
		'01/'+ 		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_BASE))),2) +'/'
		+ CONVERT(VARCHAR(4),DATEPART(YYYY,DT_BASE))	 AS DATA_SAFRA

		PASLDXMLT,
		PASLDXMR,
		PDD,
		VLR_PDD_ATU,
		VLR_PDD_ANT,
		NVL_RISCO_ANT,
		VLR_PARCELA,
		VLR_RETORNO,
		VLR_RECEITA,
		VLR_IOF,
		VLR_ISS,
		VLR_PIS,
		VLR_COFINS,
		VLR_CAPTACAO,
		vlr_IRPJ,
		VLR_CSSL,
		VLR_CRED_TRIB,
		OUTRAS_TX,
		REC_APLIC_SLDO_CX,
		REPASSE_AGENTE_6P,
		RETORNO_LOJA,
		REPASSE_AGENTE_PROMOT,
		DESP_CAPT_SLD_CX,
		DESP_CAPT_OPER,
		DESP_PESSOAL_VDA,
		DESP_PESSOAL_SUP,
		SLDO_INSCRITO,
		PROPORCAO_CARTEIRA,
		VLR_COMISSAO,
		VLR_COMISSAO_TERCO_AV,
		VLR_COMISSAO_DIFERIDA_36AVOS,
		VLR_FINANCIADO  AS VLR_OPERADO,
		DT_BASE,
		vlr_comissao_diferida_pzo_Op,
		COMISSAO_AV,
		SLD_DIFERIR_2_3,
		OPNROPER,	
		PARC,
		LIBERADO,
		TABELADO,
		OPTAC,
		COMISSAO_2_3,
		VLR_COMISSAO_15,
		DESPESA_CONTRATO,
		DESPESA_CADASTRO,
DESPESA_COMERCIAL,
CM_TARIFA,
CM_PROVISAO,
CM_TARIFA_DESPESA,
CM_IMOBILIZADO,
CM_DESP_PESSOAL,
CM_DIRETORIA,
CM_ALUGUEL,
CM_ADM_FIXA,
CM_ADM_VAR,
CM_ADM_OUTRAS_TTL2,
CM_ADM_OUTRAS_TTL3,
CM_ADM_VAR_COM,
CUSTO_COBRANCA,
DESPESA_ATRASO,
VLR_IMPOSTOS,
VLR_LUCRO_BRUTO,
CUSTO_MANUTENCAO,
VLR_RECEITA_ATRASO 
*/
	FROM	DRE_ATRASO (NOLOCK)
-- WHERE	DT_FECHA = @DTREF

--WHERE	DT_FECHA IN ( '20140430','20150430') 

-- WHERE	DT_FECHA = '20130331' 
-- WHERE	DT_FECHA BETWEEN '20140101' AND '20141231'

--	WHERE	DT_FECHA BETWEEN '20130101' AND '20130731'
--	WHERE	DT_FECHA BETWEEN '20130101' AND '20131231'
--	WHERE	DT_FECHA BETWEEN '20150101' AND  '20151231'
--'20150228'


group by
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(DD,DT_FECHA))),2)+'/'+ 
		RIGHT('00'+RTRIM(CONVERT(VARCHAR(2),DATEPART(MM,DT_FECHA))),2) +'/'+
		CONVERT(VARCHAR(4),DATEPART(YYYY,DT_FECHA))		

/*
SELECT	*	FROM	GER_BASE_BALANCETE (NOLOCK) 
	WHERE	DT_FECHA='20150430' AND EMPRESA=99
		AND CONTA  IN (

-- ******* REMOVI P/ TESTE 2-SET-2015 
 '817571005100000000',	--	8.1.7.57.10.051-9		Com. Cobrança Santana CFI - NF Promotora	-- *************Custo de Cobrança
 '817571099900000000' )

SELECT	*	FROM	GER_BASE_BALANCETE (NOLOCK) 
	WHERE	DT_FECHA='20150430' AND EMPRESA=99
		AND CONTA  IN (

-- ******* REMOVI P/ TESTE 2-SET-2015 
 '817571005100000000',	--	8.1.7.57.10.051-9		Com. Cobrança Santana CFI - NF Promotora	-- *************Custo de Cobrança
 '817571099900000000' )
	--	8.1.7.57.10.999-8		Com. Cobrança Santana CFI - NF Promotora	-- *************Custo de Cobrança
-- ******* FIM    REMOVI P/ TESTE 2-SET-2015

select * from dre_atraso (nolock) where dt_fecha='20150630'

select * from rating_historico (nolock) where num_ope='612120663A'
select * from rating_historico (nolock) where num_ope='612120663'

select * from rating_historico (nolock) where num_ope='61641704A'
select * from rating_historico (nolock) where num_ope='61641704'


*/



--	WHERE	DT_FECHA BETWEEN '20140101' AND '20141231'

