'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Componentes.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;script language=&quot;JavaScript&quot;&gt;
        '''	function HierarGrid_toggleRow(sender)
        '''	{
        '''		if(sender == null)
        '''			return;
        '''
        '''		var state = 1;
        '''
        '''		//if the hidden row has not already been generated, clone the panel into a new row
        '''		var existingRow = window.document.getElementById(sender.id + &quot;showRow&quot;);
        '''		if (existingRow==null)
        '''		{
        '''			//getting a reference to the table
        '''			var table = GetParentElementByTagName(sender, &quot;TABLE&quot;);
        '''			var index = GetParentElementByTagName(sender, &quot;TR&quot;).sectionRowIndex + 1;
        '''			//concat [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Public ReadOnly Property HierarGrid() As String
            Get
                Return ResourceManager.GetString("HierarGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;script language=&quot;JavaScript&quot;&gt;
        '''	var {--HiddenFieldName--} = (document.getElementsByName(&quot;{--HiddenFieldName--}&quot;)[0]).value.split(&quot;, &quot;);
        '''	for(var index = 0; index &lt; {--HiddenFieldName--}.length; index++)
        '''	{
        '''		if({--HiddenFieldName--}[index] != null &amp;&amp; {--HiddenFieldName--}[index] != &quot;&quot;)
        '''			HierarGrid_toggleRow(document.getElementsByName({--HiddenFieldName--}[index])[0]);
        '''	}
        '''&lt;/script&gt;.
        '''</summary>
        Public ReadOnly Property Startup() As String
            Get
                Return ResourceManager.GetString("Startup", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
