USE SIG --[Santana]
GO
/****** Object:  StoredProcedure [dbo].[SCR_fin_operacao_proj]    Script Date: 26/05/2017 
SCR_fin_operacao_proj		parametros ( dt_aplic, cliente_sel, nr_ativo)

exec [SCR_fin_operacao_proj] '2017-03-02','652', '4726', '2017-05-31', 0.0

[SCR_fin_operacao] '20170302', '652', '4726'
exec [SCR_fin_operacao_proj] '2017-05-03','581', '5067', '2017-05-31'

SELECT * FROM AUX_FIN_OPER (NOLOCK)
SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)
11,13
select POWER( (11.13/100.0 + 1.0), (1.0/252.0) )-1.0   
select ROUND( POWER( (11.13/100.0 + 1.0), (1.0/252.0) ) -1.0   , 8) 
=ARRED(((B11/100+1)^(1/252)-1);8)

SP_HELP AUX_FIN_OPER_PROJ

[SCR_fin_operacao_proj] '" & oData.Data.ToString("yyyyMMdd") & "', '" & ddlCliente.SelectedValue & "', '" & ddlAtivo.SelectedValue & "', " & valorCdi

******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC TELA PROJECAO IOPEN  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'Fin_operacao_proj' AND type = 'P')
   DROP PROCEDURE [dbo].[Fin_operacao_proj]
GO




CREATE PROCEDURE [dbo].[Fin_operacao_proj] (
	@DataDe  as datetime,
	@CLIENTE as VARCHAR(20),
	@COD_OP  as VARCHAR(20),
	@DataFECH  as datetime ,
	@vlr_CDI as float,
	@COD_PAPEL	AS VARCHAR(20)
) AS

/*
        	@PARAM1 as smalldatetime, 
			@PARAM2 as varchar(10),
			@PARAM3 as varchar(10),			
			@PARAM4 as smalldatetime, 
			@PARAM5 as decimal) AS
*/
	BEGIN

-- declare	@DataFECH  as datetime 
-- LIMPA AUX ANTERIOR
-- TRUNCATE	TABLE AUX_FIN_OPER
TRUNCATE	TABLE AUX_FIN_OPER_PROJ


DECLARE @CDI_CLI  FLOAT
SET		@CDI_CLI  = (select INDICE_PERCENTUAL from IOpen_Shop..Opn_Movimento (NOLOCK)  where Codigo=@Cod_OP)


DECLARE @PAPEL_COD  VARCHAR(20)
DECLARE @COD_TITULO VARCHAR(20)
--DECLARE @COD_PAPEL  VARCHAR(20)

SET		@COD_TITULO = (select TITULO_CODIGO from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)
-- TEXTO
SET		@PAPEL_COD  = (select PAPEL_CODIGO  from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)

DECLARE @DT_EMISSAO DATETIME
SET		@DT_EMISSAO  = (select DATA  from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)

-- INCLUI 4/8/17
-- CORRIGIR QDO FOR PRE TX FIXA E NAO CF CDI **************
DECLARE @TX_PRE FLOAT
SET		@TX_PRE = 0.0
SET		@TX_PRE = (select TAXA from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)
-- SE A TX_PRE É DIFERENTE DE 0  =>> NAO EH CDI, EH PRE FIXADA

-- AJUSTAR A TX PRE CF PAPEL  TESTE 13/11/17 ********************
SET		@TX_PRE = (select TAXA from iopen_shop..opn_movimento (nolock)  where PAPEL_codigo=@PAPEL_COD)

-- nao localizou
--SET		@COD_PAPEL  = (select CODIGO from iopen_shop..OPN_PAPEL (nolock)  where TITULO_CODIGO=@COD_TITULO AND PAPEL_CODIGO=@PAPEL_COD)
-- NUMEROS
/*
SET		@COD_PAPEL  = (select MAX(P.CODIGO)   -- EVITA DUPLICIDADE
					--  where TITULO_CODIGO=@COD_TITULO AND PAPEL_CODIGO=@PAPEL_COD)
					  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
--					  where LEFT(PAPEL_CODIGO,8)=LEFT(@PAPEL_COD,8) COLLATE DATABASE_DEFAULT  -- ANTES PARA LOCALIZAR , COMPARACAO TTL
					  where P.DATA_EMISSAO = @DT_EMISSAO
						AND P.PAPEL_CODIGO = @PAPEL_COD COLLATE DATABASE_DEFAULT )
--						AND Data_operacao=@DataDe		-- DATA OPER
--						AND INDICE_PERCENTUAL=@CDI_CLI ) -- TX CLIENTE
					--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
					-- 'RDB017001A1'  EQUIV 		RDB0170002

-- QDO NAO LOCALIZA O PAPEL
IF		ISNULL(@COD_PAPEL,'')=''
			SET		@COD_PAPEL = (SELECT	MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.DATA_EMISSAO = @DT_EMISSAO  
								-- DATA_EMISSAO ='20170302'   AND INDICE_PERCENTUAL = 116.0
										AND P.INDICE_PERCENTUAL = @CDI_CLI) -- COLLATE DATABASE_DEFAULT	)   -- TX CLIENTE		@CDI_CLI

*/

--SELECT  @COD_PAPEL  , @CDI_CLI

--select * from IOpen_Shop..OPN_POSCLIENTE (nolock)  where  papel_codigo= @COD_PAPEL order by data
--select * from IOpen_Shop..OPN_POSCLIENTE (nolock)  where  papel_codigo= 3352 order by data

/*
Create table  AUX_FIN_OPER_PROJ (
--DT_EMISSAO		smalldatetime,
Cod_Operacao	VARCHAR(20),			-- FK
Dt_proj			smalldatetime,
tx_cdi			FLOAT,
factor1			FLOAT,
factor2			FLOAT,
intermed_factor	FLOAT,
resultado		FLOAT,
vlr_dia			FLOAT,
atualiz_dia		FLOAT  )

*/

TRUNCATE TABLE AUX_FIN_OPER_PROJ

/*
Cod_Operacao	Dt_proj	tx_cdi	factor1	factor2	intermed_factor	resultado	vlr_dia	atualiz_dia
2658	2017-06-30 00:00:00	10,14	0,00038334	1,0004523412	1,25021466649466	1,25021467	62510,73	28,26

AGENCIA_CODIGO	DATA	CLIENTE_CODIGO	PAPEL_CODIGO	TIPO_ESTOQUE	CARTEIRA_CODIGO	MOVIMENTO_CODIGO	PU_ABR	PU	QUANTIDADE_ABR	QUANTIDADE	FINANCEIRO_ABR	FINANCEIRO	FINANCEIRO_VOLTA	IR	IOF	CPMF	CUSTODIA	EMITIDO	BLOQUEADO	STATUS	PU_INICIAL	QUANTIDADE_INICIAL	FINANCEIRO_INICIAL
1	2017-06-30  78	1617	1	0	2658	1.250214670000000000	1.250214670000000000	26380.7500000000	26380.7500000000	32966.68	32981.60	0.00	1155.14	0.00	0.00	1	1	0	0	1.000000000000000000	50000.00000	50000.00
*/
-- INSERE OS FECHAMENTOS DO IOPEN NA POSICAO DO CLIENTE
INSERT		AUX_FIN_OPER_PROJ
SELECT		@Cod_OP,DATA,0.0,   0.0,PU, PU, PU, FINANCEIRO,
			--FINANCEIRO, 
			CASE WHEN FINANCEIRO_ABR =0.0 THEN 0.0 ELSE FINANCEIRO-FINANCEIRO_ABR END
	FROM	IOpen_Shop..OPN_POSCLIENTE (nolock)  
WHERE  papel_codigo= @COD_PAPEL  AND DATA<=@DataFECH
order by data

-- IOPEN FAZ FECHAMENTO MENSAL EX:30/4/17 DOMINGO E O FINANCEIRO NÃO, PRECISA REMOVER
DELETE		FROM		AUX_FIN_OPER_PROJ
	WHERE	COD_OPERACAO= @COD_OP  AND DATEPART(DW,DT_PROJ) IN (1,7) -- REMOVE O FDS

-- IOPEN FAZ FECHAMENTO MENSAL EX:28/2/17 carnaval feriado
DELETE		FROM		AUX_FIN_OPER_PROJ
	WHERE	COD_OPERACAO= @COD_OP  AND DT_PROJ IN (SELECT DATA FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) 
													WHERE DATA BETWEEN @DataDe AND @DataFECH) 
-- REMOVE O Fechamento do mes = feriado


DECLARE @CONT INT
SET		@CONT = (SELECT COUNT(*) FROM AUX_FIN_OPER_PROJ (NOLOCK) WHERE COD_OPERACAO= @COD_OP )
/*
IF @CONT = 0 
BEGIN
	-- INSERE 1 REGISTRO COM O INICIAL, OPERACAO DE HOJE
END
*/

-- select * from  IOpen_Shop..GRL_INDICE_VALOR (nolock) where indice_codigo=9 order by data
-- select * from  AUX_FIN_OPER_PROJ
-- ATUALIZA O CDI ATEH O FECHAMENTO
UPDATE		AUX_FIN_OPER_PROJ
	SET		tx_cdi= VALOR --  * @CDI_CLI/100.0
					-- INCLUI 4/8/17
					-- CORRIGIR A TX DO CDI X TX NEGOCIADA COM O CLIENTE							 
	FROM	IOpen_Shop..GRL_INDICE_VALOR (nolock) 
	Where	indice_codigo=9 AND DATA = DT_PROJ
--		AND AUX_FIN_OPER_PROJ.COD_OPERACAO= @COD_OP  -- TODOS, DEPENDE DA DATA


-- INCLUI 4/8/17
-- CORRIGIR QDO FOR PRE TX FIXA E NAO CF CDI **************
UPDATE		AUX_FIN_OPER_PROJ
	SET		tx_cdi= @TX_PRE
	WHERE	@TX_PRE <>0.0



-- PROJECAO DATAS FUTURAS ************************
DECLARE @DT_AUX SMALLDATETIME
-- SE ALGUMA DATA TEM TX CDI ZERADA -- INDICA A TX DE ONTEM
SET		@DT_AUX = (SELECT MIN(DT_PROJ) FROM		AUX_FIN_OPER_PROJ  (nolock)  	Where	ISNULL(tx_cdi,0.0)=0.0)
--	SELECT @DT_AUX
IF		ISNULL(@DT_AUX,'') > ''
BEGIN
		UPDATE		AUX_FIN_OPER_PROJ
			--		ONTEM
			SET		tx_cdi= (SELECT		TX_CDI		FROM AUX_FIN_OPER_PROJ (NOLOCK) 
								WHERE	COD_OPERACAO=@Cod_OP 
									AND DT_PROJ = (SELECT	MAX(DT_PROJ) 
													FROM	AUX_FIN_OPER_PROJ  (nolock)  	
													WHERE	COD_OPERACAO=@Cod_OP AND  DT_PROJ<@DT_AUX ))
		-- INCLUI 4/8/17
		-- CORRIGIR A TX DO CDI X TX NEGOCIADA COM O CLIENTE
		--					 * @CDI_CLI/100.0
			Where	COD_OPERACAO=@Cod_OP AND ISNULL(tx_cdi,0.0)=0.0
	
END

-- DIA DE FECHAMENTO USAR A CDI PROJETADA ********* ALTERADO 7/8/17
		UPDATE		AUX_FIN_OPER_PROJ
			SET		tx_cdi= (Select PRC_CDI from  TCDI (nolock) WHERE DT_DE = @DATAFECH)
			WHERE	COD_OPERACAO=@Cod_OP AND DT_PROJ = @DATAFECH



		-- INCLUI 4/8/17  *********************
		-- CORRIGIR QDO FOR PRE TX FIXA E NAO CF CDI **************
		UPDATE		AUX_FIN_OPER_PROJ
			SET		tx_cdi= @TX_PRE
			WHERE	@TX_PRE <>0.0


-- PROJECAO DATAS FUTURAS ************************
-- DECLARE @DT_AUX SMALLDATETIME
DECLARE @DT_1D  SMALLDATETIME
DECLARE @CONTADOR	INT
DECLARE @CONT_PROJ	INT
DECLARE @CDI		FLOAT

-- ULTIMO DIA REALIZADO SEM CDI
SET @DT_AUX =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP )-- AND TX_CDI = 0.0)
SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ <= @DT_AUX)
-- ultima cdi 
SET @CDI = (SELECT TX_CDI FROM AUX_FIN_OPER_PROJ (NOLOCK) WHERE DT_PROJ = @DT_1D)
-- USAR O CDI PROJETADO * TX CONTRATO
SET @CDI = (Select PRC_CDI from  TCDI (nolock) WHERE DT_DE = (Select MIN(DT_DE) from  TCDI (nolock) WHERE DT_DE>= @DATAFECH))

-- INCLUI 4/8/17
-- CORRIGIR A TX DO CDI X TX NEGOCIADA COM O CLIENTE
-- SET @CDI =@CDI * @CDI_CLI/100.0
/*
-- se for mesmo mes e ano usar a ultima CDI
IF DATEPART(MM,@DT_AUX) = DATEPART(MM,@DT_1D) AND DATEPART(YYYY,@DT_AUX) = DATEPART(YYYY,@DT_1D)
BEGIN
	UPDATE		AUX_FIN_OPER_PROJ
		SET		TX_CDI = @CDI 
		WHERE	COD_OPERACAO=@Cod_OP AND DT_PROJ = @DT_AUX AND TX_CDI= 0.0
END
-- select @DT_AUX, @DT_1D , @CDI
*/

SET @DT_AUX =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
DECLARE @DT_FIM SMALLDATETIME
SET @DT_FIM =  (SELECT Dt_Vcto FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
-- SE NAO LOCALIZOU
IF  @DT_FIM IS NULL
		SET @DT_FIM =  (SELECT Dt_Vcto FROM FIN_RES_OPER AS P1 (NOLOCK) WHERE P1.DT_REF = @DataFECH AND P1.COD_OPERACAO=@Cod_OP)

--SET @CDI = (SELECT PRC_CDI FROM TCDI (NOLOCK) WHERE DT_DE = (SELECT MAX(DT_DE) FROM TCDI (NOLOCK) WHERE DT_DE <= @DT_AUX ))


-- select @DT_AUX, @DT_FIM , @CDI

WHILE @DT_AUX <= @DT_FIM
BEGIN
	-- SET @DT_1D  = DATEADD(D,1,@DT_AUX)
	-- CHECA SE É FDS OU FERIADO
	SET @DT_AUX = CASE	 WHEN	DATEPART(DW,@DT_AUX) =1 THEN DATEADD(D,1,@DT_AUX)
						 WHEN	DATEPART(DW,@DT_AUX) =7 THEN DATEADD(D,2,@DT_AUX)
						 ELSE   @DT_AUX	END
	-- CHECA SE É  FERIADO
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_AUX)
	SET @DT_AUX = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,1,@DT_AUX)
						 ELSE   @DT_AUX	END
	-- CHECA SE É  FERIADO 2 DIAS EX CARNAVAL
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_AUX)
	SET @DT_AUX = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,1,@DT_AUX)
						 ELSE   @DT_AUX	END

	-- CHECA SE É FDS OU FERIADO
	SET @DT_AUX = CASE	 WHEN	DATEPART(DW,@DT_AUX) =1 THEN DATEADD(D,1,@DT_AUX)
						 WHEN	DATEPART(DW,@DT_AUX) =7 THEN DATEADD(D,2,@DT_AUX)
						 ELSE   @DT_AUX	END
	-- VERIFICA O FINAL
	IF @DT_AUX > @DT_FIM
		BREAK

	-- VERIFICA O CDI PROJETADO
	--	SELECT * FROM  TCDI (NOLOCK)
	SET		@CONTADOR = (SELECT COUNT(*) FROM  TCDI (NOLOCK) WHERE DT_DE=@DT_AUX)

	-- INSERE O PROJETADO		SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)
	-- CHECA SE EXISTE
	SET		@CONT_PROJ = (SELECT COUNT(*) FROM  AUX_FIN_OPER_PROJ (NOLOCK) WHERE COD_OPERACAO=@Cod_OP AND DT_PROJ=@DT_AUX)
	IF		@CONT_PROJ = 0
	BEGIN
		SET @CDI = (SELECT PRC_CDI FROM TCDI (NOLOCK) WHERE DT_DE = (SELECT MAX(DT_DE) FROM TCDI (NOLOCK) WHERE DT_DE <= @DT_AUX ))
		-- INCLUI 4/8/17
		-- CORRIGIR A TX DO CDI X TX NEGOCIADA COM O CLIENTE
		--  SET @CDI =@CDI * @CDI_CLI/100.0
		INSERT			AUX_FIN_OPER_PROJ (COD_OPERACAO,DT_PROJ,TX_CDI)
			SELECT		@Cod_OP, @DT_AUX, @CDI		--			FROM	TCDI (nolock) 
	END

	SET @DT_AUX  = DATEADD(D,1,@DT_AUX)
END

-- ajusta a tx CDI NULL no mes corrente
		UPDATE		AUX_FIN_OPER_PROJ  
			SET		AUX_FIN_OPER_PROJ.TX_CDI	= ONTEM.TX_CDI -- TRUNCAR A 16 CASA
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.COD_OPERACAO = @Cod_OP  
				AND AUX_FIN_OPER_PROJ.TX_CDI IS NULL


		-- INCLUI 4/8/17  *********************
		-- CORRIGIR QDO FOR PRE TX FIXA E NAO CF CDI **************
		UPDATE		AUX_FIN_OPER_PROJ
			SET		tx_cdi= @TX_PRE
			WHERE	@TX_PRE <>0.0



-- ATUALIZA OS CALCULOS INTERMEDIATE FACTOR
-- DECLARE @DT_AUX SMALLDATETIME DECLARE @DT_1D  SMALLDATETIME DECLARE @DT_FIM SMALLDATETIME
SET @DT_1D  =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
--  PROX DIA A CALCULAR
SET @DT_AUX =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ > @DT_1D)
SET @DT_FIM =  (SELECT Dt_Vcto FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
-- SE NAO LOCALIZOU
IF  @DT_FIM IS NULL
		SET @DT_FIM =  (SELECT Dt_Vcto FROM FIN_RES_OPER AS P1 (NOLOCK) WHERE P1.DT_REF = @DataFECH AND P1.COD_OPERACAO=@Cod_OP)

-- pode ter resgate parcial alterado 10/7/17
-- VALOR APLICADO
DECLARE @VALORAP FLOAT
SET		@VALORAP = (SELECT VLR_ORIGINAL FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
IF	@VALORAP IS NULL
		SET @VALORAP =  (SELECT VLR_ORIGINAL FROM FIN_RES_OPER AS P1 (NOLOCK) WHERE P1.DT_REF = @DataFECH AND P1.COD_OPERACAO=@Cod_OP)

-- select @DT_1D, @DT_AUX, @DT_FIM , '1o DIA'

		--   2017-03-02 00:00:00	2017-03-03 00:00:00	2021-02-09 00:00:00	1o DIA
--  1A DATA CALCULADA
		UPDATE		AUX_FIN_OPER_PROJ  
					-- factor 1 arred 8
			SET	factor1	= convert(float,ROUND( POWER( (CONVERT(FLOAT,ONTEM.TX_CDI)/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8) ) ,
--				factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))

				-- factor 2 truncar 16
				factor2	= convert(float,ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.0000000000000000  ) + 1.0000000000000000, 16,1)),
--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2,16,1)  -- TRUNCAR A 16 CASA

				-- INT factor truncar 16
				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.0000000000000000  ) + 1.0000000000000000, 16,1 ) ,16,1) , -- TRUNCAR A 16 CASA , 1o DIA CALCULAR SEM ONTEM

				AUX_FIN_OPER_PROJ.resultado			= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.0000000000000000  ) + 1.0000000000000000, 16,1 ) ,8)  -- arredondar A 8 CASA , 1o DIA CALCULAR SEM ONTEM
--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND( ((  ( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   )  * @CDI_CLI / 100.00000000  ) + 1.00000000) * ONTEM.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--ROUND(  ((POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000  )  * @CDI_CLI / 100.00000000  ) + 1.00000000) * ONTEM.intermed_factor) ,16,1)  -- TRUNCAR A 16 CASA
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX
			-- ATUALIZA OS VALORES DO 1o DIA
		UPDATE		AUX_FIN_OPER_PROJ  
			SET	AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP ,2,1)  -- TRUNCAR A 8 CASA RESULT X VALOR APLICADO
				-- sem arred  ROUND(
			   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP,2,1) - @VALORAP   -- VLR DIA HJ - ONTEM--	AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8)   -- arred A 8 CASA
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX
					-- INCLUI EM 24/7/17 ************ AJUSTE DO 2o DIA
				AND @DT_AUX > @DataFECH  -- PROJECAO APÓS O FECHAMENTO, SOH ALTERAR OS VALORES QDO NECESSARIO

-- 2A DATA CALCULADA
		-- PROXIMA DATA A CALCULAR
		SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		SET @DT_AUX  =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ >= @DT_AUX)
		--	ONTEM DA DATA REF A CALCULAR
		SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)

-- DTA DIA A PROJETAR
DECLARE @DT_D		DATETIME

-- select @DT_AUX, @DT_1D, 'PROJET'
-- LOOP PARA CALCULAR O INTERMED_FACTOR COM DATA ANTERIOR. E OUTRAS PROJECOES CALCULADAS
WHILE @DT_AUX <= @DT_FIM
BEGIN 
		-- select @DT_AUX, @DT_1D , 'DIA D-1'

		UPDATE		AUX_FIN_OPER_PROJ  
				-- factor 1 round 8
			SET	factor1	= convert(float,ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8) ) ,
--				factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))

				-- factor 2 trunc 16
				factor2	= convert(float,ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.0000000000000000  ) + 1.0000000000000000, 16,1)),

--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2,16,1)  -- TRUNCAR A 16 CASA
				-- intermed fact  trunc 16
				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.0000000000000000  ) + 1.0000000000000000, 16,1) * ONTEM.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
/*			ANTERIOR
--			SET		AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--				   ,AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1)   -- TRUNCAR A 8 CASA
--				   ,AUX_FIN_OPER_PROJ.VLR_DIA	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1) * ONTEM.VLR_DIA   -- TRUNCAR A 8 CASA
--				   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1) * ONTEM.VLR_DIA - ONTEM.VLR_DIA   -- VLR DIA HJ - ONTEM
*/
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX

		-- SE NECESSARIO PROJETAR   ************** ALTERADO 10/7/17
		UPDATE		AUX_FIN_OPER_PROJ  
					-- resultado round 8
			SET		AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8)   -- arred A 8 CASA
-- COM BAIXA PARCIAL, CONSIDERE ONTEM E ALTERADA CONTA FACTOR 2 * VLR ONTEM		APOS 10/7/17
				-- dif dia  sem arred, sem trunc  
			   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2,8) * ONTEM.VLR_DIA,2,1) - ONTEM.VLR_DIA    -- VLR DIA HJ - ONTEM--	AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8)   -- arred A 8 CASA
				-- vlr dia trunca 2
				,AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2,8) * ONTEM.VLR_DIA ,2,1)  -- TRUNCAR A 8 CASA RESULT X VALOR APLICADO

-- ANTES DE 10/7 SEM BAIXA PARCIAL
--			   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP,2,1) - ONTEM.VLR_DIA , 2)   -- VLR DIA HJ - ONTEM--	AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8)   -- arred A 8 CASA
--				,AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP ,2,1)  -- TRUNCAR A 8 CASA RESULT X VALOR APLICADO

--				   ,AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8) * @VALORAP ,2)  -- ARREDOND A 8 CASA RESULT X VALOR APLICADO
--				   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8) * @VALORAP - ONTEM.VLR_DIA , 2)   -- VLR DIA HJ - ONTEM
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.COD_OPERACAO=@Cod_OP 
				AND @DT_AUX > @DataFECH  -- PROJECAO APÓS O FECHAMENTO, SOH ALTERAR OS VALORES QDO NECESSARIO
				AND AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX
-- AND ISNULL(AUX_FIN_OPER_PROJ.RESULTADO,0.0) = 0.0


		-- PROXIMA DATA A CALCULAR
		SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		SET	@DT_D = (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ >= @DT_AUX)
		-- SOH DIA UTIL
		IF  @DT_D > @DT_AUX SET @DT_AUX = @DT_D
		--SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		-- PROXIMA DATA A CALCULAR, PODE NAO EXISTIR, SOH DIA UTIL
		--SET @DT_D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)
		--	ONTEM DA DATA REF A CALCULAR
		SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)

END



-- zera os valores qdo 1a data = data da operaçao
-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
UPDATE		AUX_FIN_OPER_PROJ
	SET		FACTOR1=0.0, FACTOR2=0.0, intermed_factor	= 0.0,RESULTADO=0.0, ATUALIZ_DIA=0.0
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)



END


-- AJUSTA RESULTADO QDO NULLO OU PROJETADO
/*
		UPDATE		AUX_FIN_OPER_PROJ  
			SET		AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8,1)  -- TRUNCAR A 16 CASA
			WHERE	COD_OPERACAO=@Cod_OP 
				AND	AUX_FIN_OPER_PROJ.RESULTADO IS NULL
*/

-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
/*
UPDATE		AUX_FIN_OPER_PROJ  
	SET		AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--ROUND(factor2 * POWER(10,16),16) ) / POWER(10,16) 
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
	FROM    (SELECT * FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP 
		AND P1.DT_PROJ = (SELECT	MAX(P2.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P2 (NOLOCK) 
							WHERE	P2.COD_OPERACAO=@Cod_OP 
								AND P2.DT_PROJ < P1.DT_PROJ) ) AS ONTEM
--	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/
/*
select * from cobr_base_reneg (nolock) where contrato = '612119985a'
-- PLANILHA EXCEL
09/05/2017			 10,86 

-- DIARIO ATEH HJ
select * from  IOpen_Shop..GRL_INDICE_VALOR (nolock) where indice_codigo=9 order by data
-- PROJET
select * from  TCDI (nolock)
10,86 

*/


/*
-- ATUALIZA OS CALCULOS F1
-- select * from AUX_FIN_OPER_PROJ (nolock)
-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
-- SELECT		*,convert(float,ROUND(POWER( (convert(float,P.TX_CDI)/100.0 + 1.0), ((1.0/252.0)-1.0)  ) , 8) ) FROM AUX_FIN_OPER_PROJ P (NOLOCK) WHERE	P.COD_OPERACAO=@Cod_OP AND P.DT_PROJ =  '20170504'
-- SELECT MAX(P3.DT_PROJ) FROM AUX_FIN_OPER_PROJ P3 (NOLOCK) 	WHERE	P3.COD_OPERACAO=@Cod_OP AND P3.DT_PROJ < '20170504'
-- SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP
--  2017-05-03 00:00:00
UPDATE		AUX_FIN_OPER_PROJ
	SET		factor1	= convert(float,ROUND( POWER( (AUX_FIN_OPER_PROJ.TX_CDI/100.0 + 1.0), (1.0/252.0) ) -1.0   , 8) )
--ROUND(POWER( (convert(float,AUX_FIN_OPER_PROJ.TX_CDI)/100.0 + 1.0), ((1.0/252.0)-1.0)  ) , 8) )
			--ROUND(((B11/100+1)^(1/252)-1);8)   =ARRED(((tx CDI mês no dia anterior/100+1)^(1/252)-1);8)
--			factor2	= TRUNC(,
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
--			intermed_factor	=
/*
	FROM	(SELECT		* FROM AUX_FIN_OPER_PROJ P2 (NOLOCK) 
				WHERE	P2.COD_OPERACAO=@Cod_OP 
					-- ONTEM, DIA UTIL ANTERIOR
					AND P2.DT_PROJ = (SELECT MAX(P3.DT_PROJ) FROM AUX_FIN_OPER_PROJ P3 (NOLOCK) 
										WHERE	P3.COD_OPERACAO=@Cod_OP AND P3.DT_PROJ < P2.DT_PROJ) ) AS P
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/

-- ATUALIZA OS CALCULOS F2
UPDATE		AUX_FIN_OPER_PROJ
	SET		factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/

