USE SIG --[Santana]
GO
/****** Object:  StoredProcedure [dbo].[FIN_RESUMO_CALC]    Script Date: 23/06/2017 

exec FIN_RESUMO_CALC '2017-05-31',0.0

-- MES MAR-17 TEMPO 1min36

-- exec FIN_RESUMO_CALC '2017-03-01', '2017-03-31', '2017-05-31',0.0

SELECT * FROM FIN_RES_OPER (NOLOCK)
SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)

SP_HELP AUX_FIN_OPER_PROJ
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC TELA PROJECAO IOPEN  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'FIN_RESUMO_CALC' AND type = 'P')
   DROP PROCEDURE [dbo].[FIN_RESUMO_CALC]
GO




CREATE PROCEDURE [dbo].[FIN_RESUMO_CALC] (
	@DataDe   as datetime,	@DataATE  as datetime,
	@DataREF  as datetime,	@VLR_CDI  as FLOAT		 ) AS

	BEGIN

-- LIMPA AUX ANTERIOR
DELETE		FROM  FIN_RES_OPER		WHERE	DT_REF	 = @DataREF AND DT_EMISSAO BETWEEN  @DataDe AND @DataATE
TRUNCATE	TABLE AUX_FIN_OPER_PROJ
TRUNCATE	TABLE AUX_FIN_OPER   -- LIMPA A OPERACAO UNITARIA

-- DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20160930' SET		@DataATE ='20160930'
-- DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20140101' SET		@DataATE ='20141231'
-- DECLARE	@DataREF   as datetime SET		@DataREF ='20170731'
-- INSERE AS OPERACOES
INSERT FIN_RES_OPER (   DT_REF ,	DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel,	prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado, PAPEL_CODIGO )
SELECT	DISTINCT		@DataREF,	M.DATA,		M.CODIGO,  -- chave
		CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		P.PAPEL_NOME, M.INDICE_PERCENTUAL, P.PAPEL_CODIGO,
		'', M.FINANCEIRO,'',M.CLIENTE_CODIGO,
		0.0,0.0,0.0,0.0
--		, CONVERT(VARCHAR(20),L.PAPEL_CODIGO)
		, L.PAPEL_CODIGO
-- SELECT *
  From	  IOpen_Shop..Opn_Movimento	M (NoLock)
		, IOpen_Shop..Opn_Movimento_LASTRO L (NoLock)
		, IOpen_Shop..OPN_PAPEL		P (NoLock)			--  ALTEREI 5/7/17
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.DATA BETWEEN @DataDe AND @DataATE
	AND M.OPERACAO_CODIGO IN (16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND M.CODIGO=L.MOVIMENTO_CODIGO -- COLLATE DATABASE_DEFAULT  NUMERIC
	AND L.PAPEL_CODIGO=P.CODIGO -- COLLATE DATABASE_DEFAULT   NUMERIC  PAPEL_
 	AND P.DATA_BASE_VENCIMENTO > @DataREF		-- NAO VENCIDAS, NAO PAGAS
--	AND M.PAPEL_CODIGO=L.PAPEL_CODIGO COLLATE DATABASE_DEFAULT
--	AND M.INDICE_PERCENTUAL= P.INDICE_PERCENTUAL  -- TX IGUAL ********** INCLUI 5/7

-- se nao existe na fatura remover do resumo *************** nao fechou oper
-- DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20140101' SET		@DataATE ='20141231'
-- DECLARE	@DataREF   as datetime SET		@DataREF ='20170731'

DELETE	FROM	Fin_res_oper
		WHERE	Dt_ref=@DataREF
			AND Cod_Operacao NOT IN (SELECT movimento_codigo  FROM IOpen_Shop..Opn_faturas f (NoLock) )

-- DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20140101' SET		@DataATE ='20141231'
-- DECLARE	@DataREF   as datetime SET		@DataREF ='20170731'
-- liquidacao antecipada		*************** liquidados
-- se nao existe no Estoque do fim do mes => remover do resumo
DELETE	FROM	Fin_res_oper
		WHERE	Dt_ref=@DataREF
			AND papel_codigo NOT IN (SELECT		papel_codigo  FROM IOpen_Shop..opn_posestoque f (NoLock)
										WHERE	data=@DataREF and tipo_estoque=14 )


/*
USE SIG
select * from (
select  * from fin_res_oper r (nolock) where dt_ref='20170630'  ) as res
, IOpen_Shop..Opn_faturas f (NoLock) ,
(select * from IOpen_Shop..opn_posestoque (NoLock)  where data='20170630' and tipo_estoque=14) as E
where  res.Cod_Operacao = f.movimento_codigo 
and e.papel_codigo = res.papel_codigo


  REMOVI 5/7/17 NAO MAIS NECESSARIO
-- INCLUIR OS SEM CODIGO DO PAPEL LOCALIZADO TRATAR MELHOR *******************
-- INSERE AS OPERACOES 1o O MOVIMENTO DEPOIS O PAPEL
INSERT FIN_RES_OPER (   DT_REF ,	DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel,	prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado )
SELECT	DISTINCT		@DataREF,	M.DATA,		M.CODIGO,
		'','',
		-- CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		-- P.PAPEL_NOME,
		M.INDICE_PERCENTUAL, '', --P.PAPEL_CODIGO,
		0, M.FINANCEIRO,'',M.CLIENTE_CODIGO,
		0.0,0.0,0.0,0.0
-- SELECT *
  From	 IOpen_Shop..Opn_Movimento	M (NoLock)
--		,IOpen_Shop..OPN_PAPEL		P (NoLock) 
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.DATA BETWEEN @DataDe AND @DataATE
	AND M.OPERACAO_CODIGO IN (16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND M.CODIGO NOT IN (SELECT		DISTINCT M1.Cod_Operacao FROM FIN_RES_OPER	M1 (NoLock)
							WHERE	M1.DT_REF = @DataREF)
--	AND M.CODIGO IN (SELECT MAX(M1.CODIGO) FROM IOpen_Shop..Opn_Movimento	M1 (NoLock)
--						WHERE M1.CLIENTE_CODIGO= M.CLIENTE_CODIGO)
--	AND LEFT(PAPEL_CODIGO,9)=LEFT('RDB017001A1',9)

	--							AND	M1.COD_CLIENTE= CONVERT(FLOAT,M.CLIENTE_CODIGO) )
--	AND P.PAPEL_CODIGO<>M.PAPEL_CODIGO COLLATE DATABASE_DEFAULT			-- NAO LOCALIZADOS PELO CODIGO ********** 
--	AND P.DATA_BASE_VENCIMENTO > @DataATE		-- NAO VENCIDAS, NAO PAGAS
--	AND	M.DATA = P.DATA_EMISSAO  -- EXCECOES  ='20170302'  
--	AND M.INDICE_PERCENTUAL   = P.INDICE_PERCENTUAL
*/

--DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20161201' SET		@DataATE ='20161210'
--DECLARE	@DataREF   as datetime SET		@DataREF ='20170531'
-- 1563 OPER    Where Codigo=@Cod_OP 
-- AJUSTA DADOS DO PAPEL QDO NAO TEM
-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
-- DECLARE	@DataDe   as datetime,	@DataATE  as datetime  SET		@DataDe  ='20140101' SET		@DataATE ='20141231'
-- DECLARE	@DataREF   as datetime SET		@DataREF ='20170731'
UPDATE	FIN_RES_OPER
SET		PRE_CDI= CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END   -- CDI-E PRE
		--,cod_papel = PAPEL_NOME, serie_operacao = P.PAPEL_CODIGO
  From	IOpen_Shop..OPN_PAPEL		P (NoLock) 
  WHERE	FIN_RES_OPER.DT_REF = @DataREF
	AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
	and isnull(FIN_RES_OPER.papel_codigo,'') = convert(varchar(20),p.codigo)
--	and isnull(FIN_RES_OPER.cod_papel,'') = ''
--
--DECLARE @CDI_CLI  FLOAT
--SET		@CDI_CLI  = (select INDICE_PERCENTUAL from IOpen_Shop..Opn_Movimento (NOLOCK)  where Codigo=@Cod_OP)

-- QDO NAO LOCALIZA O PAPEL   -- COMENTEI 5/7/17
/*
select * from FIN_RES_OPER (nolock) where DT_REF ='20170731'
-- PAPEL SEM CODIGO
-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
UPDATE	FIN_RES_OPER
SET		FIN_RES_OPER.PAPEL_CODIGO = (SELECT MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.DATA_EMISSAO = FIN_RES_OPER.DT_EMISSAO 
										AND P.PAPEL_CODIGO=SERIE_OPERACAO COLLATE DATABASE_DEFAULT
							AND FIN_RES_OPER.PRC_CDI_REAL= P.INDICE_PERCENTUAL  -- TX IGUAL ********** INCLUI 5/7
	)   -- TX CLIENTE		@CDI_CLI
WHERE	FIN_RES_OPER.DT_REF = @DataREF
	AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
	AND	ISNULL(FIN_RES_OPER.PAPEL_CODIGO,'')=''

-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
UPDATE	FIN_RES_OPER
SET		FIN_RES_OPER.PAPEL_CODIGO = (SELECT MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.DATA_EMISSAO = FIN_RES_OPER.DT_EMISSAO 
								-- DATA_EMISSAO ='20170302'   AND INDICE_PERCENTUAL = 116.0
										AND P.PAPEL_CODIGO=SERIE_OPERACAO COLLATE DATABASE_DEFAULT
										AND P.INDICE_PERCENTUAL = FIN_RES_OPER.prc_cdi_real
						) -- COLLATE DATABASE_DEFAULT	)   -- TX CLIENTE		@CDI_CLI
WHERE	DT_REF = @DataREF
	AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
	AND	ISNULL(FIN_RES_OPER.PAPEL_CODIGO,'')=''
*/
	
-- DT_REF	DT_EMISSAO	Cod_Operacao	Dt_Vcto	dias	pre_cdi	cod_papel	prc_cdi_real	prc_cdi_interm	prc_cdi_final	serie_operacao	COD_GERENTE	vlr_original	vlr_mes_ant	vlr_mes_atual	vlr_rend_mes	vlr_projetado	cliente	COD_cliente	gerente	CANAL	ORIGEM	FUNDO	PAPEL_CODIGO
-- 2017-05-31 00:00:00	2017-03-01 00:00:00	4698	2018-03-01 00:00:00	365	CDI	LC-PJNL	110	NULL	NULL	LC0017005R3	NULL	15000	15297,48	15453,28	155,800000000001	15479,97	EASYNVEST TITULO COREETORA DE VALORES S.A.	117	NULL	NULL	NULL	NULL	3111

-- PAPEIS	VCTO E DIAS
UPDATE	FIN_RES_OPER
SET		Dt_Vcto= DATA_VENCIMENTO , dias = DIAS_PAGAMENTO
      --, AUX_FIN_OPER.PAPEL_CODIGO = P.CODIGO
	FROM	IOpen_Shop..OPN_PAPEL P (NoLock) 
	WHERE	DT_REF	 = @DataREF
		AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
		AND	P.CODIGO = FIN_RES_OPER.PAPEL_CODIGO
--  where LEFT(PAPEL_CODIGO,8)=LEFT(SERIE_OPERACAO,8) COLLATE DATABASE_DEFAULT
--  where P.PAPEL_CODIGO=SERIE_OPERACAO 

--COLLATE DATABASE_DEFAULT 	AND Data_operacao=DT_EMISSAO	AND INDICE_PERCENTUAL=prc_cdi_real   -- TX CLIENTE		@CDI_CLI
--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
-- 'RDB017001A1'  EQUIV 		RDB0170002

-- limpar as operacoes vencidas
DELETE		FIN_RES_OPER
	WHERE	DT_REF	 = @DataREF
		AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
		AND Dt_Vcto <= @DataREF  


-- CLIENTE
UPDATE	FIN_RES_OPER
SET		COD_GERENTE = GERENTE_CODIGO, 
		cliente		= NOME
  from	IOpen_Shop..OPN_CLIENTES (NoLock) 
  where DT_REF	 = @DataREF
	AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
	AND	Codigo=COD_cliente 

/*
-- GERENTE
-- SP_HELP AUX_FIN_OPER
UPDATE	AUX_FIN_OPER
SET		GERENTE =  NOME
  from	IOpen_Shop..OPN_GERENTE (NoLock) 
  where Codigo=COD_GERENTE 
*/


-- PROJETADO CADA OPERACAO
-- 1a operacao
DECLARE @CODOP1		 AS VARCHAR(20)
SET		@CODOP1 = (SELECT MIN(COD_OPERACAO)		FROM FIN_RES_OPER (NOLOCK)	WHERE	DT_REF = @DataREF AND DT_EMISSAO >=  @DataDe)
-- ULTIMA operacao
DECLARE @CODOPF		 AS VARCHAR(20)
SET		@CODOPF = (SELECT MAX(COD_OPERACAO)		FROM FIN_RES_OPER (NOLOCK)	WHERE	DT_REF = @DataREF AND DT_EMISSAO <= @DataATE )
DECLARE @CODOP		 AS VARCHAR(20)
DECLARE @COD_PAPEL	 AS VARCHAR(20)

SET		@CODOP =@CODOP1
-- DADOS DA OPERACAO
DECLARE	@DT			 AS DATETIME
DECLARE @CONTADOR	 AS INT
DECLARE	@CLIENTE	 AS VARCHAR(20)
DECLARE	@DT_MES_ANT  AS DATETIME
-- DIA 1 DO MES DO FECHAMENTO
SET		@DT_MES_ANT =  CONVERT(CHAR(4),DATEPART(YEAR,@DataREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DataREF))),2)+'01'
-- FIM DO MES ANTERIOR
SET		@DT_MES_ANT=DATEADD(DD,-1,@DT_MES_ANT)
	-- CHECA SE É FDS OU FERIADO
	SET @DT_MES_ANT = CASE	 WHEN	DATEPART(DW,@DT_MES_ANT) =1 THEN DATEADD(D,-2,@DT_MES_ANT)  -- DOM
							 WHEN	DATEPART(DW,@DT_MES_ANT) =7 THEN DATEADD(D,-1,@DT_MES_ANT)  -- SAB
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO 2 DIAS EX CARNAVAL
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END




WHILE	@CODOP <= @CODOPF  -- ANTES DO FIM
BEGIN
		-- CARREGA VARIAVEIS
		SET			@DT		=(SELECT	DT_EMISSAO
 								FROM	FIN_RES_OPER	 (NOLOCK)
								WHERE	DT_REF = @DataREF	AND COD_OPERACAO = @CODOP)
		SET			@CLIENTE=(SELECT	COD_CLIENTE
 								FROM	FIN_RES_OPER (NOLOCK)
								WHERE	DT_REF = @DataREF	AND COD_OPERACAO = @CODOP)
		SET			@COD_PAPEL=(SELECT	PAPEL_CODIGO
 								FROM	FIN_RES_OPER (NOLOCK)
								WHERE	DT_REF = @DataREF	AND COD_OPERACAO = @CODOP)

		-- PROJETA CONTRATO A CONTRATO
		-- SELECT	@DT, @CLIENTE ,	@CODOP  ,	@DataREF , @vlr_CDI , @COD_PAPEL
		EXEC  [dbo].[fin_operacao_proj] 	@DT, @CLIENTE ,	@CODOP  ,	@DataREF , @vlr_CDI , @COD_PAPEL

		-- CARREGA DADOS DA PROJECAO FINAL
		UPDATE		FIN_RES_OPER
			SET		VLR_PROJETADO			= PROJ.VLR_DIA 
			FROM	(SELECT		* FROM AUX_FIN_OPER_PROJ P (NOLOCK)
						WHERE	P.COD_OPERACAO			= @CODOP 
							AND P.DT_PROJ = (SELECT		MAX(P1.DT_PROJ) 
												FROM	AUX_FIN_OPER_PROJ P1 (NOLOCK) WHERE	P1.COD_OPERACAO=@CODOP ) ) AS PROJ
			WHERE	FIN_RES_OPER.DT_REF			= @DataREF	
				AND	FIN_RES_OPER.COD_OPERACAO   = @CODOP 

		-- CARREGA DADOS DA PROJECAO NO MES
		UPDATE		FIN_RES_OPER
			SET		VLR_MES_ATUAL = P.VLR_DIA 
			FROM	AUX_FIN_OPER_PROJ P (NOLOCK)
			WHERE	FIN_RES_OPER.DT_REF			= @DataREF	
				AND	FIN_RES_OPER.COD_OPERACAO   = @CODOP 
				AND P.COD_OPERACAO	= @CODOP 
				AND P.DT_PROJ		= (SELECT	MAX(P1.DT_PROJ) 
										FROM	AUX_FIN_OPER_PROJ P1 (NOLOCK) 
										WHERE	P1.COD_OPERACAO=@CODOP AND P1.DT_PROJ <= @DataREF)

		-- CARREGA DADOS DA PROJECAO NO MES ANTERIOR
		UPDATE		FIN_RES_OPER
			SET		VLR_MES_ANT = P.VLR_DIA 
			FROM	AUX_FIN_OPER_PROJ P (NOLOCK)
			WHERE	FIN_RES_OPER.DT_REF			= @DataREF	
				AND	FIN_RES_OPER.COD_OPERACAO   = @CODOP 
				AND P.COD_OPERACAO	= @CODOP 
				AND P.DT_PROJ		= -- @DT_MES_ANT
									 (SELECT	MAX(P1.DT_PROJ) 
										FROM	AUX_FIN_OPER_PROJ P1 (NOLOCK) 
										WHERE	P1.COD_OPERACAO=@CODOP AND P1.DT_PROJ <= @DT_MES_ANT)

		/*
		SELECT	DT_PROJ,TX_CDI,FACTOR1,FACTOR2,INTERMED_FACTOR,
				RESULTADO, VLR_DIA,ATUALIZ_DIA
		 FROM	AUX_FIN_OPER_PROJ (NOLOCK)
		WHERE	COD_OPERACAO=@CODOP
		*/

		-- EXECUTOU A ULTIMA OPERACAO
		--IF @CODOP = @CODOPF
		--	BREAK
		-- NEXT PROXIMA OPERACAO
		SET		@CODOP = (SELECT	MIN(COD_OPERACAO)		FROM FIN_RES_OPER (NOLOCK)	
							WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
								AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
								AND	COD_OPERACAO > @CODOP)
		
END

/*
SELECT *	FROM	IOpen_Shop..OPN_POSCLIENTE (nolock)  
WHERE  papel_codigo= 1333 ORDER BY DATA
SELECT * FROM AUX_FIN_OPER
*/

/*
		-- AJUSTA VCTO
		UPDATE		FIN_RES_OPER
			SET		DT_VCTO = (SELECT C.DATA_VENCIMENTO
									FROM	IOpen_Shop..OPN_PAPEL C (NoLock) 
									WHERE	C.CODIGO   = FIN_RES_OPER.PAPEL_CODIGO  )
			--(SELECT	MAX(P.CODIGO)  from	IOpen_Shop..OPN_PAPEL P (NoLock)  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT										
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
				AND	DT_VCTO IS NULL  -- SEM VENCTO

		-- AJUSTA DIAS
		UPDATE		FIN_RES_OPER
			SET		DIAS = (SELECT C.DIAS_PAGAMENTO
									FROM	IOpen_Shop..OPN_PAPEL C (NoLock) 
									WHERE	C.CODIGO   = FIN_RES_OPER.PAPEL_CODIGO  )
			--(SELECT	MAX(P.CODIGO)  from	IOpen_Shop..OPN_PAPEL P (NoLock)  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT										
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
				AND	DIAS IS NULL  -- SEM VENCTO
*/

/*
		-- AJUSTA VLR SEM PROJECAO PQ ACABOU O CONTRATO
		UPDATE		FIN_RES_OPER
			SET		VLR_PROJETADO = (SELECT C.FINANCEIRO
									FROM	IOpen_Shop..OPN_POSCLIENTE C (nolock)  
									WHERE	CONVERT(VARCHAR(20),C.PAPEL_CODIGO)   = FIN_RES_OPER.PAPEL_CODIGO   COLLATE DATABASE_DEFAULT
			/*
			(SELECT	MAX(P.CODIGO) 	  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT
			*/
										AND C.DATA=(SELECT		MAX(C1.DATA)	FROM IOpen_Shop..OPN_POSCLIENTE C1 (nolock)  
														WHERE	CONVERT(VARCHAR(20),C1.PAPEL_CODIGO)   = FIN_RES_OPER.PAPEL_CODIGO   COLLATE DATABASE_DEFAULT
															AND C1.DATA < FIN_RES_OPER.DT_VCTO ))
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
				AND	ISNULL(FIN_RES_OPER.VLR_PROJETADO,0.0) = 0.0  -- SEM PROJECCAO

*/

		-- ajusta os dados do cadastro gerente, fundo, origem
		update fin_res_oper 
			set cod_gerente = 	c.gerente_codigo
				,origem = c.codigo_extra
			from iopen_shop..opn_clientes  c (nolock) 
		where dt_ref=@DataREF
		and cod_cliente =c.codigo

		update fin_res_oper 
			set gerente = 	c.nome 
				,fundo = case	
							-- INMETRICS SA	637 ,  SIG CAPITAL SOLUÇÕES FINANCEIRAS LTDA	485
								when left(cod_papel,3)='RDB' AND COD_CLIENTE IN (485,637) THEN 'RDB V'
								when left(cod_papel,3)='RDB' THEN 'RDB'
								when left(cod_papel,2)='LC'  THEN 'LC'
								ELSE 'DPGE' END
			from iopen_shop..opn_gerente  c (nolock) 
		where dt_ref=@DataREF 
		and cod_gerente =c.codigo


		-- AJUSTA A TAXA QDO PRE NUMA NOVA COLUNA
/*
		UPDATE		FIN_RES_OPER
			SET		VLR_REND_MES = ISNULL(VLR_MES_ATUAL,0.0) - CASE WHEN ISNULL(VLR_MES_ANT,0.0)=0.0 THEN VLR_ORIGINAL ELSE VLR_MES_ANT END
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
				AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
*/

		-- AJUSTA O RENDIMENTO NO MES
		UPDATE		FIN_RES_OPER
			SET		VLR_REND_MES = ISNULL(VLR_MES_ATUAL,0.0) - CASE WHEN ISNULL(VLR_MES_ANT,0.0)=0.0 THEN VLR_ORIGINAL ELSE VLR_MES_ANT END
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF	
				AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE

		-- REMOVE OS NEGATIVOS, Q NAO CONSEGUE PROJETAR PQ NAO FECHOU OPERACAO
		DELETE		FROM		FIN_RES_OPER
			WHERE	FIN_RES_OPER.DT_REF		= @DataREF
				AND FIN_RES_OPER.DT_EMISSAO BETWEEN  @DataDe AND @DataATE
				AND FIN_RES_OPER.VLR_projetado < 10.0

-- fim processo calculo do resumo com projecoes
/*

SELECT * FROM FIN_RES_OPER (NOLOCK)
SELECT 
		DT_EMISSAO		,
		Cod_Operacao	,
		Dt_Vcto			,
		dias			,
		pre_cdi			,
		cod_papel		,
		prc_cdi_real	,
		prc_cdi_interm	,
		prc_cdi_final	,
		serie_operacao	,
		COD_GERENTE		,
		vlr_original	,
		vlr_mes_ant		,
		vlr_mes_atual	,
		vlr_rend_mes	,
		vlr_projetado	,
		cliente			,
		COD_cliente		,
		gerente			,
		CANAL			,
		ORIGEM			,
		FUNDO			,
		PAPEL_CODIGO	
 FROM	FIN_RES_OPER (NOLOCK)
WHERE DT_REF	= @DataREF	
*/

END
