USE SIG --[SANTANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS 
WHERE NAME = 'SCR_REMESSA' AND TYPE = 'P')
DROP PROCEDURE [DBO].SCR_REMESSA
GO    
	
CREATE PROCEDURE [DBO].SCR_REMESSA (                             
@DT_INI SMALLDATETIME,                    
@DT_FIM SMALLDATETIME,      
@PAGTO INT
) AS                        
                
BEGIN  

SELECT
O3CODORG,
O3DESCR,
OPNROPER,
OPDTBASE,
OPCODCLI,
OPNOMEBNF,
ABRENAVAM,
NRRENAVAM,
DCFAVNOME,
DCVALOR,
ABCHASSI,
ABUFLCPL,
EPDTLNC,
CONVERT(CHAR(5),EPHORALNC,114) AS EPHORALNC,
OPCODORG6,
OPERADOR,
OPCODORG4,
LOJA,
CODPROD,
LEFT(HORA_REMESSA,5) AS HORA_REMESSA,
DT_EMISSAO,
NUM_REMESSA,
TIPO
FROM TB_REMESSA (NOLOCK)
WHERE 1= 0+ CASE WHEN  @PAGTO='0' THEN 1       
   WHEN  @PAGTO = '1' AND TIPO = 'CREDITAS' THEN 1      
   WHEN  @PAGTO = '2' AND TIPO = 'CFI' THEN 1   
END
AND DT_EMISSAO BETWEEN @DT_INI AND @DT_FIM
ORDER BY HORA_REMESSA, TIPO

END