USE SIG --[Santana]
GO
/****** Object:  StoredProcedure [dbo].[SCR_fin_operacao_proj]    Script Date: 26/05/2017 
SCR_fin_operacao_proj		parametros ( dt_aplic, cliente_sel, nr_ativo)

exec [SCR_fin_operacao] '20170302', '652', '', '20170531',0.0


[SCR_fin_operacao] '20170302', '652', '4726'
exec [SCR_fin_operacao_proj] '2017-03-02','652', '4726', '2017-05-31', 0.0

exec [SCR_fin_operacao_proj] '2017-05-03','581', '5067', '2017-05-31'

SELECT * FROM AUX_FIN_OPER (NOLOCK)
SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)
11,13
select POWER( (11.13/100.0 + 1.0), (1.0/252.0) )-1.0   
select ROUND( POWER( (11.13/100.0 + 1.0), (1.0/252.0) ) -1.0   , 8) 
=ARRED(((B11/100+1)^(1/252)-1);8)

SP_HELP AUX_FIN_OPER_PROJ

[SCR_fin_operacao_proj] '" & oData.Data.ToString("yyyyMMdd") & "', '" & ddlCliente.SelectedValue & "', '" & ddlAtivo.SelectedValue & "', " & valorCdi

******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC TELA PROJECAO IOPEN  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_fin_operacao_proj' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_fin_operacao_proj]
GO




CREATE PROCEDURE [dbo].[SCR_fin_operacao_proj] (
	@DataDe  as datetime,
	@CLIENTE as VARCHAR(20),
	@COD_OP  as VARCHAR(20),
	@DataFECH  as datetime ,
	@vlr_CDI as float
) AS

	BEGIN

-- LIMPA AUX ANTERIOR
TRUNCATE	TABLE AUX_FIN_OPER

-- INSERE AS OPERACOES
INSERT AUX_FIN_OPER (   DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel, prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente , PAPEL_CODIGO ,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado )
SELECT	DATA, M.CODIGO,
		CASE WHEN  CHARINDEX('PRE',M.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		M.PAPEL_NOME, M.INDICE_PERCENTUAL, M.PAPEL_CODIGO,
		'', M.FINANCEIRO,'',CLIENTE_CODIGO
		, L.PAPEL_CODIGO
		,0.0,0.0,0.0,0.0
-- SELECT *
  From	  IOpen_Shop..Opn_Movimento	M (NoLock)
		, IOpen_Shop..Opn_Movimento_LASTRO L (NoLock)
		, IOpen_Shop..OPN_PAPEL		P (NoLock)			--  ALTEREI 5/7/17
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.CODIGO =@Cod_OP		-- SOMENTE A OPERACAO SELECT
	AND M.OPERACAO_CODIGO IN (16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND M.CODIGO=L.MOVIMENTO_CODIGO -- COLLATE DATABASE_DEFAULT  NUMERIC
	AND L.PAPEL_CODIGO=P.CODIGO -- COLLATE DATABASE_DEFAULT   NUMERIC  PAPEL_
/*
INSERT AUX_FIN_OPER (   	DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel,	prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado )
SELECT	DISTINCT			M.DATA,		M.CODIGO,
		CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		P.PAPEL_NOME, M.INDICE_PERCENTUAL, P.PAPEL_CODIGO,
		'', M.FINANCEIRO,'',M.CLIENTE_CODIGO,
		0.0,0.0,0.0,0.0
-- SELECT *
  From	 IOpen_Shop..Opn_Movimento	M (NoLock)
		,IOpen_Shop..OPN_PAPEL		P (NoLock) 
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.DATA = @DataDe --AND @DataATE
	AND M.OPERACAO_CODIGO IN (16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND P.PAPEL_CODIGO=M.PAPEL_CODIGO COLLATE DATABASE_DEFAULT
	AND P.DATA_BASE_VENCIMENTO > @Datade		-- NAO VENCIDAS, NAO PAGAS


-- INCLUIR OS SEM CODIGO DO PAPEL LOCALIZADO TRATAR MELHOR *******************
-- INSERE AS OPERACOES 1o O MOVIMENTO DEPOIS O PAPEL
INSERT AUX_FIN_OPER (  	DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel,	prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado )
SELECT	DISTINCT			M.DATA,		M.CODIGO,
		'','',
		-- CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		-- P.PAPEL_NOME,
		M.INDICE_PERCENTUAL, '', --P.PAPEL_CODIGO,
		0, M.FINANCEIRO,'',M.CLIENTE_CODIGO,
		0.0,0.0,0.0,0.0
-- SELECT *
  From	 IOpen_Shop..Opn_Movimento	M (NoLock)
--		,IOpen_Shop..OPN_PAPEL		P (NoLock) 
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.DATA = @DataDe-- AND @DataATE
	AND M.OPERACAO_CODIGO IN (16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND M.CODIGO NOT IN (SELECT		DISTINCT M1.Cod_Operacao FROM AUX_FIN_OPER	M1 (NoLock) )
--							WHERE	M1.DT_REF = @DataREF)
--	AND M.CODIGO IN (SELECT MAX(M1.CODIGO) FROM IOpen_Shop..Opn_Movimento	M1 (NoLock)
--						WHERE M1.CLIENTE_CODIGO= M.CLIENTE_CODIGO)
--	AND LEFT(PAPEL_CODIGO,9)=LEFT('RDB017001A1',9)

	--							AND	M1.COD_CLIENTE= CONVERT(FLOAT,M.CLIENTE_CODIGO) )
--	AND P.PAPEL_CODIGO<>M.PAPEL_CODIGO COLLATE DATABASE_DEFAULT			-- NAO LOCALIZADOS PELO CODIGO ********** 
--	AND P.DATA_BASE_VENCIMENTO > @DataATE		-- NAO VENCIDAS, NAO PAGAS
--	AND	M.DATA = P.DATA_EMISSAO  -- EXCECOES  ='20170302'  
--	AND M.INDICE_PERCENTUAL   = P.INDICE_PERCENTUAL
*/

-- 1563 OPER    Where Codigo=@Cod_OP 
-- AJUSTA DADOS DO PAPEL QDO NAO TEM
-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
UPDATE	AUX_FIN_OPER
SET		PRE_CDI= CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END   -- CDI-E PRE
		--cod_papel = PAPEL_NOME,		 serie_operacao = P.PAPEL_CODIGO
  From	IOpen_Shop..OPN_PAPEL		P (NoLock) 
  WHERE	P.CODIGO = AUX_FIN_OPER.PAPEL_CODIGO
  --WHERE	isnull(AUX_FIN_OPER.cod_papel,'') = ''
--
--DECLARE @CDI_CLI  FLOAT
--SET		@CDI_CLI  = (select INDICE_PERCENTUAL from IOpen_Shop..Opn_Movimento (NOLOCK)  where Codigo=@Cod_OP)

/*
-- PAPEL SEM CODIGO
-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
UPDATE	AUX_FIN_OPER
SET		AUX_FIN_OPER.PAPEL_CODIGO = (SELECT MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.DATA_EMISSAO = AUX_FIN_OPER.DT_EMISSAO 
										AND P.PAPEL_CODIGO=SERIE_OPERACAO COLLATE DATABASE_DEFAULT	)   -- TX CLIENTE		@CDI_CLI
WHERE	ISNULL(AUX_FIN_OPER.PAPEL_CODIGO,'')=''

-- QDO NAO LOCALIZA O PAPEL
-- DECLARE @DataREF  DATETIME SET @DataREF='20170531'
UPDATE	AUX_FIN_OPER
SET		AUX_FIN_OPER.PAPEL_CODIGO = (SELECT MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.DATA_EMISSAO = AUX_FIN_OPER.DT_EMISSAO 
								-- DATA_EMISSAO ='20170302'   AND INDICE_PERCENTUAL = 116.0
										AND P.INDICE_PERCENTUAL = AUX_FIN_OPER.prc_cdi_real
						) -- COLLATE DATABASE_DEFAULT	)   -- TX CLIENTE		@CDI_CLI
WHERE	ISNULL(AUX_FIN_OPER.PAPEL_CODIGO,'')=''
	
-- DT_REF	DT_EMISSAO	Cod_Operacao	Dt_Vcto	dias	pre_cdi	cod_papel	prc_cdi_real	prc_cdi_interm	prc_cdi_final	serie_operacao	COD_GERENTE	vlr_original	vlr_mes_ant	vlr_mes_atual	vlr_rend_mes	vlr_projetado	cliente	COD_cliente	gerente	CANAL	ORIGEM	FUNDO	PAPEL_CODIGO
-- 2017-05-31 00:00:00	2017-03-01 00:00:00	4698	2018-03-01 00:00:00	365	CDI	LC-PJNL	110	NULL	NULL	LC0017005R3	NULL	15000	15297,48	15453,28	155,800000000001	15479,97	EASYNVEST TITULO COREETORA DE VALORES S.A.	117	NULL	NULL	NULL	NULL	3111
*/


-- PAPEIS	VCTO E DIAS
UPDATE	AUX_FIN_OPER
SET		Dt_Vcto= DATA_VENCIMENTO , dias = DIAS_PAGAMENTO
      --, AUX_FIN_OPER.PAPEL_CODIGO = P.CODIGO
	FROM	IOpen_Shop..OPN_PAPEL P (NoLock) 
	WHERE	P.CODIGO = AUX_FIN_OPER.PAPEL_CODIGO
--  where LEFT(PAPEL_CODIGO,8)=LEFT(SERIE_OPERACAO,8) COLLATE DATABASE_DEFAULT
--  where P.PAPEL_CODIGO=SERIE_OPERACAO 

--COLLATE DATABASE_DEFAULT 	AND Data_operacao=DT_EMISSAO	AND INDICE_PERCENTUAL=prc_cdi_real   -- TX CLIENTE		@CDI_CLI
--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
-- 'RDB017001A1'  EQUIV 		RDB0170002


-- CLIENTE
UPDATE	AUX_FIN_OPER
SET		COD_GERENTE = GERENTE_CODIGO, 
		cliente		= NOME
  from	IOpen_Shop..OPN_CLIENTES (NoLock) 
  where Codigo=COD_cliente 

/*
-- GERENTE
-- SP_HELP AUX_FIN_OPER
UPDATE	AUX_FIN_OPER
SET		GERENTE =  NOME
  from	IOpen_Shop..OPN_GERENTE (NoLock) 
  where Codigo=COD_GERENTE 
*/


-- PROJETADO CADA OPERACAO
-- 1a operacao
DECLARE @CODOP1		 AS VARCHAR(20)
SET		@CODOP1 = (SELECT MIN(COD_OPERACAO)		FROM AUX_FIN_OPER (NOLOCK)	)
-- ULTIMA operacao
DECLARE @CODOPF		 AS VARCHAR(20)
SET		@CODOPF = (SELECT MAX(COD_OPERACAO)		FROM AUX_FIN_OPER (NOLOCK)	)
DECLARE @CODOP		 AS VARCHAR(20)
SET		@CODOP =@CODOP1
-- DADOS DA OPERACAO
DECLARE	@DT			 AS DATETIME
DECLARE @CONTADOR	 AS INT
DECLARE @COD_PAPEL		 AS VARCHAR(20)

--DECLARE	@CLIENTE	 AS VARCHAR(20)
DECLARE	@DT_MES_ANT  AS DATETIME
-- DIA 1 DO MES DO FECHAMENTO
SET		@DT_MES_ANT =  CONVERT(CHAR(4),DATEPART(YEAR,@DataFECH))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DataFECH))),2)+'01'
-- FIM DO MES ANTERIOR
SET		@DT_MES_ANT=DATEADD(DD,-1,@DT_MES_ANT)
	-- CHECA SE É FDS OU FERIADO
	SET @DT_MES_ANT = CASE	 WHEN	DATEPART(DW,@DT_MES_ANT) =1 THEN DATEADD(D,-2,@DT_MES_ANT)  -- DOM
							 WHEN	DATEPART(DW,@DT_MES_ANT) =7 THEN DATEADD(D,-1,@DT_MES_ANT)  -- SAB
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO 2 DIAS EX CARNAVAL
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END




		-- CARREGA VARIAVEIS
		SET			@DT		=(SELECT	DT_EMISSAO
 								FROM	AUX_FIN_OPER	 (NOLOCK)
								WHERE	COD_OPERACAO = @CODOP)
		SET			@CLIENTE=(SELECT	COD_CLIENTE
 								FROM	AUX_FIN_OPER (NOLOCK)
								WHERE	COD_OPERACAO = @CODOP)

		SET			@COD_PAPEL=(SELECT	PAPEL_CODIGO
 								FROM	AUX_FIN_OPER (NOLOCK)
								WHERE	COD_OPERACAO = @CODOP)




-- exec [fin_operacao_proj] '2017-05-03','581', '5067', '2017-05-31',0.0
-- exec [fin_operacao_proj] '2017-05-03','581', '5067', '2017-05-31',0.0
exec DBO.[Fin_operacao_proj] @DataDe,@CLIENTE, @COD_OP, @DataFECH , @vlr_CDI, @COD_PAPEL

SELECT	DT_PROJ,TX_CDI,FACTOR1,FACTOR2,INTERMED_FACTOR,
		RESULTADO, VLR_DIA,ATUALIZ_DIA
 FROM	AUX_FIN_OPER_PROJ (NOLOCK)
WHERE	COD_OPERACAO=@COD_OP
order by DT_PROJ
END

/*

-- declare	@DataFECH  as datetime 
-- LIMPA AUX ANTERIOR
TRUNCATE	TABLE AUX_FIN_OPER
TRUNCATE	TABLE AUX_FIN_OPER_PROJ


INSERT AUX_FIN_OPER (   DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel, prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente )
SELECT	DATA, CODIGO,
		CASE WHEN  CHARINDEX('PRE',PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		PAPEL_NOME, INDICE_PERCENTUAL, PAPEL_CODIGO,
		'', FINANCEIRO,'',CLIENTE_CODIGO
  From	IOpen_Shop..Opn_Movimento (NoLock)
  Where Codigo=@Cod_OP AND OPERACAO_CODIGO=16			-- EMISSAO

DECLARE @CDI_CLI  FLOAT
SET		@CDI_CLI  = (select INDICE_PERCENTUAL from IOpen_Shop..Opn_Movimento (NOLOCK)  where Codigo=@Cod_OP)


-- PAPEL
UPDATE	AUX_FIN_OPER
SET		Dt_Vcto= DATA_VENCIMENTO , dias = DIAS_PAGAMENTO 
  from	IOpen_Shop..OPN_PAPEL (NoLock) 
  where LEFT(PAPEL_CODIGO,8)=LEFT(SERIE_OPERACAO,8) COLLATE DATABASE_DEFAULT
	AND Data_operacao=@DataDe		-- DATA OPER
	AND INDICE_PERCENTUAL=@CDI_CLI  -- TX CLIENTE
--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
-- 'RDB017001A1'  EQUIV 		RDB0170002

-- CLIENTE
UPDATE	AUX_FIN_OPER
SET		COD_GERENTE = GERENTE_CODIGO, 
		cliente		= NOME
  from	IOpen_Shop..OPN_CLIENTES (NoLock) 
  where Codigo=COD_cliente 

/*
-- GERENTE
-- SP_HELP AUX_FIN_OPER
UPDATE	AUX_FIN_OPER
SET		GERENTE =  NOME
  from	IOpen_Shop..OPN_GERENTE (NoLock) 
  where Codigo=COD_GERENTE 
*/

DECLARE @PAPEL_COD  VARCHAR(20)
DECLARE @COD_TITULO VARCHAR(20)
DECLARE @COD_PAPEL  VARCHAR(20)

SET		@COD_TITULO = (select TITULO_CODIGO from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)
SET		@PAPEL_COD  = (select PAPEL_CODIGO  from iopen_shop..opn_movimento (nolock)  where codigo=@Cod_OP)

-- nao localizou
--SET		@COD_PAPEL  = (select CODIGO from iopen_shop..OPN_PAPEL (nolock)  where TITULO_CODIGO=@COD_TITULO AND PAPEL_CODIGO=@PAPEL_COD)
SET		@COD_PAPEL  = (select CODIGO 
					--  where TITULO_CODIGO=@COD_TITULO AND PAPEL_CODIGO=@PAPEL_COD)
					  from	IOpen_Shop..OPN_PAPEL (NoLock) 
					  where LEFT(PAPEL_CODIGO,8)=LEFT(@PAPEL_COD,8) COLLATE DATABASE_DEFAULT
						AND Data_operacao=@DataDe		-- DATA OPER
						AND INDICE_PERCENTUAL=@CDI_CLI ) -- TX CLIENTE
					--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
					-- 'RDB017001A1'  EQUIV 		RDB0170002

--SELECT  @COD_PAPEL  , @CDI_CLI

--select * from IOpen_Shop..OPN_POSCLIENTE (nolock)  where  papel_codigo= @COD_PAPEL order by data
--select * from IOpen_Shop..OPN_POSCLIENTE (nolock)  where  papel_codigo= 3352 order by data

/*
Create table  AUX_FIN_OPER_PROJ (
--DT_EMISSAO		smalldatetime,
Cod_Operacao	VARCHAR(20),			-- FK
Dt_proj			smalldatetime,
tx_cdi			FLOAT,
factor1			FLOAT,
factor2			FLOAT,
intermed_factor	FLOAT,
resultado		FLOAT,
vlr_dia			FLOAT,
atualiz_dia		FLOAT  )

*/

TRUNCATE TABLE AUX_FIN_OPER_PROJ

-- INSERE OS FECHAMENTOS DO IOPEN NA POSICAO DO CLIENTE
INSERT		AUX_FIN_OPER_PROJ
SELECT		@Cod_OP,DATA,0.0, 0.0,0.0, 0.0, PU, FINANCEIRO, CASE WHEN FINANCEIRO_ABR =0.0 THEN 0.0 ELSE FINANCEIRO-FINANCEIRO_ABR END
	FROM	IOpen_Shop..OPN_POSCLIENTE (nolock)  
WHERE  papel_codigo= @COD_PAPEL  AND DATA<=@DataFECH
order by data

-- IOPEN FAZ FECHAMENTO MENSAL EX:30/4/17 DOMINGO E O FINANCEIRO NÃO, PRECISA REMOVER
DELETE FROM		AUX_FIN_OPER_PROJ
WHERE  COD_OPERACAO= @COD_OP  AND DATEPART(DW,DT_PROJ) IN (1,7) -- REMOVE O FDS



DECLARE @CONT INT
SET		@CONT = (SELECT COUNT(*) FROM AUX_FIN_OPER_PROJ (NOLOCK) WHERE COD_OPERACAO= @COD_OP )
/*
IF @CONT = 0 
BEGIN
	-- INSERE 1 REGISTRO COM O INICIAL, OPERACAO DE HOJE
END
*/

-- select * from  IOpen_Shop..GRL_INDICE_VALOR (nolock) where indice_codigo=9 order by data
-- select * from  AUX_FIN_OPER_PROJ
-- ATUALIZA O CDI ATEH O FECHAMENTO
UPDATE		AUX_FIN_OPER_PROJ
	SET		tx_cdi= VALOR
	FROM	IOpen_Shop..GRL_INDICE_VALOR (nolock) 
	Where	indice_codigo=9 AND DATA = DT_PROJ
--		AND AUX_FIN_OPER_PROJ.COD_OPERACAO= @COD_OP  -- TODOS, DEPENDE DA DATA

-- PROJECAO DATAS FUTURAS ************************
DECLARE @DT_AUX SMALLDATETIME
-- SE ALGUMA DATA TEM TX CDI ZERADA -- INDICA A TX DE ONTEM
SET		@DT_AUX = (SELECT MIN(DT_PROJ) FROM		AUX_FIN_OPER_PROJ  (nolock)  	Where	ISNULL(tx_cdi,0.0)=0.0)
--	SELECT @DT_AUX
IF		ISNULL(@DT_AUX,'') > ''
		UPDATE		AUX_FIN_OPER_PROJ
			--		ONTEM
			SET		tx_cdi= (SELECT		TX_CDI		FROM AUX_FIN_OPER_PROJ (NOLOCK) 
								WHERE	COD_OPERACAO=@Cod_OP 
									AND DT_PROJ = (SELECT	MAX(DT_PROJ) 
													FROM	AUX_FIN_OPER_PROJ  (nolock)  	
													WHERE	COD_OPERACAO=@Cod_OP AND  DT_PROJ<@DT_AUX ))
			Where	COD_OPERACAO=@Cod_OP AND ISNULL(tx_cdi,0.0)=0.0
	
--		AND AUX_FIN_OPER_PROJ.COD_OPERACAO= @COD_OP  -- TODOS, DEPENDE DA DATA



-- PROJECAO DATAS FUTURAS ************************
-- DECLARE @DT_AUX SMALLDATETIME
DECLARE @DT_1D  SMALLDATETIME
DECLARE @CONTADOR	INT
DECLARE @CONT_PROJ	INT
DECLARE @CDI		FLOAT

-- ULTIMO DIA REALIZADO SEM CDI
SET @DT_AUX =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP )-- AND TX_CDI = 0.0)
SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ <= @DT_AUX)
-- ultima cdi 
SET @CDI = (SELECT TX_CDI FROM AUX_FIN_OPER_PROJ (NOLOCK) WHERE DT_PROJ = @DT_1D)
-- USAR O CDI PROJETADO
SET @CDI = (Select PRC_CDI from  TCDI (nolock) WHERE DT_DE = (Select MIN(DT_DE) from  TCDI (nolock) WHERE DT_DE>= @DATAFECH))
/*
-- se for mesmo mes e ano usar a ultima CDI
IF DATEPART(MM,@DT_AUX) = DATEPART(MM,@DT_1D) AND DATEPART(YYYY,@DT_AUX) = DATEPART(YYYY,@DT_1D)
BEGIN
	UPDATE		AUX_FIN_OPER_PROJ
		SET		TX_CDI = @CDI 
		WHERE	COD_OPERACAO=@Cod_OP AND DT_PROJ = @DT_AUX AND TX_CDI= 0.0
END
-- select @DT_AUX, @DT_1D , @CDI
*/

SET @DT_AUX =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
DECLARE @DT_FIM SMALLDATETIME
SET @DT_FIM =  (SELECT Dt_Vcto FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
--SET @CDI = (SELECT PRC_CDI FROM TCDI (NOLOCK) WHERE DT_DE = (SELECT MAX(DT_DE) FROM TCDI (NOLOCK) WHERE DT_DE <= @DT_AUX ))


-- select @DT_AUX, @DT_FIM , @CDI

WHILE @DT_AUX <= @DT_FIM
BEGIN
	-- SET @DT_1D  = DATEADD(D,1,@DT_AUX)
	-- CHECA SE É FDS OU FERIADO
	SET @DT_AUX = CASE	 WHEN	DATEPART(DW,@DT_AUX) =1 THEN DATEADD(D,1,@DT_AUX)
						 WHEN	DATEPART(DW,@DT_AUX) =7 THEN DATEADD(D,2,@DT_AUX)
						 ELSE   @DT_AUX	END
	-- CHECA SE É  FERIADO
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_AUX)
	SET @DT_AUX = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,1,@DT_AUX)
						 ELSE   @DT_AUX	END
	-- CHECA SE É  FERIADO 2 DIAS EX CARNAVAL
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_AUX)
	SET @DT_AUX = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,1,@DT_AUX)
						 ELSE   @DT_AUX	END

	-- CHECA SE É FDS OU FERIADO
	SET @DT_AUX = CASE	 WHEN	DATEPART(DW,@DT_AUX) =1 THEN DATEADD(D,1,@DT_AUX)
						 WHEN	DATEPART(DW,@DT_AUX) =7 THEN DATEADD(D,2,@DT_AUX)
						 ELSE   @DT_AUX	END

	-- VERIFICA O CDI PROJETADO
	--	SELECT * FROM  TCDI (NOLOCK)
	SET		@CONTADOR = (SELECT COUNT(*) FROM  TCDI (NOLOCK) WHERE DT_DE=@DT_AUX)

	-- INSERE O PROJETADO		SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)
	-- CHECA SE EXISTE
	SET		@CONT_PROJ = (SELECT COUNT(*) FROM  AUX_FIN_OPER_PROJ (NOLOCK) WHERE COD_OPERACAO=@Cod_OP AND DT_PROJ=@DT_AUX)
	IF		@CONT_PROJ = 0
	BEGIN
		SET @CDI = (SELECT PRC_CDI FROM TCDI (NOLOCK) WHERE DT_DE = (SELECT MAX(DT_DE) FROM TCDI (NOLOCK) WHERE DT_DE <= @DT_AUX ))
		INSERT			AUX_FIN_OPER_PROJ (COD_OPERACAO,DT_PROJ,TX_CDI)
			SELECT		@Cod_OP, @DT_AUX, @CDI		--			FROM	TCDI (nolock) 
	END

	SET @DT_AUX  = DATEADD(D,1,@DT_AUX)
END

-- ajusta a tx CDI NULL no mes corrente
		UPDATE		AUX_FIN_OPER_PROJ  
			SET		AUX_FIN_OPER_PROJ.TX_CDI	= ONTEM.TX_CDI -- TRUNCAR A 16 CASA
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.COD_OPERACAO = @Cod_OP  
				AND AUX_FIN_OPER_PROJ.TX_CDI IS NULL


-- ATUALIZA OS CALCULOS INTERMEDIATE FACTOR
-- DECLARE @DT_AUX SMALLDATETIME DECLARE @DT_1D  SMALLDATETIME DECLARE @DT_FIM SMALLDATETIME
SET @DT_1D  =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
--  PROX DIA A CALCULAR
SET @DT_AUX =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ > @DT_1D)
SET @DT_FIM =  (SELECT Dt_Vcto FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)

-- VALOR APLICADO
DECLARE @VALORAP FLOAT
SET		@VALORAP = (SELECT VLR_ORIGINAL FROM AUX_FIN_OPER AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)


-- select @DT_1D, @DT_AUX, @DT_FIM , '1o DIA'

		--   2017-03-02 00:00:00	2017-03-03 00:00:00	2021-02-09 00:00:00	1o DIA
--  1A DATA CALCULADA
		UPDATE		AUX_FIN_OPER_PROJ  
			SET	factor1	= convert(float,ROUND( POWER( (CONVERT(FLOAT,ONTEM.TX_CDI)/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8) ) ,
--				factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))
				factor2	= convert(float,ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.00000000  ) + 1.00000000, 16)),
--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2,16,1)  -- TRUNCAR A 16 CASA

				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.00000000  ) + 1.00000000, 16) ,16,1) , -- TRUNCAR A 16 CASA , 1o DIA CALCULAR SEM ONTEM
				AUX_FIN_OPER_PROJ.resultado			= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.00000000  ) + 1.00000000, 16) ,8)  -- arredondar A 8 CASA , 1o DIA CALCULAR SEM ONTEM
--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND( ((  ( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   )  * @CDI_CLI / 100.00000000  ) + 1.00000000) * ONTEM.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--ROUND(  ((POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000  )  * @CDI_CLI / 100.00000000  ) + 1.00000000) * ONTEM.intermed_factor) ,16,1)  -- TRUNCAR A 16 CASA
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX
			-- ATUALIZA OS VALORES DO 1o DIA
		UPDATE		AUX_FIN_OPER_PROJ  
			SET	AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP ,2,1)  -- TRUNCAR A 8 CASA RESULT X VALOR APLICADO
			   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP,2,1) - @VALORAP , 2)   -- VLR DIA HJ - ONTEM--	AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8)   -- arred A 8 CASA
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX

-- 2A DATA CALCULADA
		-- PROXIMA DATA A CALCULAR
		SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		SET @DT_AUX  =  (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ >= @DT_AUX)
		--	ONTEM DA DATA REF A CALCULAR
		SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)

-- DTA DIA A PROJETAR
DECLARE @DT_D		DATETIME

-- select @DT_AUX, @DT_1D, 'PROJET'
-- LOOP PARA CALCULAR O INTERMED_FACTOR COM DATA ANTERIOR. E OUTRAS PROJECOES CALCULADAS
WHILE @DT_AUX <= @DT_FIM
BEGIN 
		-- select @DT_AUX, @DT_1D , 'DIA D-1'

		UPDATE		AUX_FIN_OPER_PROJ  
			SET	factor1	= convert(float,ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8) ) ,
--				factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))
				factor2	= convert(float,ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.00000000  ) + 1.00000000, 16)),
--				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2,16,1)  -- TRUNCAR A 16 CASA
				AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(ROUND(( ROUND( POWER( (ONTEM.TX_CDI/100.00000000 + 1.00000000), (1.00000000/252.00000000) ) -1.00000000   , 8)  * @CDI_CLI / 100.00000000  ) + 1.00000000, 16) * ONTEM.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
/*			ANTERIOR
--			SET		AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--				   ,AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1)   -- TRUNCAR A 8 CASA
--				   ,AUX_FIN_OPER_PROJ.VLR_DIA	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1) * ONTEM.VLR_DIA   -- TRUNCAR A 8 CASA
--				   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8,1) * ONTEM.VLR_DIA - ONTEM.VLR_DIA   -- VLR DIA HJ - ONTEM
*/
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX

		-- SE NECESSARIO PROJETAR
		UPDATE		AUX_FIN_OPER_PROJ  
			SET		AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8)   -- arred A 8 CASA
				,AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP ,2,1)  -- TRUNCAR A 8 CASA RESULT X VALOR APLICADO
			   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8) * @VALORAP,2,1) - ONTEM.VLR_DIA , 2)   -- VLR DIA HJ - ONTEM--	AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8)   -- arred A 8 CASA
--				   ,AUX_FIN_OPER_PROJ.VLR_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8) * @VALORAP ,2)  -- ARREDOND A 8 CASA RESULT X VALOR APLICADO
--				   ,AUX_FIN_OPER_PROJ.ATUALIZ_DIA	=  ROUND(ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,8) * @VALORAP - ONTEM.VLR_DIA , 2)   -- VLR DIA HJ - ONTEM
			FROM    (SELECT *	FROM	AUX_FIN_OPER_PROJ AS P1 (NOLOCK) 
								WHERE	P1.COD_OPERACAO=@Cod_OP 
									AND P1.DT_PROJ = @DT_1D )	AS ONTEM
			WHERE	AUX_FIN_OPER_PROJ.COD_OPERACAO=@Cod_OP 
				AND AUX_FIN_OPER_PROJ.DT_PROJ = @DT_AUX
-- AND ISNULL(AUX_FIN_OPER_PROJ.RESULTADO,0.0) = 0.0


		-- PROXIMA DATA A CALCULAR
		SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		SET	@DT_D = (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ >= @DT_AUX)
		-- SOH DIA UTIL
		IF  @DT_D > @DT_AUX SET @DT_AUX = @DT_D
		--SET	@DT_AUX = DATEADD(D,1,@DT_AUX)
		-- PROXIMA DATA A CALCULAR, PODE NAO EXISTIR, SOH DIA UTIL
		--SET @DT_D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)
		--	ONTEM DA DATA REF A CALCULAR
		SET @DT_1D  =  (SELECT MAX(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP AND DT_PROJ < @DT_AUX)

END



-- zera os valores qdo 1a data = data da operaçao
-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
UPDATE		AUX_FIN_OPER_PROJ
	SET		FACTOR1=0.0, FACTOR2=0.0, intermed_factor	= 0.0,RESULTADO=0.0, ATUALIZ_DIA=0.0
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ = (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)



END


-- AJUSTA RESULTADO QDO NULLO OU PROJETADO
/*
		UPDATE		AUX_FIN_OPER_PROJ  
			SET		AUX_FIN_OPER_PROJ.RESULTADO	= ROUND(AUX_FIN_OPER_PROJ.intermed_factor,8,1)  -- TRUNCAR A 16 CASA
			WHERE	COD_OPERACAO=@Cod_OP 
				AND	AUX_FIN_OPER_PROJ.RESULTADO IS NULL
*/

-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
/*
UPDATE		AUX_FIN_OPER_PROJ  
	SET		AUX_FIN_OPER_PROJ.intermed_factor	= ROUND(AUX_FIN_OPER_PROJ.factor2*ontem.intermed_factor,16,1)  -- TRUNCAR A 16 CASA
--ROUND(factor2 * POWER(10,16),16) ) / POWER(10,16) 
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
	FROM    (SELECT * FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP 
		AND P1.DT_PROJ = (SELECT	MAX(P2.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P2 (NOLOCK) 
							WHERE	P2.COD_OPERACAO=@Cod_OP 
								AND P2.DT_PROJ < P1.DT_PROJ) ) AS ONTEM
--	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/
/*
select * from cobr_base_reneg (nolock) where contrato = '612119985a'
-- PLANILHA EXCEL
09/05/2017			 10,86 

-- DIARIO ATEH HJ
select * from  IOpen_Shop..GRL_INDICE_VALOR (nolock) where indice_codigo=9 order by data
-- PROJET
select * from  TCDI (nolock)
10,86 

*/


/*
-- ATUALIZA OS CALCULOS F1
-- select * from AUX_FIN_OPER_PROJ (nolock)
-- declare 	@COD_OP  as VARCHAR(20) set @COD_OP = '5067'
-- SELECT		*,convert(float,ROUND(POWER( (convert(float,P.TX_CDI)/100.0 + 1.0), ((1.0/252.0)-1.0)  ) , 8) ) FROM AUX_FIN_OPER_PROJ P (NOLOCK) WHERE	P.COD_OPERACAO=@Cod_OP AND P.DT_PROJ =  '20170504'
-- SELECT MAX(P3.DT_PROJ) FROM AUX_FIN_OPER_PROJ P3 (NOLOCK) 	WHERE	P3.COD_OPERACAO=@Cod_OP AND P3.DT_PROJ < '20170504'
-- SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP
--  2017-05-03 00:00:00
UPDATE		AUX_FIN_OPER_PROJ
	SET		factor1	= convert(float,ROUND( POWER( (AUX_FIN_OPER_PROJ.TX_CDI/100.0 + 1.0), (1.0/252.0) ) -1.0   , 8) )
--ROUND(POWER( (convert(float,AUX_FIN_OPER_PROJ.TX_CDI)/100.0 + 1.0), ((1.0/252.0)-1.0)  ) , 8) )
			--ROUND(((B11/100+1)^(1/252)-1);8)   =ARRED(((tx CDI mês no dia anterior/100+1)^(1/252)-1);8)
--			factor2	= TRUNC(,
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
--			intermed_factor	=
/*
	FROM	(SELECT		* FROM AUX_FIN_OPER_PROJ P2 (NOLOCK) 
				WHERE	P2.COD_OPERACAO=@Cod_OP 
					-- ONTEM, DIA UTIL ANTERIOR
					AND P2.DT_PROJ = (SELECT MAX(P3.DT_PROJ) FROM AUX_FIN_OPER_PROJ P3 (NOLOCK) 
										WHERE	P3.COD_OPERACAO=@Cod_OP AND P3.DT_PROJ < P2.DT_PROJ) ) AS P
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/

-- ATUALIZA OS CALCULOS F2
UPDATE		AUX_FIN_OPER_PROJ
	SET		factor2	= convert(float,ROUND(( FACTOR1 * @CDI_CLI / 100.0  ) + 1.0, 16))
			-- =TRUNCAR((Factor 1 no dia*(% CDI negociado/100)+1);16)
	WHERE	AUX_FIN_OPER_PROJ.DT_PROJ <> (SELECT MIN(P1.DT_PROJ) FROM AUX_FIN_OPER_PROJ AS P1 (NOLOCK) WHERE P1.COD_OPERACAO=@Cod_OP)
*/

*/