USE SIG --[SANTANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS 
WHERE NAME = 'SCR_REMESSA_ARQUIVO' AND TYPE = 'P')
DROP PROCEDURE [DBO].SCR_REMESSA_ARQUIVO
GO    
	
/*
DROP TABLE AUX_REMESSA_ARQUIVO
CREATE TABLE AUX_REMESSA_ARQUIVO(
CODEMPRESA INT,
DTLANCTO SMALLDATETIME,
DTVENCTO SMALLDATETIME,
COMPET SMALLDATETIME,
CTABAN INT,
FORMAPGTO INT,
CODHIST INT,
COMPLHIST VARCHAR(50),
EVECONT INT,
CENTROCUS INT,
CODCLI VARCHAR(50),
VALOR FLOAT,
DESCONTO VARCHAR(50),
DEBCRED VARCHAR(50),
NOTA INT,
CODBAN INT,
AGEDEST VARCHAR(20),
DIGDEST INT,
CONDEST INT,
NOMEFAV VARCHAR(100),
MODA INT,
DIGAGE VARCHAR(50),
CGCFAV VARCHAR(50),
NOMEBAN VARCHAR(50),
TPCONTA INT,
FINALI INT,
FINALIDOC VARCHAR(20),
FINALITED INT
)
*/

CREATE PROCEDURE [DBO].SCR_REMESSA_ARQUIVO (                             
@DT_INI SMALLDATETIME,                    
@DT_FIM SMALLDATETIME)
AS

BEGIN

DELETE FROM AUX_REMESSA_ARQUIVO

INSERT INTO AUX_REMESSA_ARQUIVO 
SELECT 
3 AS 'Código da Empresa',
DCDTEMISS AS 'Data do lançamento',
DCDTEMISS AS 'Data do vencimento',
DCDTEMISS AS 'Competência',
1001 AS 'Conta Bancária',
3 AS 'Forma de pagamento',
525 AS 'Código do Histórico',
DCNROPER AS 'Complemento do Histórico',
525 AS 'Evento Contábil',
41000 AS 'Centro de Custo',
'' AS 'Código do cliente',
DCVALOR AS 'Valor',
'' AS 'Desconto',
'Débito' AS 'Débito/Crédito',
0 AS 'Nota Fiscal',
DCDSTBCO AS 'Código do Banco',
DCDSTAGE AS 'Agência Destino',
RIGHT(DCDSTCC,1) AS 'Digito conta Destino',
SUBSTRING(DCDSTCC,0,CHARINDEX('-',DCDSTCC)) AS 'Conta Destino',
DCFAVNOME AS 'Nome do Favorecido',
41 AS 'Modalidade',
'' AS 'Digito da Agencia',
DCFAVCGC AS 'CPF/CNPJ Favorecido',
'' AS 'Nome do Banco',
1 AS 'Tipo da Conta',
20 AS 'Finalidade',
'' AS 'Finalidade DOC',
5 AS 'Finalidade TED'
FROM CDCSANTANAMICROCREDITO..CDOCS WITH (NOLOCK)
INNER JOIN CDCSANTANAMICROCREDITO..COPER  WITH (NOLOCK) ON DCNROPER = OPNROPER
WHERE DCDTEMISS BETWEEN '2019-04-12' AND '2019-04-12' AND DCIMPOK = 'S'

SELECT 
CODEMPRESA,
CONVERT(VARCHAR(10),DTLANCTO,103) AS DTLANCTO,
CONVERT(VARCHAR(10),DTVENCTO,103) AS DTVENCTO,
CONVERT(VARCHAR(10),COMPET,103) AS COMPET,
CTABAN,
FORMAPGTO,
CODHIST,
COMPLHIST,
EVECONT,
CENTROCUS,
CODCLI,
VALOR,
DESCONTO,
DEBCRED,
NOTA,
CODBAN,
AGEDEST,
DIGDEST,
CONDEST,
NOMEFAV,
MODA,
DIGAGE,
CGCFAV,
NOMEBAN,
TPCONTA,
FINALI,
FINALIDOC,
FINALITED FROM AUX_REMESSA_ARQUIVO (NOLOCK)

END