USE SIG --[Santana]
GO
/****** Object:  StoredProcedure [dbo].[SCR_fin_operacao_proj]    Script Date: 26/05/2017 
SCR_fin_operacao_proj		parametros ( dt_aplic, cliente_sel, nr_ativo)

exec SCR_financeiro_BASE '2017-03-01', '2017-03-31', '2017-05-31',0.0

SELECT * FROM AUX_FIN_OPER (NOLOCK)
SELECT * FROM AUX_FIN_OPER_PROJ (NOLOCK)

SP_HELP AUX_FIN_OPER_PROJ
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROC TELA PROJECAO IOPEN  **********************************************************************************************************************************************************************************
IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SCR_financeiro_BASE' AND type = 'P')
   DROP PROCEDURE [dbo].[SCR_financeiro_BASE]
GO




CREATE PROCEDURE [dbo].[SCR_financeiro_BASE] (
	@DataDe   as datetime,
	@DataATE  as datetime,
	@DataREF  as datetime,
	@VLR_CDI  as FLOAT		 ) AS

BEGIN
	
	-- RESUMO DAS OPERACOES
	SELECT		*	FROM FIN_RES_OPER (NOLOCK)
		WHERE	DT_REF =@DataREF
			AND DT_EMISSAO BETWEEN	@DataDE AND	@DataATE





end


/*

-- ANTERIOR
	select * 
		from (select  * from fin_res_oper r (nolock)
							 where dt_ref=@DataREF	
									AND DT_EMISSAO BETWEEN	@DataDE	AND	@DataATE ) as res, 
		(select *	
			FROM	IOpen_Shop..OPN_POSCLIENTE (nolock) 
				WHERE  data=@DataREF ) as cli
		where  res.papel_codigo =cli.papel_codigo


-- LIMPA AUX ANTERIOR
TRUNCATE	TABLE AUX_FIN_OPER
TRUNCATE	TABLE AUX_FIN_OPER_PROJ

-- INSERE AS OPERACOES
INSERT AUX_FIN_OPER (   DT_EMISSAO, Cod_Operacao, -- Dt_Vcto, dias, 
						pre_cdi,	cod_papel, prc_cdi_real, serie_operacao, 
						COD_GERENTE, vlr_original, cliente, COD_cliente,
						vlr_mes_ant,	vlr_mes_atual,	vlr_rend_mes,	vlr_projetado )
SELECT	DISTINCT	M.DATA, M.CODIGO,
		CASE WHEN  CHARINDEX('PRE',P.PAPEL_NOME,0)>0 THEN 'PRE' ELSE 'CDI' END ,  -- CDI-E PRE
		P.PAPEL_NOME, M.INDICE_PERCENTUAL, P.PAPEL_CODIGO,
		'', M.FINANCEIRO,'',M.CLIENTE_CODIGO,
		0.0,0.0,0.0,0.0
-- SELECT *
  From	IOpen_Shop..Opn_Movimento M (NoLock)
	,IOpen_Shop..OPN_PAPEL P (NoLock) 
--WHERE	M.DATA BETWEEN '20150101' AND '20170331'
WHERE	M.DATA BETWEEN @DataDe AND @DataATE
	AND M.OPERACAO_CODIGO IN (15,16)			-- EMISSAO 15 = DPGE  16= LC E RDB
	AND P.PAPEL_CODIGO=M.PAPEL_CODIGO COLLATE DATABASE_DEFAULT
	AND P.DATA_BASE_VENCIMENTO > @DataATE		-- NAO VENCIDAS, NAO PAGAS

-- 1563 OPER    Where Codigo=@Cod_OP 

--
--DECLARE @CDI_CLI  FLOAT
--SET		@CDI_CLI  = (select INDICE_PERCENTUAL from IOpen_Shop..Opn_Movimento (NOLOCK)  where Codigo=@Cod_OP)


-- PAPEIS
UPDATE	AUX_FIN_OPER
SET		Dt_Vcto= DATA_VENCIMENTO , dias = DIAS_PAGAMENTO
      , AUX_FIN_OPER.PAPEL_CODIGO = P.CODIGO
  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
--  where LEFT(PAPEL_CODIGO,8)=LEFT(SERIE_OPERACAO,8) COLLATE DATABASE_DEFAULT
  where P.PAPEL_CODIGO=SERIE_OPERACAO COLLATE DATABASE_DEFAULT
	AND Data_operacao=DT_EMISSAO		 -- DATA OPER		@DataDe
	AND INDICE_PERCENTUAL=prc_cdi_real   -- TX CLIENTE		@CDI_CLI
--  where PAPEL_CODIGO=cod_papel COLLATE DATABASE_DEFAULT
-- 'RDB017001A1'  EQUIV 		RDB0170002

-- PAPEL SEM CODIGO
UPDATE	AUX_FIN_OPER
SET		AUX_FIN_OPER.PAPEL_CODIGO = (SELECT MAX(P.CODIGO)
									  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
									  where P.PAPEL_CODIGO=SERIE_OPERACAO COLLATE DATABASE_DEFAULT
										)   -- TX CLIENTE		@CDI_CLI
WHERE	ISNULL(AUX_FIN_OPER.PAPEL_CODIGO,'')=''


-- CLIENTE
UPDATE	AUX_FIN_OPER
SET		COD_GERENTE = GERENTE_CODIGO, 
		cliente		= NOME
  from	IOpen_Shop..OPN_CLIENTES (NoLock) 
  where Codigo=COD_cliente 

/*
-- GERENTE
-- SP_HELP AUX_FIN_OPER
UPDATE	AUX_FIN_OPER
SET		GERENTE =  NOME
  from	IOpen_Shop..OPN_GERENTE (NoLock) 
  where Codigo=COD_GERENTE 
*/


-- PROJETADO CADA OPERACAO
-- 1a operacao
DECLARE @CODOP1		 AS VARCHAR(20)
SET		@CODOP1 = (SELECT MIN(COD_OPERACAO)		FROM AUX_FIN_OPER (NOLOCK))
-- ULTIMA operacao
DECLARE @CODOPF		 AS VARCHAR(20)
SET		@CODOPF = (SELECT MAX(COD_OPERACAO)		FROM AUX_FIN_OPER (NOLOCK))
DECLARE @CODOP		 AS VARCHAR(20)
SET		@CODOP =@CODOP1
-- DADOS DA OPERACAO
DECLARE	@DT			 AS DATETIME
DECLARE @CONTADOR	 AS INT
DECLARE	@CLIENTE	 AS VARCHAR(20)
DECLARE	@DT_MES_ANT  AS DATETIME
-- DIA 1 DO MES DO FECHAMENTO
SET		@DT_MES_ANT =  CONVERT(CHAR(4),DATEPART(YEAR,@DataREF))+
			RIGHT(RTRIM('00'+CONVERT(CHAR(2),DATEPART(MONTH,@DataREF))),2)+'01'
-- FIM DO MES ANTERIOR
SET		@DT_MES_ANT=DATEADD(DD,-1,@DT_MES_ANT)
	-- CHECA SE É FDS OU FERIADO
	SET @DT_MES_ANT = CASE	 WHEN	DATEPART(DW,@DT_MES_ANT) =1 THEN DATEADD(D,-2,@DT_MES_ANT)  -- DOM
							 WHEN	DATEPART(DW,@DT_MES_ANT) =7 THEN DATEADD(D,-1,@DT_MES_ANT)  -- SAB
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END
	-- CHECA SE É  FERIADO 2 DIAS EX CARNAVAL
	SET @CONTADOR = (SELECT COUNT(*) FROM  IOpen_Shop..GRL_FERIADO (NOLOCK) WHERE DATA=@DT_MES_ANT)
	SET @DT_MES_ANT = CASE	 WHEN	@CONTADOR=1 THEN DATEADD(D,-1,@DT_MES_ANT)
							 ELSE   @DT_MES_ANT	END




WHILE	@CODOP <= @CODOPF  -- ANTES DO FIM
BEGIN
		-- CARREGA VARIAVEIS
		SET		@DT=(SELECT DT_EMISSAO
 			FROM	AUX_FIN_OPER (NOLOCK)
			WHERE	COD_OPERACAO = @CODOP)
		SET		@CLIENTE=(SELECT COD_CLIENTE
 			FROM	AUX_FIN_OPER (NOLOCK)
			WHERE	COD_OPERACAO = @CODOP)

		-- PROJETA CONTRATO A CONTRATO
		EXEC  [dbo].[fin_operacao_proj] 	@DT, @CLIENTE ,	@CODOP  ,	@DataREF , @vlr_CDI 

		-- CARREGA DADOS DA PROJECAO FINAL
		UPDATE		AUX_FIN_OPER
			SET		VLR_PROJETADO = P.VLR_DIA 
			FROM	AUX_FIN_OPER_PROJ P (NOLOCK)
			WHERE	AUX_FIN_OPER.COD_OPERACAO  = @CODOP 
				AND P.COD_OPERACAO= @CODOP 
				AND P.DT_PROJ = (SELECT		MAX(P1.DT_PROJ) 
									FROM	AUX_FIN_OPER_PROJ P1 (NOLOCK) WHERE	P1.COD_OPERACAO=@CODOP )

		-- CARREGA DADOS DA PROJECAO NO MES
		UPDATE		AUX_FIN_OPER
			SET		VLR_MES_ATUAL = P.VLR_DIA 
			FROM	AUX_FIN_OPER_PROJ P (NOLOCK)
			WHERE	AUX_FIN_OPER.COD_OPERACAO  = @CODOP 
				AND P.COD_OPERACAO= @CODOP 
				AND P.DT_PROJ = @DataREF

		-- CARREGA DADOS DA PROJECAO NO MES ANTERIOR
		UPDATE		AUX_FIN_OPER
			SET		VLR_MES_ANT = P.VLR_DIA 
			FROM	AUX_FIN_OPER_PROJ P (NOLOCK)
			WHERE	AUX_FIN_OPER.COD_OPERACAO  = @CODOP 
				AND P.COD_OPERACAO= @CODOP 
				AND P.DT_PROJ = @DT_MES_ANT
/*
SELECT	DT_PROJ,TX_CDI,FACTOR1,FACTOR2,INTERMED_FACTOR,
		RESULTADO, VLR_DIA,ATUALIZ_DIA
 FROM	AUX_FIN_OPER_PROJ (NOLOCK)
WHERE	COD_OPERACAO=@CODOP
*/

		-- EXECUTOU A ULTIMA OPERACAO
		IF @CODOP = @CODOPF
			BREAK
		-- NEXT PROXIMA OPERACAO
		SET		@CODOP = (SELECT MIN(COD_OPERACAO)		FROM AUX_FIN_OPER (NOLOCK)	WHERE COD_OPERACAO > @CODOP)
		
END

/*
SELECT *	FROM	IOpen_Shop..OPN_POSCLIENTE (nolock)  
WHERE  papel_codigo= 1333 ORDER BY DATA
SELECT * FROM AUX_FIN_OPER
*/
		-- AJUSTA VCTO
		UPDATE		AUX_FIN_OPER
			SET		DT_VCTO = (SELECT C.DATA_VENCIMENTO
									FROM	IOpen_Shop..OPN_PAPEL C (NoLock) 
									WHERE	C.CODIGO   = (SELECT	MAX(P.CODIGO) 
																  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
																  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT
										)
			WHERE	DT_VCTO IS NULL  -- SEM VENCTO
		-- AJUSTA DIAS
		UPDATE		AUX_FIN_OPER
			SET		DIAS = (SELECT C.DIAS_PAGAMENTO
									FROM	IOpen_Shop..OPN_PAPEL C (NoLock) 
									WHERE	C.CODIGO   = (SELECT	MAX(P.CODIGO) 
																  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
																  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT
										)
			WHERE	DIAS IS NULL  -- SEM VENCTO

		-- AJUSTA VLR SEM PROJECAO PQ ACABOU O CONTRATO
		UPDATE		AUX_FIN_OPER
			SET		VLR_PROJETADO = (SELECT C.FINANCEIRO
									FROM	IOpen_Shop..OPN_POSCLIENTE C (nolock)  
									WHERE	CONVERT(VARCHAR(20),C.PAPEL_CODIGO)   = AUX_FIN_OPER.PAPEL_CODIGO   COLLATE DATABASE_DEFAULT
/*
(SELECT	MAX(P.CODIGO) 	  from	IOpen_Shop..OPN_PAPEL P (NoLock) 
						  where P.PAPEL_CODIGO= AUX_FIN_OPER.SERIE_OPERACAO  COLLATE DATABASE_DEFAULT) -- COLLATE DATABASE_DEFAULT
*/
										AND C.DATA=(SELECT		MAX(C1.DATA)	FROM IOpen_Shop..OPN_POSCLIENTE C1 (nolock)  
														WHERE	CONVERT(VARCHAR(20),C1.PAPEL_CODIGO)   = AUX_FIN_OPER.PAPEL_CODIGO   COLLATE DATABASE_DEFAULT
															AND C1.DATA < AUX_FIN_OPER.DT_VCTO ))
			WHERE	ISNULL(AUX_FIN_OPER.VLR_PROJETADO,0.0) = 0.0  -- SEM PROJECCAO




		-- AJUSTA O RENDIMENTO NO MES
		UPDATE		AUX_FIN_OPER
			SET		VLR_REND_MES = ISNULL(VLR_MES_ATUAL,0.0) - CASE WHEN ISNULL(VLR_MES_ANT,0.0)=0.0 THEN VLR_ORIGINAL ELSE VLR_MES_ANT END


SELECT * FROM AUX_FIN_OPER (NOLOCK)
*/
